### ISSUE TITLE
Upddate docs and samples with 'image' & 'description' options

### ISSUE THREAD

**Issue by mzampetakis** [cotes2020/jekyll-theme-chirpy#100]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [ ] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description
It seems that jekyll themes support 'image' & 'description' meta fields for a page (alongside title, author etc). However, there is no reference for them in the docs neither inside any example post. Is this in purpose left out or is it considered as a basic jekyll option so it is no worth of mentioning? I used them and seemed really helpfull so having them already there would be really helpfull for others as well.

Btw thanks for the nice theme!

**Comment by cotes2020** [comment]
> It seems that jekyll themes support 'image' & 'description' meta fields for a page...

Jekyll's predefined variables in front-matter are listed in [here](https://jekyllrb.com/docs/front-matter/). In Chirpy theme, I did add `image` to the post layout, but not `description`.  


> However, there is no reference for them in the docs neither inside any example post...

Personally, I rarely use the `image` field of posts, so I forgot about it in the docs. It will be documented in the future. Thank you for reminding me.

**Comment by mzampetakis** [comment]
So, if you accept PRs I could open one for this. Also,there are some other fields that could added as weel.

**Comment by cotes2020** [comment]
If your PRs is a supplement to the docs, it is welcome.

> Also,there are some other fields that could added as weel.

But we don't need another custom variables in front-matter for this project right now.
