### ISSUE TITLE
Issue rendering DOS/CMD script using code blocks

### ISSUE THREAD

**Issue by Cyanoxygen** [cotes2020/jekyll-theme-chirpy#101]
## Checklist
- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [x] I found the bug on the latest code of `master` branch.

## Describe the bug

This issue may due to the upstream Rogue highlighter, if I post this issue at wrong place, please tell me and I will try to post to upstream.

**To Reproduce**

Insert a code block with DOS/CMD script into a post, build and run: (the additional slash is not included in the actual post)
This script is from [here](https://dandini.wordpress.com/2019/07/15/administered-port-exclusions-blocking-high-ports/)
```
```dos
rem Modify Dynamic Port Range for Development Users
dism /online /get-features | find /i "Microsoft-Hyper-V" && (
rem Modify Dynamic Port Range
start /wait "" netsh int ipv4 set dynamicport tcp start=20000 num=16384
start /wait "" netsh int ipv4 set dynamicport udp start=20000 num=16384

rem Add Registry Key
start /wait "" reg add HKLM\SYSTEM\CurrentControlSet\Services\hns\State /v EnableExcludedPortRange /d 0 /f

goto :eof

)
\```
```
**Expected behavior**

This is a code block, containing a CMD script. The expected thing is to get a highlighted output like `rem`, `goto` or something.

This screenshot is taken in VS Code:

![image](https://user-images.githubusercontent.com/29174191/90305808-e7c62680-def8-11ea-832a-8a35fda7f51f.png)

**Screenshots**

Instead of getting a highlighted text, I got a _single line_ output with an angle bracket like this, the long long line is wrapped into multiple lines:

![image](https://user-images.githubusercontent.com/29174191/90305476-de878a80-def5-11ea-896b-57b0a8b8b6d9.png)

The vanilla clone:

![image](https://user-images.githubusercontent.com/29174191/90305773-80a87200-def8-11ea-833f-47ef07027971.png)

F12:

![image](https://user-images.githubusercontent.com/29174191/90305793-bb120f00-def8-11ea-9b2e-24ebe6793e81.png)

**Desktop**

Google Chrome | 84.0.4147.125 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | Windows 10 OS Version 2004 (Build 19041.450)

**Additional context**

**Comment by cotes2020** [comment]
Hi @Cyanoxygen,

The HTML structure chaos has been fixed, but please note that Jekyll 3 and above uses [**Rouge**](http://rouge.jneen.net/) to render the code snippets, and both `cmd` and `dos` are [not supported by rouge](https://github.com/rouge-ruby/rouge/wiki/List-of-supported-languages-and-lexers), so the rendered code block will not have syntax highlighting and line numbers.

**Comment by Cyanoxygen** [comment]
✨ Thank you very much! Your answer did help a lot to me. 

So I'm going to close this issue then, because upstream did not support this language.
