### ISSUE TITLE
How do I fix theme not applying?

### ISSUE THREAD

**Issue by DylanDevelops** [cotes2020/jekyll-theme-chirpy#1012]
**NOTE:** Before you start, the following should be completed.

- Read [Wiki][wiki] to understand the usage and the correct effect of functional design.
- Make sure no [similar issue(including closed ones)][issues] exists.
- Try to find the answer on [Jekyll Forum][forum] and [StackOverflow][stack_overflow].

[wiki]: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue
[forum]: https://talk.jekyllrb.com/
[stack_overflow]: https://stackoverflow.com/questions/tagged/jekyll

## Description

For some reason, after using the template repository, this is all that shows. How do I fix this?

## Logs/Screenshots

<img width="1512" alt="Screenshot 2023-04-27 at 9 18 08 PM" src="https://user-images.githubusercontent.com/48571264/235046342-24c65562-9a7c-4645-82a3-b9723fe1079b.png">

**Comment by sukhjinder-kumar** [comment]
Search in issues. And also closely follow deployment instructions over at [link](https://chirpy.cotes.page/posts/getting-started/#deployment)

**Comment by DylanDevelops** [comment]
> Search in issues. And also closely follow deployment instructions over at [link](https://chirpy.cotes.page/posts/getting-started/#deployment)

Perfect I did the bundle lock stuff. Now it mentions to make sure the URL is configured correctly, if my custom domain is `blog.dylanravel.com` and I have already configured it on DNS and inside the pages tab long github, do I just put that URL in the `baseURL` category inside the config.yml file?

**Comment by DylanDevelops** [comment]
okay fixed
