### ISSUE TITLE
Mobile hamburger menu

### ISSUE THREAD

**Issue by eatthebuffet** [cotes2020/jekyll-theme-chirpy#1017]
On Mobile the hamburger menu does not work.

I get no response when clicking and the browser used was chrome. I am unsure what to look for.

https://eatthebuffet.github.io

https://github.com/eatthebuffet/eatthebuffet.github.io

**Comment by Glitch3dPenguin** [comment]
This is also an issue that I am experiencing: 

https://KLabsDev.com

I just updated my website today and the hamburger is not working on mobile for me as well.

**Comment by NichtsHsu** [comment]
You don't have build the assets. Please run `npm i && npm run build` and add `assets/js/dist/*.min.js` under your git's control. Please note that this repository is not a template, if you are not familiar with Jekyll and js, a better way is to fork [chirpy-starter](https://github.com/cotes2020/chirpy-starter).

**Comment by Glitch3dPenguin** [comment]
> You don't have build the assets. Please run `bash tools/init`. Please note that this repository is not a template, if you are not familiar with Jekyll and js, a better way is to fork [chirpy-starter](https://github.com/cotes2020/chirpy-starter).

Ahh, I was working on an update and I grabbed the wrong repo. That did fix my issue. Thanks!
