### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by anargya-web** [cotes2020/jekyll-theme-chirpy#1019]
**NOTE:** Before you start, the following should be completed.

- Read [Wiki][wiki] to understand the usage and the correct effect of functional design.
- Make sure no [similar issue(including closed ones)][issues] exists.
- Try to find the answer on [Jekyll Forum][forum] and [StackOverflow][stack_overflow].

[wiki]: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue
[forum]: https://talk.jekyllrb.com/
[stack_overflow]: https://stackoverflow.com/questions/tagged/jekyll

## Description

Well I installed as in the tutorial. But this is what happened. 

OS: Ubuntu 22.04 LTS
Node: 20.0.1 and 18.16.0
## Operations you have already tried

I've tried using different versions of node and npm. 

## Logs/Screenshots

![IMG_20230505_201724](https://user-images.githubusercontent.com/132619756/236468918-fe88b92e-05dd-44d2-a299-93e702c634a7.jpg)

**Comment by josephKimiri** [comment]
try running `npm i && npm run build`
