### ISSUE TITLE
How can I add custom menu entries?

### ISSUE THREAD

**Issue by AleCie** [cotes2020/jekyll-theme-chirpy#102]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

I have tried adding new md files in tabs folder and editing existing ones, however it doesn't add the pages to the menu and whenever I modify existing page it doesn't recognise it anymore.

**Comment by cotes2020** [comment]
Add the tab data in file `_data/tabs.yml`.
