### ISSUE TITLE
Mobile view burger Icon to show menu is not working.

### ISSUE THREAD

**Issue by simples1** [cotes2020/jekyll-theme-chirpy#1025]
[wiki]: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue

## Describe the bug
Not able to view Menu on mobile view.

## To Reproduce

1. Go to MOBILE VIEW
2. Click on Burger Icon
3. No response

## Expected behavior
Should show menu.

## Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |         |
| `gem -v`                          |         |
| `bundle -v`                       |         |
| `bundle exec jekyll -v`           |         |
| `bundle info jekyll-theme-chirpy` |         |

## Additional context

 
![Screenshot 2023-05-07 at 19 41 25](https://user-images.githubusercontent.com/16004713/236696643-03a6642b-9161-4b2a-a1fc-023ba522401c.png)

**Comment by v4vong** [comment]
I met this problem before, but after updating the contents by pushing, it was solved. Weird.

**Comment by Sereinxm** [comment]
how to update the content

**Comment by koppor** [comment]
Same issue here.

```
Uncaught TypeError: document.getElementById(...) is null
    <anonymous> https://blog.jabref.org/assets/js/dist/post.min.js:4
    <anonymous> https://blog.jabref.org/assets/js/dist/post.min.js:4
```

    document.getElementById("toc-wrapper")

Example post not working: https://blog.jabref.org/2024/08/26/GSoC-CSL/

Example post working: https://blog.jabref.org/2024/03/11/JabRef-20-years-start/

**Comment by cotes2020** [comment]
Hi @koppor, 

You might want to consider creating a new issue and providing a detailed description according to the template, rather than commenting under an outdated and incomplete issue. Maintainers usually don't pay attention to closed issues.
