### ISSUE TITLE
Add support for Cloudflare Analytics

### ISSUE THREAD

**Issue by bonanitech** [cotes2020/jekyll-theme-chirpy#1026]
**NOTE:** Before you start, the following should be completed.

- Read [Wiki][wiki] to understand the usage and the correct effect of functional design.
- Make sure no [similar issue(including closed ones)][issues] exists.
- Make sure the request is based on the latest code in the `master` branch.

[wiki]: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue

## Is your feature request related to a problem? Please describe

Currently, the theme only supports Google Analytics. It would be great if it had support for Cloudflare Analytics.

https://www.cloudflare.com/analytics/

**Comment by cotes2020** [comment]
Hi @bonanitech, I don't personally use Cloudflare Analytics, if you're willing to implement this feature and submit a PR then I'd be happy to merge it.

**Comment by bonanitech** [comment]
I'll try adding it to my site. If I'm successful, I'll submit a PR here.

Closing this for now.
