### ISSUE TITLE
Ugly white background appears when site is employed on dark theme

### ISSUE THREAD

**Issue by Biplab-Dutta** [cotes2020/jekyll-theme-chirpy#1029]
On my local server, the output seems to be fine.
However, as my site is deployed I get this ugly looking white background. I don't know why.

Hee's the repo to my blog site.
https://github.com/Biplab-Dutta/personal_site

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/63902683/e2f5577a-1100-4450-b483-1e027e8634d6)

**Comment by sukhjinder-kumar** [comment]
I don't see any such issues on your [website](https://biplabdutta.com.np/posts/pattern-matching-dart/). Dark theme seems to be working fine.

**Comment by Biplab-Dutta** [comment]
@sukhjinder-kumar actually yes. I have no idea how it's fixed now.
But now I am seeing other issues. The promp icons are not being rendered properly..
![IMG_20230511_011343.jpg](https://github.com/cotes2020/jekyll-theme-chirpy/assets/63902683/0f31275a-48e3-4512-a467-4fdba4a12cb5)

![IMG_20230511_011406.jpg](https://github.com/cotes2020/jekyll-theme-chirpy/assets/63902683/6ec03caa-3ccc-411f-92d1-a655e72d8dc5)

**Comment by sukhjinder-kumar** [comment]
Not really sure what is going on. But I do see that your CD workflow is showing many errors. This means what you might be seeing locally is way ahead of what you are seeing on your website.
![error message](https://github.com/cotes2020/jekyll-theme-chirpy/assets/82507694/c8fcc369-c073-4dd5-b520-b68ec78c39d3)
My guess is you didn't follow the setup instruction properly, Check them out [here](https://chirpy.cotes.page/posts/getting-started/). You might have missed [this](https://chirpy.cotes.page/posts/getting-started/) or something trivial like installing dependencies with `bundle` on your local machine. 
Also, I think you are using Cloudflare, you might wanna look up issues as there seems to be some problem there. Lastly (or rather first of all), do you see prompt-icon on your local build?

Hope it helps!
