### ISSUE TITLE
404 error in categories and tags

### ISSUE THREAD

**Issue by hillsonghimire** [cotes2020/jekyll-theme-chirpy#103]
I've tried for hours(4 hours) but still when I click on categories or on tags I am redirected to 404 page not found. I think I am following the documentation and seeing other past issues but still can't figure out where I'm wrong.

hosting in github(eg. hillsonghimire.github.io). but hosting this blog from another repository(eg: hillsonghimire.github.io/blog).

I'm new so any input is appreciated.

**Comment by hillsonghimire** [comment]
Got help from previous issue creators #95

**Comment by cotes2020** [comment]
So, do you mean that this issue has been solved?

**Comment by achyutap** [comment]
Can anyone tell  where is publish.sh?
