### ISSUE TITLE
Cache-control? Always need hard refresh for new posts to show up.

### ISSUE THREAD

**Issue by ianyepan** [cotes2020/jekyll-theme-chirpy#1031]
I was wondering if we could manually set the cache-control of my Jekyll website. Perhaps something along the lines of: `Cache-Control: max-age=3600, must-revalidate`.

The issue is that when I post a new post and it goes through the pipeline etc. I need to hard refresh for the post to actually show up. This behavior is consistent with all my other devices that previously visited my website. All of them reuse the cache aggressively and will need hard refresh to see the new post. A similar issue was opened here: https://github.com/cotes2020/jekyll-theme-chirpy/issues/135 but was closed without proper answer IMHO.

If it's just for my own development purposes, I can certainly perform the hard refresh. **But my concern is when other users who visit my site won't be able to see the new posts in time, if they don't hard refresh.**

Thanks!

Edit: related discussion: https://github.com/cotes2020/jekyll-theme-chirpy/issues/527

**Comment by NichtsHsu** [comment]
Finally I disabled PWA on my blog according to [this comment](https://github.com/cotes2020/jekyll-theme-chirpy/issues/527#issuecomment-1079998986).

**Comment by ianyepan** [comment]
@NichtsHsu Thanks Nihil! I'll give that a try. So to be clear, you didn't touch any of these two lines:

```js
// in js-selector.html
<script defer src="{{ '/app.js' | relative_url }}"></script> 


// in swcache.js
...
  '{{ "/app.js" | relative_url }}',
...
```

You just swapped out all the contents of sw.js with the snippet you linked to?

```js
self.addEventListener("install", function (e) {
  self.skipWaiting();
});

self.addEventListener("activate", function (e) {
  self.registration
    .unregister()
    .then(function () {
      return self.clients.matchAll();
    })
    .then(function (clients) {
      clients.forEach((client) => client.navigate(client.url));
    });
});
```

**Comment by cotes2020** [comment]
Hi @ianyepan, If your website is hosted on GitHub Pages, there is no possibility to control `Cache-Control`.

If PWA is enabled, your website will pop up an update window after a few seconds. You can simply click on it without needing to hard refresh.

In addition, I think you may have overlooked [the commit](https://github.com/cotes2020/jekyll-theme-chirpy/commit/106c981bac71e7434204a77e1f0c9c61d6eb1509) below #527. If you want to disable PWA, you just need to set it to "false" in `_config.yml`.

**Comment by PowerPCFan** [comment]
I disabled PWA in _config.yml and super old versions of content are still being served on my website, only way to get the new version is Ctrl+Shift+R or Ctrl+F5. I'm on Microsoft Edge on Windows 11 if that matters. Any ideas on what this could be?
