### ISSUE TITLE
Dark Mode and mobile menu not working

### ISSUE THREAD

**Issue by devopsinka** [cotes2020/jekyll-theme-chirpy#1033]
**NOTE:** Before you start, the following should be completed.

- Read [Wiki][wiki] to understand the usage and the correct effect of functional design.
- Make sure no [similar issue(including closed ones)][issues] exists.
- Make sure the bug is found in the latest code of the `master` branch.

[wiki]: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue

## Describe the bug

When the last tag is launched locally, switching between dark and light mode does not work, and the mobile menu does not work either.
When investigating through developer tools, a 404 error is visible for http://127.0.0.1:4000/assets/js/dist/misc.min.js
Similar behavior for the production environment

## To Reproduce

1. Download project on tags v5.6.1 from zip or tar.gz
2. Unzip project
3. Go to project and open project in terminal
4. bundle
5. bundle exec jekyll s 
6. Open your local site and click on dark button and open your site with responsive

## Expected behavior

After starting the server everything works

## Logs/Screenshots

![screen_error](https://github.com/cotes2020/jekyll-theme-chirpy/assets/5451242/bc686801-082e-431f-b622-1f7b47808b1f)

## Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |         |
| `gem -v`                          |         |
| `bundle -v`                       |         |
| `bundle exec jekyll -v`           |         |
| `bundle info jekyll-theme-chirpy` |         |

**Comment by josephKimiri** [comment]
run `npm i && npm run build` on your local machine.
