### ISSUE TITLE
¿Is there a way to change the image shown when sharing a post?

### ISSUE THREAD

**Issue by camartinezbu** [cotes2020/jekyll-theme-chirpy#104]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

I would like to know if it is possible to change the image shown when sharing a link for a post in social media. Currently, every link shows the avatar that appears in the sidebar and I would like to set a specific image for each post.

Thank you in advance.

**Comment by cotes2020** [comment]
Yes, you can add a image to a post by:

```yaml
---
image: /path/to/image
---
```

See the [source code](https://github.com/cotes2020/jekyll-theme-chirpy/blob/71ac3e176242134f987904bce8a63f1673eaf79d/_layouts/post.html#L64-L66).

**Comment by camartinezbu** [comment]
Thank you very much!

**Comment by CoolJosh0221** [comment]
I'm using the stater version of the theme is there's no _layouts directory
