### ISSUE TITLE
Page always fails when updating (git push)

### ISSUE THREAD

**Issue by inhanbyeol94** [cotes2020/jekyll-theme-chirpy#1045]
There is always a page error when updating (git push).

If you go to the action value in github, no error is displayed, but when you run Re-run all job, the page returns normally.

What's the reason?

**error page : --- layout: home # Index page ---**

**Comment by joshjohanning** [comment]
Do you have a link to your workflow run where you are seeing this?

**Comment by Inhanbyeol** [comment]
> 이것을 보고 있는 워크플로 실행에 대한 링크가 있습니까?

I'm a beginner, so which route should I show you?

**Comment by Inhanbyeol** [comment]
> Do you have a link to your workflow run where you are seeing this?

https://github.com/Inhanbyeol/Inhanbyeol.github.io/actions/runs/5037827656

**Comment by sikutisa** [comment]
@Inhanbyeol 
I think the issues below will help.
#628, #968

And the following link will also help you.
https://chirpy.cotes.page/posts/getting-started/#deployment
