### ISSUE TITLE
Is there way to use toggle in post?

### ISSUE THREAD

**Issue by 4862abd** [cotes2020/jekyll-theme-chirpy#1048]
Is there any way to use toggle(Something that you can see and not see when you click) in post?
I want to write side imformations which are not important with main topic.
Thank you.

**Comment by T13nn3s** [comment]
Hi @4862abd,

Markdown is supporting HTML, please see earlier question about creating a toggle https://github.com/cotes2020/jekyll-theme-chirpy/pull/792

This is your solution:

```
<details>
    <summary>Toggle</summary>
Text in toggle
</details>
```

The result:

![Create toggle in Markdown](https://i.imgur.com/M28pXBO.png)

**Comment by 4862abd** [comment]
Thanks a lot.
For now, I will check all issues for check imformations.
