### ISSUE TITLE
Recently Updated list tries to wrap long post titles in 6.0

### ISSUE THREAD

**Issue by joshjohanning** [cotes2020/jekyll-theme-chirpy#1049]
## Describe the bug

It looks like in Chirpy 6, the recently updated list is trying to wrap the titles instead of dropping the extra length with `...`. There are mostly-hidden characters that show up as a bunch of dots/lines now.

Tested in a fresh copy of 6.0 to verify it wasn't just my instance. See screenshot: 

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/19912012/803f237b-8d61-4eb5-a814-78c79775c3a1)

## To Reproduce

- In chirpy 6.0+, make a long post title (over ~32 characters)

## Expected behavior

- It should not wrap and just cut off the longer text

## Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |   ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [x86_64-linux]      |
| `gem -v`                          |      3.3.26   |
| `bundle -v`                       |      Bundler version 2.3.26   |
| `bundle exec jekyll -v`           |     jekyll 4.3.2    |
| `bundle info jekyll-theme-chirpy` |     jekyll-theme-chirpy (6.0.0)    |

### Desktop

- OS: Ubuntu 20.04
- Browser: Chrome latest

**Comment by cotes2020** [comment]
Thanks for the feedback @joshjohanning! Chirpy v6.x updates the major version of Bootstrap, so the same stylesheet code behaves differently, will fix it soon.

**Comment by joshjohanning** [comment]
thank you!
