### ISSUE TITLE
Avatar does not display

### ISSUE THREAD

**Issue by JinHanLei** [cotes2020/jekyll-theme-chirpy#1057]
Whether it is local or Github pages, the avatar cannot be displayed.

I can see \<img src="https://chirpy-img.netlify.app/commons/avatar.jpg" alt="avatar" onerror="this.style.display='none'" width="112" height="112"\>  on your website, but I don't have it.

Thank you very much.

**Comment by JinHanLei** [comment]
edit the _config.yml
avatar: /assets/img/favicons/apple-touch-icon.png

**Comment by iamtalhaasghar** [comment]
> edit the _config.yml avatar: /assets/img/favicons/apple-touch-icon.png

you are a gem! thanks @JinHanLei

**Comment by MindStudioOfficial** [comment]
When I write
`avatar: /assets/img/my_logo.png`

It tries to access
`http://assets/img/my_logo.png`
