### ISSUE TITLE
why toc-wrapper has unloaded class

### ISSUE THREAD

**Issue by dayongbz** [cotes2020/jekyll-theme-chirpy#106]
## Checklist

- [X] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [X] There are no similar question on existing issues (including closed ones).
- [X] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

In demo site, toc-wrapper is existed.
but my [site](https://dayongbz.github.io/posts/%EC%97%90%ED%94%BC%EC%86%8C%EB%93%9C_5._%EB%84%A4%EC%9D%B4%EB%B2%84_%EA%B0%9C%EB%B0%9C%EC%9E%90%EB%8A%94_%EC%96%B4%EB%96%A4_%EC%84%B1%EC%9E%A5%EC%9D%84_%EA%B2%BD%ED%97%98%ED%95%A0%EA%B9%8C-_-_NAVER_DEVELOPER_OPEN_CLASS/) doesn't have toc-wrapper.
Because my toc-wrapper has unloaded class.
How can i solve this problem??

**Comment by cotes2020** [comment]
Please check out [these codes](https://github.com/cotes2020/jekyll-theme-chirpy/blob/44476f271f224fa4ac6c6e29e937536a14f75177/assets/js/_utils/toc-filter.js#L10-L13): If a post has neither H1 nor H2 title, the toc block will be hidden.

**Comment by dayongbz** [comment]
thank you~
