### ISSUE TITLE
sitemap.xml generating URLs incorrectly

### ISSUE THREAD

**Issue by sherozsamatov** [cotes2020/jekyll-theme-chirpy#1068]
### First case
After build is complete,  I have noticed localhost:4000 is added at the beginning of the URL in sitemaps.xml file. But the site doesn't break, works normally.

This is when `baseurl` is empty in config.yml

Here's the result:

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/50622092/847bc49c-b316-473f-9833-b64552f31d5c)
<br>
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/50622092/fcc13ff6-f2be-4328-a0b1-8bb584ef1cc8)

### Second case

But if I assign my site address at `baseurl`, then the site breaks and sitemap.xml displays localhost:4000 +  my site address.

Here's the result:

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/50622092/d1e16c63-62fa-47c1-97e7-d07ea646d97c)
<br>
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/50622092/a0fcf53d-ed74-4594-bfd5-3eee0247f557)

**What steps can I take to solve these issues?**

**Any help would be appreciated.**

_UPDATE_

I just checked the live website, the sitemap.xml file looks fine.

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/50622092/2dccd5eb-d78b-483f-a7ea-f00c13c20470)

Not sure what's happening here.

**Comment by NichtsHsu** [comment]
When you use `bundle exec jekyll b` to build site, `localhost` will be used.
If you want to use your own domain, do `JEKYLL_ENV=production bundle exec jekyll b` (also used on Github Action).
