### ISSUE TITLE
Error Initialization

### ISSUE THREAD

**Issue by coffstation** [cotes2020/jekyll-theme-chirpy#107]
## Checklist

- [ x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x ] There are no similar reports on existing issues (including closed ones).
- [ ] I found the bug on the latest code of `master` branch.

## Describe the bug

after executing locally ( bash tools/run.sh ), an error emerges:

cp: cannot stat '/mnt/c/Users/pablo/Desktop/jekyll-theme-chirpy-master/.git': No such file or directory

![image](https://user-images.githubusercontent.com/56101523/91129946-d4ddef80-e678-11ea-9738-24b497758601.png)

I don't idea what happens

**Comment by cotes2020** [comment]
Please add the missing part of the issue template and fill in the information, otherwise this report will not be able to follow up.
