### ISSUE TITLE
Add Custom Icons Library

### ISSUE THREAD

**Issue by tudorjnu** [cotes2020/jekyll-theme-chirpy#1077]
## Description

Hello! I would like to add a custom font library, [academicons](https://jpswalsh.github.io/academicons/) to be more specific. Is there a simple way to do this? So far, I grabbed the static assets, but I am not sure what to do next.

Thank you!

**Comment by cotes2020** [comment]
Their project docs has already provided detailed instructions on how to use their icons. In Chirpy project, you can add their CSS links to the file `_includes/metadata-hook.html`.
