### ISSUE TITLE
can't hide sidebar on mobile website[GH hosted]

### ISSUE THREAD

**Issue by Hans-han** [cotes2020/jekyll-theme-chirpy#1081]
**NOTE:** Before you start, the following should be completed.

- Read [Wiki][wiki] to understand the usage and the correct effect of functional design.
- Make sure no [similar issue(including closed ones)][issues] exists.
- Try to find the answer on [Jekyll Forum][forum] and [StackOverflow][stack_overflow].

[wiki]: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue
[forum]: https://talk.jekyllrb.com/
[stack_overflow]: https://stackoverflow.com/questions/tagged/jekyll

## Description

in mobile website , the sidebar is always on and no menu bar available to hide 

## Operations you have already tried
compare my code with others who used the chirpy templates

## Logs/Screenshots

![IMG_4945](https://github.com/cotes2020/jekyll-theme-chirpy/assets/32208045/d43f0770-8380-4f66-9736-c7535739513e)
![IMG_4946](https://github.com/cotes2020/jekyll-theme-chirpy/assets/32208045/d674bce8-9d09-4bd0-b14d-e83ca9609316)

**Comment by jjikin** [comment]
I am experiencing the same issue. Can you help how you solved it?
