### ISSUE TITLE
Updating to new version from starter - update critical files

### ISSUE THREAD

**Issue by DylanDijk** [cotes2020/jekyll-theme-chirpy#1088]
## Description

I want to update from `5.4.0` to `6.0.1`, and was wondering what the best way is to update critical files.

## What documentation says:

In the [upgrade guide](https://github.com/cotes2020/jekyll-theme-chirpy/wiki/Upgrade-Guide) within the [wiki](https://github.com/cotes2020/jekyll-theme-chirpy/wiki) it describes how to upgrade to a newer version of the template. 

It mentions:

> As the version upgrades, the critical files (for details, see the [startup template](https://github.com/cotes2020/chirpy-starter)) and configuration options will change. We can use the GitHub API to get the file changes in the version upgrade.

So I want to upgrade from `5.4.0` to `6.0.1`, so [this url](https://github.com/cotes2020/chirpy-starter/compare/v5.4.0...v6.0.1) shows the corresponding changes. But, I am not sure how to use this url to update the files.

## Similar issue

In [this issue](https://github.com/cotes2020/jekyll-theme-chirpy/issues/1058) they recommend:

> to use git to merge upstream

## Operations already tried

So following the recommendation of the issue I linked above, I set the [chirpy repo](https://github.com/cotes2020/jekyll-theme-chirpy) as an upstream remote, and then merged the tag v6.0.1 with `git merge v6.0.1 --allow-unrelated-histories`.

```
git remote add upstream git@github.com:cotes2020/jekyll-theme-chirpy.git
git fetch upstream
git merge v6.0.1 --allow-unrelated-histories
```

But this then gives multiple merge conflicts with files that I have customised, for example, I changed the timezone in the `_config.yml` file. I also get conflicts with my favicon files (not sure what is going on there).

So, should I just deal with conflicts manually, or am I missing something and there is a better way to do this.

Thanks

**Comment by cotes2020** [comment]
Hi there, GitHub's dynamic URL allows you to observe all file changes on the browser. If you prefer to get updates locally, of course you can use Git.

The update of the critical files in the Wiki is for `chirpy-starter`, why do you set the source repository (_jekyll-theme-chirpy_) as upstream instead of the starter repository?

**Comment by DylanDijk** [comment]
I changed the source repository to jekyll-theme-chirpy and tried to merge, as I did in my original issue, but I get the same issue with the conflicts.
What is the best way to get the updates? Do you just apply the changes in _Github's dynamic URL_ manually?

I just want to know what the recommended workflow is for updating to a newer version, or do you just update the version number in the Gemfile.

Thanks

**Comment by NichtsHsu** [comment]
Set upstream to [chirpy-starter](https://github.com/cotes2020/chirpy-starter) instead of jekyll-theme-chirpy.

**Comment by DylanDijk** [comment]
@NichtsHsu When I try with chirpy-starter set as upstream, I still get the conflicts which requires many manual ammendments. Is there a better way to do this?

**Comment by BigBrotherJu** [comment]
@DylanDijk Conflicts are expected, you just have to solve them manually.

**Comment by Freedom89** [comment]
I tried to follow these instructions, how do I update the submodule assets/lib so I can run things locally before deploying? 

Vscode editor does not allow me to edit `lib`, not sure how I can update this portion
