### ISSUE TITLE
ToC is not working 

### ISSUE THREAD

**Issue by real2u2l8** [cotes2020/jekyll-theme-chirpy#1090]
## Description

I aleady run  `npm install build ` and bundle update also nodejs, npm is latest but ToC is not working

## Operations you have already tried

`
npm install && npm run build 
bundle update
`
<img width="99" alt="image" src="https://github.com/cotes2020/jekyll-theme-chirpy/assets/42805229/55edd957-6083-4406-acb4-99e6583c5700">
<img width="49" alt="image" src="https://github.com/cotes2020/jekyll-theme-chirpy/assets/42805229/c0947874-363c-44b6-af97-90d4fe3180fb">
<img width="108" alt="image" src="https://github.com/cotes2020/jekyll-theme-chirpy/assets/42805229/b4d6079e-a938-45f0-8d60-cdd6f1d64a60">

anyway that mean is problems something?
<img width="772" alt="image" src="https://github.com/cotes2020/jekyll-theme-chirpy/assets/42805229/97cce9fc-8b5f-4a30-9a8c-374dc4b76cb7">

## Logs/Screenshots

<img width="608" alt="image" src="https://github.com/cotes2020/jekyll-theme-chirpy/assets/42805229/4eaefef5-9182-49ac-8351-973fc0836d58">

### check my blog on here

 https://real2u2l8.github.io/posts/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0%EC%97%90-%EC%95%9E%EC%84%9C-%EB%B3%B4%EC%95%88-%EA%B4%80%EB%A0%A8/

**Comment by lyducka** [comment]
I have the same question, I have been deleting the repo and fork again, it also does not work.

**Comment by hahaha1110** [comment]
i think your ` /assets/js/dist/ ~~.min.js` is wrong or dosen't exist

if your error like this ,

```
- _site/404.html
  *  internal script /assets/js/dist/page.min.js does not exist (line 1)
- _site/about/index.html
  *  internal script /assets/js/dist/page.min.js does not exist (line 1)
- _site/archives/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/categories/git/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/categories/index.html
                  .
                  .
                  .
                  .
HTML-Proofer found 10 failures!
Error: Process completed with exit code 1.
```

after run `npm install` and run this script
```
NODE_ENV=production npx rollup -c --bundleConfigAsCjs
```
and remove or comment out  `assets/js/dist` of the  `.gitignore` file like this

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/51695122/1ba7a861-3ee3-46a4-9285-a5fc6ac4e56f)

then, commit & push to git

**Comment by lyducka** [comment]
> i think your ` /assets/js/dist/ ~~.min.js` is wrong or dosen't exist
> 
> if your error like this ,
> 
> ```
> - _site/404.html
>   *  internal script /assets/js/dist/page.min.js does not exist (line 1)
> - _site/about/index.html
>   *  internal script /assets/js/dist/page.min.js does not exist (line 1)
> - _site/archives/index.html
>   *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
> - _site/categories/git/index.html
>   *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
> - _site/categories/index.html
>                   .
>                   .
>                   .
>                   .
> HTML-Proofer found 10 failures!
> Error: Process completed with exit code 1.
> ```
> 
> after run `npm install` and run this script
> 
> ```
> NODE_ENV=production npx rollup -c --bundleConfigAsCjs
> ```
> 
> and remove or comment out `assets/js/dist` of the `.gitignore` file like this
> 
> ![image](https://user-images.githubusercontent.com/51695122/245974531-1ba7a861-3ee3-46a4-9285-a5fc6ac4e56f.png)
> 
> then, commit & push to git

I use the GitHub pages and action auto deploy to pages, how to run the script 'NODE_ENV=production npx rollup -c --bundleConfigAsCjs'

Thank you so much

**Comment by real2u2l8** [comment]
> i think your ` /assets/js/dist/ ~~.min.js` is wrong or dosen't exist
> 
> if your error like this ,
> 
> ```
> - _site/404.html
>   *  internal script /assets/js/dist/page.min.js does not exist (line 1)
> - _site/about/index.html
>   *  internal script /assets/js/dist/page.min.js does not exist (line 1)
> - _site/archives/index.html
>   *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
> - _site/categories/git/index.html
>   *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
> - _site/categories/index.html
>                   .
>                   .
>                   .
>                   .
> HTML-Proofer found 10 failures!
> Error: Process completed with exit code 1.
> ```
> 
> after run `npm install` and run this script
> 
> ```
> NODE_ENV=production npx rollup -c --bundleConfigAsCjs
> ```
> 
> and remove or comment out `assets/js/dist` of the `.gitignore` file like this
> 
> ![image](https://user-images.githubusercontent.com/51695122/245974531-1ba7a861-3ee3-46a4-9285-a5fc6ac4e56f.png)
> 
> then, commit & push to git

Unfortunately, my repo already have .js files also nodejs, npm is latest..
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/42805229/7187e446-44d5-43ac-91ba-40ad317a27d6)

**Comment by Xallt** [comment]
I don't know if this is helpful, but took some time for me to figure out in https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/_includes/toc.html you can see how at least an H2 / H3 heading has to be present for the Table of Contents to be summoned. If your post has only H1 headings, no Table of Contents is created

**Comment by huccihuang** [comment]
> I don't know if this is helpful, but took some time for me to figure out In https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/_includes/toc.html you can see how at least an H2 / H3 heading has to be present for the Table of Contents to be summoned. If your post has only H1 headings, no Table of Contents is created

thanks, u help me a lot
