### ISSUE TITLE
please help me make links open in new tabs by default

### ISSUE THREAD

**Issue by sublimeclemency** [cotes2020/jekyll-theme-chirpy#1093]
please help me make links open in new tabs by default. in posts, links don't open in new tabs. how to customize this?

also, i need help on changing the color of links when hovering. i didn't find that anywhere in `_sass`...

thanks in advance!

**Comment by NichtsHsu** [comment]
Try [jekyll-target-blank](https://github.com/keithmifsud/jekyll-target-blank).

**Comment by sublimeclemency** [comment]
thanks @NichtsHsu !
