### ISSUE TITLE
Preview Images appear to load indefinitely

### ISSUE THREAD

**Issue by itswzyss** [cotes2020/jekyll-theme-chirpy#1100]
**NOTE:** Before you start, the following should be completed.

- Read [Wiki][wiki] to understand the usage and the correct effect of functional design.
- Make sure no [similar issue(including closed ones)][issues] exists.
- Try to find the answer on [Jekyll Forum][forum] and [StackOverflow][stack_overflow].

[wiki]: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue
[forum]: https://talk.jekyllrb.com/
[stack_overflow]: https://stackoverflow.com/questions/tagged/jekyll

## Description

Any image specified as a preview image appears to load forever unless the page is reloaded multiple times. Using regular images in the body of posts / pages have no issue. I tried both local and remote hosting for preview images - no change.

## Operations you have already tried

- Clear browser cache thinking it was a local issue
- Try local image path rather than remote -- same issue
- Double-check wiki and getting started post to make sure I didn't miss something

## Logs/Screenshots

https://github.com/cotes2020/jekyll-theme-chirpy/assets/25228751/1e4c39a2-bab3-4035-9748-97e5c22e0cd9

https://github.com/cotes2020/jekyll-theme-chirpy/assets/25228751/aeb72803-474b-4239-b0f2-56c00f3555f4

**Comment by itswzyss** [comment]
Just after making this post, I realized that this seems to only affect Google Chrome v114.0.5735.134. Edge and Firefox don't seem to show this issue at all.

**Comment by clearbluejar** [comment]
seeing the same on my site... Chrome 114.0.5735.133

**Comment by clearbluejar** [comment]
seemed to resolve after closing the browser. could have been some issue with the cache as I was debugging a liveserver preview of the site.

**Comment by itswzyss** [comment]
@clearbluejar I thought the same, however I was able to replicate this across multiple devices unrelated to the development process 🤔

**Comment by timothystewart6** [comment]
It also happens on Mobile Safari on the image image preview and the post image

**Comment by timothystewart6** [comment]
> It also happens on Mobile Safari on the image image preview and the post image

Just reporting back.  It's gone now.  Must have been caching from cloudflare.  Seems to have cleared itself up for me with mobile Safari

**Comment by itswzyss** [comment]
Thanks for checking back in -- I also use Cloudflare and forgot how aggressive their caching can be. I'll tinker with that and report my findings.

-------- Original Message --------

**Comment by itswzyss** [comment]
> @timothystewart6 Thanks for checking back in -- I also use Cloudflare and forgot how aggressive their caching can be. I'll tinker with that and report my findings.

Cleared browser cache and also purged cache on my domain -- still seeing the same issue. Even when trying to break it, I can't replicate this on Firefox. Chrome on Desktop and Mobile tho, consistently breaks.

**Comment by sublimeclemency** [comment]
same. i use chrome, and the images sometimes load infinitely. :(

**Comment by cotes2020** [comment]
When the browser loads the image from the cache, the `lazyloaded` event is not fired, so the current JS logic cannot properly remove the shimmer effect.

https://github.com/cotes2020/jekyll-theme-chirpy/blob/4fe145e9809ee1b370d9891135939534751462d0/_javascript/modules/components/img-lazyload.js#L10-L15

**Comment by timothystewart6** [comment]
> When the browser loads the image from the cache, the `lazyloaded` event is not fired, so the current JS logic cannot properly remove the shimmer effect.
> 
> https://github.com/cotes2020/jekyll-theme-chirpy/blob/4fe145e9809ee1b370d9891135939534751462d0/_javascript/modules/components/img-lazyload.js#L10-L15

Great find!  Thank you!

**Comment by itswzyss** [comment]
> When the browser loads the image from the cache, the `lazyloaded` event is not fired, so the current JS logic cannot properly remove the shimmer effect.
> 
> https://github.com/cotes2020/jekyll-theme-chirpy/blob/4fe145e9809ee1b370d9891135939534751462d0/_javascript/modules/components/img-lazyload.js#L10-L15

I see -- I was wondering if this had something to do with caching. Is there an easy way to mitigate this issue or is this just something we'll have to deal with? Digging into js is definitely a bit outside of what I can mess with.

**Comment by Rootjhon** [comment]
after update [df8ff54](https://github.com/cotes2020/jekyll-theme-chirpy/commit/df8ff546ec1c8d21a3d25e0124665001fcf756f3)

issues still happen in post page. (cover image)

```
---
title: xxxx
date: xxx
categories: [x,y]
image:
  path:  the pic's url 
---
```

**Comment by Mohamed3nan** [comment]
same problem!

**Comment by jinhg0214** [comment]
It's a temporary measure, but I solved it like this.

In the shimmer class of the` _sass/addon/common.scss/commons.scss` file
```
&::before{
    content: '';
    // position: absolute;
    // background: var(--shimmer-bg);
    // height: 100%;
    // width: 100%;
    // -webkit-animation: shimmer 1.3s infinite;
    // animation: shimmer 1.3s infinite;
}
```
It was resolved by annotating the inside part.
