### ISSUE TITLE
Adding an applause button to posts

### ISSUE THREAD

**Issue by MVP-Harry** [cotes2020/jekyll-theme-chirpy#1102]
## Description

I want a way to receive quick feedback from my audience. Although writing comments is a viable option, most people likely won't take the efforts to do so, while a "upvote/thumbs-up/applause" button would be perfect for that purpose.

## Operations you have already tried

* I've read the chirpy tutorials, and didn't find such a feature
     * I did notice that the giscus comments support upvote/emoji features, but I'm not exactly sure if that's going to help
* I found [applause-button](https://applause-button.com/), which seems like exactly what I want
* I also found [this blog](https://lazyren.github.io/devlog/add-applause-button-for-jekyll-post.html) that explains how to add the applause button to a jekyll post

Unfortunately, I wasn't able to implement the last two resources that I've found (I *really* don't know much when it comes to web developments :cry: ), as the methods described don't quite work because I'm using chirpy. 

Any help would be appreciated! Thanks in advance!

**Comment by otzslayer** [comment]
Like this?

**Comment by otzslayer** [comment]
If you're looking at my blog and want something like this, take a look at the following commits.

https://github.com/otzslayer/otzslayer.github.io/commit/6751750647eedb716a7f787ce61700e9f85dc127
https://github.com/otzslayer/otzslayer.github.io/commit/60eff6cc93f79b588e41c8cbbb95554ec51ef7eb

**Comment by sublimeclemency** [comment]
thank you @otzslayer for your example repository! i found it helpful for adding this feature.

**Comment by MVP-Harry** [comment]
@otzslayer thank you for helping! I checked out your commit and tried to replicate it (you can see in this [this commit](https://github.com/MVP-Harry/mvp-harry.github.io/commit/ee7351d3e663f9bbaca15ec887785f3a28c5dead)). However, instead of showing the applause button as expected, it only shows a colored line (see image below).

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/64049111/f53df1f8-4158-4078-a2f7-e0589681f95a)

Do you know what might be causing the issue? Thank you so much!

**Comment by MVP-Harry** [comment]
I was able to fix the problem after a *long* time :laughing: I think it's because I used the chirpy starter pack when I first started creating the blog, which caused some issues with the commit that @otzslayer provided earlier! 

Closing the issue since it's fixed :+1:

**Comment by tofulim** [comment]
@MVP-Harry i had same issue and fix it by changing applause-botton's location at post.html
