### ISSUE TITLE
Convert to Hugo

### ISSUE THREAD

**Issue by ichsanull** [cotes2020/jekyll-theme-chirpy#1106]
## Description

Does anyone want to try converting this template to hugo?

**Comment by khoguan** [comment]
Yes, I do. But I am still a newbie web developer. Currently my blog using Jekyll + Chirpy theme has more than one thousand articles. It takes more than 100 sec. to build my site.

**Comment by Hentioe** [comment]
When using Jekyll, I use the Chirpy theme. Then I switched to Hugo and developed my own theme, which borrows heavily from Chirpy's design.

Visit here to see how effective it is: https://blog.hentioe.dev/

My blog theme is currently not open source, and maintaining an open source Hugo theme is exhausting. You can star or watch the [Hentioe/hugo-tranquil-theme](https://github.com/Hentioe/hugo-tranquil-theme) repository to let me know that someone is looking at it and I'll have ideas for open source.
