### ISSUE TITLE
One Icon-Border Intended?

### ISSUE THREAD

**Issue by gypark23** [cotes2020/jekyll-theme-chirpy#1109]
**NOTE:** Before you start, the following should be completed.

- Read [Wiki][wiki] to understand the usage and the correct effect of functional design.
- Make sure no [similar issue(including closed ones)][issues] exists.
- Try to find the answer on [Jekyll Forum][forum] and [StackOverflow][stack_overflow].

[wiki]: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue
[forum]: https://talk.jekyllrb.com/
[stack_overflow]: https://stackoverflow.com/questions/tagged/jekyll

## Description

Hi, I just had a quick question on the design on the sidebar-bottom icons;
Was it intended to only have one icon-border between contrast button and the github button?
And no icon-border between other icons?

I have a easy fix in my mind but wasn't sure if it was intended so I wanted to make sure before I make a PR.

<img width="235" alt="스크린샷 2023-06-26 오후 10 16 35" src="https://github.com/cotes2020/jekyll-theme-chirpy/assets/68811862/e85070f3-01e6-4af9-ae0e-c3fc29f4bf4b">

**Comment by cotes2020** [comment]
Obviously intentional

**Comment by gypark23** [comment]
Got it. Ill close the issue.
