### ISSUE TITLE
is there a problem with chirpy doc website?

### ISSUE THREAD

**Issue by zarif59** [cotes2020/jekyll-theme-chirpy#1118]
website chirpy look like this from my computer.

![Screenshot from 2023-06-29 23-04-50](https://github.com/cotes2020/jekyll-theme-chirpy/assets/38664661/45ead9ea-c898-4b5b-b9d4-7b1154c72039)

**Comment by zarif59** [comment]
looks like the problem come from the cdn. the website loaded properly if i using vpn, i think my isp is the problem. 
![Screenshot from 2023-06-30 21-11-52](https://github.com/cotes2020/jekyll-theme-chirpy/assets/38664661/4fc1a838-c4fc-4014-94ab-a27878178049)

**Comment by Mohamed3nan** [comment]
I think it's due to static-assets not activated

**Comment by zarif59** [comment]
yeah, i got it fix by using the static assests. apparently my ISP block the CDN website. all good now.
