### ISSUE TITLE
How do i configure the markdown to use some specific markdown feature?

### ISSUE THREAD

**Issue by Freedom89** [cotes2020/jekyll-theme-chirpy#1119]
I was using mkdown/pymdown previously and I noticed some markdown features are not compatible with kramdown. 

For example, I like to use the tabbed markdown feature shown here: https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/?h=

or the details feature:

https://facelessuser.github.io/pymdown-extensions/extensions/details/

I know I can do this with html or plugins such as jekyll tabs like https://github.com/Ovski4/jekyll-tabs.

**Comment by NichtsHsu** [comment]
Please check [Markdown Options chapter of the Jekyll doc](https://jekyllrb.com/docs/configuration/markdown/).
