### ISSUE TITLE
`tools/run.sh` Not updating website after changes

### ISSUE THREAD

**Issue by bcaddy** [cotes2020/jekyll-theme-chirpy#112]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [ ] I found the bug on the latest code of `master` branch.

## Describe the bug

When I run `tools/run.sh` and then make changes to the markdown those changes are not automatically reflected in the browser. I can force them to be reflected by using control-c and rerunning the command.

### To Reproduce
1. fork
2. git clone
3. run tools/init.sh
4. run tools/run.sh
5. start editing

### Expected behavior

Expected the webpage to automatically update with changes

### Desktop

- OS: MacOS 10.15.6
- Browser: safari
- Version: 13.1.2

### Additional context
I had this issue with a different theme as well where I was running `jekyll serve --watch --force_polling --livereload` and had the same issue. Am I doing something wrong?

**Comment by cotes2020** [comment]
Please read the docs, alright?

![Annotation 2020-08-28 045125](https://user-images.githubusercontent.com/11371340/91493869-85065f00-e8ea-11ea-83b3-cb557da33f83.png)

**Comment by bcaddy** [comment]
I did that. Installing fswatch didn't resolve the issue.

**Comment by bcaddy** [comment]
And it's working now for some reason. Sorry for wasting your time

**Comment by bcaddy** [comment]
Upon further investigation there does appear to be some kind of bug here that has to do with the directory name.  When I use `run.sh -r` in a directory named `bcaddy.github.io` it does not refresh as expected. If I simply change the directory name to `jekyll-theme-chirpy` it works fine. Any ideas?

**Comment by cotes2020** [comment]
You should point out the details of naming the folder `xxx.github.io` when submitting this issue, so as to hit the bug.

The problem is caused by improper use of regular expressions, it will mistakenly ignore file changes that include the path of `.git`. It has now been fixed.

**Comment by honnix** [comment]
I also have problems regarding `fswatch`.

First all, here is my env:

* Ubuntu 20.04
* fswatch 1.14.0
* master branch

`fswatch` as started by `fswatch -0 -r -e "/\..*" "$WORK_DIR" | xargs -0 -I {} bash "./${SYNC_TOOL}" {} "$WORK_DIR" . &` doesn't monitor subfolders, so I had to use `-r`. Then `fswatch` could report file change, but multiple/many times for the same file and that resulted recreating pages many times; and what seemed to be worse was, upon recreating pages, something triggered `fswatch` to detect the same file change over and over again, and it became a dead loop.

**Comment by cotes2020** [comment]
Hi @honnix,

`fswatch` uses the inotify monitor by default on Linux. its monitoring log is not as fine as macOS. I have improved the compatibility when using fswatch (see the commit above). Thank you for reporting this cross-platform issue.

**Comment by honnix** [comment]
@cotes2020 Looks awesome! Thanks for fixing this. I will pick up this change and report back.

**Comment by honnix** [comment]
This works. Thanks for fixing it.

**Comment by honnix** [comment]
Hmm, maybe not fully. I left it running for a while, then got:
```
Event queue overflow.                                                                                                                          │
Status code: 1
```
I checked that `fswatch` died.

**Comment by cotes2020** [comment]
>```
>Event queue overflow.                                                                                                                          │
>Status code: 1
>```

Maybe the flag `--allow-overflow` of *fswatch* should be used.

**Comment by ricardo-dlc** [comment]
Any updates on this? I still have problems even with fswatch installed. No restart after change on file but the file under .container its updated.
