### ISSUE TITLE
New page not rendering correctly, html in the wrong place.  

### ISSUE THREAD

**Issue by BernardMcWeeney** [cotes2020/jekyll-theme-chirpy#1125]
## Describe the bug
I added a custom tab called journal.md, that has a custom layout called journal
the custom layout is an exact replica of the home.html with an additional where clause to filter for a certain post . I want to display all posts with the custom post type called journal defined in their front matter. 
When you go to the Journal page, the correct posts are displayed and nearly everything is correct apart from the incorrect rendering of the feature image and the link does not wrap around the post card.

upon further inspection, when looking at the html, all expected items are actually built but just incorrectly so. The feature image and link are all there in the html code.

## To Reproduce

1. Create a new layout with the same exact contents of the home.html layout
2. Create new tab and change the layout to the new layout created in step 1
3. build the site
4. visit the new tab created, you will see the problem

## Expected behavior
Go to the new tab and see the exact same thing as the home page but this is not happening

## Logs/Screenshots

This is the home.html page and is correct
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/99593468/4023e91a-0f17-4165-ac3c-7cba35528070)

This is the journal.html page and is incorrect
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/99593468/2fb43f33-e140-4884-8469-38dbb2b2b477)

See that the feature image is not rendered and if you were to click on the post, there is no link to go to. However when you inspect the page, you can see that the feature image and links are there but they are not in their correct position.

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/99593468/fe9f760f-d771-4db8-9bfa-cfaafa9ea48e)
see here, the post preview content should be within this <a> tag but instead its just closed prematurely

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/99593468/e39bd840-390a-4886-b875-ae07be7822b3)
The same for the feature image 

## Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |     ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [arm64-darwin22]    |
| `gem -v`                          |    3.4.12     |
| `bundle -v`                       |    Bundler version 2.4.12     |
| `bundle info jekyll-theme-chirpy` |     jekyll-theme-chirpy (6.0.1)    |

**Comment by Mohamed3nan** [comment]
For better debugging, I recommend first running it locally and then trying to use local "Static Assets"

**Comment by BernardMcWeeney** [comment]
> For better debugging, I recommend first running it locally and then trying to use local "Static Assets"

Thank you @Mohamed3nan, However the problem still persists even with Static Assets enabled.

**Comment by NichtsHsu** [comment]
The home page is special.

1. In many `*.html` files there are special handlings for the `home` layout.
2. The paginator of Jekyll can only paginate for the `index.html` (which uses `home` layout). The [`jekyll-paginate-v2`](https://github.com/sverrirs/jekyll-paginate-v2) might solve the problem but it is not supported by Github Pages.

**Comment by BernardMcWeeney** [comment]
> The home page is special.
> 
> 
> 
> 1. In many `*.html` files there are special handlings for the `home` layout.
> 
> 2. The paginator of Jekyll can only paginate for the `index.html` (which uses `home` layout). The [`jekyll-paginate-v2`](https://github.com/sverrirs/jekyll-paginate-v2) might solve the problem but it is not supported by Github Pages.

Thank you @NichtsHsu, I'll investigate the paginator, at-least I have narrowed it down some what.
