### ISSUE TITLE
[Suggestion] remove submodule and include contents directly "chirpy-static-assets"

### ISSUE THREAD

**Issue by Mohamed3nan** [cotes2020/jekyll-theme-chirpy#1127]
## Is your feature request related to a problem? Please describe
This theme is really good, but the complexity of installing it making is a bit confusing!
Especially with submodules and static assets
If you take a look at everyone who tries to install this theme you will find that the site is not rendered due to the submodule
Even the demo site! :D

## Describe the solution you'd like
Just remove the submodule and include contents directly "chirpy-static-assets"

**Comment by Mohamed3nan** [comment]
Also how to upgrade the static assets in case of self host?

**Comment by NichtsHsu** [comment]
I don't think it's possible, the chirpy theme uses CDN hosting assets by default, and static assets are a useless burden for those using default configuration.

**Comment by Mohamed3nan** [comment]
> I don't think it's possible, the chirpy theme uses CDN hosting assets by default, and static assets are a useless burden for those using default configuration.
> 

Yea, right

> > Also how to upgrade the static assets in case of self host?
> 
> I think you just need to do a `git pull` on the `assets/lib` directory.

I mean how to upgrade these  `assets/lib` directory, some of them are outdated, I try to upgrade them but some new versions do not use .map files which generate some testings errors when deploying site
