### ISSUE TITLE
Making images responsive

### ISSUE THREAD

**Issue by bcaddy** [cotes2020/jekyll-theme-chirpy#113]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description
Is there a way to make image size responsive for images embedded in posts without adding a new plugin?

**Comment by bcaddy** [comment]
Example. The whole image should be visible but only the top left 2/3rds or so is
![Screen Shot 2020-08-27 at 17 31 08](https://user-images.githubusercontent.com/41171425/91496979-1cd46080-e88b-11ea-9abe-cd0f5cc36b36.png)

**Comment by cotes2020** [comment]
@bcaddy This can be achieved through CSS.

**Comment by bcaddy** [comment]
Could you elaborate on that? I'm not a web dev and the whole point of me using Jekyll themes is to not deal too much with CSS and HTML.

**Comment by bcaddy** [comment]
Images in posts appear to be responsive but not in tabs. Is there a simple way to just make images in tabs responsive as well?

**Comment by cotes2020** [comment]
> Images in posts appear to be responsive but not in tabs. Is there a simple way to just make images in tabs responsive as well?

That's a good point, I will update the `page` layout later. BTW, I am not a web dev either :)

**Comment by bcaddy** [comment]
Thanks! 

You're closer than I am :) I just write scientific software for simulations and barely know the difference between HTML and CSS

**Comment by cotes2020** [comment]
Done, please checkout the latest code.

**Comment by bcaddy** [comment]
That fixed it. Thanks!
