### ISSUE TITLE
not working sidebar menu and search

### ISSUE THREAD

**Issue by LeeKangW** [cotes2020/jekyll-theme-chirpy#1134]
## Description

1. The sidebar menu button does not work on the mobile screen.  
2. search system not working  
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/48194683/e86aa5bf-0caf-456a-baa6-8f3375256292)  

## Operations you have already tried

I received a new one because it seemed to be a javascript problem, but the problem was not solved.

## Logs/Screenshots

please check my website on mobile
[web site link](https://leekangw.github.io/)

**Comment by azhu021** [comment]
Obviously, you break the relevant source code during making custom modification. Try rebuild a new repo with the original source code.

**Comment by NichtsHsu** [comment]
I'm guessing you never ran `bash tools/init`. One of the parts of this script is to generate various `*.min.js` files and submit them, but I don't see these files in your repo.

I recommend that you re-fork this repository to avoid missing more, but if you are willing to generate these files manually, please refer to the following process:

```
npm install
npm run build
git add -f assets/js/dist/
```

**Comment by LeeKangW** [comment]
> I'm guessing you never ran `bash tools/init`. One of the parts of this script is to generate various `*.min.js` files and submit them, but I don't see these files in your repo.
> 
> I recommend that you re-fork this repo to avoid missing more, but if you prefer to generate these files manually, please refer to the following process:
> 
> ```
> npm install
> npm run build
> git add -f assets/js/dist/
> ```

like you said, i didn't run `bash tools/init`.  
so i will try to run `bash tools/init` or `npm install` process.

thanks. NichtsHsu. 👍

**Comment by ChanJoon** [comment]
> Thank you all comments.
> 
> like NichtsHsu said, i didn't run `bash tools/init`. so i will try to run `bash tools/init` or `npm install` process.
> 
> if i can't fix it. i will try re-fork again.

Hi I have a problem that search is not working. I saw your page and it looks now working.
Can you share how did you solve your problem?

**Comment by LeeKangW** [comment]
> > Thank you all comments.
> > like NichtsHsu said, i didn't run `bash tools/init`. so i will try to run `bash tools/init` or `npm install` process.
> > if i can't fix it. i will try re-fork again.
> 
> Hi I have a problem that search is not working. I saw your page and it looks now working. Can you share how did you solve your problem?


Hi.
did you try running `bash tools/init`?

if not fixed, please read my post([link](https://leekangw.github.io/posts/100/)).

**Comment by ChanJoon** [comment]
Thanks! @LeeKangW  You saved my searching bar :smile: 

I did `bash tools/init` in the getting started. There was a problem but I just ignored.
I solved after watching your post 'Javascript build' section.

I will share the problem and how I solved.
The reason why the error happened in the bash script was `npx rimraf assets/js/dist` in package.json.

This is the problem of Node.js version. Since `npm rimraf` command was not working in my local, I reinstalled Node.js using nvm.

Then
```bash
npm install
npm run build
```

This creates javascript files in `assets/js/dist/`. Before that, I copied those files in the previous releases e.g. 5.2.2.
But created files are bit different.
```bash
	modified:   assets/js/dist/categories.min.js
	modified:   assets/js/dist/commons.min.js
	modified:   assets/js/dist/home.min.js
	modified:   assets/js/dist/misc.min.js
	modified:   assets/js/dist/page.min.js
	modified:   assets/js/dist/post.min.js
	deleted:    assets/js/dist/pvreport.min.js
```

Thanks again.

**Comment by ntaloventi** [comment]
> Thanks! @LeeKangW You saved my searching bar 😄
> 
> I did `bash tools/init` in the getting started. There was a problem but I just ignored. I solved after watching your post 'Javascript build' section.
> 
> I will share the problem and how I solved. The reason why the error happened in the bash script was `npx rimraf assets/js/dist` in package.json.
> 
> This is the problem of Node.js version. Since `npm rimraf` command was not working in my local, I reinstalled Node.js using nvm.
> 
> Then
> 
> ```shell
> npm install
> npm run build
> ```
> 
> This creates javascript files in `assets/js/dist/`. Before that, I copied those files in the previous releases e.g. 5.2.2. But created files are bit different.
> 
> ```shell
> 	modified:   assets/js/dist/categories.min.js
> 	modified:   assets/js/dist/commons.min.js
> 	modified:   assets/js/dist/home.min.js
> 	modified:   assets/js/dist/misc.min.js
> 	modified:   assets/js/dist/page.min.js
> 	modified:   assets/js/dist/post.min.js
> 	deleted:    assets/js/dist/pvreport.min.js
> ```
> 
> Thanks again.

what nodejs version work?

**Comment by ChanJoon** [comment]
@ntaloventi Sorry for late reply. 
```bash
$ node -v
v18.18.0
```
