### ISSUE TITLE
Subcategories aren't subs!

### ISSUE THREAD

**Issue by Mohamed3nan** [cotes2020/jekyll-theme-chirpy#1135]
**NOTE:** Before you start, the following should be completed.

- Read [Wiki][wiki] to understand the usage and the correct effect of functional design.
- Make sure no [similar issue(including closed ones)][issues] exists.
- Make sure the bug is found in the latest code of the `master` branch.

[wiki]: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue

## Describe the bug

Referring to this [issue](https://github.com/cotes2020/jekyll-theme-chirpy/issues/893):
> ## Background Note
> Post_1
> 
> ```
> categories: [C_1, S_1]
> ```
> 
> Post_2
> 
> ```
> categories: [C_2, S_1]
> ```
> 
> ## Expect
> * Post_1 in  `<url>/categories/C_1/S_1/Post_1`
> * Post_2 in  `<url>/categories/C_2/S_1/Post_2`
> 
> **But,in fact:**
> 
> * Post_1 in  `<url>/categories/S_1/Post_1`
> * Post_2 in  `<url>/categories/S_1/Post_2`
> 
> ## Question
> * Is it a bug or by design?
> * if 'by design', how to reach **SUB**_categories?
> 
> thanks a lot.

The current "categories" tab is not working as expected and showing **wrong** "sub category" because the generated content in _site is all main category and this line in front matter `categories: [TOP_CATEGORIE, SUB_CATEGORIE]` is also wrong and misleading

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/19733801/0bf85eca-dcd7-4d8e-b047-09e87bb848eb)

So in the current situation to remove the confusion and misleading concept "sub category" I suggest removing the subcategory dropdown in the "categories" tab page and make them all main categories (because they are all main in _site) until introducing a real subcategory

Thanks, I hope this makes sense

**Comment by Mohamed3nan** [comment]
Okay btw I changed the logic for it, 
here
```html
---
layout: page
# All the Categories of posts
---

{% include lang.html %}

{% assign HEAD_PREFIX = 'h_' %}
{% assign LIST_PREFIX = 'l_' %}

{% assign group_index = 0 %}

{% assign sort_categories = site.categories | sort %}

{% for category in sort_categories %}
  {% assign category_name = category | first %}
  {% assign posts_of_category = category | last %}

  <div class="card categories">
    <!--category -->
    <div
      id="{{ HEAD_PREFIX }}{{ group_index }}"
      class="card-header d-flex justify-content-between hide-border-bottom"
    >
      <span class="ms-2">
        <i class="far fa-folder{% if posts_of_category.size > 0 %}-open{% endif %}"></i>

        {% capture _category_url %}/categories/{{ category_name | slugify | url_encode }}/{% endcapture %}
        <a href="{{ _category_url | relative_url }}" class="mx-2">{{ category_name }}</a>

        <!-- posts count -->
        {% assign top_posts_size = site.categories[category_name] | size %}
        <span class="text-muted small font-weight-light">      
          {{ top_posts_size }}

          {% if top_posts_size > 1 %}
            {{
              site.data.locales[lang].categories.post_measure.plural
              | default: site.data.locales[lang].categories.post_measure
            }}
          {% else %}
            {{
              site.data.locales[lang].categories.post_measure.singular
              | default: site.data.locales[lang].categories.post_measure
            }}
          {% endif %}
        </span>
      </span>

      <!-- arrow -->
      {% if top_posts_size > 0 %}
        <a
          href="#{{ LIST_PREFIX }}{{ group_index }}"
          data-bs-toggle="collapse"
          aria-expanded="false"
          aria-label="{{ HEAD_PREFIX }}{{ group_index }}-trigger"
          class="category-trigger hide-border-bottom"
        >
          <i class="fa-solid fa-angle-down"></i>
        </a>
      {% else %}
        <span data-bs-toggle="collapse" class="category-trigger hide-border-bottom disabled">
          <i class="fa-solid fa-angle-right"></i>
        </span>
      {% endif %}
    </div>
    <!-- .card-header -->

    <!-- Posts  -->
    <div id="{{ LIST_PREFIX }}{{ group_index }}" class="collapse" aria-expanded="false">
      <ul class="list-group">
        {% for post in posts_of_category %}
          <li class="list-group-item">
            <i class="fa-regular fa-file"></i>
            <a href="{{ post.url | relative_url }}" class="mx-2">{{ post.title }}</a>
            <span class="text-muted small font-weight-light">
              {% include datetime.html date=post.date wrap='span' class='text-muted small' lang=lang %}
            </span>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
  <!-- .card -->

    {% assign group_index = group_index | plus: 1 %}
{% endfor %}
```
Looks good for me!
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/19733801/c3b077c2-b92b-4bd6-a3fa-b3af69ba3668)

Gonna close this now.

**Comment by DylanDijk** [comment]
So this is now just having all categories as main categories?
I also found it misleading that the presentation on the web page made it seem that the subcategories would act as subsets of the categories in the level above.

**Comment by NichtsHsu** [comment]
Like I said in https://github.com/cotes2020/jekyll-theme-chirpy/issues/893#issuecomment-1433998908, this is an issue of `jekyll-archives` plugin. You can also find a third party solution in that comment.

**Comment by DylanDijk** [comment]
@NichtsHsu Ok thank you, does this require all the changes made in this commit?

**Comment by NichtsHsu** [comment]
This commit only does three things:

1. Clone `jekyll-archives` to local `.gems/jekyll-archives` and add subcategories feature,
2. Modify `Gemfile` to point `jekyll-archives` to the local path,
3. Update layout files to suit subcategories.

So the answer is yes, all modifications except the `README.md` are necessary.
