### ISSUE TITLE
Improve the page speed by inline JS / CSS

### ISSUE THREAD

**Issue by JinchaoLove** [cotes2020/jekyll-theme-chirpy#1137]
**NOTE:** Before you start, the following should be completed.

- Read [Wiki][wiki] to understand the usage and the correct effect of functional design.
- Make sure no [similar issue(including closed ones)][issues] exists.
- Make sure the request is based on the latest code in the `master` branch.

[wiki]: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue

## Is your feature request related to a problem? Please describe

The performance of web page is sometimes **slow** in the mobile devices, as analyzed by [PageSpeed Insights](https://pagespeed.web.dev/analysis/https-chirpy-cotes-page/uimvq098uf?form_factor=mobile).

## Describe the solution you'd like

Can the potentially blocked resources / libraries, which require [online](https://cdn.jsdelivr.net/) access, be converted to inline elements?

**Comment by NichtsHsu** [comment]
What you request has already been implemented:

https://github.com/cotes2020/jekyll-theme-chirpy/blob/e8ef69ad1784661c5bb06dbcf530cfa37af63383/_config.yml#L104-L107

**Comment by JinchaoLove** [comment]
> 

That's great! Thanks!
