### ISSUE TITLE
Favicon not updating

### ISSUE THREAD

**Issue by bcaddy** [cotes2020/jekyll-theme-chirpy#114]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [ ] I found the bug on the latest code of `master` branch.

## Describe the bug

I followed the instructions in the docs to replace the favicon then reran `build.sh` and `run.sh`. The favicon didn't update, it's still the Chirpy icon

### To Reproduce

1. follow the docs to replace favicon
2. rebuild and run site
3. the favicon didn't update

### Expected behavior

The favicon to update

### Desktop

- OS: MacOS 10.15.6
- Browser: Safari
- Version: 13.2.1

**Comment by cotes2020** [comment]
I won't let this obvious bug exist, please check your project carefully.

**Comment by bcaddy** [comment]
I did. Many times. Changing the favicon by following the docs isn't rocket science and it didn't work.  I just made a fresh clone of this repo (not my fork of it), ran the `init.sh` script then replace the favicon files and the issue is still there

**Comment by cotes2020** [comment]
Then you should consider clearing your browser's cache.

**Comment by bcaddy** [comment]
That did it. Thank you for your help.
