### ISSUE TITLE
Dark mode with optional change to light

### ISSUE THREAD

**Issue by Mohamed3nan** [cotes2020/jekyll-theme-chirpy#1141]
The main goal is to:

Default to dark mode regardless of the system setting
But allow the user to toggle between dark and light

How to achieve this basic option with the very complex code logic!!!
I really tried but the logic here mode-toggle.html is so complex :/

**Comment by sukhjinder-kumar** [comment]
Maybe only me but can you suggest a use case?

**Comment by Mohamed3nan** [comment]
> Maybe only me but can you suggest a use case?

use case is to give the user the option to select whatever he wants!
some users use light mode in the browser while their system is in dark mode and vice versa..

So it makes sense as the site owner to set a default theme for example dark, and give the user/visitor the option to choose too!

I think all websites working with this logic.

**Comment by 9xN** [comment]
lol i modified the javascript on my site to do exactly this if u wanna check it out

**Comment by Mohamed3nan** [comment]
> 

I checked your repo but actually didn't find it
you are using the default behavior used in chirpy `theme_mode: # [light|dark]`

**Comment by 9xN** [comment]
> > lol i modified the javascript on my site to do exactly this if u wanna check it out
> 
> I checked your repo but actually didn't find it you are using the default behavior used in chirpy `theme_mode: # [light|dark]` So, it will depend on the default theme mode in the visitor browser

no im not i said i modified the actual javascript file itself can you not read?

**Comment by Mohamed3nan** [comment]
> > > lol i modified the javascript on my site to do exactly this if u wanna check it out
> > 
> > 
> > I checked your repo but actually didn't find it you are using the default behavior used in chirpy `theme_mode: # [light|dark]` So, it will depend on the default theme mode in the visitor browser
> 
> no im not i said i modified the actual javascript file itself can you not read?

I see, you edited "mode-toggle.html" but still how to make the default theme "dark" and give the visitor the option to change it?

**Comment by 9xN** [comment]
> > > > lol i modified the javascript on my site to do exactly this if u wanna check it out
> > > 
> > > 
> > > I checked your repo but actually didn't find it you are using the default behavior used in chirpy `theme_mode: # [light|dark]` So, it will depend on the default theme mode in the visitor browser
> > 
> > 
> > no im not i said i modified the actual javascript file itself can you not read?
> 
> I see, you edited "mode-toggle.html" but still how to make the default theme "dark" and give the visitor the option to change it?

it already does that with my code....

**Comment by Mohamed3nan** [comment]
> > > > > lol i modified the javascript on my site to do exactly this if u wanna check it out
> > > > 
> > > > 
> > > > I checked your repo but actually didn't find it you are using the default behavior used in chirpy `theme_mode: # [light|dark]` So, it will depend on the default theme mode in the visitor browser
> > > 
> > > 
> > > no im not i said i modified the actual javascript file itself can you not read?
> > 
> > 
> > I see, you edited "mode-toggle.html" but still how to make the default theme "dark" and give the visitor the option to change it?
> 
> it already does that with my code....

It's not working my brother you can test it with your website too, not the same logic I mentioned

**Comment by 9xN** [comment]
> > > > > > lol i modified the javascript on my site to do exactly this if u wanna check it out
> > > > > 
> > > > > 
> > > > > I checked your repo but actually didn't find it you are using the default behavior used in chirpy `theme_mode: # [light|dark]` So, it will depend on the default theme mode in the visitor browser
> > > > 
> > > > 
> > > > no im not i said i modified the actual javascript file itself can you not read?
> > > 
> > > 
> > > I see, you edited "mode-toggle.html" but still how to make the default theme "dark" and give the visitor the option to change it?
> > 
> > 
> > it already does that with my code....
> 
> It's not working my brother you can test it with your website too, not the same logic I mentioned your website is following the same browser theme, if light then light, if dark then dark

youre retarded

**Comment by Mohamed3nan** [comment]
any suggestions?

**Comment by 9xN** [comment]
do what i did but this dude is too incompetent to understand how

**Comment by Mohamed3nan** [comment]
> do what i did but this dude is too incompetent to understand how

instead of talking and speaking with bad language, show us HOW?

for your information, I reported you and I'm ready to report you again if you say anything not polite

**Comment by 9xN** [comment]
why would i tell someone so clueless they just go about reporting people for no reason

**Comment by Mohamed3nan** [comment]
the reason for reporting you is that you are not polite
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/19733801/6cc008f3-c541-4312-9bb3-45a10e4718f0)

and I'm gonna report you again

**Comment by 9xN** [comment]
> the reason for reporting you is that you are not polite ![image](https://user-images.githubusercontent.com/19733801/258542844-6cc008f3-c541-4312-9bb3-45a10e4718f0.png)
> 
> and I'm gonna report you again

thats abuse of the system ill be reporting you as well you clueless incompetent human being

**Comment by Mohamed3nan** [comment]
Report me for what? I didn't say anything bad about you, but you are keeping harassing me, you can just move on and not reply but you keep harassing me for no reason, and that's why I reported you

**Comment by 9xN** [comment]
im not harassing you stop speaking if you have nothing intelligent to say

**Comment by Mohamed3nan** [comment]
I'm the issue creator, So I have the right to write as I like, it's not against Github Rules
You again keep harassing me, I'm waiting for the report status by the way..

**Comment by 9xN** [comment]
> I'm the issue creator, So I have the right to write as I like, it's not against Github Rules You again keep harassing me, I'm waiting for the report status by the way..

not gonna happen bubba also im not harassing you once again so keep crying and get back to me when you give your head a shake

**Comment by Mohamed3nan** [comment]
> > I'm the issue creator, So I have the right to write as I like, it's not against Github Rules You again keep harassing me, I'm waiting for the report status by the way..
> 
> not gonna happen bubba also im not harassing you once again so keep crying and get back to me when you give your head a shake

👍🏻

**Comment by cotes2020** [comment]
Duplicate of #156

It's an old and repetitive topic, but I'm willing to take a stand one more time: this need is out of the norm. A website shouldn't allow a first-time user to see a dark mode page when his/her system is in light mode.

**Comment by Mohamed3nan** [comment]
> Duplicate of #156
> 
> It's an old and repetitive topic, but I'm willing to take a stand one more time: this need is out of the norm. A website shouldn't allow a first-time user to see a dark mode page when his/her system is in light mode.

ok thanks

**Comment by Yn3-3xh** [comment]
> 처음 사용자가 다크 모드 페이지를 볼 수 있도록 허용해서는 안 됩니다.

Thank you

**Comment by seonb2n** [comment]
Hi. I found out how to set up default dark mode regardless what is system prefer.
This need is out of the norm though, but if you still want to set it up, try this method.

You don't need to modify _config.yml.
You should edit mode-toggle.html file.

_config.yml
`theme_mode: # [light|dark]`

mode-toggle.html
```html
    constructor() {
      // if (this.hasMode) {
      //   if (this.isDarkMode) {
      //     if (!this.isSysDarkPrefer) {
      //       this.setDark();
      //     }
      //   } else {
      //     if (this.isSysDarkPrefer) {
      //       this.setLight();
      //     }
      //   }
      // }
      this.setDark();

      let self = this;

      /* always follow the system prefers */
      this.sysDarkPrefers.addEventListener('change', () => {
        if (self.hasMode) {
          if (self.isDarkMode) {
            if (!self.isSysDarkPrefer) {
              self.setDark();
            }
          } else {
            if (self.isSysDarkPrefer) {
              self.setLight();
            }
          }

          self.clearMode();
        }

        self.notify();
      });
    } /* constructor() */
```
