### ISSUE TITLE
not showing author name

### ISSUE THREAD

**Issue by safinakib** [cotes2020/jekyll-theme-chirpy#1143]
---
title: Alphonso mango production highest among all varieties
author:  Robert d. jr
date: 2023-07-22 01:56:00 +0600
categories: [Mango,fruits]
tags: [agriculture,food production,farmer] #TAG names should be lowercase
---
 author name not showing 
author name only shows when i set author name to cotes then it says Cotes Chung whats going on i can't understand
also im using a default git jekyll action the action script in the repo doesn't work for me both in jekyll-theme-chirpy and chirpy-starter for some reason.

**Comment by sublimeclemency** [comment]
hi @safinakib
to properly set author name for posts, remember to edit `_data/authors.yml` to be similar to https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/_data/authors.yml
jekyll is confusing, really.
good luck!

**Comment by safinakib** [comment]
[sublimeclemency](https://github.com/sublimeclemency) But what if there is more then one author, like if i want to make a reference post from a local newspaper as shown previously in that case the author is different what should i do then?

**Comment by safinakib** [comment]
[sublimeclemency](https://github.com/sublimeclemency) thanks for the help.
