### ISSUE TITLE
Change home page to "about" page

### ISSUE THREAD

**Issue by bcaddy** [cotes2020/jekyll-theme-chirpy#115]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

Hopefully my last question, I'd like to rearrange the tabs so that the first one/"home" tab is an About tab (which I've already created) and the current Home tab becomes a "blog" tab somewhere farther down. Example
![Screen Shot 2020-08-28 at 11 22 05](https://user-images.githubusercontent.com/41171425/91584494-bac63a80-e920-11ea-9b7c-6ee7df205ff8.png)

Is there a simple way to switch which tab is the "home"/base tab? I've tried changing the baseurl and url but it breaks lots of other stuff

**Comment by cotes2020** [comment]
There is no easy way to do this right now. You can put the contents of the Home page into `index.html`, but you need to handle other small details, such as breadcrumb, and so on. But If you're not familiar with Jekyll and Web development, I don't recommend this.

**Comment by bcaddy** [comment]
Ok, thanks!

**Comment by Soccerbeats** [comment]
Changing the index.html - layout: "home" to "page" allows you to write markup on the home page like any of the other tabs. with is great, but...
If you change any of the other _tabs - "layout:" to "home", it will not display all of your posts. Is there a way to do this? I love that we can now change the home page to be whatever we want but I would not like to loose the functinality of displaying all of my posts.
Thanks,
