### ISSUE TITLE
Transplant theme to Halo CMS

### ISSUE THREAD

**Issue by AirboZH** [cotes2020/jekyll-theme-chirpy#1150]
**NOTE:** Before you start, the following should be completed.

- Read [Wiki][wiki] to understand the usage and the correct effect of functional design.
- Make sure no [similar issue(including closed ones)][issues] exists.
- Try to find the answer on [Jekyll Forum][forum] and [StackOverflow][stack_overflow].

[wiki]: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue
[forum]: https://talk.jekyllrb.com/
[stack_overflow]: https://stackoverflow.com/questions/tagged/jekyll

## Description

Hello developer,

Thank you for coding such an awesome theme. I'm very interested in your theme. 👍
🙁However, my blog is powered by [Halo](https://github.com/halo-dev/halo), a new CMS that uses Java. 
Can I transplant the jekyll-theme-chirpy to a Halo theme?😊

📕Here is my repository: [halo-theme-chirpy](https://github.com/AirboZH/halo-theme-chirpy)

Thank you very much for your patience and support.

**Comment by cotes2020** [comment]
Sure, you are free to modify the code as long as it meets the terms of [MIT](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/LICENSE).
