### ISSUE TITLE
Mark down Code block Error

### ISSUE THREAD

**Issue by d0razi** [cotes2020/jekyll-theme-chirpy#1154]
Adding the contents below to the markdown document code block causes this error, is there a solution?

```bash
	prompt_newline() {
  if [[ -n $CURRENT_BG ]]; then
    echo -n "%{%k%F{$CURRENT_BG}%}$SEGMENT_SEPARATOR
%(?.%F{$CURRENT_BG}.%F{red})❯%f"

  else
    echo -n "%{%k%}"
  fi

  echo -n "%{%f%}"
  CURRENT_BG=''
}

## Main prompt
build_prompt() {
  RETVAL=$?
  prompt_status
  prompt_virtualenv
  prompt_aws
  prompt_context
  prompt_dir
  prompt_git
  prompt_bzr
  prompt_hg
  prompt_newline
  prompt_end
}
```
Error
`Liquid syntax error (line 38): Unknown tag 'k' in /home/runner/work/d0razi.github.io/d0razi.github.io/_posts/2023-07-31-omz-custom.md `

**Comment by NichtsHsu** [comment]
From [Jekyll doc](https://jekyllrb.com/docs/liquid/tags/):

> If you are using a language that contains curly braces, you will likely need to place `{% raw %}` and `{% endraw %}` tags around your code. Since Jekyll `4.0 `, you can add `render_with_liquid: false` in your front matter to disable Liquid entirely for a particular document.

**Comment by d0razi** [comment]
Thank you! I solve problem
