### ISSUE TITLE
Chirpy post not displaying on the homepage

### ISSUE THREAD

**Issue by quicklinks-li** [cotes2020/jekyll-theme-chirpy#1167]
## Description

I have created a post in the _posts folder, but it is not showing up on the home page. I dont know what to try because I just started to learn this theme. Feel free to ask questions.

**Comment by ZhengYuan-Public** [comment]
Try to read this [guide](https://chirpy.cotes.page/posts/write-a-new-post/)

**Comment by quicklinks-li** [comment]
The name of the file is in the correct format and i did add the yaml to the top of the page. I will just try forking the repo again and see if the copy was corrupted.

**Comment by quicklinks-li** [comment]
Thanks for your help, but I found out that it was failing to find the images I added to the root directory, so it would not create the file so chripy could not find it. I created another repository for images, and it worked.
