### ISSUE TITLE
Some markdown file is working fine on local, but failed to pass HTML-Proofer on GitHub Actions

### ISSUE THREAD

**Issue by ZhengYuan-Public** [cotes2020/jekyll-theme-chirpy#1169]
## Describe the bug
I've been transferring my notes using your theme and loved it so much. But I had a tiny problem with my notes for markdown [here](https://github.com/ZhengYuan-Public/zhengyuan-public.github.io/blob/main/_posts/2020-04-05-MarkdownNotes.md). 

Personally, I don't think there is anything special about this document, and running on local is working perfectly. But somehow when pushed to GitHub, Actions failed at HTML-Proofer. I have to disable HTML-Proofer temporally.

## Logs/Screenshots

```shell
Run bundle exec htmlproofer _site --disable-external --check-html --allow_hash_href
  bundle exec htmlproofer _site --disable-external --check-html --allow_hash_href
  shell: /usr/bin/bash -e {0}
  env:
    GITHUB_PAGES: true
Running ["ScriptCheck", "LinkCheck", "ImageCheck", "HtmlCheck"] on ["_site"] on *.html... 


- _site/posts/MarkdownNotes/index.html
Ran on [2](https://github.com/ZhengYuan-Public/zhengyuan-public.github.io/actions/runs/5825265515/job/15796388328#step:6:2)5 files!
  *  internally linking to link_url, which does not exist (line [4](https://github.com/ZhengYuan-Public/zhengyuan-public.github.io/actions/runs/5825265515/job/15796388328#step:6:4)01)
     <a href="link_url">Link Text</a>

HTML-Proofer found 1 failure!
```
## Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |2.6.10p210         |
| `gem -v`                          |         |
| `bundle -v`                       |2.1.4         |
| `bundle exec jekyll -v`           |4.3.2         |
| `bundle info jekyll-theme-chirpy` |6.1.0         |

### Desktop
- OS: macOS 13.5
- Browser: Chrome 115.0.5790.170

## Suggestion
Please consider adding emoji support by default (with `jemoji` for example).

**Comment by cotes2020** [comment]
Maybe now is a good time for you to learn to read log messages.

**Comment by ZhengYuan-Public** [comment]
I just can't see how this log message can be used to debug my markdown file...

- `_site/posts/MarkdownNotes/index.html` 
This is an HTML file generated, not written by myself.

- `internally linking to link_url, which does not exist (line [4](https://github.com/ZhengYuan-Public/zhengyuan-public.github.io/actions/runs/5825265515/job/15796388328#step:6:4)01)` 
Suppose this is the useful message, I guess `line[4]` resulted in the problem. But line 4 of my markdown file is still the YAML header, which is just a date `date: 2020-04-05 12:00:00`

**Comment by NichtsHsu** [comment]
You wrote an invalid hyperlink in your post.

https://github.com/ZhengYuan-Public/zhengyuan-public.github.io/blob/46399b4cf6dcd1251e04a9deb748b65e0f0a2729/_posts/2020-04-05-MarkdownNotes.md?plain=1#L187
