### ISSUE TITLE
Not able to run locally

### ISSUE THREAD

**Issue by zeina99** [cotes2020/jekyll-theme-chirpy#117]
## Checklist

- [X] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [X] There are no similar reports on existing issues (including closed ones).
- [X] I found the bug on the latest code of `master` branch.

### To Reproduce

1. fork the repo
2. clone the repo
3. follow steps on `Usage` guide
4. running `bash tools/run.sh` outputs:
 ```
usage: dirname path
usage: dirname path
```
### Expected behavior

expected it to run locally, but instead I got errors

### Desktop

- OS: MacOS Catalina
- Browser: Brave
- Version: 2.5

**Comment by cotes2020** [comment]
Please update your report: The log is too rough to help tracking. You must paste the input command and the complete output log. What's more, show me your bash version by `bash --version`.
