### ISSUE TITLE
Is there a way to enable the old "TimeAgo"?

### ISSUE THREAD

**Issue by michelinux** [cotes2020/jekyll-theme-chirpy#1170]
**NOTE:** Before you start, the following should be completed.

- Read [Wiki][wiki] to understand the usage and the correct effect of functional design.
- Make sure no [similar issue(including closed ones)][issues] exists.
- Try to find the answer on [Jekyll Forum][forum] and [StackOverflow][stack_overflow].

[wiki]: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue
[forum]: https://talk.jekyllrb.com/
[stack_overflow]: https://stackoverflow.com/questions/tagged/jekyll

## Description

Hi, is there a way to enable the relative date format, something like "4 days ago" like it was before commit [6d35f5f](https://github.com/cotes2020/jekyll-theme-chirpy/commit/6d35f5f8da044cfad071628bb53776de03efaae4)?
I understand I can edit some code to have it back in that way, but I am wondering if there is a setting or another way of doing it that I missed, so that I can keep using the latest Chirpy version.
🙏 Thanks.

**Comment by cotes2020** [comment]
No. It's gone.

**Comment by michelinux** [comment]
Got it. Thanks.
