### ISSUE TITLE
Scrolling problem

### ISSUE THREAD

**Issue by zhgchgli0718** [cotes2020/jekyll-theme-chirpy#1173]
## Describe the bug

Hello, I really like the Chirpy Theme, but I encountered a scrolling issue when I recently updated to version 6.1.x. 

When the website is opened using the built-in Instagram browser, scrolling gets stuck at the top and I'm unable to scroll down. 

I didn't experience this issue with version 5.x.x.

Thank you.

## To Reproduce

1. Open Instagram App
2. Go to my account: zhgchgli
3. Click the link at about section
4. Open link in built-in Instagram browser
5. Stuck at the top and unable to scroll down
-->

## Expected behavior
able to scroll down

## Logs/Screenshots
https://github.com/cotes2020/jekyll-theme-chirpy/assets/33706588/2124edbf-5819-4c03-9560-ec614e9702e6

## Environment
chirpy theme v6.1

### Smartphone
iPhone 13 / iOS 16.6

**Comment by cotes2020** [comment]
This report is invalid. 

Adding the demo site – <https://chirpy.cotes.page> that runs `v6.1.0` to your IG profile link, and you will see that it's scrolling feature is working properly, just as it did in the previous versions.
