### ISSUE TITLE
Change the index.html file in the Chripy Starter to index.md

### ISSUE THREAD

**Issue by quicklinks-li** [cotes2020/jekyll-theme-chirpy#1174]
I was trying to open the GitHub pages page, but all it would show is --- layout: home ---. Once I renamed the file, it worked. IDK if that is just an issue with my run of it or not. If it is feel free to close this request. Thanks for the great Jekyll theme!

**Comment by cotes2020** [comment]
Please make sure you read through the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/7819fd08437e68cc684c60a1cb5858b93b6a37f7/.github/CONTRIBUTING.md) carefully, if you don't follow the rules inside to open issue in the future, then your account will be banned, thank you.

**Comment by quicklinks-li** [comment]
Sorry, i never saw that. My bad.
