### ISSUE TITLE
category page cannot be found

### ISSUE THREAD

**Issue by poburi** [cotes2020/jekyll-theme-chirpy#118]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [ ] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

When I click on a category and enter it, it says that the page cannot be found.
[here](https://poburi.github.io/categories/demo/)

**Comment by cotes2020** [comment]
It looks like you didn't finish this:

![image](https://user-images.githubusercontent.com/11371340/92099869-9fba6580-ee0d-11ea-8172-5cced39c7220.png)
