### ISSUE TITLE
Make the left menu, consisting of avatar, and main buttons, collapsed by clicking on the button.

### ISSUE THREAD

**Issue by usmanovbf** [cotes2020/jekyll-theme-chirpy#1183]
## Is your feature request related to a problem? Please describe

The left menu cuts the 1/5 width from the page, and this area could be less disstractfull and more useful, e.g. for reading the articles in the centre 

## Describe the solution you'd like

Make the left menu, consisting of avatar, and main buttons, collapsed by clicking on the button.

## Describe alternatives you've considered

The only useful alternative is to collapse the left menu

## Additional context

No, thanks!

**Comment by cotes2020** [comment]
The sidebar exists to avoid the body text area moving to the left. This is the advantage of a 3-column layout: it allows the eye to look straight down the center line of the screen when reading.

So I disagree that putting away the sidebar improves the reading experience. The result is actually the opposite.

**Comment by usmanovbf** [comment]
@cotes2020 after collapsing the left menu to the tiny bar it's possible to keep the same centered text as before or make it wider little bit. Thus, it still will help you to "look straight down the center line of the screen when reading."

**Comment by cotes2020** [comment]
Widening the content area will degrade the reading experience: your eyes will need to turn left and right to read a line of text.

You actually just like the two-column layout, but I'm not interested in that.
