### ISSUE TITLE
Embedding custom html badges

### ISSUE THREAD

**Issue by ericlikedis** [cotes2020/jekyll-theme-chirpy#1192]
> **Tips**: Remember, contributions to this repository should follow the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

## Is your feature request related to a problem? Please describe
No, but I would like to one day see in the future that I could have a custom HTML badge off to the right hand side of the blog just under "Trending Tags".

## Describe the solution you'd like
The ability to place custom html into the theme for customizability 

## Describe alternatives you've considered

I tried editing the index.html under the _sites > blogging > index.html and placing the script tag just under the "Trending Tags" div tag. 

## Additional context

![IMG_9165](https://github.com/cotes2020/jekyll-theme-chirpy/assets/48847865/b22476b7-5065-41ab-a1d5-eddd4170c0d7)

The screenshot seems to do this idea justice. I would simply like a feature where I can place a badge to represent my rank from TryHackMe off to the right hand side for visitors to see.

**Comment by ericlikedis** [comment]
reference: https://stackoverflow.com/questions/72954006/how-can-i-add-a-linkedin-badge-to-a-jekyll-page

**Comment by anonfaded** [comment]
this feature would be awesome, will try asking chat gpt :)

**Comment by cotes2020** [comment]
Filling every inch of the screen goes against the principle of minimalist design, so you can add this feature in a customized version.

**Comment by NichtsHsu** [comment]
I suggest you fork the [jekyll-theme-chirpy](https://github.com/cotes2020/jekyll-theme-chirpy) directly if you need customization.

**Comment by anonfaded** [comment]
> I suggest you fork the [jekyll-theme-chirpy](https://github.com/cotes2020/jekyll-theme-chirpy) directly if you need customization.

i tried to fork but it is just giving errors, on Github Pages it was showing the content of .html file which was a front matter for layout rather than hosting the website.
Kindly share how to customise the startup template theme ? likewant to change that old twitter logo to X in the social media icons and want to change the footer text which is "Some rights reserved" to something else, plz share the details,
