### ISSUE TITLE
Searchinput trigger shortcut

### ISSUE THREAD

**Issue by Rootjhon** [cotes2020/jekyll-theme-chirpy#1194]
> **Tips**: Remember, contributions to this repository should follow the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

## Is your feature request related to a problem? Please describe

- **Search trigger shortcut**

> like github style
> ![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/12013966/f04714be-ac2b-4734-83b9-996df4b8c6a8)

## Describe the solution you'd like

``` html
<script>
    $(document).on('keydown', function(event) {
        SearchBoxQuickTrigger(event);
    });

    function SearchBoxQuickTrigger(event) {
        var searchBox = $('#search-input');
        if (event.which === 191) {
            if (searchBox[0] !== document.activeElement) {
            event.preventDefault();
            searchBox.focus();
            }
        }
    }
</script>
```

**Comment by cotes2020** [comment]
So I opened a poll, and whether or not this request goes through is decided by the results of a community vote.

- #1238

**Comment by cotes2020** [comment]
New conclusion: shortcut-activated search requires a pop-up search input field to work with, which doesn't fit the existing static input box design, so this feature shouldn't be added at this stage.
