### ISSUE TITLE
Use HTML5 elements: header, nav, aside, main, article, section

### ISSUE THREAD

**Issue by Lucent** [cotes2020/jekyll-theme-chirpy#1196]
An almost-perfect theme, but please consider using HTML5 elements rather than DIV soup. I see you already use `<footer>`. #sidebar can be `<aside>` or `<nav>`, #main-wrapper can be `<main>`, #topbar-wrapper can be `<header>`, .post can be `<article>`. Also worth looking into `<section>`.

**Comment by cotes2020** [comment]
Thanks! This request will be considered, and you are welcome to create a PR to help improve it.

**Comment by Lucent** [comment]
Wow, quick quality work! I will definitely be switching to this theme.
