### ISSUE TITLE
Github Actions Build and Deploy fails for clean version

### ISSUE THREAD

**Issue by maxawake** [cotes2020/jekyll-theme-chirpy#1197]
> **Tips**: Remember, contributions to this repository should follow the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

## Describe the bug

Automatic build and deploy with github pages does not work. When cloning the repo and commiting it plain to github pages, the build and deploy action errors saying that the theme gem could not be found. After changing the _config.yml to list a remove_theme to be cotes2020/jekyll-theme-chirpy it errors saying 
` Liquid Exception: Liquid error (/github/workspace/_includes/read-time.html line 3): wrong number of arguments (given 2, expected 1) included in /_layouts/post.html`

## To Reproduce

1. Download repo
2. Change _config.yml theme to remove_theme
3. push changes and trigger workflow
4. Error

## Expected behavior

Should work without errors or at least say what the problem is

## Logs/Screenshots

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/13322597/07ddb079-2589-4c1e-babb-011a9a0fa7da)

## Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |         |
| `gem -v`                          |         |
| `bundle -v`                       |         |
| `bundle exec jekyll -v`           |         |
| `bundle info jekyll-theme-chirpy` |         |

**Comment by cotes2020** [comment]
Please read the contributing guidelines.
