### ISSUE TITLE
Can't go to category page

### ISSUE THREAD

**Issue by skylerseo** [cotes2020/jekyll-theme-chirpy#120]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [x] I found the bug on the latest code of `master` branch.

### To Reproduce

1. Go to '~~~.github.io/tabs/categories/'
2. Click on 'any category'
3. See error

### Expected behavior

When I click any category, I see the error page, down picture.

### Screenshots

<img width="320" alt="스크린샷 2020-09-05 오전 3 43 22" src="https://user-images.githubusercontent.com/59784467/92275370-f87f2080-ef29-11ea-89dd-a2b827512b57.png">

<img width="587" alt="스크린샷 2020-09-05 오전 3 23 09" src="https://user-images.githubusercontent.com/59784467/92275081-66771800-ef29-11ea-81b0-a589730cbb3f.png">

### Software

- Ruby version: [by running: `ruby -v`]
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
- Gem version: [by running: `gem -v`]
3.0.3
- Bundler version: [by running: `bundle -v`]
Bundler version 1.17.2
- Jekyll version: [by running: `bundle list | grep " jekyll "`]
jekyll 4.1.1

### Desktop

- OS: [macOS 10.15.6]
- Browser: [Chrome 84.0.4147.125 (Official Build) (64-bit)]

### Smartphone

- Device: [e.g. iPhone 6]
- OS: [e.g. iOS 13.6.1]
- Browser: [e.g. Chrome 22]

### Additional context

I want you to fix this bug if you can, and have time. If you fix, I love you! Love your theme too😍

**Comment by cotes2020** [comment]
Hi @skylerseo, until you finish the [tutorial](https://chirpy.cotes.info/posts/getting-started/), I can’t say I love you too

**Comment by skylerseo** [comment]
@cotes2020 It worked! My problem was [tools/publish.sh] thing! Sorry and thanks a lot😻

**Comment by cotes2020** [comment]
Not t exactly. As mentioned at https://github.com/cotes2020/jekyll-theme-chirpy/issues/95#issuecomment-683915940, the best way to deploy on Github Pages is to use Github Action Workflow instead of `tools/publish.sh`

**Comment by skylerseo** [comment]
@cotes2020 I read that #95 comment, thank you!
