### ISSUE TITLE
插入图片的路径在本地md编辑器和网页端不一致

### ISSUE THREAD

**Issue by sirlis** [cotes2020/jekyll-theme-chirpy#122]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

目录结构如下

```
_posts
    |--post1.md
assets
    |--img
          |--postimg
                |--1.jpg
```

注意到再 post1.md 中插入图片是用以下链接形式

```
/assets/img/postsimg/1.jpg
```
这种形式再 typora 或者 vscode 中图片无法加载，因为默认认定 _posts 文件夹作为 root path。

如果将图片的路径修改为如下

```
../assets/img/postsimg/1.jpg
```
那么 typora 或者 vscode 中预览 md 时可以正常显示出图片了，但发布到 github pages 时却无法显示。

请问如何修改 themes 使得本地和网络上的图片均能够正常显示呢？最好是通过修改主题的某个配置（permanent link？）来实现~ 

感谢大佬做的漂酿的 theme ~

**Comment by cotes2020** [comment]
> - [ ] I searched the Internet for related problems, but still couldn't solve it.

上网随便一搜都有答案吧，这是本地文件系统路径和 Web 路径的差异。想本地预览全状态渲染效果（包括图片），请本地运行 Jekyll 而不是使用 MD 编辑器。

**Comment by sirlis** [comment]
> > * [ ]  I searched the Internet for related problems, but still couldn't solve it.
> 
> 上网随便一搜都有答案吧，这是本地文件系统路径和 Web 路径的差异。想本地预览全状态渲染效果（包括图片），请本地运行 Jekyll 而不是使用 MD 编辑器。

您好，因为之前用的另一个 Jekyll 的 theme （https://github.com/ray525/3-Jekyll），可以通过修改 _config.yml 里面的 permalink 来使得本地 md 编辑器和 web 的渲染效果保持一致。

以下是我搜到的方法：

-------------------------------
为了在`.md`中使用图片相对路径，保持本地和线上显示一致，需要修改Jekyll默认的永久链接格式。Jekyll默认的永久链接格式为：
```
permalink: :year/:month/:day/:title/
```
会导致使用相对路径插入图片的帖子（如`./assets/img/postsimg/20200505/1.jpg`）无法定位到图片的真正位置。因此需在`_config.yml`中修改为以下语句：
```
permalink: :year-:month-:day-:title/
```
修改后，`_posts`中帖子的图片无论是在本地还是在线上均能正常显示。

--------------------------------------

本意是只用专注于写 markdown 的 post 然后直接同步到git上即可，无需关心其它的。关于您说的本地运行 jekyll 我再去搜搜把~ anyway 感谢设计提供这个主题~

**Comment by cotes2020** [comment]
> 为了在.md中使用图片相对路径，保持本地和线上显示一致，...
> 
>```
>permalink: :year-:month-:day-:title/
>```

试问，你清楚这样声明的含义以及结果吗？如果否的话，就抽空去 Jekyll 官网了解一下 [permalink](https://jekyllrb.com/docs/permalinks/) 的介绍，资料要找一手的，不然被骗了还感觉美滋滋。

现在来简单分析一下引述中列出的那个疑似某毒搜索的答案，`:year-`, `:month-`, `:month-`, `:day-` 这四个 placeholder 由于末尾被加了`-` 变成是无效的字段，Jekyll 读取的时候就会忽略，只按 `:title/` 来输出路径，这样你的 post 输出文件就等于放置在 Web 的根目录:

| Permalink statement| Access URL | Comment |
| :--- | :--- | :--- | 
|`:title/`| http(s)://domain/**post-title/**| 加粗的部分就是 permalink 
|`:year-:month-:day-:title/`| http(s)://domain/**post-title/**| URL 和上面一个卵样

本地文件目录结构:

```sh
.
├── _posts
│   └── post-title.md  # 本地 MD 编辑器访问`../assets/img/image.jpg`可达
│
├── assets
│   └── img
│   	 └── image.jpg
```

 构建输出的 Web 目录结构 （`permalink: :title/`）:

```sh
.
├── post-title.html  # Web 访问`../assets/img/image.jpg`可达，相当于 `/assets/img/image.jpg`
│
├── assets
│   └── img
│   	 └── image.jpg
```

在 Web 项目里，`../` 这类的物理相对路径应该禁止，因为很容易出错。

在本项目，`_config.yml` 注释已经写明了，项目还有一些关系到 `permalink` 的内部链接，譬如 `Recent Update`，假如被随意更改，但是没有修改其对应 `layout` 的源码，将会导致部分站内链接失效，到时麻烦别来抱怨说 “辣鸡项目不能跑、有 bug...”之类的肺腑之言。

最后，我说的“本地运行 Jekyll...” 意思是在本地机器运行这个项目，方法在 ReadMe 写的详细的不能再详细了，但万一你比较喜欢“上网找找”的话请随意～
