### ISSUE TITLE
side bar contact icons not stacking

### ISSUE THREAD

**Issue by lsilvam** [cotes2020/jekyll-theme-chirpy#1224]
## Describe the bug

On the side bar the contact icons (configure in the ~\contact.yml file are no longer stacking. the only way to see them is to scroll horizontally . This happened after updating to  [v6.2.0](https://github.com/cotes2020/jekyll-theme-chirpy/commit/52084f85d4ec4554005e736ef8c3497d6d4d316a)

## To Reproduce

1. Go to ''gemfile"
2. Update version to v 6.2.0
3. Run bundle update jekyll-theme-chirpy
4. Open website
5. See error

## Expected behavior

After updating the theme from v6.1.0 the layout of the side bar with the avatar and links would not change configurations.

## Logs/Screenshots

Icons are displayed in a single row, part-1:
<img width="256" alt="firefox_86qUsPQBKD" src="https://github.com/cotes2020/jekyll-theme-chirpy/assets/53966548/874557b6-b14d-4f37-8bf8-7c6aee3c75ad">

part-2:
<img width="236" alt="firefox_42zLUXds81" src="https://github.com/cotes2020/jekyll-theme-chirpy/assets/53966548/e69d9aa9-e47c-41a5-b0c8-8c79af9ee2d3">

## Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |         |
| `gem -v`                          |         |
| `bundle -v`                       |         |
| `bundle exec jekyll -v`           |         |
| `bundle info jekyll-theme-chirpy` |   6.2.1      |

### Desktop

- OS: Windows ver 22H2
- Browser: Firefox 117.0 & Edge 116.0.1938.76

**Comment by cotes2020** [comment]
Thank you for raising this issue. It will be fixed in next patch.
