### ISSUE TITLE
tools/init is extremely destructive

### ISSUE THREAD

**Issue by Lucent** [cotes2020/jekyll-theme-chirpy#1225]
In trying to update with the upstream, I encountered rebase problems after the init script wiped intro .md files. I commited my changes to my own _posts and images, fetched upstream, and ran tools/init again only to find it did a git reset --hard, destroyed my commit containing all my posts, and further rm -rf everything in /posts! If there are individual sample posts of your own you want to delete, that's fine, but rm -rf an entire directory nor git reset --hard reasonably belong in any init script!

**Comment by cotes2020** [comment]
You only need to run the init script the first time you work on a fork, as explained in "Getting Startted".

**Comment by Lucent** [comment]
Rather than require users run exactly the right scripts only at the proscribed time, why not follow the "robustness principle" and "principle of least astonishment" of computing—be conservative in what you send, don't surprise users? If you want to `rm` files you created, that's fine. But `rm -rf` the entire `_posts/` directory as part of a script called "init" followed by `git reset --hard` then saying RTFM is pretty user hostile for what's otherwise a great, widely used project.
