### ISSUE TITLE
Layout Issue in code blocks in version 6.2.2

### ISSUE THREAD

**Issue by Biplab-Dutta** [cotes2020/jekyll-theme-chirpy#1235]
After upgrading jekyll-theme-chirpy to version 6.2.2, my code block section looks as shown in the picture..
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/63902683/48023515-702b-4ff2-8d90-1f09479cd5de)
The three dots as indicated by the arrow seem to have zero top left padding.
How can I get it fixed?

Here's my site if you want to check it out. 
https://biplabdutta.com.np

Also, this is how it looks on mobile phone on portrait mode.
<img src="https://github.com/cotes2020/jekyll-theme-chirpy/assets/63902683/0e53daf0-a5ff-4e7f-a488-3f56d94ff16d" width=300 height="500"/>

**Comment by NichtsHsu** [comment]
I think you have some files that were not upgraded to v6.2.2, for example `_sass/addon/syntax.scss` in this issue.

Your site:
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/35688135/088db631-1176-459c-9bee-307767ab9071)

Demo site:
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/35688135/77c5e61d-5816-41ea-b84b-a4d9fad420f8)

**Comment by NichtsHsu** [comment]
Update:

No, I think it’s because the definition of `$code-header-height` is missing in the `_sass/addon/variables.scss` file.

**Comment by Biplab-Dutta** [comment]
> Update:
> 
> No, I think it’s because the definition of `$code-header-height` is missing in the `_sass/addon/variables.scss` file.

Is there anything I can do on my side to get it fixed?

**Comment by NichtsHsu** [comment]
It will be easier for investigation the cause if you are willing to share your repository link :)

**Comment by Biplab-Dutta** [comment]
@NichtsHsu Sure. It's open sourced.
https://github.com/Biplab-Dutta/personal_site

**Comment by NichtsHsu** [comment]
Hi @Biplab-Dutta ,

Version of `jekyll-sass-converter` in your `Gemfile.lock` is too old.
Just run `bundle update` and all will be fine.

**Comment by Biplab-Dutta** [comment]
Shall give it a try tonight and shall let you know and close the issue if that fixes my problem. Thanks.

**Comment by Biplab-Dutta** [comment]
@NichtsHsu Tried updating the bundle. But didn't work.
My gemfile.lock shows no any git difference even after running `bundle update`.

**Comment by NichtsHsu** [comment]
Do you build your site on linux-musl? It seems that `jekyll-sass-converter` v3.0 is not supported on the linux-musl platform:

https://github.com/cotes2020/chirpy-starter/blob/bcb2c56f84502ec60e946dc4f15b3f6e7fd6c6f4/Gemfile#L25C50-L28

**Comment by Biplab-Dutta** [comment]
@NichtsHsu I don't know what that is. It was there when I created the project with the starter template.

**Comment by NichtsHsu** [comment]
You can try removing the `Gemfile.lock` from your repository and triggering the Github Action again.
