### ISSUE TITLE
code block doesn't show correctly when code type is unsupported

### ISSUE THREAD

**Issue by Karmenzind** [cotes2020/jekyll-theme-chirpy#1244]
### Checklist

- [X] I'm willing to follow the [Contributing Guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Describe the bug

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/17923071/8b1b1517-2ab3-4b04-8f41-05fc68049532)

It seems `crontab` is not recognized by the theme. So it displayed:

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/17923071/f1650c03-c5c1-44c1-bfac-c07182a4b678)

But code block shows if the code type is left blank.

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/17923071/edc22742-8dc4-4f79-9a95-9f1331179cb0)

### Expected Behavior

Treat any unknown types the same as `plaintext`.

### Environment

- Ruby:  3.1.1
- Jekyll:  4.3.2
- Chirpy:  5.6.1

**Comment by cotes2020** [comment]
Made a mistake and thought it was another spam

**Comment by Karmenzind** [comment]
:cry: I thought it was closed because I was using the old version. After updating to 6.2.2 with your current Gemfile in chirpy-starter, the issue still remains.

**Comment by cotes2020** [comment]
This is the result of the `Kramdown` rendering, you shouldn't report it as a `bug`, it's an `enhancement` request.

**Comment by Karmenzind** [comment]
Then it should be a feature request.
Maybe you can add a new setting option to control how to render it.

**Comment by cotes2020** [comment]
So why specify unsupported languages, isn't leaving a blank step the effect you want?

**Comment by Karmenzind** [comment]
Because the language is supported in local editor. Now I need to remember to remove the tag after editing the block. Still thanks.
