### ISSUE TITLE
Adding a link in the preview image's alt closes the <head> of the page

### ISSUE THREAD

**Issue by xaviermignot** [cotes2020/jekyll-theme-chirpy#1250]
### Checklist

- [X] I'm willing to follow the [Contributing Guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Describe the bug

I have tried to add a link in the alt element of my latest post's preview image. As I took the image from Unsplash I wanted to add a link to the author's profile.
Adding the link as a `a` HTML element works great in the image caption but the value is also used in the `<meta property="og:image:alt">` in the `head`. As the value is not escaped there, it "closes" the `head` of the page which causes these side-effects:
- The end of the alt is writting at the very beginning of the `body`
- The favicon is not found

You can see how it looks here:
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/6839988/a3d10d7b-0f6d-42d1-9717-e79a62d3dd53)

And how the `head` is cut in the browser's dev tools:
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/6839988/3e15f11f-178d-4b1a-b2e2-691a7ce53501)

### Steps To Reproduce

I have reproduce the issue on a fresh environment, starting from the latest commit of the Chirpy starter repo, following these steps:
1. Adding an image in the `/assets/img` folder
2. Create a `test.md` file in the `_drafts` folder with the following content:
```yaml
---
title: Post title
img_path: /assets/img
image:
  path: banner.jpg
  # alt: Let's put a "/>
  alt: Let's put a <a href="https://chirpy.cotes.page">link</a> here
---
```
3. Running `bundle exec jekyll s -D -l` and navigate to the draft

### Expected Behavior

If I remove the HTML code from the `alt` property, the `head` of the page is not cut and the side-effects mentionned in the description doesn't appear. This behavior and the link in the image caption would be perfect :)

### Environment

- Ruby: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
- Jekyll: jekyll 4.3.2
- Chirpy: jekyll-theme-chirpy (6.2.2)

### Anything else?

I have been fiddling a little with this, and it seems that adding `Hello "/>` is also causing the issue. But I wasn't able to find in the code where the `<meta property="og:image:alt"` element is generated...
Please let me know if adding HTML there is a terrible idea, I'm open to any suggestion.

**Comment by cotes2020** [comment]
> ... if another property could be added for the caption of the preview image ...

This shouldn't be a good idea, the design goal is to maximize the use of common parameters with `jekyll-seo-tag`.

Also, image annotations should just be plain strings, not fancy rich text.

**Comment by xaviermignot** [comment]
Ok that make sense, I wasn't aware of the design goal and how it relates to the `jekyll-seo-tag` plugin.  
Thanks again for your replies and of course your awesome work on this theme.
I will stick to text-only content for my image captions and close this issue.

**Comment by mattpopovich** [comment]
I've ran into the same bug. I'm also trying to credit someone else's photo. Unfortunate result.
