### ISSUE TITLE
Math equation rendering bug (possibly caused by mathjax)

### ISSUE THREAD

**Issue by ZhengYuan-Public** [cotes2020/jekyll-theme-chirpy#1262]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Built from `jekyll-theme-chirpy`

### Describe the bug

Some inline math formulas were not rendered correctly with jekyll-theme-chirpy, but it's working as expected in Typora which also uses Mathjax for rendering (Check here [Typora - Math and Academic Functions](https://support.typora.io/Math/#:~:text=Typora%20supports%20rendering%20normal%20mathematics,process%20is%20processed%20by%20MathJax.)).

I wonder what's the difference and how can I fix my equations.

### Steps To Reproduce

Here is the contents of my equations (Typora source code mode), or the markdown file at [here](https://github.com/ZhengYuan-Public/zhengyuan-public.github.io/blob/main/_posts/2019-06-03-ProgrammingBasics.md)

<img width="702" alt="image" src="https://github.com/cotes2020/jekyll-theme-chirpy/assets/9320285/b2ad2079-a137-4465-ade2-f5f69d10af66">

---

Here is what it looks like in Typora
<img width="738" alt="image" src="https://github.com/cotes2020/jekyll-theme-chirpy/assets/9320285/1dc3012d-c85c-441c-bf0e-3b1b51ad3ec0">

---

Here is what it looks like on my GitHub page
<img width="887" alt="image" src="https://github.com/cotes2020/jekyll-theme-chirpy/assets/9320285/4b5a8795-dccb-4fd7-a169-c0ac38791a55">

### Expected Behavior

Since Typora is also using MathJax, they should have the same output.

### Environment

- Ruby: 2.6.10p210
- Jekyll: 4.3.2
- Chirpy: 6.1.0

**Comment by ZhengYuan-Public** [comment]
Just found another inline math that can't be rendered correctly. I can't find any pattern why it's not working.


$ x_i \longrightarrow P(y|x_i; \Theta) \longrightarrow P^*(y|x_i) $

---
In Typora
<img width="521" alt="image" src="https://github.com/cotes2020/jekyll-theme-chirpy/assets/9320285/c009970a-1098-4bac-ab1d-c9d57be26cc0">

---
In GitHub page
<img width="766" alt="image" src="https://github.com/cotes2020/jekyll-theme-chirpy/assets/9320285/63d61c60-78d7-4340-bd20-7a022f505f7f">

**Comment by sukhjinder-kumar** [comment]
Answering to your latest comment, the error is with `|`. I asked Google Bard and this is what it replied -

> The issue is that MathJax interprets the vertical bar (|) in P(y∣x) as a delimiter for a fraction. To fix this, you can either escape the vertical bar with a backslash (\\), or enclose the entire expression in double dollar signs ($$).

And it works, i.e use `$ x_i \longrightarrow P(y\|x_i; \Theta) \longrightarrow P^*(y\|x_i) $`

**Comment by ZhengYuan-Public** [comment]
> Answering to your latest comment, the error is with `|`. I asked Google Bard and this is what it replied -
> 
> > The issue is that MathJax interprets the vertical bar (|) in P(y∣x) as a delimiter for a fraction. To fix this, you can either escape the vertical bar with a backslash (\), or enclose the entire expression in double dollar signs ($$).
> 
> And it works, i.e use `$ x_i \longrightarrow P(y\|x_i; \Theta) \longrightarrow P^*(y\|x_i) $`

Thanks for your reply. The equation from my last comment is working on the GitHub page now, but the output is not consistent in Typora, which is something like the image below

<img width="753" alt="image" src="https://github.com/cotes2020/jekyll-theme-chirpy/assets/9320285/5c36eca4-313e-4618-bad8-b365425ba4b2">

I think the problem is still why MathJax is not working consistently in Typora and Jekyll. 

Similarly, it seems `{` and `}` are also not interpreted correctly 
```
$ (-1)^{sign} = (-1)^0 = +1 \in \{-1, +1\} $ is working in Typora, not on the GitHub page;
$ (-1)^{sign} = (-1)^0 = +1 \in {-1, +1} $ is not working in either.
```

**Comment by sukhjinder-kumar** [comment]
`$ (-1)^{sign} = (-1)^0 = +1 \in \{-1, +1\} $` and `$ (-1)^{sign} = (-1)^0 = +1 \in {-1, +1} $` is working on blog post. Of course in later case `{}` aren't rendered for syntax reasons. Not sure what is the problem you faced.

**Comment by deepConnectionism** [comment]
@ZhengYuan-Public @cotes2020 

> MathJax is not working consistently in Typora and Jekyll.

I have the same problem as you.

### example1   

`${\mathbf{F}}\_{x}$, ${\mathbf{F}}\_{y}$ and ${\mathbf{F}}\_{t}$ `

vscode:

![image](https://github.com/user-attachments/assets/4e9dac0e-063f-4bc6-83f4-e4291996ca63)

chirpy:
![image](https://github.com/user-attachments/assets/6a1e3eba-9c1f-4c6f-a797-3dba7215ac3d)

### example2   

`${\mathbf{F}}_{x}$, ${\mathbf{F}}_{y}$ and ${\mathbf{F}}_{t}$`

vscode:

![image](https://github.com/user-attachments/assets/76518a23-9029-48f3-bbe5-7065c6fc8489)

chirpy:

![image](https://github.com/user-attachments/assets/11d602c6-dd71-4884-a784-03d884c83422)

### example3  

`$${\mathbf{F}}_{x}$$, $${\mathbf{F}}_{y}$$ and $${\mathbf{F}}_{t}$$`

vscode:

![image](https://github.com/user-attachments/assets/3588b7ee-6dba-4425-ba9d-3e080548261d)

chirpy:

![image](https://github.com/user-attachments/assets/77f741a1-7b74-4195-9c69-0c51d063e3e1)

---

### example4

`$ x_i \longrightarrow P(y\|x_i; \Theta) \longrightarrow P^*(y\|x_i) $`  

vscode:

![image](https://github.com/user-attachments/assets/77c0c6ac-c18c-46fe-8460-9d0ec76ceab5)

chirpy:

![image](https://github.com/user-attachments/assets/e13bc4f3-35ff-4087-8a9b-dedec6c57769)

### example5

`$ x_i \longrightarrow P(y|x_i; \Theta) \longrightarrow P^*(y|x_i) $`

vscode:

![image](https://github.com/user-attachments/assets/e13bc4f3-35ff-4087-8a9b-dedec6c57769)

chirpy:

![image](https://github.com/user-attachments/assets/8b18114c-77de-412b-8e40-5611640cc529)

### example6

`xxx, $$ x_i \longrightarrow P(y|x_i; \Theta) \longrightarrow P^*(y|x_i) $$, xxx`

vscode:

![image](https://github.com/user-attachments/assets/c51e79e2-c403-477b-ba97-e7073d8833a9)

chirpy:

![image](https://github.com/user-attachments/assets/6e7cec73-c779-4bf5-94bf-33e36ebea3f0)
