### ISSUE TITLE
HTML-Proofer errors after using the chippy-starter, failing at "Test Site"

### ISSUE THREAD

**Issue by RadiantHero6** [cotes2020/jekyll-theme-chirpy#1266]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

I'm currently trying to make a simple blog and I've followed this guide specifically to help me learn to make a Github pages with Jekyll https://www.youtube.com/watch?v=F8iOU1ci19Q

Followed the guide as is and when doing a local preview everything works as it should, but when I go to build it, it fails almost instantly. It shows this error. Specifically it stops at the "Test Site" portion of the build.

The error log says that a lot of the files don't exist.

`Run bundle exec htmlproofer _site \
Running 3 checks (Scripts, Links, Images) in ["_site"] on *.html files...

Checking 17 internal links
Checking internal link hashes in 1 file
Ran on 11 files!

For the Links > Internal check, the following failures were found:

* At _site/RadiantHero6/404.html:1:

  internally linking to /assets/img/favicons/apple-touch-icon.png, which does not exist

* At _site/RadiantHero6/404.html:1:

  internally linking to /assets/img/favicons/favicon-32x32.png, which does not exist

* At _site/RadiantHero6/404.html:1:

  internally linking to /assets/img/favicons/favicon-16x16.png, which does not exist

* At _site/RadiantHero6/404.html:1:

  internally linking to /assets/img/favicons/site.webmanifest, which does not exist

* At _site/RadiantHero6/404.html:1:

  internally linking to /assets/img/favicons/favicon.ico, which does not exist

* At _site/RadiantHero6/404.html:1:

  internally linking to /assets/css/jekyll-theme-chirpy.css, which does not exist

* At _site/RadiantHero6/404.html:1:

  internally linking to /, which does not exist

* At _site/RadiantHero6/404.html:1:

  internally linking to /, which does not exist

* At _site/RadiantHero6/404.html:1:

  internally linking to /, which does not exist

* At _site/RadiantHero6/404.html:1:

  internally linking to /, which does not exist

* At _site/RadiantHero6/404.html:1:

  internally linking to /categories/, which does not exist

* At _site/RadiantHero6/404.html:1:

  internally linking to /tags/, which does not exist

* At _site/RadiantHero6/404.html:1:

  internally linking to /archives/, which does not exist

* At _site/RadiantHero6/404.html:1:

  internally linking to /about/, which does not exist

* At _site/RadiantHero6/404.html:1:

  internally linking to /feed.xml, which does not exist

* At _site/RadiantHero6/404.html:1:

  internally linking to /posts/newPost/, which does not exist

* At _site/RadiantHero6/404.html:1:

  internally linking to /tags/randomthoughts/, which does not exist

* At _site/RadiantHero6/404.html:1:

  internally linking to /tags/randomthoughts/, which does not exist

* At _site/RadiantHero6/about/index.html:1:

  internally linking to /assets/img/favicons/apple-touch-icon.png, which does not exist

* At _site/RadiantHero6/about/index.html:1:

  internally linking to /assets/img/favicons/favicon-32x32.png, which does not exist

* At _site/RadiantHero6/about/index.html:1:

  internally linking to /assets/img/favicons/favicon-16x16.png, which does not exist

* At _site/RadiantHero6/about/index.html:1:

  internally linking to /assets/img/favicons/site.webmanifest, which does not exist

* At _site/RadiantHero6/about/index.html:1:

  internally linking to /assets/img/favicons/favicon.ico, which does not exist

* At _site/RadiantHero6/about/index.html:1:

  internally linking to /assets/css/jekyll-theme-chirpy.css, which does not exist

* At _site/RadiantHero6/about/index.html:1:

  internally linking to /, which does not exist

* At _site/RadiantHero6/about/index.html:1:

  internally linking to /, which does not exist

* At _site/RadiantHero6/about/index.html:1:

  internally linking to /, which does not exist

* At _site/RadiantHero6/about/index.html:1:

  internally linking to /, which does not exist

* At _site/RadiantHero6/about/index.html:1:

  internally linking to /categories/, which does not exist

* At _site/RadiantHero6/about/index.html:1:

  internally linking to /tags/, which does not exist

* At _site/RadiantHero6/about/index.html:1:

  internally linking to /archives/, which does not exist

* At _site/RadiantHero6/about/index.html:1:

  internally linking to /about/, which does not exist

* At _site/RadiantHero6/about/index.html:1:

  internally linking to /feed.xml, which does not exist

* At _site/RadiantHero6/about/index.html:1:

  internally linking to /posts/newPost/, which does not exist

* At _site/RadiantHero6/about/index.html:1:

  internally linking to /tags/randomthoughts/, which does not exist

* At _site/RadiantHero6/about/index.html:1:

  internally linking to /tags/randomthoughts/, which does not exist

* At _site/RadiantHero6/archives/index.html:1:

  internally linking to /assets/img/favicons/apple-touch-icon.png, which does not exist

* At _site/RadiantHero6/archives/index.html:1:

  internally linking to /assets/img/favicons/favicon-32x32.png, which does not exist

* At _site/RadiantHero6/archives/index.html:1:

  internally linking to /assets/img/favicons/favicon-16x16.png, which does not exist

* At _site/RadiantHero6/archives/index.html:1:

  internally linking to /assets/img/favicons/site.webmanifest, which does not exist

* At _site/RadiantHero6/archives/index.html:1:

  internally linking to /assets/img/favicons/favicon.ico, which does not exist

* At _site/RadiantHero6/archives/index.html:1:

  internally linking to /assets/css/jekyll-theme-chirpy.css, which does not exist

* At _site/RadiantHero6/archives/index.html:1:

  internally linking to /, which does not exist

* At _site/RadiantHero6/archives/index.html:1:

  internally linking to /, which does not exist

* At _site/RadiantHero6/archives/index.html:1:

  internally linking to /, which does not exist

* At _site/RadiantHero6/archives/index.html:1:

  internally linking to /, which does not exist

* At _site/RadiantHero6/archives/index.html:1:

  internally linking to /categories/, which does not exist

* At _site/RadiantHero6/archives/index.html:1:

  internally linking to /tags/, which does not exist

* At _site/RadiantHero6/archives/index.html:1:

  internally linking to /archives/, which does not exist

* At _site/RadiantHero6/archives/index.html:1:

  internally linking to /about/, which does not exist

* At _site/RadiantHero6/archives/index.html:1:

  internally linking to /feed.xml, which does not exist

* At _site/RadiantHero6/archives/index.html:1:

  internally linking to /posts/newPost/, which does not exist

* At _site/RadiantHero6/archives/index.html:1:

  internally linking to /posts/newPost/, which does not exist

* At _site/RadiantHero6/archives/index.html:1:

  internally linking to /tags/randomthoughts/, which does not exist

* At _site/RadiantHero6/archives/index.html:1:

  internally linking to /tags/randomthoughts/, which does not exist

* At _site/RadiantHero6/categories/index.html:1:

  internally linking to /assets/img/favicons/apple-touch-icon.png, which does not exist

* At _site/RadiantHero6/categories/index.html:1:

  internally linking to /assets/img/favicons/favicon-32x32.png, which does not exist

* At _site/RadiantHero6/categories/index.html:1:

  internally linking to /assets/img/favicons/favicon-16x16.png, which does not exist

* At _site/RadiantHero6/categories/index.html:1:

  internally linking to /assets/img/favicons/site.webmanifest, which does not exist

* At _site/RadiantHero6/categories/index.html:1:

  internally linking to /assets/img/favicons/favicon.ico, which does not exist

* At _site/RadiantHero6/categories/index.html:1:

  internally linking to /assets/css/jekyll-theme-chirpy.css, which does not exist

* At _site/RadiantHero6/categories/index.html:1:

  internally linking to /, which does not exist

* At _site/RadiantHero6/categories/index.html:1:

  internally linking to /, which does not exist

* At _site/RadiantHero6/categories/index.html:1:

  internally linking to /, which does not exist

* At _site/RadiantHero6/categories/index.html:1:

  internally linking to /, which does not exist

* At _site/RadiantHero6/categories/index.html:1:

  internally linking to /categories/, which does not exist

* At _site/RadiantHero6/categories/index.html:1:

  internally linking to /tags/, which does not exist

* At _site/RadiantHero6/categories/index.html:1:

  internally linking to /archives/, which does not exist

* At _site/RadiantHero6/categories/index.html:1:

  internally linking to /about/, which does not exist

* At _site/RadiantHero6/categories/index.html:1:

  internally linking to /feed.xml, which does not exist

* At _site/RadiantHero6/categories/index.html:1:

  internally linking to /posts/newPost/, which does not exist

* At _site/RadiantHero6/categories/index.html:1:

  internally linking to /tags/randomthoughts/, which does not exist

* At _site/RadiantHero6/categories/index.html:1:

  internally linking to /tags/randomthoughts/, which does not exist

* At _site/RadiantHero6/index.html:1:

  internally linking to /assets/img/favicons/apple-touch-icon.png, which does not exist

* At _site/RadiantHero6/index.html:1:

  internally linking to /assets/img/favicons/favicon-32x32.png, which does not exist

* At _site/RadiantHero6/index.html:1:

  internally linking to /assets/img/favicons/favicon-16x16.png, which does not exist

* At _site/RadiantHero6/index.html:1:

  internally linking to /assets/img/favicons/site.webmanifest, which does not exist

* At _site/RadiantHero6/index.html:1:

  internally linking to /assets/img/favicons/favicon.ico, which does not exist

* At _site/RadiantHero6/index.html:1:

  internally linking to /assets/css/jekyll-theme-chirpy.css, which does not exist

* At _site/RadiantHero6/index.html:1:

  internally linking to /, which does not exist

* At _site/RadiantHero6/index.html:1:

  internally linking to /, which does not exist

* At _site/RadiantHero6/index.html:1:

  internally linking to /, which does not exist

* At _site/RadiantHero6/index.html:1:

  internally linking to /categories/, which does not exist

* At _site/RadiantHero6/index.html:1:

  internally linking to /tags/, which does not exist

* At _site/RadiantHero6/index.html:1:

  internally linking to /archives/, which does not exist

* At _site/RadiantHero6/index.html:1:

  internally linking to /about/, which does not exist

* At _site/RadiantHero6/index.html:1:

  internally linking to /feed.xml, which does not exist

* At _site/RadiantHero6/index.html:1:

  internally linking to /posts/newPost/, which does not exist

* At _site/RadiantHero6/index.html:1:

  internally linking to /posts/newPost/, which does not exist

* At _site/RadiantHero6/index.html:1:

  internally linking to /tags/randomthoughts/, which does not exist

* At _site/RadiantHero6/index.html:1:

  internally linking to /tags/randomthoughts/, which does not exist

* At _site/RadiantHero6/posts/newPost/index.html:1:

  internally linking to /assets/img/favicons/apple-touch-icon.png, which does not exist

* At _site/RadiantHero6/posts/newPost/index.html:1:

  internally linking to /assets/img/favicons/favicon-32x32.png, which does not exist

* At _site/RadiantHero6/posts/newPost/index.html:1:

  internally linking to /assets/img/favicons/favicon-16x16.png, which does not exist

* At _site/RadiantHero6/posts/newPost/index.html:1:

  internally linking to /assets/img/favicons/site.webmanifest, which does not exist

* At _site/RadiantHero6/posts/newPost/index.html:1:

  internally linking to /assets/img/favicons/favicon.ico, which does not exist

* At _site/RadiantHero6/posts/newPost/index.html:1:

  internally linking to /assets/css/jekyll-theme-chirpy.css, which does not exist

* At _site/RadiantHero6/posts/newPost/index.html:1:

  internally linking to /, which does not exist

* At _site/RadiantHero6/posts/newPost/index.html:1:

  internally linking to /, which does not exist

* At _site/RadiantHero6/posts/newPost/index.html:1:

  internally linking to /, which does not exist

* At _site/RadiantHero6/posts/newPost/index.html:1:

  internally linking to /, which does not exist

* At _site/RadiantHero6/posts/newPost/index.html:1:

  internally linking to /categories/, which does not exist

* At _site/RadiantHero6/posts/newPost/index.html:1:

  internally linking to /tags/, which does not exist

* At _site/RadiantHero6/posts/newPost/index.html:1:

  internally linking to /archives/, which does not exist

* At _site/RadiantHero6/posts/newPost/index.html:1:

  internally linking to /about/, which does not exist

* At _site/RadiantHero6/posts/newPost/index.html:1:

  internally linking to /feed.xml, which does not exist

* At _site/RadiantHero6/posts/newPost/index.html:1:

  internally linking to /posts/newPost/, which does not exist

* At _site/RadiantHero6/posts/newPost/index.html:1:

  internally linking to /tags/randomthoughts/, which does not exist

* At _site/RadiantHero6/posts/newPost/index.html:1:

  internally linking to /tags/randomthoughts/, which does not exist

* At _site/RadiantHero6/posts/newPost/index.html:1:

  internally linking to /tags/randomthoughts/, which does not exist

* At _site/RadiantHero6/posts/newPost/index.html:1:

  internally linking to /pictures/jigen.png, which does not exist

* At _site/RadiantHero6/tags/index.html:1:

  internally linking to /assets/img/favicons/apple-touch-icon.png, which does not exist

* At _site/RadiantHero6/tags/index.html:1:

  internally linking to /assets/img/favicons/favicon-32x32.png, which does not exist

* At _site/RadiantHero6/tags/index.html:1:

  internally linking to /assets/img/favicons/favicon-16x16.png, which does not exist

* At _site/RadiantHero6/tags/index.html:1:

  internally linking to /assets/img/favicons/site.webmanifest, which does not exist

* At _site/RadiantHero6/tags/index.html:1:

  internally linking to /assets/img/favicons/favicon.ico, which does not exist

* At _site/RadiantHero6/tags/index.html:1:

  internally linking to /assets/css/jekyll-theme-chirpy.css, which does not exist

* At _site/RadiantHero6/tags/index.html:1:

  internally linking to /, which does not exist

* At _site/RadiantHero6/tags/index.html:1:

  internally linking to /, which does not exist

* At _site/RadiantHero6/tags/index.html:1:

  internally linking to /, which does not exist

* At _site/RadiantHero6/tags/index.html:1:

  internally linking to /posts/newPost/, which does not exist

* At _site/RadiantHero6/tags/randomthoughts/index.html:1:

  internally linking to /posts/newPost/, which does not exist

* At _site/RadiantHero6/tags/randomthoughts/index.html:1:

  internally linking to /tags/randomthoughts/, which does not exist

* At _site/RadiantHero6/tags/randomthoughts/index.html:1:

  internally linking to /tags/randomthoughts/, which does not exist

* At _site/RadiantHero6/tags/randomthoughts/index.html:1:

  internally linking to /tags, which does not exist

For the Scripts check, the following failures were found:

* At _site/RadiantHero6/404.html:1:

  internal script reference /assets/js/dist/page.min.js does not exist

* At _site/RadiantHero6/404.html:1:

  internal script reference /app.js does not exist

* At _site/RadiantHero6/about/index.html:1:

  internal script reference /assets/js/dist/page.min.js does not exist

* At _site/RadiantHero6/about/index.html:1:

  internal script reference /app.js does not exist

* At _site/RadiantHero6/archives/index.html:1:

  internal script reference /assets/js/dist/misc.min.js does not exist

* At _site/RadiantHero6/archives/index.html:1:

  internal script reference /app.js does not exist

* At _site/RadiantHero6/categories/index.html:1:

  internal script reference /assets/js/dist/categories.min.js does not exist

* At _site/RadiantHero6/categories/index.html:1:

  internal script reference /app.js does not exist

* At _site/RadiantHero6/index.html:1:

  internal script reference /assets/js/dist/home.min.js does not exist

* At _site/RadiantHero6/index.html:1:

  internal script reference /app.js does not exist

* At _site/RadiantHero6/posts/newPost/index.html:1:

  internal script reference /assets/js/dist/post.min.js does not exist

* At _site/RadiantHero6/posts/newPost/index.html:1:

  internal script reference /app.js does not exist

* At _site/RadiantHero6/tags/index.html:1:

  internal script reference /assets/js/dist/commons.min.js does not exist

* At _site/RadiantHero6/tags/index.html:1:

  internal script reference /app.js does not exist

* At _site/RadiantHero6/tags/randomthoughts/index.html:1:

  internal script reference /assets/js/dist/misc.min.js does not exist

* At _site/RadiantHero6/tags/randomthoughts/index.html:1:

  internal script reference /app.js does not exist

HTML-Proofer found 166 failures!
Error: Process completed with exit code 1.`

When looking at the terminal, I get no errors with the building (I don't think) and only see the error on Github itself.

`Counting objects: 100% (7/7), done.
Delta compression using up to 16 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 407 bytes | 407.00 KiB/s, done.
Total 4 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.`

### Steps To Reproduce

1. In an Arch Linux environment, I cloned the page to my PC to work on it locally. The token was set to contents, pages to read/write.
2. After following the video I posted above, I got to the part for building the website, outside of making a new post and editing the _config.yml, nothing additional was done 
3. I did `git status` `git add .`, `git commit -m "comment`, then finally `git push`. No errors from the terminal as said above, 
4. Checked the Github page and got the HTML-parser error as shown above.

### Expected Behavior

After compiling the website, it would be pushed to the main branch without error.

### Environment

- Ruby: `ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux]`
- Jekyll: `jekyll 4.3.2`
- Chirpy: `jekyll-theme-chirpy (6.2.2)
        Summary: A minimal, responsive and feature-rich Jekyll theme for technical writing.
        Homepage: https://github.com/cotes2020/jekyll-theme-chirpy
        Documentation: https://github.com/cotes2020/jekyll-theme-chirpy/#readme
        Source Code: https://github.com/cotes2020/jekyll-theme-chirpy
        Wiki: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
        Bug Tracker: https://github.com/cotes2020/jekyll-theme-chirpy/issues
        Path: /usr/lib/ruby/gems/3.0.0/gems/jekyll-theme-chirpy-6.2.2
`

### Anything else?

When running the local server I have to run it under sudo (I know not the best things to do) but when not running it, I get

`/usr/lib/ruby/3.0.0/fileutils.rb:243:in `mkdir': Permission denied @ dir_s_mkdir - /home/josh/Documents/GitHub/RadiantHero6/.jekyll-cache/Jekyll/Cache/Jekyll--Converters--Markdown/3c (Errno::EACCES)`

I don't think this is causing the issue, but I figured I'd throw it out there. 

Here is a link to the _config.yml https://github.com/RadiantHero6/RadiantHero6/blob/main/_config.yml

And here's a link to the Gemfile https://github.com/RadiantHero6/RadiantHero6/blob/main/Gemfile

I think the error is due to pathing issues, but I'm unsure as to why it would work fine under local server, but not being pushed to Github.

**Comment by RadiantHero6** [comment]
Why is this closed? I filled out the info best I can.

**Comment by dawany** [comment]
I am facing the same issue here
Any solutions?

**Comment by radianthero** [comment]
> I am facing the same issue here Any solutions?

Restart the process, verify the name os correct from the template, worked for me.

**Comment by sidwarkd** [comment]
@radianthero I had the same issue. In my case I found that the GH Actions was building the site in one location and htmlproofer was running against a different folder. In pages-deploy.html I changed `bundle exec htmlproofer _site \` to `bundle exec htmlproofer _site${{ steps.pages.outputs.base_path }} \`

**Comment by gezuka77** [comment]
> > I am facing the same issue here Any solutions?
> 
> Restart the process, verify the name os correct from the template, worked for me.

I am also facing the same issue as above. Can you clarify what is the " name os"? thanks

**Comment by twaslowski** [comment]
This issue is caused by a path mismatch of the build directory and the directory that the test refers to.

```
bundle exec jekyll b -d "_site${{ steps.pages.outputs.base_path }}"
```

This builds to e.g. `_site/blog`.

```
bundle exec htmlproofer "_site" \
            \-\-disable-external=true \
            \-\-ignore-urls "/^http:\/\/127.0.0.1/,/^http:\/\/0.0.0.0/,/^http:\/\/localhost/"
```

This verifies `_site`, which fails. Running `bundle exec htmlproofer "_site${{ steps.pages.outputs.base_path }}"` fixes the issue for me.

**Comment by LastHaoBrother** [comment]
我遇到同样的问题，应该怎么做

**Comment by imcpap** [comment]
My site was created with [chirpy-starter](https://github.com/cotes2020/chirpy-starter) and had the same problem at first. If you follow the [official guideline](https://github.com/cotes2020/jekyll-theme-chirpy/wiki/Upgrade-Guide#upgrade-the-fork) step by step, the problem may be solved. 

In addition, although this may not be the official answer, here's an equally quick solution: 
- If you created a local repository using the `bundle exec jekyll s` command with Terminal, you would have a `_site` folder in your local copy. 
- Now, go to the `.gitignore` file and delete the `_site` line. The folder will be pushed now, and everything works fine, at least for me.

**Comment by SoumyaK4** [comment]
@imcpap htmlproofer error only occurs when any link is not `https` or it's a broken internal link.

Make sure you don't have any of these 2 errors and it'll work

**Comment by pro100svitlo** [comment]
thank you @imcpap for the hint.
wonder if this shoul be fixed by default 🤔
