### ISSUE TITLE
everything going wrong on setup

### ISSUE THREAD

**Issue by KoolKidz112** [cotes2020/jekyll-theme-chirpy#127]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [x] I found the bug on the latest code of `master` branch.

## Describe the bug
I'm not sure if this is just a problem with one of the gems, but for whatever reason whenever I do the setup exactly  I still get lots of errors thrown in my face, then I find a solution, and now i've reached a dead end.

### To Reproduce

1. follow steps up until initialization
2. type in bash tools/init.sh --no-gh
3. error:
```
tools/init.sh: line 9: $'\r': command not found
: invalid optionine 10: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
tools/init.sh: line 11: $'\r': command not found
tools/init.sh: line 13: $'\r': command not found
tools/init.sh: line 14: syntax error near unexpected token `$'{\r''
'ools/init.sh: line 14: `help() {
```
4. run again and it throws the same error
5. try to run locally, returns same error as init.sh ~~tells me i forgot tzinfo (which apparently was removed in a recent commit)~~
6. add timezone, asks me to put some sort of require at top of eventmachine script, i do that
7. no socket and ebadf errors, not sure what to do

### Expected behavior
for it to init correctly, the timezones to work correctly and to be able to run it

### Screenshots
![2020-09-13 10_20_20-Window](https://user-images.githubusercontent.com/22648124/93020490-628f6980-f5ab-11ea-8d49-37185064a3e2.png)

### Software

- Ruby version: 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32]
- Gem version: 3.0.3
- Bundler version: 2.1.4
- Jekyll version: 4.1.1

### Desktop

- OS: Windows 10 Enterprise 1909
- Browser: Version 85.0.4183.102 (Official Build) (64-bit)

**Comment by cotes2020** [comment]
Google is your friend: <https://stackoverflow.com/questions/5230798/r-character-in-shell-script>

Since you are using Windows 10,I suggest to run this project in WSL.

**Comment by KoolKidz112** [comment]
alright, so im using wsl (i think) and i did dos2unix but
![2020-09-13 11_43_24-Window](https://user-images.githubusercontent.com/22648124/93022288-8f954980-f5b6-11ea-976b-5b6164a19694.png)
im not incredibly tech savvy and im not sure if im doing this right??
i tried googling again and scrolling down further but i guess either there was no good answer, it seemed to complicated, or something else
also, for whatever reason running dos2unix on init.sh made it say it already initialized
on a sidenote are there extra things you need to do to put a site w/ this theme on ftp clients?

**Comment by cotes2020** [comment]
The link above is to let you know why this problem occurs. Also, what I want to express is, first delete your local clone, then clone again under wsl, and run this project.

**Comment by KoolKidz112** [comment]
great now im stuck running in circles trying to get a ssh key working
running in git bash removes the weird \r error but still forces me to download tzinfo which was removed in a commit obviously for a reason i hope
ill try to get thiss wsl thing working
