### ISSUE TITLE
Contents are empty after forking version 6.2.2 

### ISSUE THREAD

**Issue by ancatut** [cotes2020/jekyll-theme-chirpy#1271]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Built from `jekyll-theme-chirpy`

### Describe the bug

The contents sidebar appears empty for all posts:
![grafik](https://github.com/cotes2020/jekyll-theme-chirpy/assets/7820090/13742218-1c76-4de2-be05-db988682c74b)

### Steps To Reproduce

I encountered this issue both on the localhost as well as after deploying to Github Pages. Clearing the browser cache did not resolve it, as someone else reported (https://github.com/cotes2020/jekyll-theme-chirpy/issues/1236).

### Expected Behavior

I expected to see the contents of the headlines in the post in the sidebar.

### Environment

ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x64-mingw-ucrt]
jekyll 4.3.2
jekyll-theme-chirpy (6.2.2)

**Comment by NichtsHsu** [comment]
Have you run `tools/init`?

**Comment by ancatut** [comment]
> Have you run `tools/init`?

Yes! I do also get some JS errors though when running the local server, unsure if this is related: `ERROR `/assets/js/dist/post.min.js' not found.`
