### ISSUE TITLE
Make images in tabs not always expand

### ISSUE THREAD

**Issue by rzimmerdev** [cotes2020/jekyll-theme-chirpy#1279]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

I have the following problem:

When inserting a image using the <img> tag within any markdown tab file, such as the about.md file, the image automatically expands when clicked upon. This makes it impossible to add a <a> link tag around the image tag, so as to link to a reference for example, since clicking on the image expands it instead of redirecting to the link. Any suggestions on how to edit the default implementation?

### Describe the solution you'd like

Maybe make the popup class optional to the images, only active if I myself write <img class="popup"> in the HTML

### Describe alternatives you've considered

I've tried adding the image with the default markdown tag, which did work, but limits what I can do to the image.

**Comment by rzimmerdev** [comment]
I've found a somewhat limited workaround:
<div markdown="1">
[![alt text here](https://img.com)][https://redirect_url_here.com]
</div>

Altough this doesnt allow me to add tags to the image...

**Comment by serezhka** [comment]
Hi @rzimmerdev, I do it this way:

assetss/css/jekyll-theme-chirpy.scss
```scss
---
---

@import 'main';

/* append your custom style below */

.nopopup {
  pointer-events: none;
}
```

my-post.md
```md
![image](/assets/img/image.jpg){: width="100" .left .nopopup}
```

**Comment by rzimmerdev** [comment]
But doesn't this still leave the non-functional link problem?
