### ISSUE TITLE
Suggestions for tutorial

### ISSUE THREAD

**Issue by ZhengYuan-Public** [cotes2020/jekyll-theme-chirpy#1305]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

I have been bothered by some inline math rendering issues for weeks and I finally managed to find solutions. I think the solutions I found are worth being mentioned in the [Writing a New Post](https://chirpy.cotes.page/posts/write-a-new-post/) tutorial for people who write a lot of math in their posts.

[Here](https://zhengyuan-public.github.io/posts/PersonalBlogWithJekyll/#latex-math-equations-in-jekyll) are my experiments and the solutions I found.

### Describe the solution you'd like

This summary part of my solutions should be enough. But feel free to verify it first and modify the wording.

# Summary
The standard markdown syntax adds block math with `$$ math $$` and inline math with `$ math $`. However, kramdown (the default markdown engine of Jekyll) uses a different syntax as explained [here](https://kramdown.gettalong.org/syntax.html). With [jekyll-theme-chirpy](https://github.com/cotes2020/jekyll-theme-chirpy), the syntax from kramdown doc is also not working correctly, and here are the solutions that work:

- block math should be added with `$$ math $$` with a blank line both before and after `$$`
- inline math (normal) should be added with `$$ math $$` without any blank lines before or after `$$`
- inline math (in lists) should be added with `\$$ math $$`

**Comment by cotes2020** [comment]
Alright, are you considering submitting it as a PR?

**Comment by ZhengYuan-Public** [comment]
> Alright, are you considering submitting it as a PR?

Sure, but it will be my first time to submit a PR. Please give me some time to learn how to do that :D

**Comment by cotes2020** [comment]
[GitHub Docs: Creating a pull request
](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)

**Comment by ZhengYuan-Public** [comment]
> [GitHub Docs: Creating a pull request ](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)

A PR has been submitted, please review it at your convenience.

**Comment by deepConnectionism** [comment]
> inline math (normal) should be added with $$ math $$ without any blank lines before or after $$
This works, but because I write in Markdwon, I usually use $... $ as inline math, how can I support it? Otherwise the article can not display normally on other blog platforms.
