### ISSUE TITLE
Empty spaces in home layout after upgrading to 6.2.3

### ISSUE THREAD

**Issue by DmitriyFrogo** [cotes2020/jekyll-theme-chirpy#1312]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

I found that after upgrading from 6.2.2 to 6.2.3, now all posts on home page, have empty space right after preview image, if you use images smaller than expected
![chirpy623-1](https://github.com/cotes2020/jekyll-theme-chirpy/assets/65223198/a793b8a4-16d7-4256-8c5f-cff2e18e13c3)

Also I found quick fix for me
You need to add `width="100%" height="100%"` in this part of code:
https://github.com/cotes2020/jekyll-theme-chirpy/blob/897b57bfb4404c9ccbb5909008b7029980272e65/_layouts/home.html#L64

Like this: `<img src="{{ src }}" alt="{{ alt }}" width="100%" height="100%" {{ lqip }}>`

So it looks like this now:
![chirpy623-2](https://github.com/cotes2020/jekyll-theme-chirpy/assets/65223198/92ca2af9-ed5b-4307-97e8-e420c2c3aaa9)

I'm not a developer, so I don't know if there will be problems from my fix, but at first look it works fine

### Steps To Reproduce

1. Upgrade chirpy-starter from 6.2.2 to 6.2.3
2. Open home page
3. See empty spaces within preview images

### Expected Behavior

No empty spaces

### Environment

- Ruby: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x64-mingw-ucrt]
- Jekyll: jekyll 4.3.2
- Chirpy: jekyll-theme-chirpy (6.2.3)

**Comment by geduardo** [comment]
Same issue, thanks for the fix.

**Comment by DmitriyFrogo** [comment]
> Same issue, thanks for the fix.

As I said above, I'm not a developer, so I can't guarantee that my fix won't break something else
I suggest you to wait and see what @cotes2020 can say about it

**Comment by bigsk1** [comment]
having same issue but using starter and no _layout to modify. 

ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]

<a href="https://imageshack.com/i/pmIuAtHFj" target="_blank"><img alt="FireShot Pro Screen Capture" src="https://imagizer.imageshack.com/img922/1218/IuAtHF.th.jpg" border="0"></a><br/><a href="https://imageshack.com/i/pmIuAtHFj" target="_blank">View Screen Capture</a>

**Comment by cotes2020** [comment]
It is indeed an issue, but you won't get blanks if you follow the docs and use _1.91 : 1_ images.

**Comment by DmitriyFrogo** [comment]
> It is indeed an issue, but you won't get blanks if you follow the docs and use _1.91 : 1_ images.

You're right, but we're lazy people and we want to write posts, not think about aspect ratios :D
The main problem is that this behavior was not present in 6.2.2
Without my small fix with "width/height=100%", I need to manually resize 150+ images, but now I can even use ugly stretched 100x100 image
