### ISSUE TITLE
Background image scrolls along with post

### ISSUE THREAD

**Issue by humanishh** [cotes2020/jekyll-theme-chirpy#1314]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Built from `jekyll-theme-chirpy`

### Describe the bug

I have heavily modified this theme to suit my requirements of an academic website (I quite like the 3-panel layout, which chirpy does best). I noticed that whenever I set an user-chosen image as the background (specified in the 'body' wrapper in the commons.scss file), and I go to the section where the posts are displayed ('Thoughts' in my case), and click on the post, the image is stretched by a huge amount. The image is aligned with the entire length of the post, it therefore scrolls along with the post, therefore stretching it to the current width of the screen. I have looked at the files and I could not understand the underlying reason. (For context, the 4 bright sources on the left of the Home written above the 'Text and Typography' line (in image 1) are the exact same 4 sources seen in image 2. Notice the degree to which they have been vertically stretched)
![1 Normal](https://github.com/cotes2020/jekyll-theme-chirpy/assets/58658805/759f0f75-15bf-4795-8d58-95f316b0b2e0)
![2 Distorted](https://github.com/cotes2020/jekyll-theme-chirpy/assets/58658805/e2578e9c-a586-4518-adae-4430a1361618)

### Steps To Reproduce

1. Set  background: url('Image.png'); in the body {} wrapper (line 31 in my commons.scss file)
2. Open the Thoughts tab
3. Click on any post

### Expected Behavior

Ideally, the post should scroll whilst the background image stays constant. Instead, the image scrolls too

### Environment

- Ruby:  ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-linux]
- Jekyll:  jekyll 4.3.2
- Chirpy:  6.2.2

**Comment by DmitriyFrogo** [comment]
First of all - you didn't read [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md) properly
It's not theme bug, but your code, and you should've create [discussion here](https://github.com/cotes2020/jekyll-theme-chirpy/discussions)

What about your issue
I was bored, so I tried to figure out
I see on your screenshot, that you not uploaded post image, and have problem with "page.image.no_bg" placeholder
Delete this line or try to fix by yourself (give it fixed width/height maybe?)
https://github.com/cotes2020/jekyll-theme-chirpy/blob/897b57bfb4404c9ccbb5909008b7029980272e65/_layouts/post.html#L35

**Comment by humanishh** [comment]
I am so sorry for the mistakes. This is my first time posting an issue on Github. 
Here is the Image
![Bkg](https://github.com/cotes2020/jekyll-theme-chirpy/assets/58658805/00b7a740-6233-467a-8bff-dc81daaca983)
