### ISSUE TITLE
添加对post正文的截断支持，使得首页仅显示截断前的内容

### ISSUE THREAD

**Issue by sirlis** [cotes2020/jekyll-theme-chirpy#132]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There are no similar request on existing issues (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

目前首页的post列表，直接摘取文章开头的一部分。假如post开头是目录，显示效果略尴尬。

![image](https://user-images.githubusercontent.com/12960298/93451951-648a5d00-f90a-11ea-9180-c477e282c0cf.png)

能否增加对类似`<!--more-->`的支持，使得首页只显示`<!--more-->`之前的内容？

## Describe the solution you'd like

无。恕在下不懂。

## Describe alternatives you've considered

或者改成固定截取第一个段落也行。

## Additional context

目前加上`<!--more-->`么的效果。

```
诺兰的新电影《信条》，凭借硬核的科幻背景和烧脑的剧情回路，成功绕晕了广大观影群众。本文试图从电影中的科学概念出发，一步步解析电影剧情的时间线索。

<!--more-->

- [1. 前言](#1-前言)
- [2. 熵](#2-熵)
```

![image](https://user-images.githubusercontent.com/12960298/93452257-c9de4e00-f90a-11ea-9dd6-248361132888.png)

**Comment by cotes2020** [comment]
Duplicate issue #42
