### ISSUE TITLE
HTML entities are not being decoded properly in the preview on the post list page

### ISSUE THREAD

**Issue by davidmolinacano** [cotes2020/jekyll-theme-chirpy#1332]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Built from `jekyll-theme-chirpy`

### Describe the bug

If the first lines of a post contains some special HTML entities inside a `<code>` tag, they are shown encoded in the post preview. For example:

`|>` is transformed into |&gt;

Post content:

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/128705267/156cf921-2001-4dbc-94e9-6cb4642c21e5)

Post preview:

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/128705267/7d18894a-d660-4431-8e9b-16c06fe179e5)

### Steps To Reproduce

1. Write a post whose first line contains some special HTML entity like &, >, < inside a `<code>` tag.
2. Go to the post preview page
3. In the preview, the HTML entities are shown encoded (&amp;, &gt;, &lt;)

### Expected Behavior

The HTML entities should be shown decoded in the post preview as they are shown in the post content

### Environment

- Ruby: 
- Jekyll: 
- Chirpy:

**Comment by carlosescri** [comment]
A solution could be to accept some kind of `excerpt` meta like the `title` in the front matter so, if present, that's used _raw_ instead of the current default behavior of stripping HTML, escaping, etc.

**Comment by Mal-X-Hunter** [comment]
what's solution

**Comment by carlosescri** [comment]
if post has excerpt meta do
      output meta.excerpt
    else
      do whatever is being done now
    end

It's been a long since the last time I used Jekyll and Liquid so I'm won't try to provide an actual snippet until I have some time to take a look 😅. 

    ---
    title: Hello world
    excerpt: |
      <p>This should be used raw…</p>
    ---

I mean, I see this as a feature, so people in this case don't have to change the template just to do that while the code is relatively simple.

**Comment by hectorperez** [comment]
I think @carlosescri's solution is elegant and would be a new small feature for Chirpy.
@cotes2020 what do you think?

**Comment by StrongShiv8** [comment]
Is it implemented yet . The `except`  feature for Chirpy Theme ?
