### ISSUE TITLE
Is is possible to add an auto-generated "time to read the post"

### ISSUE THREAD

**Issue by dopewind** [cotes2020/jekyll-theme-chirpy#134]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

Is it possible to add an "time to read" along with the description of each post?

This would greatly encourage a reader to read the content as it will give them a rough amount of time they have to dedicate to it.

I think [this](https://carlosbecker.com/posts/jekyll-reading-time-without-plugins) and [this ](https://int3ractive.com/blog/2018/jekyll-read-time-without-plugins/) would give a clear idea on what I meant.

Please have a go at this if you have some spare time

**Comment by cotes2020** [comment]
I don’t think this feature is necessary, but you can add it to your fork :)
