### ISSUE TITLE
Cache invalidation?

### ISSUE THREAD

**Issue by kadinzhang** [cotes2020/jekyll-theme-chirpy#135]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [X] There are no similar question on existing issues (including closed ones).
- [X] I searched the Internet for related problems, but still couldn't solve it.
- [X] My question is based on the latest code of `master` branch.

## Description

Whenever I push an update out to github pages, I need to manually delete my cache in order to view changes. For example, if I Ctrl-shift-r, I can see the new changes, but following that up with a normal reload reverts everything. Is there any cache invalidation I can implement?

**Comment by cotes2020** [comment]
What is your browser type and version?

**Comment by kadinzhang** [comment]
I'm using Chrome 85 (newest version).

**Comment by cotes2020** [comment]
That is the cache of [PWA tech](https://web.dev/progressive-web-apps/): Every time your website is updated, the PWA process of the browser will check the latest content of the server in the background and update the local cache. Before that, the content displayed on the browser is cached from the previous version. Usually this process takes tens of seconds to several minutes, and you do not need to force refresh. If you are in a hurry to see the latest content immediately, you can use the `incognito` mode in Chrome.
