### ISSUE TITLE
yq: error: argument files : can't open 'categories.*'

### ISSUE THREAD

**Issue by nanometre380** [cotes2020/jekyll-theme-chirpy#136]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

I got 404-Not Found on "Categories" and "Tags" Page.
In tutorial, You said 'Once the build is complete, a new remote branch called gh-pages will appear',  but there is no 'gh-pages' of mine.
I also tried tools /publish.sh, but I got 'yq: error: argument files: can't open 'categories.*': [Errno 22] Invalid argument: 'categorie', 'yq: error: argument files: can't open 'category': [Errno 2] No such file or directory: 'categ'...the same goes for tags. 
I don't know what's the problem. Please help me.

**Comment by cotes2020** [comment]
> You said 'Once the build is complete, a new remote branch called gh-pages will appear', but there is no 'gh-pages' of mine.

So, why not check the GitHub Actions log to investigate the cause of the build failure?

> I also tried tools /publish.sh, but I got 'yq: error: argument files: can't open 'categories.*': [Errno 22] Invalid argument: 'categorie', 'yq: error: argument files: can't open 'category': [Errno 2] No such file or directory: 'categ'...the same goes for tags.

Didn’t the error message indicate the reason?  Please correct the `categories` definition of your posts.
