### ISSUE TITLE
The blog title images are not fixed in their frames

### ISSUE THREAD

**Issue by anonfaded** [cotes2020/jekyll-theme-chirpy#1367]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

The blog title images are not fixed in their frames when i push it to github page [here](https://anonfaded.github.io) , but they are perfect on localhost.
It was all fine for previous posts but after uploading my second last post, all the title pictures for blog posts got strange and they are not in their frames, their is empty space which you can see in the attached screenshot below. 

![Screenshot](https://github.com/cotes2020/jekyll-theme-chirpy/assets/124708903/b2c17662-8a3d-4baf-8564-f1c9c23f5bb0)

### Steps To Reproduce

.

### Expected Behavior

The blog title images should be fixed in it frame but its going to left and an empty space on right is being created

### Environment

- Ruby: 
- Jekyll: 
- Chirpy: 

### Anything else?

Is this a bug or what? on localhost if its all good then why on github pages it is getting empty space in its frames?

**Comment by cotes2020** [comment]
Duplicated of #1312
