### ISSUE TITLE
Live Demo link in README is broken

### ISSUE THREAD

**Issue by kkangmj** [cotes2020/jekyll-theme-chirpy#1386]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

Demo link in REAME.md and [jamstack themes website](https://jamstackthemes.dev/theme/jekyll-theme-chirpy/) is not working. I found proper link in repository description section.

### Steps To Reproduce

1. Click 'Live Demo' link in README or click 'Demo' button in jamstack themes website.

### Expected Behavior

Should be linked to demo website. 

### Environment

Chrome, Windows 11

**Comment by cotes2020** [comment]
The link now work properly.
