### ISSUE TITLE
The menu button does not work on the mobile version

### ISSUE THREAD

**Issue by edsouzadev** [cotes2020/jekyll-theme-chirpy#1389]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

The menu button does not work on the mobile version. I click the button, but it doesn't open the menu. Could anyone help to resolve

### Steps To Reproduce

The button that opens the menu in the mobile version does not work in the local installation or in Github pages
![Screenshot 2023-11-23 at 10-19-11 Edson Souza](https://github.com/cotes2020/jekyll-theme-chirpy/assets/149672520/4b40a619-a659-4c2a-b70a-e78879938691)

### Expected Behavior

When clicking the button, the menu should open, but it is not working. Test across browsers.

### Environment

- Ruby: 
- Jekyll: 
- Chirpy:

**Comment by nrjycyd** [comment]
Same problem

**Comment by nrjycyd** [comment]
#1033 
I found the solution
