### ISSUE TITLE
How can I add Category and sub-posts inside each category ?

### ISSUE THREAD

**Issue by YasserElsnbary** [cotes2020/jekyll-theme-chirpy#139]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

**Comment by cotes2020** [comment]
I'm not quite sure what you mean, could you be more specific？
