### ISSUE TITLE
Tags page 404: Page not found

### ISSUE THREAD

**Issue by Onurbolatogluu** [cotes2020/jekyll-theme-chirpy#140]
I have a problem when I enter the tags section of the site I run on github. I see 404 even if I add a new tag. What's the problem?
![tags](https://user-images.githubusercontent.com/46894029/94972188-601c9180-0511-11eb-9c2c-3611e33d58a4.PNG)

**Comment by cotes2020** [comment]
Relax, follow the tutorials and you won't get a 404.

**Comment by Onurbolatogluu** [comment]
@cotes2020 I have read the documents but it is still the same. Problem not solved.

1. git clone https://github.com/Onurbolatogluu/Onurbolatogluu.github.io.git -b master --single-branch

2- run bash tools / init.sh

3- run git push -u origin master

What's missing?

**Comment by cotes2020** [comment]
@Onurbolatogluu You missed the entire **Deployment** section. Why not continue patiently read the rest of the _Getting Started_, it only takes a few minutes.

**Comment by Onurbolatogluu** [comment]
Thank you for your support, I'm new around here. My problem has been fixed.
