### ISSUE TITLE
Chirpy theme: ‘a’ tag is missing a reference when author url is missing

### ISSUE THREAD

**Issue by SRodi** [cotes2020/jekyll-theme-chirpy#1403]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

 GH Actions build jobs are failing when author url is missing.

see build example here https://github.com/SRodi/srodi.github.io/actions/runs/7058684466/job/19214755311

```
Running 3 checks (Scripts, Links, Images) in ["_site"] on *.html files...


Checking 43 internal links
Checking internal link hashes in 2 files
Ran on 17 files!


For the Links check, the following failures were found:

* At _site/posts/how-to-test-terraform-modules/index.html:1:

  'a' tag is missing a reference


HTML-Proofer found 1 failure!
Error: Process completed with exit code 1.
```

### Steps To Reproduce

Assuming `GitHub actions` are configured to automatically build the project on commit pushes to remote.

1. Create file `_data/_authors.yml` with the author info omitting the url, something like 

```yml
srodi:
  name: Simone Rodigari
```

2. Add author details in the _Front Matter_ as follows

```yml
---
title: "..."
date: 2023-09-19 09:00:00 +0100
categories: ["...", "..."]
tags: ["...", "..."]
author: srodi
...
---
```

3. GH Action build job fails

### Expected Behavior

* job should not fail
* error message could be more descriptive
* default url could be set? (i.e. website url)

### Environment

```
❯ ruby -v
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-darwin23]
❯ bundle exec jekyll -v
jekyll 4.3.2
❯ bundle info jekyll-theme-chirpy
  * jekyll-theme-chirpy (6.3.1)
        Summary: A minimal, responsive, and feature-rich Jekyll theme for technical writing.
        Homepage: https://github.com/cotes2020/jekyll-theme-chirpy
        Documentation: https://github.com/cotes2020/jekyll-theme-chirpy/#readme
        Source Code: https://github.com/cotes2020/jekyll-theme-chirpy
        Wiki: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
        Bug Tracker: https://github.com/cotes2020/jekyll-theme-chirpy/issues
        Path: /Users/simone/.gem/ruby/3.2.2/gems/jekyll-theme-chirpy-6.3.1
```

### Anything else?

Reference to community blog post with solution: https://talk.jekyllrb.com/t/chirpy-theme-a-tag-is-missing-a-reference/8731

**Comment by cotes2020** [comment]
Hi @SRodi, thanks for submitting this issue, but this is caused by the missing required attribute `url` which is one of the required items as shown in the `data.authors` template.

https://github.com/cotes2020/jekyll-theme-chirpy/blob/84ea68cab0c09492162aa9672421bca16651e689/_data/authors.yml#L6

> error message could be more descriptive

The error message is generated by the plugin [**Html Proofer**](https://github.com/gjtorikian/html-proofer) and we can't change it.

**Comment by SRodi** [comment]
thanks @cotes2020 that makes sense to me! But what did @chuckhoupt mean with the following [in this comment](https://talk.jekyllrb.com/t/chirpy-theme-a-tag-is-missing-a-reference/8731/3?u=srodi)? Should this be reported in another repo?

>postscript: the theme behavior in the absence of an author’s URL should probably be reported as a bug.

**Comment by cotes2020** [comment]
I think what he means is to submit a report on this repository, which is what you've already done.

I don't think there is a need at this stage to allow the behavior of empty `author.url`, as author names without links don't make much sense. **Html-Proofer** just makes sure that it's possible to warn a site about missing required fields.

**Comment by chuckhoupt** [comment]
Some background: The `author.url` field was only [added to Jekyll-SEO-Plugin a few years ago as an optional field](https://github.com/jekyll/jekyll-seo-tag/pull/453/files). So I think it is reasonable to expect themes using `authors.yml` to also treat it as optional. The only required field is `author.name`.

A classic case of an URL-less author would be an anonymous reporter, but many people won't have home pages.

```
anon:
  name: Anonymous Reporter
  picture: /img/masked-face.jpg
```

**Comment by cotes2020** [comment]
@chuckhoupt thanks for adding this valuable information, would you be willing to create a PR to help with this enhancement?
