### ISSUE TITLE
Bug on local install

### ISSUE THREAD

**Issue by CM-CA** [cotes2020/jekyll-theme-chirpy#1414]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Built from `jekyll-theme-chirpy`

### Describe the bug

After execute the command to start local server, i recived a sass compilation error.

### Steps To Reproduce

1. Using a Debian based SO and after clone the repo, i proceed to build the aplication.
2. When i execute the comman `bundle exec jekyll s` i recive the error
![2023-12-10-19:22:02-sc](https://github.com/cotes2020/jekyll-theme-chirpy/assets/22884689/666c613e-e045-43e1-8999-f381b8969e33)
3. After check files, i found the error on assets/css/jekyll-theme-chirpy.scss. The bug in question occurs due to the first two lines, which should be removed.
![2023-12-10-19:27:08-sc](https://github.com/cotes2020/jekyll-theme-chirpy/assets/22884689/88fc917e-9e86-4de3-bdb0-99e9ae8cab2c)

### Expected Behavior

After delete both lines, finally i can run the server and start working in local mode.
![2023-12-10-19:47:20-sc](https://github.com/cotes2020/jekyll-theme-chirpy/assets/22884689/e4079d88-19ed-4ae0-ba52-5885afd1f1e7)
![2023-12-10-19:44:34-sc](https://github.com/cotes2020/jekyll-theme-chirpy/assets/22884689/59f85aa7-077e-4262-aee9-d5b03d933adb)

### Environment

- Ruby: 
- Jekyll: 
- Chirpy:

**Comment by CM-CA** [comment]
But theme doesnt load.
![2023-12-10-19:59:48-sc](https://github.com/cotes2020/jekyll-theme-chirpy/assets/22884689/881a6e29-b1d0-4b99-9ab7-65c8159b4590)
![2023-12-10-20:00:12-sc](https://github.com/cotes2020/jekyll-theme-chirpy/assets/22884689/d458e585-cfe4-4d85-aaba-2f1356f19a0d)

**Comment by chuckhoupt** [comment]
> 3. After check files, i found the error on assets/css/jekyll-theme-chirpy.scss. The bug in question occurs due to the first two lines, which should be removed.

That's not an error. The (empty) YAML front-matter is required by Jekyll to trigger SASS/SCSS processing. See [Jekyll's Asset doc for details](https://jekyllrb.com/docs/assets/).

The problem you have is in step 2, where the SASS-Embed gem fails to load due to an apparently corrupt shared library (`libc.so`)? Here the error:

```
/.../ sass-embedded-1.69.5.../dart: error while loading shared libraries: /lib/×86_64_linux_gnu/libc.so invalid ELF header
```

The root cause is likely something to do with the Ruby and Gem building setup on the system.

**Comment by CM-CA** [comment]
Thank you very much for the response. It's correct; point 3 was due to an error in the installation. After correcting it, the issue is now resolved. My apologies.
