### ISSUE TITLE
Image caption support

### ISSUE THREAD

**Issue by libesz** [cotes2020/jekyll-theme-chirpy#144]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There are no similar request on existing issues (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

I am just converting my wordpress blog to GHP + this template, which is great so far, thanks for doing it! After a lot of automated conversion I arrived to image captions.
My side dump contains image miniatures, which are links to the full size images with caption. It looks like this:
```
[caption id="attachment\_428" align="aligncenter" width="300" caption="caption text"][![]({{ site.baseurl }}/assets/images/2011/03/IMGP7194-300x200.jpg "IMGP7194")]({{ site.baseurl }}/assets/images/2011/03/IMGP7194.jpg)[/caption]
```
I learned [here](https://stackoverflow.com/questions/19331362/using-an-image-caption-in-markdown-jekyll) that Jekyll supports caption generation. So if I change the above snippet to this:
```
[![]({{ site.baseurl }}/assets/images/2011/03/IMGP7194-300x200.jpg "IMGP7194")]({{ site.baseurl }}/assets/images/2011/03/IMGP7194.jpg)
*caption text*
```
It generates an `<em>` tag under the `<a>` in the same `<p>`.
Now the problem is that the caption text is in the same line as the image, while I would expect to be below the image.

## Describe the solution you'd like

With the pattern above, I was able to add a custom css like this to cover both links and pure images:
```
img + em, a + em { display: block; text-align: center; }
```

## Additional context

I am not a frontend guy so I could easily miss some other alternatives which are already supported.

**Comment by cotes2020** [comment]
looks cool, I will take the time to research this solution

**Comment by cotes2020** [comment]
Hi @libesz,

The style for common  (no hyperlink) image caption has been added, but for now it does not fit the style of the hyperlink image. Because it will be forced to give up the underline effect of the text link, otherwise, a horizontal line will be displayed under the hyperlink picture. 

Once the [`:has()`](https://drafts.csswg.org/selectors-4/#has-pseudo) selector is online, I'll add support for the missing part.

**Comment by libesz** [comment]
Thanks. I will check what I can do until then with my content...

**Comment by cotes2020** [comment]
After some thought, waiting for the CSS standard to be updated and for major browsers to support new features was a long way off, so I solved this problem with JS.

**Comment by libesz** [comment]
Thank you for the solution. Seems works fine with my content!
