### ISSUE TITLE
Image float causing text features to bug

### ISSUE THREAD

**Issue by MrKragh** [cotes2020/jekyll-theme-chirpy#1441]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

When you have a page/post with a lot of text and using the image placement as described, this works quite well!
Unfortunately I experience that if you use block quote, prompts, lists and even captions the image, the boxes / text is misplaced.
I guess the fix is the same for the text features being stretched, not sure the fix is the same for the caption though. 
CSS isn't really my specialty, therefore seeking help to get this working as I would expect them to work.

### Steps To Reproduce

Example 1
````
![img](img.png){: .left}
_This caption should be under the image_
````

Example 2
````
![img](img.png){: .left}
> This block quote shouldn't stretch across the image
````

Example 2.1
````
![img](img.png){: .left}
> This block quote shouldn't stretch across the image
{: .prompt-info }
````

Example 3
````
![img](img.png){: .left}
- My Bullets
- Should Not
- Be Hidden
- Behind the
- Image
````

### Expected Behavior

Expected behavior explained in the examples.

### Environment

- Ruby: `ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]`
- Jekyll: `jekyll 4.3.2`
- Chirpy: `jekyll-theme-chirpy (6.3.1)`

**Comment by cotes2020** [comment]
https://chirpy.cotes.page/posts/write-a-new-post/#position

<img width="781" alt="Screen Shot 2024-01-02 at 02 29 42" src="https://github.com/cotes2020/jekyll-theme-chirpy/assets/11371340/7ca280b3-3931-4448-96fd-cf2b0d32bfc8">

**Comment by MrKragh** [comment]
Wauw, sorry about that, I don't know how I managed to miss that other than it was late!
I guess the same comes into play for the other scenarios? It's actually more those I'm interested in having to work if possible.

**Comment by cotes2020** [comment]
> \> This block quote shouldn't stretch across the image ....

When discussing rendering effects, shouldn't you take screenshots to illustrate them? From the example you gave, I'm not sure what effect is desired.

**Comment by MrKragh** [comment]
I'm no graphics person. I've attached an image showing the "wrong" rendering. What I'd expect is the image behaving like a block, therefore bullets beginning next the image, the blockquote starting next tot the image and the prompt the same. Hope that makes sense?

![example](https://github.com/cotes2020/jekyll-theme-chirpy/assets/17195820/7be9b4c1-375d-4bf0-ab5e-7cb3b705c0a9)

**Comment by cotes2020** [comment]
Thx, that screenshot is what's needed, I now know what the bug is.

**Comment by cotes2020** [comment]
@MrKragh It makes sense to use images `left` / `right` with quote-block or prompt-block, but lists don't, because floating an image affects the integrity of the list:

Code:

```markdown
![img](https://chirpy-img.netlify.app/commons/avatar.jpg){: .left w='80' }

- list item 1
- list item 2
- list item 3
- list item 4
- list item 5
- list item 6
```

Output:

<img width="435" alt="Screen Shot 2024-01-02 at 05 45 51" src="https://github.com/cotes2020/jekyll-theme-chirpy/assets/11371340/52fa005e-5eb7-47eb-bf3a-a7c4ffca8f5f">

So I'm not going to fix the issue of overlapping dots with lists when images are floated, and we should instead avoid floating images with lists behind them when writing.

**Comment by MrKragh** [comment]
Thank you @cotes2020  for the nice, fast and well explained update! That's much appreciated! Looking forward to write posts having this ability in the future.

If I didn't already say - thank you as well for an awesome theme!

**Comment by cotes2020** [comment]
I'm going to undo the changes that were made to address this issue, as it introduces a lot of complexity and bugs. See #1477.

Maybe this issue shouldn't be treated as a bug, but as a special need when writing. We can manually add the Bootstrap class `d-flex` to indent the blockquote.

**For block-quote**:

```markdown
![img](img.png){: .left}
> This block quote shouldn't stretch across the image
{: .d-flex }
```

**For prompts**:

```markdown
![img](img.png){: .left}
> This block quote shouldn't stretch across the image
{: .prompt-info .d-flex }
```
