### ISSUE TITLE
How to set a default `og:image`

### ISSUE THREAD

**Issue by mattpopovich** [cotes2020/jekyll-theme-chirpy#1452]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

When sharing a link to a chirpy-created site, the default "image preview" shown is a chirpy related image. I don't know how or where this is being grabbed from.
Ex. : 
![Example default chirpy image for a post that does not define the image](https://private-user-images.githubusercontent.com/16565428/293626826-4e0913e6-3a79-4738-b243-4a5910e16181.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNjk4ODYsIm5iZiI6MTcwNDI2OTU4NiwicGF0aCI6Ii8xNjU2NTQyOC8yOTM2MjY4MjYtNGUwOTEzZTYtM2E3OS00NzM4LWIyNDMtNGE1OTEwZTE2MTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDA4MTMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MzRkMGJmYjA0YTYyNGMwNTViMjFlNTU4NTkxNjRmNmUxOWQ3NDI1MjNhY2JmODBiNGY1NTEzYmFlYzc2NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8oCspgH5mICi5LG63bF5XOLRG3cKjt3pFfVWI977PgY)

For my post [here](https://mattpopovich.com/posts/the-best-places-to-ski-in-colorado-without-a-season-pass/), which [does not define](https://github.com/mattpopovich/mattpopovich.com/blob/main/_posts/2023-02-28-the-best-places-to-ski-in-colorado-without-a-season-pass.md) `image:` in the markdown header and thus does not define `og:image` in the page's html, as confirmed by [socialsharepreview.com](https://socialsharepreview.com/?url=https://mattpopovich.com/posts/the-best-places-to-ski-in-colorado-without-a-season-pass/).

### Describe the solution you'd like

I'd like to be able to define a default `image: /path/to/image.png` that will be used as `og:image` whenever it is not explicitly described in the markdown header.

### Describe alternatives you've considered

[This issue](https://github.com/cotes2020/jekyll-theme-chirpy/issues/858) states that we can define an `image:` in `index.html` for a preview image to be shown when sharing the link to the root of the site. I've confirmed this works. But it **only** works for the root of the site. And not any other posts or page on the site. 

Similar issue [here](https://github.com/cotes2020/jekyll-theme-chirpy/issues/901) that didn't seem to help me...

### Additional context

There's also a chance that I have something stale as I used chirpy-starter about a year ago and might have missed updating something...

**Comment by cotes2020** [comment]
The `og:image` is read from the [preview image](https://chirpy.cotes.page/posts/write-a-new-post/#preview-image) of each page. So you can set up the [default front matter](https://jekyllrb.com/docs/configuration/front-matter-defaults/) to add a default preview image for each page.

**Comment by mattpopovich** [comment]
Thanks cotes, that's close to what I was looking for. But I'm not really trying to set a default image for each post, as the image I have in mind isn't for the post specifically, it's really for the whole site in general. I'm really just trying to get a default image to be used for the `og:image` tag throughout the site. Like if we could take the `avatar:` from `_config.yml` to be the default `og:image` tag, that would be perfect.
Think this is possible? Or point me in the right direction of how I could implement it?

**Comment by cotes2020** [comment]
> ... hide it from displaying prominently at the top of every post.

The current functionality does not support this, it requires customization of `og:image` to work.

**Comment by mattpopovich** [comment]
Ok, I think I have largely achieved what I wanted. I could not figure out where the chirpy image of the link preview was being grabbed from. Turns out, there are a [few default favicons](https://github.com/cotes2020/jekyll-theme-chirpy/tree/master/assets/img/favicons) in jekyll-theme-chirpy. I had generated my favicons so long ago that the conventions for names of the favicon files have changed. I was missing the [mstile-150x150.png](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/assets/img/favicons/mstile-150x150.png) file. Since I didn't have it, the chirpy default was being used. 

I have now generated new favicons in [this commit](https://github.com/mattpopovich/mattpopovich.com/commit/0c233e60b4d7f04e6038315e9f61421dd107a962) and we now have a small, default preview image used on iOS. 

Before (top), and after (below).

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/16565428/ccee9db2-9b97-490f-acdf-f91aef7fb38c)

Yay!
