### ISSUE TITLE
v6.4.0 seems to have broken post.image social preview image (at least in Slack)

### ISSUE THREAD

**Issue by joshjohanning** [cotes2020/jekyll-theme-chirpy#1467]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Built from `jekyll-theme-chirpy`

### Describe the bug

After updating to `v6.4.0`, when sharing links in social (ie: Slack), the preview image doesn't show:

I do not have `social_preview_image` configured in the `_config.yml`.

On `v6.3.1`:
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/19912012/cc580cd0-3fe5-4769-b03a-0f3932fdc76c)

On `v6.4.0`:
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/19912012/074ad5fc-77a6-469a-ab54-b7b262a68acc)

### Steps To Reproduce

1. Share link in social (ie: Slack) - no `page.image` preview image in the share

### Expected Behavior

1. Should have a preview image when posting in Slack

### Environment

- Ruby: ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [arm64-darwin23]
- Jekyll: jekyll 4.3.2
- Chirpy: jekyll-theme-chirpy (6.4.0)

**Comment by cotes2020** [comment]
@joshjohanning thanks for the quick feedback, I'll look into this.

**Comment by joshjohanning** [comment]
Yay! Thanks for the quick fix 😄 

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/19912012/2e27f255-4e24-490a-bdde-1fe1ae78b12e)

**Comment by cotes2020** [comment]
My bad, that feature (#1463) was temporarily developed on a Linux machine, and as a Mac user I'm not used to Linux GUI tools :)
