### ISSUE TITLE
Equation numbers

### ISSUE THREAD

**Issue by bcaddy** [cotes2020/jekyll-theme-chirpy#147]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

Is there a way to number equations and automatically reference them in the text? In latex equations are automatically numbered and they can be referenced anywhere with `\ref{equation name}`. This doesn't appear to be possible in jekyll

**Comment by cotes2020** [comment]
Sorry, I don't have a clue.

**Comment by bcaddy** [comment]
Ok, thanks
