### ISSUE TITLE
Recent Updates not working on github pages :(

### ISSUE THREAD

**Issue by Kijung-Luke-Kim** [cotes2020/jekyll-theme-chirpy#148]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

![20201009-1](https://user-images.githubusercontent.com/55977034/95558787-c180bb00-0a51-11eb-833a-260bd9fd2633.PNG)

I have just installed your theme and deployed it on gh-pages, but nothing appears on Recent Update in the sidebar even if I added some posts.
Any suggestion on perhaps why this is happening?

**Comment by cotes2020** [comment]
It seems that because the file name of your article contains parentheses, e.g:
```
2020-09-29-Forager-모작(3)-오늘할일.md
```
 
But Jekyll did not fully  make it percent-encoded when generating the URLs (let's extract only the file name part):

```
# Note that the parentheses part haven't been encoded
Forager-%EB%AA%A8%EC%9E%91(1)-%EC%98%A4%EB%8A%98%ED%95%A0%EC%9D%BC
```

Which should be:

```
# Full encoded string
Forager-%EB%AA%A8%EC%9E%91%281%29-%EC%98%A4%EB%8A%98%ED%95%A0%EC%9D%BC
```

So the **Recent Update** list cannot identify the modified posts with the "wrong" url, I'm not sure if it's a bug of Jekyll.

To get the update list back to normal, I suggest that except for the symbol `-`, please do not randomly use other symbolic characters in the post file name.

**Comment by achyutap** [comment]
I have the same problem but My file names don't have any special symbols other than `-`  but still not working

**Comment by Kijung-Luke-Kim** [comment]
> I have the same problem but My file names don't have any special symbols other than `-` but still not working

if my memory is correct, Recent Updates didn't work if you also include numbers inside filenames.
Try changing numbers inside post filenames into something alphabetical like 1->first.

Hope this will solve your problem.

**Comment by achyutap** [comment]
If my post files does not contain dates they will not appear any more :)

**Comment by Kijung-Luke-Kim** [comment]
I meant those numbers aside from dates, 
like try changing 2021-01-03-python-calculator-l1.md into 2021-01-03-python-calculator-lone.md.

**Comment by achyutap** [comment]
It is not working

**Comment by Kijung-Luke-Kim** [comment]
If you have changed the filename, you have to try making some random modifications to the posts and commit again to see if it's showing on Recent Updates.
Based on how I understood this template, Recent Updates will show the posts based on when it was last updated, not when it is posted.
Also, make sure your publishing source is gh-pages branch.

**Comment by achyutap** [comment]
where to push `master` branch or `gh-pages`?

**Comment by Kijung-Luke-Kim** [comment]
master

**Comment by achyutap** [comment]
I pushed into master and set gh-pages as diffault branch but it does not work

**Comment by achyutap** [comment]
It is working in only one page category/tkinter/calculator but not in post page
