### ISSUE TITLE
Truly dark mode

### ISSUE THREAD

**Issue by lotusk08** [cotes2020/jekyll-theme-chirpy#1483]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

<img width="1699" alt="Screen Shot 2024-01-15 at 12 26 41" src="https://github.com/cotes2020/jekyll-theme-chirpy/assets/82992510/3024fb70-f83d-44bf-8218-29339384084f">
The browser don't understand dark mode when render the color of the top and bottom windows.

### Describe the solution you'd like

How can we enable dark mode for full page of web?

**Comment by cotes2020** [comment]
The dark mode of the browser app is controlled by the operating system.
