### ISSUE TITLE
How can i see list of category? error 404

### ISSUE THREAD

**Issue by DEVHEE** [cotes2020/jekyll-theme-chirpy#149]
When I click sidebar's CATEGORIES>Blogging(or Demo or Tutorial), it occurres 404 error page.
(with copy of jekyll-theme-chirpy repo.)

how can i fix it?

**Comment by Seungju182** [comment]
I have this same issue..

**Comment by belintani** [comment]
Does someone solved it? I followed the readme and also getting 404 page
