### ISSUE TITLE
Google analytics not working because tag in wrong location

### ISSUE THREAD

**Issue by yarkhinephyo** [cotes2020/jekyll-theme-chirpy#1496]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

Hi! Thank you for maintaining the project.

I know the issue has been mentioned in #551, but I have found the problem and have a proposal for a fix.

The problem is that even though the tag-related scripts are present in HTML body, google analytics requires the tag to be in the header.

<img width="639" alt="image" src="https://github.com/cotes2020/jekyll-theme-chirpy/assets/19868916/6e27576b-adb1-4cd6-bb9e-9cdbdb3a4f57">

When I moved the tag-related scripts to the header manually, the verification works.

<img width="639" alt="image" src="https://github.com/cotes2020/jekyll-theme-chirpy/assets/19868916/7724aa77-c4a4-4bd7-9175-34a25af39e2a">

## Proposed fix

I would like to move `include google-analytics.html` the `head.html` file. If it is okay, I will create a PR. Thank you.

### Steps To Reproduce

1. Insert 'G-XXXXXX' tag in _config.yml file.
2. Build with JEKYLL_ENV=production
3. The necessary tag is added to HTML body.
4. Host the website with S3
5. Disable Ad Blocker for the website
6. Test the website for the presence of Google Analytics tag with Google Search Console ownership verification
7. The test fails

### Expected Behavior

The test passes

### Environment

- Ruby: 3.2.3
- Jekyll: 4.3.3
- Chirpy: 6.4.2

**Comment by cotes2020** [comment]
Google tells you that you should place the **validation code** in the `<head>`, not the whole `gtag.js`. You should check if the config file has the `google_site_verification` field filled in, if so then the `jekyll-seo-tag` plugin will generate the site validation information in the `<head>`.

A simple question for you and the #551 guys,  if this project really has GA collection issues as you claim, then how come the [demo site](https://cotes2020.github.io/chirpy-demo/) has been running for over four years without failing a single day with the same template code?

**Comment by nonameincense** [comment]
There is no problem with data collection using that tag, but you have to insert the tag separately in the head for ownership authentication. So I also inserted the tag in the head after deleting the js.

**Comment by yarkhinephyo** [comment]
> There is no problem with data collection using that tag, but you have to insert the tag separately in the head for ownership authentication. So I also inserted the tag in the head after deleting the js.

I see. I will just do that then. Thank you
