### ISSUE TITLE
Twitter Cards Missing Images

### ISSUE THREAD

**Issue by timothystewart6** [cotes2020/jekyll-theme-chirpy#1497]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

When cards render on twitter, the images are missing [example tweet](https://twitter.com/TechnoTimLive/status/1747480473595506984)

This has worked in the past [past working example tweet](https://twitter.com/TechnoTimLive/status/1724454030750163092)

### Steps To Reproduce

1. Using chirpy theme ` jekyll-theme-chirpy (6.4.2)`
2. visit twitter.com
3. paste link inside of tweet composer
4. see the tweet without an image

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/1322205/a625e527-684b-4c36-ae62-9a9e9a5d7e3f)

### Expected Behavior

Twitter cards should render images as they did previously.

### Environment

- Ruby:  `ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin23]`
- Jekyll: `jekyll 4.3.3`
- Chirpy: `6.4.2`

```bash
  * jekyll-theme-chirpy (6.4.2)
	Summary: A minimal, responsive, and feature-rich Jekyll theme for technical writing.
	Homepage: https://github.com/cotes2020/jekyll-theme-chirpy
	Documentation: https://github.com/cotes2020/jekyll-theme-chirpy/#readme
	Source Code: https://github.com/cotes2020/jekyll-theme-chirpy
	Wiki: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
	Bug Tracker: https://github.com/cotes2020/jekyll-theme-chirpy/issues
	Path: /Users/user/.rvm/gems/ruby-3.2.2/gems/jekyll-theme-chirpy-6.4.2
```

### Anything else?

@bigsk1 suggested this fix in the tweet above, however I didn't want to replace the theme's version of `head.html` at this time

https://github.com/bigsk1/bigsk1.github.io/blob/main/_includes/head.html

**Comment by timothystewart6** [comment]
Also, after testing @bigsk1's changes in his repo, I can confirm the card now work.  Tested by DM'ing myself to (hopefull) prevent caching

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/1322205/3aa2310b-26a7-4d3c-b270-51f34bd119d1)

**Comment by bigsk1** [comment]
The issue seems to be needing absolute url for twitter cards

```bash
<meta name="twitter:image" content="https://bigsk1.com/assets/images/bigsk1.webp">
```

not 

```bash
<meta name="twitter:image" content="/assets/images/bigsk1.webp">
```

My example in head.html  

Twitter Image Meta Tag: In both the {% if page.image %} and {% elsif site.social_preview_image %} sections, I added <meta name="twitter:image" content="{{ img_url }}" />. This ensures Twitter has the correct image URL for both specific pages and the site-wide fallback.

Absolute URL for Page Image: For page.image, I've ensured the absolute URL is used by applying {{ src | absolute_url }}.

```bash
{%- capture seo_tags -%}
  {% seo title=false %}
{%- endcapture -%}

<!-- Setup Open Graph image -->

{% if page.image %}
  {% assign src = page.image.path | default: page.image %}

  {% unless src contains '://' %}
    {%- capture img_url -%}
      {{ src | absolute_url }}
    {%- endcapture -%}

    {%- capture og_image -%}
      <meta property="og:image" content="{{ img_url }}" />
      <meta name="twitter:image" content="{{ img_url }}" />
    {%- endcapture -%}

    {% assign old_meta_clip = '<meta name="twitter:card"' %}
    {% assign new_meta_clip = og_image | append: old_meta_clip %}
    {% assign seo_tags = seo_tags | replace: old_meta_clip, new_meta_clip %}
  {% endunless %}

{% elsif site.social_preview_image %}
  {%- capture img_url -%}
    {{ site.social_preview_image | absolute_url }}
  {%- endcapture -%}

  {%- capture og_image -%}
    <meta property="og:image" content="{{ img_url }}" />
    <meta name="twitter:image" content="{{ img_url }}" />
  {%- endcapture -%}

  {% assign old_meta_clip = '<meta name="twitter:card"' %}
  {% assign new_meta_clip = og_image | append: old_meta_clip %}
  {% assign seo_tags = seo_tags | replace: old_meta_clip, new_meta_clip %}
{% endif %}    

{{ seo_tags }}

```

**Comment by timothystewart6** [comment]
Thank you @bigsk1. I can confirm after using the local template with these changes, it works https://github.com/techno-tim/techno-tim.github.io/commit/4608f15b7dbe7d05fd841e2f2ed0391fe6366c10

**Comment by timothystewart6** [comment]
hmmm, this seems to have broken it on other platforms (discord) 
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/1322205/7991b8ec-d0e0-448e-9c92-a243a07b14f7)

**Comment by bigsk1** [comment]
testing open graph shows ok 

https://www.opengraph.xyz/

**Comment by timothystewart6** [comment]
interesting.  It does look correct on OG however it does not in Discord
https://discord.com/channels/677701098101932032/803484989827055626/1198026636126330880

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/1322205/4ee32c4a-eb0b-49d6-9f82-37f711448a93)

**Comment by timothystewart6** [comment]
I am not too familiar with liquid but it seem like there's a page image getting assigned and a site image.

**Comment by timothystewart6** [comment]
I see, now I have 2 `og:image` tags.  Trying to fix

**Comment by timothystewart6** [comment]
All fixed!  Seems like it is now fixed for both twitter and og cards.  I have an image preview in twitter and the images on other socials only render once:  https://github.com/techno-tim/techno-tim.github.io/blob/master/_includes/head.html

I am happy to open a PR, but @bigsk1 did most of the work and I am not sure if my hacks to his liquid code is right 🤣

**Comment by bigsk1** [comment]
oh nice I was off trying to solve also and saw this great, let me check it out

**Comment by timothystewart6** [comment]
Proof that it worked on twitter:
https://twitter.com/TechnoTimLive/status/1748480321060733110

Proof that it worked with OG
https://mastodon.social/@technotim/111785120941155450

I actually posted this on all socials (FB, LinkedIn, etc) and it rendered fine everywhere

**Comment by bigsk1** [comment]
@timothystewart6 looks good bring it on home

**Comment by bigsk1** [comment]
@timothystewart6 I just submitted one

**Comment by cotes2020** [comment]
@timothystewart6 Thanks for submitting this, but it's essential to note that describing a topic in a dozen posts will make it difficult for maintainers to understand what you intend to do. 

Since there has already been a PR submitted, I will update the progress of the issue there (#1498).

**Comment by timothystewart6** [comment]
Thanks!  The initial post describes the issue.  The other comments are supporting facts.

**Comment by timothystewart6** [comment]
@cotes2020 the initial issues describes the issue.  The other posts are supporting facts.

**Comment by bigsk1** [comment]
@timothystewart6 I updated the head.html based on some feedback, can you verify all working ok for you, I dont use discord but all is checking out ok for me  https://github.com/bigsk1/bigsk1.github.io/blob/main/_includes/head.html
