### ISSUE TITLE
Setting up Google Analytics

### ISSUE THREAD

**Issue by ensj** [cotes2020/jekyll-theme-chirpy#150]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [x] I found the bug on the latest code of `master` branch.

### To Reproduce

1. Go to '_config.yml'
2. Add Google Analytics Tracking ID
3. Deploy

### Expected behavior

Google Analytics should start collecting pageview data.

### Screenshots

![Image](https://i.imgur.com/2MTrLpT.png)

**Comment by ensj** [comment]
My current fix is to include the ga html file in the head, and to use the async google analytics code snippet. This doesn't fix the HTML request error however. I tried using the gtag script instead as well, which doesn't show any errors, but google analytics still doesn't receive data.

**Comment by cotes2020** [comment]
The Google Analytics code snippet has been running on the [demo website](https://chirpy.cotes.info/) for more than one year, and no problems regarding PV collection failure have been found yet.

You can check out the PV report on the demo site, which is updated hourly.

**Comment by FFute** [comment]
To enable this feature , you must generate your site as `product` enviroment.
add `JEKYLL_ENV=product` when building your site.

**Comment by repozitor** [comment]
I used this syntax in my _config.yml for loading tag manager and analytics
none of them loaded. Do you know what's wrong?

google_analytics:
  id: G-WSSNVSS97Y # fill in your Google Analytics ID

google:
  tag_manager:
    container_id: GTM-5HZ2KFL
    
  The building is fine. You can check my website to see if the script is loaded or not. I see that it is not loaded.

https://repozitor.com
