### ISSUE TITLE
Images continue shimmering even after loading

### ISSUE THREAD

**Issue by sudo-nano** [cotes2020/jekyll-theme-chirpy#1507]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Built from `jekyll-theme-chirpy`

### Describe the bug

Images in posts continue to have the shimmer animation even when the image is done loading. 

### Steps To Reproduce

1. Build a site with `jekyll-theme-chirpy` that has a post with an image 
2. Go to the post with an image
3. Image continues to shimmer forever 

This behavior was reproduced in Firefox 121.0.1 in both normal and private browsing (incognito) with addons and caching disabled, as well as Google Chrome 121.0.6167.85 in both normal and incognito mode with no addons. Reproduced both locally and when deployed to GitHub sites. 

~~This bug is currently present on this page of my site: https://sudo-nano.github.io/posts/Villager-House-Detonator/~~
I have disabled the shimmer effect on my site using the [temporary solution in issue 1100](https://github.com/cotes2020/jekyll-theme-chirpy/issues/1100), but this issue still needs a permanent solution. 

### Expected Behavior

Image stops shimmering after loading. 

### Environment

- Ruby: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
- Jekyll: jekyll 4.3.3
- Chirpy: jekyll-theme-chirpy (6.4.2)

**Comment by cotes2020** [comment]
Please, just read the docs.
