### ISSUE TITLE
Embed youtube videos

### ISSUE THREAD

**Issue by libesz** [cotes2020/jekyll-theme-chirpy#151]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There are no similar request on existing issues (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

I would like to insert embedded youtube videos to the posts without any plugins that prevents GHP usage. Is there a way to do it with chirpy?

## Describe the solution you'd like

Anything which does not need an extra plugin.

## Describe alternatives you've considered

I found descriptions like this: https://thisisa.blog/how-to-embed-media-github-pages
I can use this method unless there is a way to do it with the theme directly.

**Comment by cotes2020** [comment]
For now, this theme does not provide a special way to implement embedded video. Basically, you can simply use `<iframe>` in the post to dispaly video. If you want to save the time of writing the HTML code, you can use `{% include %}` to reuse `<iframe>` code snippets according to the [tutorial](https://thisisa.blog/how-to-embed-media-github-pages) you mentioned.

**Comment by libesz** [comment]
Thanks! Will use that then.
