### ISSUE TITLE
Removing favicons manifest and browserconfig as instructed breaks deploy step

### ISSUE THREAD

**Issue by GriceTurrble** [cotes2020/jekyll-theme-chirpy#152]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [x] I found the bug on the latest code of `master` branch.

## Describe the bug

The example post `2019-08-11-customize-the-favicon.md` describes how to generate favicons for the site. The last step says to delete files `browserconfig.xml` and `manifest.json` from the generated files.

However, these two files are referenced in `_includes/favicons.html`, so they appear to be requirements. Further, when `tools/test.sh` runs on the project, `htmlproofer` will throw errors for these missing files.

When using CI workflows to deploy the site to GitHub Pages, because that test step fails, the site cannot be deployed. Users would either have to replace those two files or edit the `_includes/favicons.html` file to remove those lines in order to pass the htmlproofer check.

### To Reproduce

1. Follow instructions in example post indicated to generate favicons, including removing the `manifest.json` and `browserconfig.xml` files.
2. Run `tools/test.sh` to test the site.
3. Get error from test script.

### Software

Local software irrelevant: using GitHub Actions CI workflows that execute `tools/test.sh` generates the same issue when the files have been removed.

### Additional context

I think the instruction to remove the files should be changed, either removed or the copy updated to indicate their importance.

**Comment by cotes2020** [comment]
This following table may help you understand the meaning of the instruction：

>  ✓ means keep, ✗ means delete

|Source|`*.PNG` | `*.JPG` | `browserconfig.xml`|`manifest.json` |
| --- | --- | --- | --- | --- |
| Generated by [`favicon-generator`](https://www.favicon-generator.org/) |✓ |✓ |✗|✗|
| From  [`Chirpy`](https://github.com/cotes2020/jekyll-theme-chirpy/) |✗|✗|✓ |✓ |
