### ISSUE TITLE
Dynamicaly switch logo based on mode-toggle

### ISSUE THREAD

**Issue by tomasApo** [cotes2020/jekyll-theme-chirpy#1527]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

No the template has no issue, it arises due to my odd logo design. 

### Describe the solution you'd like

 I have a logo with a transparent bg. When I switch mode it becomes barely readable. 
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/75183079/c16c009f-aac4-42ca-96bc-6ac205297892)
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/75183079/32683744-c4a5-459e-8851-e9a5439446b2)

I gave this a shot by messing with `sidebar.html` and `mode-toggle.html` to switch logo images based on the status of my website `modeStatus` but I got no success. 

I'd like to be able to switch logo images when the user clicks the sidebar mode button 

### Describe alternatives you've considered

happy to not have this feature but simply give me some guidance on how I can perform the changes myself. 
Thank you

**Comment by tomasApo** [comment]
https://github.com/tomasApo/tomasApo.github.io

**Comment by chuckhoupt** [comment]
Before modifying the theme, I'd suggest trying to create a logo that works on both light and dark backgrounds. Some techniques are briefly discussed here:

https://dev.to/ulitroyo/about-your-transparent-logo-1ik0

The current logo can only be used on a dark background, which will cause problems elsewhere. For example, when the site is bookmarked in Safari, the apple-touch-icon is barely visible:

<img width="192" alt="image" src="https://github.com/cotes2020/jekyll-theme-chirpy/assets/1627217/67b51473-1263-42ec-97d3-7f382aa76590">
