### ISSUE TITLE
I can serve at remote page, but can't serve at local

### ISSUE THREAD

**Issue by su-mmer** [cotes2020/jekyll-theme-chirpy#153]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

Thank you for reading this, And please understand that I am not good at English.
I finished the tutorial and I have written my blog well, but there is an error locally in 2 articles.
Code runs well in github.io, but it only generates 404 pages local server in my computer.
Can I know why? I can't find it when I search.
Both 127.0.0.1:4000 and localhost:4000 have the same results.
I use Window10, chrome.

![성공](https://user-images.githubusercontent.com/50980974/96203381-b6bbae00-0f9c-11eb-80ac-7ccd7c449ff5.PNG)
This is github.io. It succeed.

![실패](https://user-images.githubusercontent.com/50980974/96203404-c20ed980-0f9c-11eb-85a5-8116bdda89c7.PNG)
This is local. It is failed.

**Comment by cotes2020** [comment]
If you want to run this project on Windows 10, complete the tutorial on WSL or Docker.

**Comment by su-mmer** [comment]
wow.. Thank you. I just downloaded Ruby.
