### ISSUE TITLE
PageView counter at top of the posts using Goatcounter

### ISSUE THREAD

**Issue by sukhjinder-kumar** [cotes2020/jekyll-theme-chirpy#1532]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

Add page view count on top of the blog post.

### Describe the solution you'd like

Recently support for goatcounter has been provided. As per this [documentation](https://www.goatcounter.com/help/visitor-counter#:~:text=You%20can%20display%20a%20page's,prevent%20unintentional%20leaking%20of%20data.&text=You%20can%20also%20remove%20the%20async%20attribute.) it is very much possible to print page view on our posts.

We can call the API and get the page count as follows -
```js
// Fetch JSON data from the provided URL
fetch('https://[MYCode].goatcounter.com/counter/[relative URL].json')
  .then(response => response.json())
  .then(data => {
    console.log(data.count);
  })
  .catch(error => console.error('Error fetching JSON:', error));
```
I am not very good at web development, and hence I am not able to integrate it with the templates. Even adding to the index.html page gives errors (`Error fetching Json`). 
```html
<div id="jsonAttribute"></div>

<script>
  // Fetch JSON data from the provided URL
  fetch('https://[MYCode].goatcounter.com/counter/[relative URL].json')
    .then(response => {response.json(); console.log(response.json());})
    .then(data => {
      // Display the desired attribute
      document.getElementById('jsonAttribute').innerText = data.count;
    })
    .catch(error => console.error('Error fetching JSON:', error));
</script>
```

If it helps, Chatgpt 3.5 states the following as a possible error "If you're able to fetch the JSON data successfully using the same JavaScript code in a .js file when running it with Node.js but encountering an error when trying to fetch it within an HTML file, the issue might be related to CORS (Cross-Origin Resource Sharing) restrictions."

From my understanding of the chirpy template, one has to add a working HTML code (shown above) in `post.html`. And add some CSS to make it look clean. Maybe display it to the right, alongside posted and updated (at the start of the post), as in below.
![Screenshot from 2024-02-09 04-49-09](https://github.com/cotes2020/jekyll-theme-chirpy/assets/82507694/698c10de-9f0c-4098-860b-b3efbd29ccc2)

**Comment by kungfux** [comment]
@sukhjinder-kumar  I have implemented views counter recently using GoatCounter, here what I have done.

- I have copied original `_layouts/post.html` to my project, so I can override it to add views counter where I want it to be
```html
      <span>
        {% include views.html tooltip=true lang=lang %}
        {{ site.data.locales[lang].post.pageview_measure }}
      </span>
```
- Created a new file `_includes/views.html` to have views counter logic
```html
<!-- Views Counter -->

<script>
  const r = new XMLHttpRequest();
  r.addEventListener('load', function() {
      document.querySelector('#views').innerText = JSON.parse(this.responseText).count
  });
  const uri = location.pathname.replace(/\/$/, "");
  r.open('GET', 'https://{{ site.goatcounter.id }}.goatcounter.com/counter/' + encodeURIComponent(uri) + '.json');
  r.send();
</script>

<span>
  <em id="views">
    ∞
  </em>
</span>
```

The JS code is taken from GoatCounter site https://www.goatcounter.com/help/visitor-counter#json-851
That's about it. I hope this helps you get what you want while waiting for the changes in the theme.

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/10548881/f67e4ca4-5da2-41ed-a404-350823cec71a)

**Comment by sukhjinder-kumar** [comment]
Thank you for taking your time and helping me out. This solves my issue. Just to be sure, is there something we can do so that Adblocker doesn't block the request? I saw it on your github.io too, ublock is blocking the request (works in incognito).

**Comment by sukhjinder-kumar** [comment]
New to open source, but you should release the above code as PR. I think many people will find it useful. Thanks once again.

**Comment by kungfux** [comment]
I was happy to help @sukhjinder-kumar 

> is there something we can do so that Adblocker doesn't block the request?

I don't think so. If user decided to protect his privacy and so Adblock extension prevents to send requests to analytics, there is no way to bypass easily, I guess.

Please check additional info available in GoatCounter's [FAQ](https://kungfux.goatcounter.com/help/faq#blocked) regarding this problem as there are options described.
