### ISSUE TITLE
Restrict Giscus Origins

### ISSUE THREAD

**Issue by timothystewart6** [cotes2020/jekyll-theme-chirpy#1534]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

Currently, anyone with your `gisscuss.repo_id` can post to your discussion board.  This can lead to others spamming your discussion board (un)intentionally.

### Describe the solution you'd like

Please expose the [origins](https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md#origins) attribute in `_config.yml`  so we restrict which origins can load giscus.

### Describe alternatives you've considered

None, no known alternatives exist.

**Comment by cotes2020** [comment]
The situation is a bit awkward, this feature requires a file `giscus.json` to be created in the repo root directory.

Currently I have no way to decide whether to generate this file based on the site config. If a user doesn't use giscus, then his/her repository will have a useless `giscus.json`.

Perhaps you can create this file in your own repo and configure it as needed.

**Comment by timothystewart6** [comment]
I see.  Couldn't you just generate the file if the key `giscus.repo` is defined?  Otherwise I agree, I can just create a `giscuss.json`

**Comment by timothystewart6** [comment]
Ah, nevermind.  This would always be undefined when the site is generated.

**Comment by timothystewart6** [comment]
I will close it then, I totally understand why this would be confusing for some and there is a workaround if using giscus.
