### ISSUE TITLE
CI Workflow doesn't trigger on newer repositories with 'main' branch.

### ISSUE THREAD

**Issue by Sharkaboi** [cotes2020/jekyll-theme-chirpy#154]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [x] I found the bug on the latest code of `master` branch.

## Describe the bug
Same as title, newer repositories now have `main` branch instead of `master` default naming convention, so the CI branch doesn't trigger.
[Source](https://github.com/github/renaming#new-repositories-use-main-as-default-branch-name)

### To Reproduce

1. Download the theme from jekyll.
2. Perform all the required setup.
3. Push to new repository (NOT FORK)
4.  CI never runs.

### Expected behavior
CI should have run on either `main` or `master` branch and force pushed to `gh-pages`.
[Source](https://github.com/github/renaming#new-repositories-use-main-as-default-branch-name)

### Fix
Add both branches to on push branches in the `.github/workflows/pages-deploy.yml` file. Also mention in the documentation if possible.

Thanks for the awesome theme :)

**Comment by cotes2020** [comment]
This will not happen if the project is obtained through **Fork**. If you copy the project to a new repo, you can modify the trigger branch in the GH-Actions workflow by yourself.

I think adding `main` to the trigger branch of this project is not a perfect solution. What if the default branch of the GitHub repos is set to the `default` branch a few years from now for political reasons? Do we have to add `default` to CI again?  If so, there are two redundant branches left in the workflow file:

```yaml
on:
  push:
    branches: [master, main, default, .....] #  assuming that `master`, `main` are the 'old' default branches 
```

**Comment by Sharkaboi** [comment]
Yes, the issue won't be there on forking but still persists when someone downloads from [JekyllThemes Listing](http://jekyllthemes.org/themes/jekyll-theme-chirpy/) directly as there is no git history with it.

I agree on the part with having redundant branches, but I believe a beginner/someone who has no clue about Github Actions would have issues with it still. Just a note on the documentation would be fine I guess for this.

Thanks for the response.
