### ISSUE TITLE
Wrong image paths in v6.5.0

### ISSUE THREAD

**Issue by pluto0x0** [cotes2020/jekyll-theme-chirpy#1541]
### Checklist

- [x] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

I set `img_path` in posts but the image url in the html pages rendered was wrong (http 404).

This used to work well but not with v6.5.0. I temporarily masked this error by specifying a earlier version in `Gemfile`:

```
gem "jekyll-theme-chirpy", "~> 6.2", "< 6.5.0"
```

And the error can be reproduced by switching back to

```
gem "jekyll-theme-chirpy", "~> 6.2", ">= 6.3.0"
```

### Steps To Reproduce

I set image path in the post as

```
---
...
img_path: /_posts/
---
```
and insert image in markdown as

```
![alt](../upload/img/example.png){: w="400" }
```

and the directory structure is

```
├─assets
│  ├─css
│  ├─img
│  │  └─favicons
│  └─lib
├─upload
│  └─img
├─_data
├─_plugins
├─_posts
└─_tabs
```

But the image URLs in the rendered HTML are like

```
https://example.com/upload/img/example.png../upload/img/example.png
```

---

Also, setting `img_path` area to `/_posts` results in the same problem.

### Expected Behavior

The image URL in the html should be

```
https://example.com/upload/img/example.png
```

### Environment

- Ruby: 3.1.4
- Jekyll: 4.3.3
- Chirpy: 6.5.0
(Jekyll runs on Github Actions)

**Comment by joshjohanning** [comment]
I'm seeing something very similar, @cotes2020, after upgrading to `v6.5.0`. 

Here's some of my front matter:

```yml
img_path: /assets/screenshots/2022-03-08-my-post
image:
  path: ../my-other-post/security-overview-dark.png
  width: 100%
  height: 100%
  alt: my image
pin: false
---
```

The test command in the build and publish workflow fails with:

```
* At _site/posts/my-post/index.html:1:

  internal image /assets/screenshots/2023-02-28-my-other-post/security-overview-dark.png../2023-02-28-my-other-post/security-overview-dark.png does not exist
```

In this case, I'm referencing an image in a different folder relative to the `img_path` default. 

The same thing happens when referencing relative image paths in the post as well (in addition to the front matter) with `img_path` set.

```
![image-light](./../2023-09-07-my-third-post/git-lfs-light.png){: .shadow }{: .light }
![image-light](./../2023-09-07-my-third-post/git-lfs-dark.png){: .shadow }{: .dark }
_image caption_
```

Test output: 
```
* At _site/posts/my-third-post/index.html:9:

  internally linking to /assets/screenshots/2023-09-07-my-third-post/git-lfs-light.png./../2023-09-07-my-third-post/git-lfs-light.png, which does not exist

* At _site/posts/migrate-to-git-lfs/index.html:9:

  internally linking to /assets/screenshots/2023-09-07-my-third-post/git-lfs-dark.png./../2023-09-07-my-third-post/git-lfs-dark.png, which does not exist
```

**Comment by cotes2020** [comment]
Hi @joshjohanning, #1553 should be able to fix this issue.

**Comment by joshjohanning** [comment]
@cotes2020 looks good to me 🚀  🎉   Thanks!
