### ISSUE TITLE
Cannot switch dark/light mode of the website

### ISSUE THREAD

**Issue by ptmkhanh29** [cotes2020/jekyll-theme-chirpy#1544]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Built from `jekyll-theme-chirpy`

### Describe the bug

I can not switch dark/light mode of the website

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/113729333/092ac8ca-e80f-4f84-8e53-c1e585cb837e)

And the code reported an error that the folder could not be found as follows

<img width="419" alt="image" src="https://github.com/cotes2020/jekyll-theme-chirpy/assets/113729333/823f7108-7997-4fb1-9634-be11eae04d98">

When I checked the project again, I saw that this dist folder was not there

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/113729333/2f9dc799-8608-4346-9fdc-cb19c1ff04bd)

### Steps To Reproduce

1. 

### Expected Behavior

1

### Environment

- Ruby: 
- Jekyll: 
- Chirpy:

**Comment by ptmkhanh29** [comment]
Currently, I have fixed the error, I would like to close the issue

**Comment by hillsonghimire** [comment]
How did you fix it? I am facing the same error!

**Comment by kungfux** [comment]
What are the build steps because I cannot reproduce it?

**Comment by syehoonkim** [comment]
Dear all,
You should install node.js and run ```bash tools/init```.
If you are using POSIX system like Ubuntu, there is no problem. Just do it.
But you are in Windows environment, then you should do it on WSL like Ubuntu.
(Maybe MSYS2 work but not tried.)
The command will build ```assets/dist/*.min.js``` files and everything will work well.

**Comment by NichtsHsu** [comment]
If you review the `tools/init` script, you can find how it builds these `*.min.js` files:

https://github.com/cotes2020/jekyll-theme-chirpy/blob/950839175ab232103f6127fd6a99ac724ecc9e89/tools/init#L102-L103

**Comment by syehoonkim** [comment]
You are right, but when I tried, npm run build didn't go well. I don't know why...I didn't dig it. It gave me headach.
