### ISSUE TITLE
Github Pages deploy error, HTML-Proofer, custom domain?  

### ISSUE THREAD

**Issue by tomasApo** [cotes2020/jekyll-theme-chirpy#1556]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

Locally the website is working perfectly but I no longer can get it to deploy with github. Haven't deployed in 3 weeks. within this time I only remember putting a Custom domain with github pages settings. 
https://tomasapo.github.io/ -> apolonia.co.uk  

### Steps To Reproduce

Please see https://github.com/tomasApo/tomasApo.github.io/actions when builds started failing, and my troubleshooting attempts/ 

### Expected Behavior

Simply deploys like it used to. 

### Environment

- Ruby: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
- Jekyll: jekyll 4.3.3
- Chirpy:  jekyll-theme-chirpy (6.5.0)

### Anything else?

`
Run bundle exec htmlproofer _site \
Running 3 checks (Scripts, Links, Images) in ["_site"] on *.html files...

Checking 107 internal links
Checking internal link hashes in 4 files
Ran on 20 files!

For the Scripts check, the following failures were found:

* At _site/404.html:1:

  internal script reference /app.js does not exist

* At _site/about/index.html:1:

  internal script reference /app.js does not exist

* At _site/archives/index.html:1:

  internal script reference /app.js does not exist

* At _site/index.html:1:

  internal script reference /app.js does not exist

* At _site/posts/MxMaster/index.html:1:

  internal script reference /app.js does not exist

* At _site/posts/SmartBasil/index.html:4:

  internal script reference /app.js does not exist

* At _site/posts/releaseV1/index.html:9:

  internal script reference /app.js does not exist

* At _site/posts/releaseV2/index.html:89:

  internal script reference /app.js does not exist

* At _site/shop/index.html:1:

  internal script reference /app.js does not exist

* At _site/tags/arduino-uno/index.html:1:

  internal script reference /app.js does not exist

* At _site/tags/embedded-rust/index.html:1:

  internal script reference /app.js does not exist

* At _site/tags/esp32/index.html:1:

  internal script reference /app.js does not exist

* At _site/tags/feathers2/index.html:1:

  internal script reference /app.js does not exist

* At _site/tags/index.html:1:

  internal script reference /app.js does not exist

* At _site/tags/righ-to-repair/index.html:1:

  internal script reference /app.js does not exist

* At _site/tags/stm32f3/index.html:1:

  internal script reference /app.js does not exist

* At _site/tags/usb-c/index.html:1:

  internal script reference /app.js does not exist

HTML-Proofer found 17 failures!`

**Comment by rudzainy** [comment]
I am going through similar issue. I tried a bunch of things, however I keep coming back to this error:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/configure-pages@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

I also tried bumping up GitHub Actions versions with negative results ☹️

**Comment by tomasApo** [comment]
Hey @rudzainy. I managed to solve the "warning" about Node.js by following @joshjohanning commit.  My issue remained hence I reverted the change, either way the warning from github actions was gone. 

https://github.com/cotes2020/jekyll-theme-chirpy/pull/1554/commits/143eec2a31b53c7cb15918d300a7210d6541994b

**Comment by rudzainy** [comment]
For the time being, I just commented out the tests in `pages-deploy.yml` so that at least something is showing on my site 😞

**Comment by Brainor** [comment]
You can temperarily bypass the problem by modifying `Gemfile`
```diff
- gem "jekyll-theme-chirpy", "~> 6.5", ">= 6.5.1"
+ gem "jekyll-theme-chirpy", "~> 6.4.2"
```

**Comment by tomasApo** [comment]
@Brainor you wizard, it works now, thank you. 

Do you mind explaining or pointing me in the right direction on why this version change solves the github page issue?

**Comment by Brainor** [comment]
I just know the version `6.4.2` works and version `6.5.1` doesn't work, so I manually set the `jekyll-theme-chirpy` version to be `6.4.2` to solve this problem.
I don't know where the true problem/bug lies, so this is the best I can do😄
