### ISSUE TITLE
Override system preference when in dual theme mode

### ISSUE THREAD

**Issue by Marnick39** [cotes2020/jekyll-theme-chirpy#156]
I am currently adjusting this (beautiful) theme to fit my needs, and have currently hard-coded a preference for the dark mode while in dual-mode (to allow  a reader to still switch to light mode if they choose).

## Checklist
- [X] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There are no similar request on existing issues (including closed ones).
- [X] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [X] I was in the `master` branch of the latest code.

## Describe the solution you'd like
If you approve, I would like to add a setting in _config.yml to override the system preference with your own (when in dual mode)
If you like I could make the PR with the proposed solution. If so, I could use suggestions concerning the variable name and how to best document it.

## Describe alternatives you've considered
My current solution hard-codes my preference in _layouts/default.html, but this could easily be replaced by a var which could be set in _config.yml.
```
{% capture prefer_mode %}
  {% if site.theme_mode == "dual" %}
    mode="dark"
  {% endif %}
{% endcapture %}
```

**Comment by cotes2020** [comment]
In the switchable mode (`theme_mode: dual`), the default theme following the device color preference is the most in line with usage habits, so I won't change it according to your suggestions. This personalized change is more suitable to stay in your Fork version :)
