### ISSUE TITLE
When using a CDN ( img_cdn ), clickable images doesn't adhere to the CDN settings

### ISSUE THREAD

**Issue by MagnusJohansson** [cotes2020/jekyll-theme-chirpy#1568]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Built from `jekyll-theme-chirpy`

### Describe the bug

I have setup a CDN for my images, and all is good except when I try to have a clickable image. 
Then it will not use the CDN URL prefix, but rather fallback to the host URL

### Steps To Reproduce

1. Update the _config.yml to have a working CDN setup.
`img_cdn: "https://your-cdn.com"`

2. In a post create a "standard" image tag. This works as expected, the CDN  prefix URL is used:
`![The flower](/images/the-flower.jpg)`

3. In a post create a clickable image, that navigates to a full resolution image ("the-flower-high-res.jpg"):
`[![The flower](/images/the-flower.jpg)](/images/the-flower-high-res.jpg)`

4. Build and publish
5. Observe that the post in step 2 is working as expected. (I.e. https://your-cdn.com/images/the-flower.jpg) whereas the example in step 3 will not use the CDN , but rather fallback to the host/root URL (I.e. https://hosting-site.com/images/the-flower.jpg and https://hosting-site.com/images/the-flower-high.res.jpg respectively)

### Expected Behavior

Even when using clickable markdown images, we should be able to use a CDN.

### Environment

- Ruby: 3-1-3p185
- Jekyll: 4.3.3
- Chirpy: 6.5.1

**EDIT: Correction in step 5, the "showing" image is grabbed from the CDN URL, but the clickable anchor tag is pointing to the host URL.**

**Comment by cotes2020** [comment]
Hold on, the docs never says that `img_cdn` will be used for external link URLs.

The reason for this is simply because we can't predict what type of resource the external link will be, and if it's some internal page, then it's wrong to automatically add the image CDN to it. 

For instance:

## Input

```md
[![cover](/path/to/cover.png)](/path/to/some-docs.html)
```

## Output

```html
<!-- Wrong, HTML pages don't need image CDN -->
<a href="{CDN}/path/to/some-docs.html">
  <img src="{CDN}/path/to/cover.png" ... />
</a>
```

**Comment by MagnusJohansson** [comment]
Yes, that makes perfect sense, of course. 
I was just so focused on getting my images up on a CDN network, and didn't think about the generic nature of clicking the image...

Thanks.

**Comment by cotes2020** [comment]
Perhaps you could consider adding a CDN to the external links to achieve the desired effect.

```md
[![The flower](/images/the-flower.jpg)]({CDN}/images/the-flower-high-res.jpg)
```
