### ISSUE TITLE
Pageviews regression in 6.5.2 gem

### ISSUE THREAD

**Issue by steveng57** [cotes2020/jekyll-theme-chirpy#1581]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

It seems that the post.html layout in the 6.5.2 gem does not have the pageviews code in it.  It looks fine in 6.5.1.

If you download the 6.5.1 gem, you can see it in post.html around line 77.  It is not there in the downloaded 6.5.2 gem.

It looks fine on github.

This means that it will work if you are on version 6.5.1 from the chirpy starter, and it will work if you are working from a fork.  If you are working with the 6.5.2 gem from the chirpy starter, then it will not work. 

It also means that the goatcounter stats are not being updated, as the javascript selector looks like it is missing the pageviews bits too.

### Steps To Reproduce

1. from the starter kit, work with 6.5.1
2. enable all goatcounter settings in _config.yml
3. verify that it works.
4. upgrade to 6.5.2
5. verify that pageviews no longer work

### Expected Behavior

Pageviews on goatcounter should be updating.
Pageviews displays should be shown on post layouts.

### Environment

Chirpy 6.5.2 from chirpy starter

**Comment by kungfux** [comment]
Sorry for the misunderstanding. Pageviews on goatcounter #1543 was not planned to be released as part of the v6.5.1. This feature was not merged into the `production` branch, and it is not mentioned in the [release notes](https://github.com/cotes2020/jekyll-theme-chirpy/releases/tag/v6.5.1) for v.6.5.1. This was done by accident.

According to the [release plan](https://github.com/users/cotes2020/projects/2), it is planned for next major release.

**Comment by steveng57** [comment]
I see.   I'll close it out then.
