### ISSUE TITLE
default layout should pass lang=lang as parameter to search-loader.html

### ISSUE THREAD

**Issue by neilboyd** [cotes2020/jekyll-theme-chirpy#1582]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Built from `jekyll-theme-chirpy`

### Describe the bug

At the end of `default` layout is this line:
```
{% include_cached search-loader.html %}
```
it should pass in the `lang` parameter:
```
{% include_cached search-loader.html lang=lang %}
```
because it's used inside of `search-loader.html` to set `not_found` variable.

### Steps To Reproduce

View source - `noResultsText` is empty:
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/1768373/7873056c-1c3c-44a4-a305-90c575549df5)

### Expected Behavior

`noResultsText` gets the value from the included language

### Environment

- Ruby: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
- Jekyll: jekyll 4.3.3
- Chirpy: jekyll-theme-chirpy (6.2.3)

I'm using Chirpy 6.2.3, but the bug is still there in latest `master`

### Anything else?

The real reason I want this is because I want to customize `search-loader.html` and I need `lang`.

**Comment by cotes2020** [comment]
Thanks for reaching out. Looks like this bug has been around since 61fdbcb83a3601ecae62ec230602b94a5eb832e1.

**Comment by neilboyd** [comment]
> Thanks for reaching out. Looks like this bug has been around since [61fdbcb](https://github.com/cotes2020/jekyll-theme-chirpy/commit/61fdbcb83a3601ecae62ec230602b94a5eb832e1).

It probably worked okay until https://github.com/cotes2020/jekyll-theme-chirpy/commit/4fe145e9809ee1b370d9891135939534751462d0
