### ISSUE TITLE
Liquid code being displayed in related-posts.html

### ISSUE THREAD

**Issue by steveng57** [cotes2020/jekyll-theme-chirpy#1596]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

In my post markdown, if I have any liquid code immediately after the Front Matter, when this post is displayed in the "Further Reading" section (which I believe is defined by related-posts.html), then the liquid code is being displayed, instead of it being stripped out.

### Steps To Reproduce

In related-posts.html the code to display a post is below, from line 85 or so.  There doesn't look to be anything to strip out Liquid code.
```liquid
                  {% include no-linenos.html content=post.content %}
                  {{ content | markdownify | strip_html | truncate: 200 | escape }}
```

### Expected Behavior

I'm not a Jekyll expert by any means, but it looks like the code should be...
```liquid
                  {% capture new-content %}
                    {% include no-linenos.html content=post.content %}
                  {% endcapture %}
                  {{ new-content | markdownify | strip_html | truncate: 200 | escape }}
```

### Environment

- Ruby:  ruby 3.2.1 (2023-02-08 revision 31819e82c8) [x64-mingw-ucrt]
- Jekyll:  jekyll 4.3.3
- Chirpy:  jekyll-theme-chirpy (6.5.3)

**Comment by steveng57** [comment]
Another, perhaps better solution, is to look for a 'description' field in the post Front Matter.  If it does not exist, carry on as usual, if it does exist however, use it in the related-posts (Further Reading) sections, and also in the descriptive blurb in the home page.

**Comment by kungfux** [comment]
I think it's a great feature to have a `description` field in the front matter, as it can help work around this problem as well as https://github.com/cotes2020/jekyll-theme-chirpy/discussions/1516. However, the original issue should be fixed separately.

I would like to have this feature for my posts as well, to have control over the post description that appears in multiple places. I will work on it.

**Comment by cotes2020** [comment]
Which version of Chirpy are you using? Please fill in the software environment or this issue will be considered an invalid report, thank you.

**Comment by kungfux** [comment]
I'm able to reproduce the problem reported on latest `master` branch. While @steveng57 is using custom HTML file to include some `<head>`'s, I have used video embedding to demo it below.

```markdown
---
title: Writing a New Post
author: cotes
date: 2019-08-08 14:10:00 +0800
categories: [Blogging, Tutorial]
tags: [writing]
render_with_liquid: false
---

{% include embed/youtube.html id='Balreaj8Yqs' %}
```

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/10548881/5c061527-a64d-4b43-8d94-82acfa093365)
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/10548881/50644b7c-4471-4f96-954b-24c7042acd9b)

**Comment by cotes2020** [comment]
@kungfux Note the special variable for that post: 

```yml
---
render_with_liquid: false
---
```

If you comment out this line, Jekyll will render the liquid code

**Comment by kungfux** [comment]
> If you comment out this line, Jekyll will render the liquid code

My bad. You're right. I made it in hurry cause I was pretty sure I reproduced it a few days back.

Now I see why do you ask to provide necessary details 😅

Thanks @cotes2020.

**Comment by steveng57** [comment]
I updated my op with version details.
