### ISSUE TITLE
unknow specific language for codeblock will cause format error on chirpy 6.2.3

### ISSUE THREAD

**Issue by Iolop** [cotes2020/jekyll-theme-chirpy#1610]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

I found this error when i try to use *assmembly* codeblock in typora and paste my markdown into chirpy(6.2.3).
```
    ```assembly
    CODE HERE
    ```
    {: file="LOCATION"}
```
after build in github pages，i found this block lose it's **div** class
for a simple c codeblock ,it will be wrapped in 
```html
<div class="language-c highlighter-rouge" />
```
but assembly codeblock only build with a 
```html
<pre file="LOCATION">...</pre>
```
here is the build pages
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/11701126/b1e447ea-d27f-4b85-abc5-272467038561)

### Describe the solution you'd like

i wonder maybe there is a way could detect this? just auto remove the unsupported language or wrapped it correctly.

**Comment by cotes2020** [comment]
Duplicate of #1244

**Comment by Iolop** [comment]
> Duplicate of #1244

thx,I didn't find that in issue,maybe the keyword is not correct :P
