### ISSUE TITLE
Pull requests merging conflict

### ISSUE THREAD

**Issue by eth0sec** [cotes2020/jekyll-theme-chirpy#162]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description
I have a fork of this repo which I'm using for my own repo. I keep getting Pull Requests from this main repo. However, I can't merge any of them due to conflicts.
![efefgojh](https://user-images.githubusercontent.com/47247405/97564964-533e7100-19dd-11eb-8e6b-6722d680d1b1.PNG)
Am I supposed to merge them?

Thanks.

**Comment by cotes2020** [comment]
Why not? Just resolve the conficts and then merge the latest code.

**Comment by eth0sec** [comment]
Alright, Thanks.
