### ISSUE TITLE
Issues with "yq" on WSL2

### ISSUE THREAD

**Issue by fiseni** [cotes2020/jekyll-theme-chirpy#163]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description
If you're using WSL2 (Ubuntu) on Windows, then installing `yq` is not quite straightforward. It's installed through `snap`, and `snap` can't be installed on WSL2 due to the `systemd` dependency. 
There are hacks, please refer to this github [issue](https://github.com/microsoft/WSL/issues/5126), but none of them are persistent solutions.

Any chance we can use some `yq` alternative in `create_pages.sh` script?

**Comment by cotes2020** [comment]
Try this:

```terminal
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
sudo add-apt-repository ppa:rmescandon/yq
sudo apt update
sudo apt install yq -y
```

See: <https://github.com/mikefarah/yq#on-ubuntu-1604-or-higher-from-debian-package>

**Comment by fiseni** [comment]
Great, installed successfully from the external apt-repository.

Thanks!
