### ISSUE TITLE
How to config in local and blog follow is not working

### ISSUE THREAD

**Issue by Khant-Nyar** [cotes2020/jekyll-theme-chirpy#165]
## Checklist

- [ ] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [ ] There are no similar question on existing issues (including closed ones).
- [ ] I searched the Internet for related problems, but still couldn't solve it.
- [ ] My question is based on the latest code of `master` branch.

## Description

If you doe't mine,Show to How to setup in local and How to Upload a post Please

**Comment by Cloufish** [comment]
To be honest he does mind and with these issues, you'll only raise world tension and bring us war with China...

Khant, watch some Jekyll tutorial and about the directory structure that it has, with these basics you probably will understand.
One of my favorites is from Giraffe Academy [Course](https://youtu.be/T1itpPvFWHI)

**Comment by Khant-Nyar** [comment]
**Thanks a lot bro**
