### ISSUE TITLE
Linkedin Share

### ISSUE THREAD

**Issue by SoOM3a** [cotes2020/jekyll-theme-chirpy#1654]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

When sharing a post to linkedin through an error
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/24592480/919181de-d06e-45d3-beb6-8ebc7acddcc5)
this due to post url special char has been decoded. 

automatic generated from sharing button: `https://www.linkedin.com/sharing/share-offsite/?url=soom3a.github.io%2FAboutMe%2FBlogs%2Fposts%2Fwindows_core_process`
Correct sharing link should be : 
`https://www.linkedin.com/sharing/share-offsite/?url=https://soom3a.github.io/Blogs/posts/windows_core_process`
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/24592480/b379b2b2-a74e-479d-9e2f-fc63dd7b2f3d)

### Steps To Reproduce

- Activate linkedin sharing 
- Create a post
- Try to share the post via linkedin button 

### Expected Behavior

Expected behavior should share via linkedin without manually update the url 
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/24592480/b379b2b2-a74e-479d-9e2f-fc63dd7b2f3d)

### Environment

- Ruby 
`ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [x64-mingw-ucrt]`
- Jekyll
`jekyll 4.3.3`
- Chirpy
```
* jekyll-theme-chirpy (6.5.5)
        Summary: A minimal, responsive, and feature-rich Jekyll theme 
for technical writing.
        Homepage: https://github.com/cotes2020/jekyll-theme-chirpy    
        Documentation: https://github.com/cotes2020/jekyll-theme-chirpy/#readme
        Source Code: https://github.com/cotes2020/jekyll-theme-chirpy 
        Wiki: https://github.com/cotes2020/jekyll-theme-chirpy/wiki   
        Bug Tracker: https://github.com/cotes2020/jekyll-theme-chirpy/issues
        Path: C:/Users/abdel/.local/share/gem/ruby/3.2.0/gems/jekyll-theme-chirpy-6.5.5
```

**Comment by cotes2020** [comment]
> automatic generated from sharing button: `https://www.linkedin.com/sharing/share-offsite/?url=soom3a.github.io%2FAboutMe%2FBlogs%2Fposts%2Fwindows_core_process`

Your `url` is missing the protocol part, so I infer that your `site.url` is also missing the protocol. Please read the documentation on how to set the correct value for it.
