### ISSUE TITLE
can make custom tabs by category??

### ISSUE THREAD

**Issue by lawiparadise** [cotes2020/jekyll-theme-chirpy#170]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

I want to change tab by categories

1: home tabs
-> HOME
-> CATEGORIES
-> TAGS
-> ARCHIVES
-> ABOUT

2: Algorithm tabs (when if I click Algorithm category's article)
->FIRST tab
->SECOND tab
->THIRD tab

2-1: Algorithm tabs (when if I click Algorithm category's article)
->FIRST tab
  -> INNER tab
->SECOND tab
  -> Article1
  -> Article2
->THIRD tab

<img width="928" alt="ques" src="https://user-images.githubusercontent.com/12179624/99140698-6b71e980-2687-11eb-940d-6c17695a9245.png">

1,2,3 is possible??
1 : possible
2 : ?
2-1 : ?

please help me!! thanks

if can't get easy way,
then can i make branch and pull request ???

**Comment by cotes2020** [comment]
Hi @lawiparadise,

By refactoring the code, yes. In theory, you can change tabs to any style you like. However, if you want to do this as a PR, then I don't approve of it. Because this will turn the blog into a user manual site.

**Comment by lawiparadise** [comment]
Good~~ Thanks!! OK
then, is it hard to me to change tabs...?? you think??

**Comment by cotes2020** [comment]
I think you should ask yourself:

1. Do I know HTML/CSS?
2. Do I know the development of Jekyll site?

If you answered yes to both, you can easily change the tabs. Otherwise, consider custom development before you learn the above two skills.

**Comment by lawiparadise** [comment]
1. YES
2. NO

OK I see, Thanks ur kind answer!
Thanks to good theme! I love it!!

**Comment by SilentGlasses** [comment]
A bit late but if you want to build a manual/documentation site, mkdocs is what I would suggest you use @lawiparadise

**Comment by lawiparadise** [comment]
oh mkdocs great!!
thank you😁

2021년 12월 23일 (목) 10:59, SilentGlasses ***@***.***>님이 작성:

**Comment by PBeamA** [comment]
Also very late but I too want use cote2020's theme -- but not as a blog.
This might be useful: https://github.com/PBeamA/chirpy-starter-modified/
  - I think it's a bit closer to what you want.

**Comment by jocile** [comment]
I was able to add new links in the side menu by simply adding new .md files in the _tabs folder, I even created another site in another repository with the same name as the link: see in https://jocile.com/ ->  https://github.com/jocile/jocile.github.io

**Comment by jakewqj** [comment]
> I was able to add new links in the side menu by simply adding new .md files in the _tabs folder, I even created another site in another repository with the same name as the link: see in https://jocile.com/ -> https://github.com/jocile/jocile.github.io

It looks pretty amazing. Exactly what I am trying to do for now.
