### ISSUE TITLE
Collection / Pages support

### ISSUE THREAD

**Issue by MFlisar** [cotes2020/jekyll-theme-chirpy#1713]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

I want to have pages and custom collections on my page and I want them to be supported by all features of chirpy, namely:

* breadcrumbs
* search

### Describe the solution you'd like

**Breadcrumbs**

When using a collection, the breadcrumbs only show the page name and not the path.

![grafik](https://github.com/cotes2020/jekyll-theme-chirpy/assets/2437726/32c33b59-e0c5-4d07-8d4e-f2993159aa83)

I would like the breadcrumb to show the path here...

**Search**

Searching does currently only search posts. Would be nice if I could enable searching inside pages and collections as well.

### Additional context

Is this something that is totally out of scope or would you consider adding support for collections in the future?

**Comment by cotes2020** [comment]
This is a site designed for a collection of `posts`, changing it to adapt to other custom collections is not the goal. You should make adjustments in your own fork.
