### ISSUE TITLE
Disqus comments feature not working

### ISSUE THREAD

**Issue by anonfaded** [cotes2020/jekyll-theme-chirpy#1715]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Built from `jekyll-theme-chirpy`

### Describe the bug

The disqus comments feature was working before but not working now without any changes to the website, its enabled in config file and also in posts but still the comments are not showing. my website repo: https://github.com/fadedhood/fadedhood.github.io

### Steps To Reproduce

open website: fadedhood.com
open any post and see in the bottom no disqus comments.

### Expected Behavior

The disqus comments should be shown

### Environment

- Ruby: default 
- Jekyll: default
- Chirpy: default

**Comment by viv1** [comment]
This would have happened because the name for the `comments` active provider property was changed from `active` to `provider`:

See: https://github.com/cotes2020/jekyll-theme-chirpy/commit/f8390d4384600fb015728b1b186570fa58ca216f

**Comment by anonfaded** [comment]
thanks, now its fixed
