### ISSUE TITLE
JS not loading on some browsers

### ISSUE THREAD

**Issue by matiassalles99** [cotes2020/jekyll-theme-chirpy#1718]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

When navigating to a page in some browsers (eg: Default Android Browser, Microsoft Edge, or even Chrome in Incognito mode), bootstrap and other JS libraries don't load. You can even see it with Chirpy's demo page in Incognito Mode inside Chrome:

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/57004457/30ed5297-7647-46b1-8b17-090c2a5376d0)

### Steps To Reproduce

1. Navigate to https://chirpy.cotes.page/ in Incognito mode inside Google Chrome

### Expected Behavior

JS should load an styles shouldn't look off on any of these browsers

### Environment

- Ruby: 3.x
- Jekyll: 4.3.3
- Chirpy: 6.5.5

### Anything else?

maybe we are missing cross-origin and integrity attributes in the <link tag?

**Comment by amrhossamdev** [comment]
Yes, I can confirm and luckily it happened when I tried to post a new blog!

so I thought it was a mistake but the original website was broken

**Comment by kungfux** [comment]
This happens due to certificate expiration for https://cdn.jsdelivr.net/ that is used for JS hosting.

```
NET::ERR_CERT_DATE_INVALID
Subject: sni.cloudflaressl.com

Issuer: Cloudflare Inc ECC CA-3

Expires on: May 2, 2024

Current date: May 2, 2024
```

So, this issue should be reported to and fixed by https://www.jsdelivr.com/.

However, it's a good case for us to consider hosting dependencies by ourselves.

**Comment by matiassalles99** [comment]
Interesting, I guess I had it cached locally and that's why it fails only in incognito. I was wondering indeed if there was a way to host dependencies ourselves, but that's a feature request, so I'll close this issue. Thx @kungfux :)

**Comment by NichtsHsu** [comment]
> I  was wondering indeed if there was a way to host dependencies ourselves, but that's a feature request

Chirpy already supports self-hosting:

https://github.com/cotes2020/jekyll-theme-chirpy/blob/dcb0add47bf1adf92215514f1ccfa4661d5215be/_config.yml#L128-L134

... and check the [Manually Build and Deploy](https://chirpy.cotes.page/posts/getting-started/#manually-build-and-deploy) section from chirpy's getting start.
