### ISSUE TITLE
Justify text in a post

### ISSUE THREAD

**Issue by LearningAlgorithms** [cotes2020/jekyll-theme-chirpy#172]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar questions on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description
Hello, and thanks for your work on this fantastic theme.

I have been searching if there is any way to justify all the text in a post. Any way to select the alignment of the blog in general to justified.

**Comment by cotes2020** [comment]
Do you mean to change the alignment of the text to center or right? According to the normal reading experience, the text is aligned to the left, so changing it is not necessary.

**Comment by LearningAlgorithms** [comment]
Yes, I was meaning to change the alignment to make it justified.

**Comment by Dodain** [comment]
@cotes2020 kudos on the amazing theme. I also have the same question, the text in the theme isn't "Justified". Do we have a way to Justify the text? Not right or centre align but [Justify](https://www.w3schools.com/cssref/pr_text_text-align.ASP)

**Comment by cotes2020** [comment]
Hi @Dodain, all you need to do is customize the relevant CSS selector to `text-align: justify;`

**Comment by Dodain** [comment]
Please bear with me, may sound stupid but where is the CSS file I need to modify? I have written a .md file in _posts. I need the text in that post to be Justified.

**Comment by cotes2020** [comment]
See: <https://github.com/cotes2020/chirpy-starter#customing-stylesheet>

If you want to modify the style of the theme, I think you should learn some basic CSS knowledge and learn how to use the browser DevTool to find the CSS selector.

For now, you add the following to the style file:

```css
.post-content { text-align: justify; }
```

**Comment by Dodain** [comment]
Thanks, @cotes2020 , the text is justified now.
