### ISSUE TITLE
issue occurs when using tag and categories tabs is clicked

### ISSUE THREAD

**Issue by thevillagehacker** [cotes2020/jekyll-theme-chirpy#173]
# Summary
Repo is forked and changed the username into mine and the website is deployed the problem is when you click the categories and tags tab in navigation it shows 404 error message but the website you hosted in your server works good. I don't know what's the problem with this codes.

## Reference
![image](https://user-images.githubusercontent.com/32858162/99258025-f3015900-283d-11eb-932e-b3a649520848.png)

please check this URL
https://ghostonwater.github.io/

- I just forked the repository and edited the config file the only thing i changed is repo URL only.

Thanks
Ghost

**Comment by cotes2020** [comment]
1. Why do you ignore the checklist of the issue template?
2. Why don't you read docs?
