### ISSUE TITLE
Add Markdownify processing to description: field Front Matter rendering.

### ISSUE THREAD

**Issue by steveng57** [cotes2020/jekyll-theme-chirpy#1739]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

Would like the ability to have basic markdown formatting in the description; field of a post.

### Describe the solution you'd like

The new description: field in the Front Matter YAML is awesome and works great.  It  would be even better if it could handle markdown used in the description, for bolding and italisizing etc.

For example:
```YAML
description: This is a **REALLY** cool thing.
```

Would be rendered as:

This is a **REALLY** cool thing.

**Comment by pavel-perina** [comment]
I assume that primary purpose of description is to generate `<meta description="...">` tag for SEO optimization and i was surprised that it's used as a kind of sub-header on every page and for index in v7. Since then, some of my pages have basically double introduction so I'm not sure I like it. Obviously author can't make everyone happy :-)

**Comment by steveng57** [comment]
> I assume that primary purpose of description is to generate `<meta description="...">` tag for SEO optimization and i was surprised that it's used as a kind of sub-header on every page and for index in v7. Since then, some of my pages have basically double introduction so I'm not sure I like it. Obviously author can't make everyone happy :-)

I think it had the SEO intent for some other folk, but my interest was in being able to have something better than just the first line of the post showing up on other places, like the home pages, and 'for further reading' blocks at the bottom of other post.  Also, in my case, the first lines of my post pages are Liquid code and that should not be showing up anywhere.  This is a way to make sure that doesn't happen.
