### ISSUE TITLE
Automated repository README.md as post content

### ISSUE THREAD

**Issue by extinctCoder** [cotes2020/jekyll-theme-chirpy#1743]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

i want to add some of my projects as project category blog posts. lets say my project short description is already in my readme file. there are no way of importing the content in the site.

### Describe the solution you'd like

it will be something like yml file for social link content where I can put the repository link and then the site can pull the readme file from the repo.
it must need to be public repo.

**Comment by huanyushi** [comment]
If I understand you correctly, you probably want to automatically update the description (e.g. README.md) on a repo to the post content. 

I don't think this is a function of **static** websites, maybe you should look for plugins or something like [gh-contrib-graph](https://github.com/lengthylyova/gh-contrib-graph) (which automatically updates GitHub contributions graph in HMTL).

**Comment by extinctCoder** [comment]
i have a repo here https://github.com/binaryloom/TaskManagementSystem
i want to create a blog post based on the repo. and this is the content https://github.com/binaryloom/TaskManagementSystem/blob/main/README.md
