### ISSUE TITLE
error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/jekyll-theme-chirpy.scss':

### ISSUE THREAD

**Issue by ebmarquez** [cotes2020/jekyll-theme-chirpy#1744]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Built from `jekyll-theme-chirpy`

### Describe the bug

Build find locally, but when it runs with github actions it can't find "Can't find stylesheet to import."

https://github.com/ebmarquez/ebmarquez.github.io/actions/runs/9069896682/job/24920477188

Run bundle exec jekyll b -d "_site"
  bundle exec jekyll b -d "_site"
  shell: /usr/bin/bash -e {0}
  env:
    GITHUB_PAGES: true
    JEKYLL_ENV: production
/home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll.rb:[2](https://github.com/ebmarquez/ebmarquez.github.io/actions/runs/9069896682/job/24920477188#step:5:2)8: warning: csv was loaded from the standard library, but will no longer be part of the default gems since Ruby [3](https://github.com/ebmarquez/ebmarquez.github.io/actions/runs/9069896682/job/24920477188#step:5:3).4.0. Add csv to your Gemfile or gemspec. Also contact author of jekyll-[4](https://github.com/ebmarquez/ebmarquez.github.io/actions/runs/9069896682/job/24920477188#step:5:4).3.3 to add csv into its gemspec.
/home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/safe_yaml-1.0.[5](https://github.com/ebmarquez/ebmarquez.github.io/actions/runs/9069896682/job/24920477188#step:5:5)/lib/safe_yaml/transform.rb:1: warning: base[6](https://github.com/ebmarquez/ebmarquez.github.io/actions/runs/9069896682/job/24920477188#step:5:6)4 was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add base64 to your Gemfile or gemspec. Also contact author of safe_yaml-1.0.5 to add base64 into its gemspec.
Configuration file: /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/_config.yml
 Theme Config file: /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/_config.yml
            Source: /home/runner/work/ebmarquez.github.io/ebmarquez.github.io
       Destination: /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
Error: Can't find stylesheet to import.
  ╷
1 │ @import 'dist/bootstrap';
  │         ^^^^^^^^^^^^^^^^
  ╵
  main.bundle.scss 1:[9](https://github.com/ebmarquez/ebmarquez.github.io/actions/runs/9069896682/job/24920477188#step:5:10)                                                                               @import
  /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/assets/css/jekyll-theme-chirpy.scss 1:9  root stylesheet 
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/jekyll-theme-chirpy.scss':
                    Can't find stylesheet to import.
                    ------------------------------------------------
      Jekyll 4.3.3   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------

### Steps To Reproduce

Run github action deployment action.

Fails with bundle exec jekyll command

### Expected Behavior

does not fail and find the missing css stylesheet.

### Environment

- Ruby: ruby 3.3.1 (2024-04-23 revision c56cd86388) [x86_64-linux]
- Jekyll:
Run bundle exec jekyll -v
  bundle exec jekyll -v
  shell: /usr/bin/bash -e {0}
  env:
    GITHUB_PAGES: true
  
/home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll.rb:[2](https://github.com/ebmarquez/ebmarquez.github.io/actions/runs/9070044498/job/24920949929#step:7:2)8: warning: csv was loaded from the standard library, but will no longer be part of the default gems since Ruby [3](https://github.com/ebmarquez/ebmarquez.github.io/actions/runs/9070044498/job/24920949929#step:7:3).4.0. Add csv to your Gemfile or gemspec. Also contact author of jekyll-[4](https://github.com/ebmarquez/ebmarquez.github.io/actions/runs/9070044498/job/24920949929#step:7:4).3.3 to add csv into its gemspec.
/home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/safe_yaml-1.0.[5](https://github.com/ebmarquez/ebmarquez.github.io/actions/runs/9070044498/job/24920949929#step:7:5)/lib/safe_yaml/transform.rb:1: warning: base[6](https://github.com/ebmarquez/ebmarquez.github.io/actions/runs/9070044498/job/24920949929#step:7:6)4 was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add base[6](https://github.com/ebmarquez/ebmarquez.github.io/actions/runs/9070044498/job/24920949929#step:7:7)4 to your Gemfile or gemspec. Also contact author of safe_yaml-1.0.5 to add base64 into its gemspec.
jekyll 4.3.3
- Chirpy:
Run bundle info jekyll-theme-chirp
  bundle info jekyll-theme-chirp
  shell: /usr/bin/bash -e {0}
  env:
    GITHUB_PAGES: true
  
  * jekyll-theme-chirpy (7.0.0)
	Summary: A minimal, responsive, and feature-rich Jekyll theme for technical writing.
	Homepage: https://github.com/cotes[2](https://github.com/ebmarquez/ebmarquez.github.io/actions/runs/9070044498/job/24920949929#step:6:2)020/jekyll-theme-chirpy
	Documentation: https://github.com/cotes2020/jekyll-theme-chirpy/#readme
	Source Code: https://github.com/cotes2020/jekyll-theme-chirpy
	Wiki: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
	Bug Tracker: https://github.com/cotes2020/jekyll-theme-chirpy/issues
	Path: /home/runner/work/ebmarquez.github.io/ebmarquez.github.io

### Anything else?

Run bundle exec jekyll b -d "_site"
  bundle exec jekyll b -d "_site"
  shell: /usr/bin/bash -e {0}
  env:
    GITHUB_PAGES: true
    JEKYLL_ENV: production
/home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll.rb:[2](https://github.com/ebmarquez/ebmarquez.github.io/actions/runs/9069896682/job/24920477188#step:5:2)8: warning: csv was loaded from the standard library, but will no longer be part of the default gems since Ruby [3](https://github.com/ebmarquez/ebmarquez.github.io/actions/runs/9069896682/job/24920477188#step:5:3).4.0. Add csv to your Gemfile or gemspec. Also contact author of jekyll-[4](https://github.com/ebmarquez/ebmarquez.github.io/actions/runs/9069896682/job/24920477188#step:5:4).3.3 to add csv into its gemspec.
/home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/safe_yaml-1.0.[5](https://github.com/ebmarquez/ebmarquez.github.io/actions/runs/9069896682/job/24920477188#step:5:5)/lib/safe_yaml/transform.rb:1: warning: base[6](https://github.com/ebmarquez/ebmarquez.github.io/actions/runs/9069896682/job/24920477188#step:5:6)4 was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add base64 to your Gemfile or gemspec. Also contact author of safe_yaml-1.0.5 to add base64 into its gemspec.
Configuration file: /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/_config.yml
 Theme Config file: /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/_config.yml
            Source: /home/runner/work/ebmarquez.github.io/ebmarquez.github.io
       Destination: /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
Error: Can't find stylesheet to import.
  ╷
1 │ @import 'dist/bootstrap';
  │         ^^^^^^^^^^^^^^^^
  ╵
  main.bundle.scss 1:9                                                                               @import
  /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/assets/css/jekyll-theme-chirpy.scss 1:9  root stylesheet 
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/jekyll-theme-chirpy.scss':
                    Can't find stylesheet to import.
                    ------------------------------------------------
      Jekyll 4.3.3   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-sass-converter-3.0.0/lib/jekyll/converters/scss.rb:1[7](https://github.com/ebmarquez/ebmarquez.github.io/actions/runs/9069896682/job/24920477188#step:5:8)5:in `rescue in convert': Can't find stylesheet to import. (Jekyll::Converters::Scss::SyntaxError)

        raise SyntaxError, e.message
              ^^^^^^^^^^^^^^^^^^^^^^
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-sass-converter-3.0.0/lib/jekyll/converters/scss.rb:159:in `convert'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:105:in `block in convert'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:104:in `each'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:104:in `reduce'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:104:in `convert'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:[8](https://github.com/ebmarquez/ebmarquez.github.io/actions/runs/9069896682/job/24920477188#step:5:9)4:in `render_document'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:63:in `run'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:572:in `render_regenerated'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:564:in `block in render_pages'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:563:in `each'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:563:in `render_pages'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:211:in `render'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:80:in `process'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/command.rb:28:in `process_site'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:65:in `build'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:36:in `process'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/command.rb:[9](https://github.com/ebmarquez/ebmarquez.github.io/actions/runs/9069896682/job/24920477188#step:5:10)1:in `block in process_with_graceful_fail'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `each'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/exe/jekyll:15:in `<top (required)>'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/bin/jekyll:25:in `load'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/bin/jekyll:25:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `load'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/3.3.0/bundler/cli/exec.rb:23:in `run'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/3.3.0/bundler/cli.rb:451:in `exec'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/3.3.0/bundler/cli.rb:34:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/3.3.0/bundler/cli.rb:28:in `start'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/exe/bundle:28:in `block in <top (required)>'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/3.3.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/exe/bundle:20:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/bin/bundle:25:in `load'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/bin/bundle:25:in `<main>'
/home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/sass-embedded-1.77.1-x86_64-linux-gnu/lib/sass/compiler/host.rb:86:in `compile_request': Can't find stylesheet to import. (Sass::CompileError)
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/sass-embedded-1.77.1-x86_64-linux-gnu/lib/sass/compiler.rb:171:in `compile_string'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/sass-embedded-1.77.1-x86_64-linux-gnu/lib/sass/embedded.rb:37:in `compile_string'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-sass-converter-3.0.0/lib/jekyll/converters/scss.rb:160:in `convert'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:[10](https://github.com/ebmarquez/ebmarquez.github.io/actions/runs/9069896682/job/24920477188#step:5:11)5:in `block in convert'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:104:in `each'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:104:in `reduce'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:104:in `convert'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:84:in `render_document'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:63:in `run'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:572:in `render_regenerated'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:564:in `block in render_pages'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:563:in `each'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:563:in `render_pages'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:2[11](https://github.com/ebmarquez/ebmarquez.github.io/actions/runs/9069896682/job/24920477188#step:5:12):in `render'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:80:in `process'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/command.rb:28:in `process_site'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:65:in `build'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:36:in `process'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `each'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.3/exe/jekyll:15:in `<top (required)>'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/bin/jekyll:25:in `load'
	from /home/runner/work/ebmarquez.github.io/ebmarquez.github.io/vendor/bundle/ruby/3.3.0/bin/jekyll:25:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `load'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/3.3.0/bundler/cli/exec.rb:23:in `run'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/3.3.0/bundler/cli.rb:451:in `exec'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/invocation.rb:[12](https://github.com/ebmarquez/ebmarquez.github.io/actions/runs/9069896682/job/24920477188#step:5:13)7:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/3.3.0/bundler/cli.rb:34:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/3.3.0/bundler/cli.rb:28:in `start'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/exe/bundle:28:in `block in <top (required)>'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/3.3.0/bundler/friendly_errors.rb:1[17](https://github.com/ebmarquez/ebmarquez.github.io/actions/runs/9069896682/job/24920477188#step:5:18):in `with_friendly_errors'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.9/exe/bundle:[20](https://github.com/ebmarquez/ebmarquez.github.io/actions/runs/9069896682/job/24920477188#step:5:21):in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/bin/bundle:25:in `load'
	from /opt/hostedtoolcache/Ruby/3.3.1/x64/bin/bundle:25:in `<main>'
Error: Process completed with exit code 1.

**Comment by lamininA1** [comment]
```
# Misc
_sass/dist
assets/js/dist
```
Remove those two line in `.gitignore`
```
# Misc
#_sass/dist
#assets/js/dist
```

**Comment by RaphLeRetour** [comment]
Hello ! I have the same issue while deploying on Github Pages. Removing the `@import 'dist/bootstrap';` fixed the issue but now the site is defaced (which is totally expected).

Did you find a fix for this issue ? Removing the two lines from the .gitignore file doesn't resolve the problem. It seems like the problem started to happen after May 11th commits regarding the Boostrap dependency.

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/128185647/115e9467-ea4a-49e6-acf1-14d69b2629b1)

**Comment by lamininA1** [comment]
> Hello ! I have the same issue while deploying on Github Pages. Removing the `@import 'dist/bootstrap';` fixed the issue but now the site is defaced (which is totally expected).
> 
> Did you find a fix for this issue ? Removing the two lines from the .gitignore file doesn't resolve the problem. It seems like it started to happen after May 11th commits regarding the Boostrap dependency.
> 
> ![image](https://private-user-images.githubusercontent.com/128185647/331814771-115e9467-ea4a-49e6-acf1-14d69b2629b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNDkzODEsIm5iZiI6MTcxNjA0OTA4MSwicGF0aCI6Ii8xMjgxODU2NDcvMzMxODE0NzcxLTExNWU5NDY3LWVhNGEtNDllNi1hY2YxLTE0ZDY5YjI2MjliMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQxNjE4MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODYzNWFhYjg0MzYwZDNkOWJlNGUyODI2MTVmN2JmNjljOTdjNGU5NjJlMmUyMWIzOWU4NjI2MzExNmIyYzQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.68Nc5IL0EP6OsfYgcLt2RPP8Neg--jTSnYUby2mUbqY)
> 
> Also, please note that the issue doesn't happen on my local test environment, only while deploying to Github. Unfortunately I don't have a sufficient knowledge of Jekyll or the template to track down the problem. Thank you @cotes2020 !

You shouldn't remove bootstrap! That thing is like css bundle that helps your site style. After modified `.gitignore` file, you need to command `git add .`, `git commit -m "Your massage"`, and `git push`. Above problem occur since the repo doesn't have sass files (which is same as css file) and `*.min.js` files.

**Comment by RaphLeRetour** [comment]
I still got the issue after removing these lines for the gitignore file ...

**Comment by lamininA1** [comment]
Did you do the push again?

**Comment by RaphLeRetour** [comment]
Yes ofc

**Comment by lamininA1** [comment]
> Yes ofc

I just checked you repo. And those two line are still there. Even _sass/dist folder and js/dist folder are not there. Could you check again?

**Comment by RaphLeRetour** [comment]
This is a new repo forked from a few commits before the boostrap change I deleted the previous one to work on a clean version

**Comment by NichtsHsu** [comment]
> Hello ! I have the same issue while deploying on Github Pages. Removing the @import 'dist/bootstrap'; fixed the issue but now the site is defaced (which is totally expected).

This file is generated by `npm i && npm run build`, and this command is executed by [tools/init](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/tools/init):

https://github.com/cotes2020/jekyll-theme-chirpy/blob/0102abae062be24ec289fb7facb11950aca79e3f/tools/init#L91-L92

The `_sass/dist` directory is in `.gitignore` by default. Similarly, [tools/init](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/tools/init) will remove it:

https://github.com/cotes2020/jekyll-theme-chirpy/blob/0102abae062be24ec289fb7facb11950aca79e3f/tools/init#L94-L95

You can check your fork by referring to the above steps. As a last resort, you can [tools/init](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/tools/init), however this will delete all your modifications.

**Comment by RaphLeRetour** [comment]
Did just that, deployement is ok but the site layout is still messed

**Comment by NichtsHsu** [comment]
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/35688135/54de044c-cd41-40c2-9a6d-101805ae910f)

Have you set the source of Github Pages to Github Action?

**Comment by RaphLeRetour** [comment]
Forgot to switch -_- my original mistake is that I didn't notice that there was another `dist` directory in the `_sass` folder.

Anyway it's working now. Thank you so much !!
