### ISSUE TITLE
All images will be displayed when switching images (including light and dark mode).

### ISSUE THREAD

**Issue by huanyushi** [cotes2020/jekyll-theme-chirpy#1748]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

The image-switching feature was introduced in version 7.0.0. 

When we specify images for both the light and dark modes separately within a post, we can switch to the next image using a button. However, it will display all images (regardless of whether they are for the light or dark mode) uniformly.

### Steps To Reproduce

For example, if we have a post like

```markdown
para1

![fig1](fig1-light.png){: .light}
![fig1](fig1-dark.png){: .dark}

para2

![fig2](fig2-light.png){: .light}
![fig2](fig2-dark.png){: .dark}
```

When we switch images using the button, the displayed image sequence is `fig1-light.png`, `fig1-dark.png`, `fig2-light.png`, `fig2-dark.png`.

### Expected Behavior

I think that when switching images, only the images corresponding to the current mode are displayed. For example, when we are in light mode, the displayed image sequence is `fig1-light.png`, `fig2-light.png`.

### Environment

- Ruby: 3.2.1
- Jekyll: 4.3.3
- Chirpy: 7.0.0

### Anything else?

Nothing.

**Comment by cotes2020** [comment]
Sorry, I don't understand what the "switching image" is, could you please provide a screenshot to illustrate the problem?

**Comment by kungfux** [comment]
If I understand correctly, the question is about `glightbox` and the ability to view all images by "toggling" to the next/previous image in the gallery.

Here is a live example https://kungfux.github.io/posts/resource-limitations-cause-bugs/#case-1-gdi-object-leaks. The post contains images created specifically for light and dark themes. If you open an image and toggle to next/previous, you will see an image not for the current theme in the gallery.

**Comment by huanyushi** [comment]
Yes, this is exactly the issue I want to feedback on.

**Comment by huanyushi** [comment]
Yes, what @kungfux said was exactly what I wanted to feedback on.

If you click an image on https://chirpy.cotes.page/posts/text-and-typography/#darklight-mode--shadow, you can see the `next` button,

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/100574401/78bbdec5-e7f2-4277-bd0a-8e202803d00f)

If you click the button it will switch to the next image and you will see all images (regardless of whether they are for the light or dark mode).

**Comment by cotes2020** [comment]
I'm just keeping `Glightbox`'s default behavior, to hide images that don't fit the theme mode, you may need to modify `Glightbox` configuration, or have `Glightbox` disable looping images, and just use its zoom.

Either way, you're welcome to submit a PR to help improve this!
