### ISSUE TITLE
 Would like the ability to have basic markdown formatting in the description; field of a post.

### ISSUE THREAD

**Issue by steveng57** [cotes2020/jekyll-theme-chirpy#1764]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

The new description: field in the Front Matter YAML is awesome and works great. It would be even better if it could handle markdown used in the description, for bolding and italisizing etc.

For example:

description: This is a **REALLY** cool thing.
Would be rendered as:

This is a REALLY cool thing.

### Describe the solution you'd like

The new description: field in the Front Matter YAML is awesome and works great. It would be even better if it could handle markdown used in the description, for bolding and italisizing etc.

**Comment by huanyushi** [comment]
Just delete `escape` in `_includes/post-description.html`, see [here](https://github.com/cotes2020/jekyll-theme-chirpy/blob/0102abae062be24ec289fb7facb11950aca79e3f/_includes/post-description.html#L16), can solve your problem.

```diff
{%- comment -%}
  Get post description or generate it from the post content.
{%- endcomment -%}

{%- assign max_length = include.max_length | default: 200 -%}

{%- capture description -%}
{%- if post.description -%}
  {{- post.description -}}
{%- else -%}
  {%- include no-linenos.html content=post.content -%}
  {{- content | markdownify | strip_html -}}
{%- endif -%}
{%- endcapture -%}

- {{- description | strip | truncate: max_length | escape -}}
+ {{- description | strip | truncate: max_length  -}}
```

Effect:
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/100574401/9d896da4-1918-4a30-8239-9e47f7de57d0)

The function of `escape` in Liquid can be found [here](https://shopify.github.io/liquid/filters/escape/),

> Escapes a string by replacing characters with escape sequences (so that the string can be used in a URL, for example). It doesn’t change strings that don’t have anything to escape.

In Jekyll blogs, the 'escape' filter is typically used to HTML-escape the output, ensuring that when rendered on a webpage, it won't be interpreted as HTML tags, thereby mitigating potential security risks such as XSS (Cross-Site Scripting) attacks.

In the above code snippet in `_includes/post-description.html`, the 'escape' filter is applied after the 'truncate' filter. This means it ensures that the text after truncation does not contain any unescaped HTML tags. The purpose of this is to maintain the security of the page by ensuring that the truncated text length does not include any unescaped HTML tags.

If you delete 'escape', it may lead to potential bugs. I believe this is why the author closed the issues you previously opened.

**Comment by huanyushi** [comment]
For example, If you make the last word of the description displayed in home bold, you will find that all other post previews have become bold. Other layouts of the page will also be broken.

<table>
<tr>
<td>
<img src="https://github.com/cotes2020/jekyll-theme-chirpy/assets/100574401/001ac348-cd8b-4f33-bf54-21468086707b"></td>
<td><img src="https://github.com/cotes2020/jekyll-theme-chirpy/assets/100574401/3474c0b6-2c5a-453c-b784-94d5a38b6a01"> </td>
</tr>
</table>

### So I don't suggest you do this

**Comment by steveng57** [comment]
Thanks for the detailed explanation, much appreciated!  I am a bit smarter now.

would there be anything wrong with:
```liquid
{%- capture description -%}
{%- if post.description -%}
  {{- post.description  | strip | truncate: max_length | markdownify | escape -}}
{%- else -%}
```

**Comment by huanyushi** [comment]
> Thanks for the detailed explanation, much appreciated! I am a bit smarter now.
> 
> would there be anything wrong with:
> 
> ```
> {%- capture description -%}
> {%- if post.description -%}
>   {{- post.description  | strip | truncate: max_length | markdownify | escape -}}
> {%- else -%}
> ```

It doesn't work.

**Comment by cotes2020** [comment]
Duplicate of #1739
