### ISSUE TITLE
Error /assets/js/dist/home.min.js

### ISSUE THREAD

**Issue by Vctrsnts** [cotes2020/jekyll-theme-chirpy#1765]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Using docker

docker-compose and container `bretfisher/jekyll-serve:latest`

### Describe the bug

Hi.
When run the theme with ( docker jelly-server in local server ) and navigate for the page, all time see the same error:
`ERROR `/assets/js/dist/home.min.js' not found.`

I see this [error](https://github.com/cotes2020/jekyll-theme-chirpy/issues/1056) and use this [solution](https://github.com/cotes2020/jekyll-theme-chirpy/issues/942#issuecomment-1592449176) and [this](https://github.com/cotes2020/jekyll-theme-chirpy/wiki/Development-&-Test-Environments#compiling-js-files).

But not have any result. Is possible because to use in docker? How resolv the problem?

Thanks

### Steps To Reproduce

The problem is that I user this theme in docker.
1. And when run in docker ( docker exec -it jekyll sh )
2. cd tools > sh run
3. Not have any solution

### Expected Behavior

Solution the problem??

### Environment

- Ruby:  3.1.5
- Jekyll:  4.3.3
- Chirpy:  the last version. I fork the project

### Anything else?

I think, I dont now

**Comment by seaque** [comment]
Having the same problem since Chirpy 7.0

**Comment by cotes2020** [comment]
Whether you use docker or not is not the issue, you should first read the docs on how to build some of the static CSS/JS files needed to run the project

**Comment by lukebewitched** [comment]
This is an issue to be honest. I tried all the steps and it's not working. Any help would be appreciated.

**Comment by seaque** [comment]
It used to work fine, after updating Chirpy gem it breaks. Nothing drastic changed in config, pages deploy changed Ruby version. I don't think I am doing something wrong.

**Comment by kungfux** [comment]
It works inside Docker container within configuration being added in #1781.

It will be hard to continue discussion without seeing `Dockerfile` you are using.

**Comment by seaque** [comment]
I am not using Docker. The local version works fine. Deploying to GitHub Pages completes the action and publishes the site, only after then I have to go to the site and check console to see the error.

**Comment by lukebewitched** [comment]
It states that the files are not available locally, but works fine on the Github Pages. I run the local version without them, then deploy the pages to the GP. For now, I'll use this as a step-gap.

**Comment by yu45020** [comment]
In case you haven't found the solution.

The [document](https://chirpy.cotes.page/posts/getting-started/#setting-up-natively-recommended-for-unix-like-os) is not clear for this step because it is necessary for both linux and windows 

You need to run 

```bash
bash tools/init.sh
```
It will then rename files such as "_javascript/home.js" to "_site/assets/js/dist/home.min.js"
