### ISSUE TITLE
Could this repo worked with username.github.io/project_name

### ISSUE THREAD

**Issue by zhwang4ai** [cotes2020/jekyll-theme-chirpy#1780]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

This repo is designed to be re-named as username.github.io, could it work with username.github.io/project_name? 

How to config the URL and the baseurl variable?

### Describe the solution you'd like

None

**Comment by cotes2020** [comment]
http://www.catb.org/~esr/faqs/smart-questions.html
