### ISSUE TITLE
Menu location - located on top instead of sidebar / side menu ?

### ISSUE THREAD

**Issue by claude-cp** [cotes2020/jekyll-theme-chirpy#1784]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

I could not find any closed issue regarding this, and I'm just curiously opening this.
Feel free to close, but just a brief answer whether this is supported or will be supported would be great.

### Describe the solution you'd like

Expandable menu from the top instead of from the side. 
Either by pushing the rest of the content down, or opening on top of existing content.

### Describe alternatives you've considered

Other themes, really, but I really like this one.

**Comment by cotes2020** [comment]
Such a change completely alters the existing interaction logic, so I'm sorry to tell you that it's not going to happen.
