### ISSUE TITLE
TypeError: Failed to register a ServiceWorker for scope ('https://username.github.io/') with script ('https://username.github.io/sw.min.js'): A bad HTTP response code (404) was received when fetching the script.

### ISSUE THREAD

**Issue by seaque** [cotes2020/jekyll-theme-chirpy#1791]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

Console gives out this error, tries to find `sw.min.js` in root directory. General layout breaks.

### Steps To Reproduce

1. Generate repo from `chirpy-starter`
2. In config, make self_host enabled true.
3. In pages-deploy.yml, make submodules true.
4. Run `git submodule init` and `git submodule update`
5. Configure your basic settings accordingly (site url and base url if needed)
6. Enable GitHub pages in repo settings with sources as GitHub actions
7. Push your changes to the repo to trigger build actions
8. Go to website and open developer console

### Expected Behavior

Site showing correct layout and functionality.

### Environment

- Ruby: 3.2.2
- Jekyll: 4.3.3
- Chirpy: 7.0 ~ 7.0.1

### Anything else?

https://seaque.github.io/chirpytest/

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/45668726/36b4d6f2-f5ff-43fb-b912-f65a3ff2b4a6)

**Comment by cotes2020** [comment]
Please read Jekyll's documentation to learn how to configure `baseurl` correctly, thanks.

**Comment by seaque** [comment]
I started getting this error after pulling version 7.0 on my main blog repo, without changing anything about the base url that used to work for months. Did something changed on that? Otherwise my config is set up correctly. Website has the domain name and base url starts with a slash.

**Comment by seaque** [comment]
further help would be appreciated. I had successfully made another example but after a certain commit it broke again, and undoing the commit did not fix it. I am at lost here.

**Comment by seaque** [comment]
I hope I'll get an answer when he gets off of his high horse. Not to mention passive agressive behaviour on multiple issue's comments, treating us like idiots who can't read. I have been using this theme for years because it is just the best. But that never justifies this kind of attitude.
