### ISSUE TITLE
Some options for site.lang are incompatible with giscus API 

### ISSUE THREAD

**Issue by tripercy** [cotes2020/jekyll-theme-chirpy#1808]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Built from `jekyll-theme-chirpy`

### Describe the bug

The giscus comment system won't work if its lang option is set to default (leaving "giscus:lang:" empty in _config.yml) AND site.lang is set to a language option with a language code followed by a country code, i.e. vi-VN, en-ES.
Instead of displaying a comment section, the IFrame displays "Giscus.app refused to connect".

### Steps To Reproduce

1. Setup an app using chirpy theme in the given environment.
2. Create a sample post in that app.
3. Go to [giscus.app](https://giscus.app/) and configure a repository for comments.
4. In _config.yml, set the following configs:
```yml
lang: vi-VN
...
comments:
 provider: giscus
 ...
 giscus:
  ... // The configs obtained from https://giscus.app/
  lang: 
  ...
```
5. Build and serve the app
```sh
bundle exec jekyll s
```
6. Go to the sample post and scroll to the comment section.
7. Observe the bug: the for the comment section displays: "Giscus.app refused to connect".

### Expected Behavior

The comment section displayed correctly

### Environment

- Ruby: ruby 3.3.2 (2024-05-30 revision e5a195edf6) [arm64-darwin22]
- Jekyll: jekyll 4.3.3
- Chirpy: jekyll-theme-chirpy (7.0.1)

### Anything else?

After checking the giscus API, I noticed that the language codes for available languages never have a following country code, so the language options with the code of that type will cause the API call to fail.

**Comment by cotes2020** [comment]
Good catch 👍
