### ISSUE TITLE
run actions时bundle install locally报错

### ISSUE THREAD

**Issue by shawnyeung** [cotes2020/jekyll-theme-chirpy#184]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

今天在更新blog的时候，突然出现这个错误，我把最新的文件删除，尝试只上传老文件，问题依旧。
麻烦您帮忙看看如何解决？谢谢
![image](https://user-images.githubusercontent.com/7479612/101014132-58747a00-35a0-11eb-9713-4b3c20ed4f4f.png)
![image](https://user-images.githubusercontent.com/7479612/101014393-c91b9680-35a0-11eb-8456-57280340a78f.png)

**Comment by cotes2020** [comment]
![image](https://user-images.githubusercontent.com/11371340/101015486-7642de80-35a2-11eb-98ba-5a82bd473f8c.png)

Please keep your code up to date.

**Comment by shawnyeung** [comment]
感谢您的回复。
不过我是GitHub的小白，不知道我这种情况算不算是uptodate：我每天都在用GitHub的桌面版更新文件，除了post里面的文章一直在更新外，其他的所有文件都一直没咋动。目前我master里面的文件，就是最新的。

**Comment by cotes2020** [comment]
> 不知道我这种情况算不算是uptodate...

![image](https://user-images.githubusercontent.com/11371340/101055906-5cff5980-35c5-11eb-91d1-7e19d53515c0.png)

你已经落后 upstream 44 个 commit 了

> 不过我是GitHub的小白...

这。。。至少你要会用 git 命令吧：

- [Configuring a remote for a fork
](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork)
- [Syncing a fork
](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork)

**Comment by shawnyeung** [comment]
感谢感谢，您不指出来，我是真不知道这个   我去研究研究，再次感谢
