### ISSUE TITLE
description variable in front matter of post is not working

### ISSUE THREAD

**Issue by Swag3009** [cotes2020/jekyll-theme-chirpy#1869]
[###](url) Checklist
![Screenshot from 2024-07-23 16-18-42](https://github.com/user-attachments/assets/ddc500b5-1b9f-45d9-a444-22a99de9a84e)

In the above picture, on the left hand side, in front matter I have written description, but it's not visible in the right hand side post page. 

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

In the front matter of my blog post I am using description variable to write a description of my blog that I am writing. But the way the description is working in chirpy blog site, it is not working. It is not displaying the description at all. And in home page it is displaying the first line of the blog and not description even after mentioning it in the front matter. 

### Steps To Reproduce

Write a new blog post, write "description: My description I want to display" in the front matter. And it will not be displayed not in the blog page and in the home page. 

### Expected Behavior

In the blog page, under the title, description should be displayed with a different font other than title and blog font. In the home page, in the list of blogs, under the title of blog, description should be displayed not the first letters of blog.

### Environment

- Ruby: 
- Jekyll: 
- Chirpy:

**Comment by cotes2020** [comment]
From the style of this issue, my experience tells me that it's an invalid report. But I want to give you a chance to change my mind: can you provide some basic environment information?

**Comment by kungfux** [comment]
Please upgrade to the [version 7](https://github.com/cotes2020/jekyll-theme-chirpy/releases/tag/v7.0.0) where this feature was added.

**Comment by Swag3009** [comment]
> From the style of this issue, my experience tells me that it's an invalid report. But I want to give you a chance to change my mind: can you provide some basic environment information?

Sir, maybe because I'm not able to understand things, as I'm a beginner trying to understand jekyll and writing my first blog, this issue I'm getting. But for that reason, I tried to understand looking at your chirpy blog post markdown code and tried to copy past in my blog, it was still not working. If I am doing something wrong I'll really appreciate you pointing that out. I'll surely provide basic environment information, but I'm not able to understand what exactly you are asking, could you please explain

**Comment by Swag3009** [comment]
> Please upgrade to the [version 7](https://github.com/cotes2020/jekyll-theme-chirpy/releases/tag/v7.0.0) where this feature was added.

Is there any documentation that explains how to upgrade it? I'm trying to use video in blog post as well, it is showing error saying couldn't locate the 'embed/video.html' file... Maybe these are the features in the new version.

**Comment by kungfux** [comment]
Please check [Upgrade guide](https://github.com/cotes2020/jekyll-theme-chirpy/wiki/Upgrade-Guide)
