### ISSUE TITLE
Mermaid diagrams are rendered twice after upgrading from version 6.5.5 to 7.0.1

### ISSUE THREAD

**Issue by erikgraa** [cotes2020/jekyll-theme-chirpy#1873]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

After upgrading my starter site gem from 6.5/6.5.5 to 7.0/7.0.1, any Mermaid diagram gets rendered/presented twice.

Reverting back to 6.5.5 resolves the issue.

### Steps To Reproduce

Any post with `mermaid: true` in the front matter in version `6.5.5` will be rendered twice in version `7.0.1`

### Expected Behavior

Mermaid diagrams should only render once.

### Environment

- Ruby: ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x64-mingw-ucrt]
- Jekyll: jekyll 4.3.3
- Chirpy: jekyll-theme-chirpy (6.5.5)

**Comment by ivan-penchev** [comment]
can you upload a video of this happening, I am running mine with quite a few mermaid diagrams and see 0 issues with gem 7.0.1
