### ISSUE TITLE
Deprecation Warning: Sass's behavior

### ISSUE THREAD

**Issue by unbreakabl3** [cotes2020/jekyll-theme-chirpy#1875]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

Started to get a few of these errors when running `JEKYLL_ENV=production bundle exec jekyll serve --open-url --livereload --watch`. All the errors related to `*.scss` files.

```
Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

    ╷
99  │ ┌   .dark {
100 │ │     display: none;
101 │ │   }
    │ └─── nested rule
... │
106 │     --categories-icon-hover-color: darkslategray;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
    ╵
    /Users/user/_sass/colors/typography-light.scss 106:3  light-scheme()
    /Users/user/_sass/addon/commons.scss 7:7              @import
    /Users/user/_sass/main.scss 7:9                       @import
    main.bundle.scss 2:9                                                                                    @import
    /Users/user/assets/css/jekyll-theme-chirpy.scss 1:9   root stylesheet
```

### Steps To Reproduce

Run `JEKYLL_ENV=production bundle exec jekyll serve --open-url --livereload --watch`

### Expected Behavior

There are should not be an errors

### Environment

- Ruby: ruby 3.3.4 (2024-07-09 revision be1089c8ec) [arm64-darwin23]
- Jekyll: jekyll 4.3.3
- Chirpy: jekyll-theme-chirpy (7.0.1)
        Summary: A minimal, responsive, and feature-rich Jekyll theme for technical writing.
        Homepage: https://github.com/cotes2020/jekyll-theme-chirpy
        Documentation: https://github.com/cotes2020/jekyll-theme-chirpy/#readme
        Source Code: https://github.com/cotes2020/jekyll-theme-chirpy
        Wiki: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
        Bug Tracker: https://github.com/cotes2020/jekyll-theme-chirpy/issues
        Path: /opt/homebrew/lib/ruby/gems/3.3.0/gems/jekyll-theme-chirpy-7.0.1

**Comment by cotes2020** [comment]
Thank you for your report. I will find time to investigate this issue.

**Comment by dr34mhacks** [comment]
Facing the same error would love to know if there is any update.

**Comment by kinesis19** [comment]
I hvae same problem T.T

In my case following:
Add rouge 
```bash
gem install rouge
```
