### ISSUE TITLE
本地jekyll server运行的效果与github端不一致

### ISSUE THREAD

**Issue by cuidianjay** [cotes2020/jekyll-theme-chirpy#188]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

首先，非常感谢您的开源，让我这种博客小白也能有构建自己博客的能力。
自己调查：我看了issue里面这个#10 ，也运行了init.sh
关于 **本地jekyll server运行的效果与github端不一致**，我有两个问题：
1.本地左侧tab栏顺序与github端不一致，如下图：
  ![本地tab栏与tags图片](https://cuidianjay.github.io/assets/img/local1.png)
  ![github端tab栏与tags图片](https://cuidianjay.github.io/assets/img/remote1.png)
2.本地tags、categories里面的文章可以路由到，github端路由不到
  ![本地tags图片](https://cuidianjay.github.io/assets/img/local2.png)
  ![github端tags图片](https://cuidianjay.github.io/assets/img/remote2.png)
[这里](https://github.com/cuidianjay/cuidianjay.github.io.git)是我的代码，website文件在gh-pages分支docs目录下。

**Comment by cuidianjay** [comment]
[这里](https://cuidianjay.github.io/)是博客地址

**Comment by cuidianjay** [comment]
这里是init.sh执行图片
[init.sh结果图](https://cuidianjay.github.io/assets/img/initres.png)

**Comment by cotes2020** [comment]
Hi, 

1. 请先把你的图片链接修改好吧（目前这个状况我是没心情一个个点开图片看的 😂）

   markdown 语法展示图片是：

   ```markdown
   ![](/url/to/image)
   ```

2. 寻求问题的答案，第一步是要看项目 README 还有其他文档，而不是去翻 issue ，你列出来那个 #10 是针对远古时代 `v1.0` 之前代码，现在版本已经来到 `v2.6.2`，代码结构、使用方法都已经天翻地覆。还是那句，自我评估是小白的话，就请严格根据文档来部署操作，先别急着做文档指示以外的操作（包括移动项目文件的位置），等你读懂代码再开始玩花也不迟
