### ISSUE TITLE
Following the Getting Started Guide gives me this error

### ISSUE THREAD

**Issue by Kamek437** [cotes2020/jekyll-theme-chirpy#1880]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

I followed the chirpy guide, and when I run bash/tools.sh I got this error:
```
HEAD is now at 20987f2 chore(release): 7.0.1
Submodule 'assets/lib' (https://github.com/cotes2020/chirpy-static-assets.git) registered for path 'assets/lib'
Cloning into '/mnt/c/Users/kamek/OneDrive/Documents/Code/Websites/kamek437.github.io/assets/lib'...
Submodule path 'assets/lib': checked out 'b9c58cf485a7dcbc833e698d67dd1850bdc93eb3'
npm warn deprecated read-pkg-up@11.0.0: Renamed to read-package-up

added 706 packages, and audited 886 packages in 5m

143 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> jekyll-theme-chirpy@7.0.1 build
> concurrently npm:build:*

/mnt/c/Users/kamek/OneDrive/Documents/Code/Websites/kamek437.github.io/node_modules/yargs/build/index.cjs:1
{const i=new te(t,e,s,de);return Object.defineProperty(i,"argv",{get:()=>i.parse(),enumerable:!0}),i.help(),i.version(),i}),argsert:h,isPromise:f,objFilter:g,parseCommand:o,Parser:fe,processArgv:b,YError:e};module.exports=ue;
                                                                                                                          ^

SyntaxError: Unexpected token ')'
    at wrapSafe (node:internal/modules/cjs/loader:1427:18)
    at Module._compile (node:internal/modules/cjs/loader:1449:20)
    at Module._extensions..js (node:internal/modules/cjs/loader:1588:10)
    at Module.load (node:internal/modules/cjs/loader:1282:32)
    at Module._load (node:internal/modules/cjs/loader:1098:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
    at Module.require (node:internal/modules/cjs/loader:1304:12)
    at require (node:internal/modules/helpers:123:16)
    at Object.<anonymous> (/mnt/c/Users/kamek/OneDrive/Documents/Code/Websites/kamek437.github.io/node_modules/yargs/index.cjs:5:30)

Node.js v22.5.1
```
I am running Arch Linux via WSL2.
ruby -v 3.1.3
node -v Node.js v22.5.1
uname -a Linux Spellbook 6.8.11-locietta-WSL2-xanmod1

### Steps To Reproduce

Fork it on github as per guide. git clone your fork of chirpy. cd chirpyfork bash tools/init.sh

### Expected Behavior

Site to build and be ready to push to github pages for my site.

### Environment

- Ruby: 
- Jekyll: 
- Chirpy: 
ruby 3.3.4 (2024-07-09 revision be1089c8ec) [x86_64-linux]
jekyll 4.3.3
jekyll-theme-chirpy (7.0.1)
node -v v22.5.1

### Anything else?

Am I doing something wrong? I really want to use this the design is awesome!

**Comment by cotes2020** [comment]
In the beginning, you chose `chirpy-starter` for "How did you create the site?", but in "Steps To Reproduce", you mentioned using fork. Please do not waste the project maintainers' time and use the Starter to create your site.

**Comment by Kamek437** [comment]
I might have missclicked I forked it.
