### ISSUE TITLE
点击 Categories 和 Tags 页面的内容找不到

### ISSUE THREAD

**Issue by flykyle** [cotes2020/jekyll-theme-chirpy#19]
在 Mac 上运行 Jekyll serve，在本地查询预览。
点击 Categories 和 Tags 页面的内容找不到。

**Comment by cotes2020** [comment]
请先阅读一下 README

**Comment by flykyle** [comment]
我按照 README 重新执行了一遍，还是一样的问题

**Comment by cotes2020** [comment]
把你的仓库贴出来

**Comment by flykyle** [comment]
我的仓库地址是： https://github.com/flykyle/flykyle.github.io

运行 bash tools/run.sh 提示的是下面的错误：

tools/run.sh: line 15: realpath: command not found
usage: dirname path
usage: dirname path

**Comment by cotes2020** [comment]
😂流程都没跑通就说‘执行了一遍’，那你要给本地机器安装`realpath`阿

**Comment by flykyle** [comment]
执行 brew install coreutils，现在可以了。
