### ISSUE TITLE
Duplicate headers (SEO)

### ISSUE THREAD

**Issue by AvaPL** [cotes2020/jekyll-theme-chirpy#1907]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

First of all - thank you for creating an maintaining Chirpy! I really love it.

I’ve noticed a few SEO-related issues that might impact page indexing, and I wanted to share them.

Scan of my page resulted in:
- `h1` duplicates because the page title is put in `h1` tag and it appears on every page in the sidebar - because of that, posts might be treated as duplicates despite having different titles
- similar issue with `h2`, because "Recently Updated" and "Trending Tags" are `h2`
- `</html>`, `</head>`, `</body>` closing tags are missing in the page source

### Describe the solution you'd like

Headers probably shouldn't be used for common components that appear on every page. They should only be used for the contents of posts.

Closing tags - of course the solution is to add them :)

**Comment by cotes2020** [comment]
> ...
> * `h1` duplicates because the page title is put in `h1` tag and it appears on every page in the sidebar - because of that, posts might be treated as duplicates despite having different titles
> * similar issue with `h2`, because "Recently Updated" and "Trending Tags" are `h2`

There is considerable debate online about whether the uniqueness of `<H1>` tags should be maintained, but so far, there are no authoritative documents confirming that multiple `<H1>` tags have a negative impact on SEO performance. 

I'm open to this, so if you'd like to replace these seemingly redundant `<H1>` tags, feel free to submit a PR.

> ...
>  * `</html>`, `</head>`, `</body>` closing tags are missing in the page source

These tags can be omitted, as the W3C specifications explain in detail.
