### ISSUE TITLE
npm related vs-code tasks in the template. should they be removed?

### ISSUE THREAD

**Issue by virzak** [cotes2020/jekyll-theme-chirpy#1930]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

For someone who is new to this project I found that tasks like `Build JS (watch)` in tasks.json need me to bring files from the theme

### Steps To Reproduce

- Create a project from template and open in VS Code
- Run VS Code task `Build JS (watch)`

### Expected Behavior

Expected to not encounter an error, but instead got something like npm isn't installed.

### Environment

```sh
vscode ➜ /workspaces/docs (jekyll) $ ruby -v
ruby 3.3.4 (2024-07-09 revision be1089c8ec) [x86_64-linux]
vscode ➜ /workspaces/docs (jekyll) $ bundle exec jekyll -v
/usr/local/rvm/gems/default/gems/jekyll-4.3.3/lib/jekyll.rb:28: warning: csv was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add csv to your Gemfile or gemspec. Also contact author of jekyll-4.3.3 to add csv into its gemspec.
/usr/local/rvm/gems/default/gems/safe_yaml-1.0.5/lib/safe_yaml/transform.rb:1: warning: base64 was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add base64 to your Gemfile or gemspec. Also contact author of safe_yaml-1.0.5 to add base64 into its gemspec.
jekyll 4.3.3
vscode ➜ /workspaces/docs (jekyll) $ bundle info jekyll-theme-chirpy
  * jekyll-theme-chirpy (7.1.0)
        Summary: A minimal, responsive, and feature-rich Jekyll theme for technical writing.
        Homepage: https://github.com/cotes2020/jekyll-theme-chirpy
        Documentation: https://github.com/cotes2020/jekyll-theme-chirpy/#readme
        Source Code: https://github.com/cotes2020/jekyll-theme-chirpy
        Wiki: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
        Bug Tracker: https://github.com/cotes2020/jekyll-theme-chirpy/issues
        Path: /usr/local/rvm/gems/default/gems/jekyll-theme-chirpy-7.1.0
```

**Comment by cotes2020** [comment]
Indeed, some unnecessary `tasks` are exported to the starter repository.

**Comment by cotes2020** [comment]
The vscode tasks in starter repository got fixed, thanks for the report.

https://github.com/cotes2020/chirpy-starter/commit/6ae78258092c8e1b1b30f53bbc9ce8ba98703e78#diff-7d76d7533653c23b753fc7ce638cf64bdb5e419927d276af836d3a03fdf1745a
