### ISSUE TITLE
Add costum JAVASCRIPT

### ISSUE THREAD

**Issue by quickplaymobile** [cotes2020/jekyll-theme-chirpy#1946]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

Can't add external html into head

### Describe the solution you'd like

I'm using GitHub actions and I don't have a full dev environment and I would like to add google ads to my site. It requests pasting a js link into the head.

**Comment by cotes2020** [comment]
It's a feature that's been around for 1 year:
-  #1015

**Comment by quickplaymobile** [comment]
> It's a feature that's been around for 1 year:
> 
> * [feat: allow users to define custom metadata #1015](https://github.com/cotes2020/jekyll-theme-chirpy/pull/1015)

It's not working for some reason. Here have a look: https://github.com/quickplaymobile/quickplaymobile.github.io/blob/main/_includes/metadata-hook.htm
