### ISSUE TITLE
Built a Docker image that can directly run Chirpy.

### ISSUE THREAD

**Issue by liuzhaoze** [cotes2020/jekyll-theme-chirpy#1962]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

No.

### Describe the solution you'd like

I built a Docker image that includes the development environment needed to run Chirpy. This should help in running the website locally more quickly. I uploaded the image to [DockerHub](https://hub.docker.com/r/liuzhaoze/chirpy-build) and described the usage in the Repository overview. Any suggestion on my work is welcome. If it can help others, I would be happy to have my [image repository](https://hub.docker.com/r/liuzhaoze/chirpy-build) mentioned here: <https://chirpy.cotes.page/posts/getting-started/#setting-up-the-environment>.

**Comment by kungfux** [comment]
If the intent of the Docker image is to provide a development environment, [Devcontainer](https://chirpy.cotes.page/posts/getting-started/#using-dev-containers-recommended-for-windows) works well for this purpose and is already included in the repository and documentation. JFYI.

**Comment by liuzhaoze** [comment]
Got it, thanks for the reminder and your reply!
