### ISSUE TITLE
Mobile view burger Icon to show menu is not working sometimes

### ISSUE THREAD

**Issue by koppor** [cotes2020/jekyll-theme-chirpy#1963]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

Click on mobile burger does not do anything:

![image](https://github.com/user-attachments/assets/6dac3d31-51d2-4d0a-94d8-3feac2f687c4)

```
Uncaught TypeError: document.getElementById(...) is null
    <anonymous> https://blog.jabref.org/assets/js/dist/post.min.js:4
    <anonymous> https://blog.jabref.org/assets/js/dist/post.min.js:4
```

![image](https://github.com/user-attachments/assets/67ec654b-e237-45dc-8463-3b5fc5dab9c4)

### Steps To Reproduce

1. Open https://blog.jabref.org/2024/09/18/JabCon24/
2. Shrink browser size
3. Click on burger menu

### Expected Behavior

Burger menu opens

### Environment

- Ruby: 3.3 - Source: https://github.com/JabRef/blog.jabref.org/blob/main/.github/workflows/pages-deploy.yml
- Jekyll: ?
- Chirpy: 7.1 - Source: https://github.com/JabRef/blog.jabref.org/blob/main/Gemfile

### Anything else?

Follow-up to https://github.com/cotes2020/jekyll-theme-chirpy/issues/1025

**Comment by cotes2020** [comment]
Hi,

> ### Steps To Reproduce
> 
> 1. Open https://blog.jabref.org/2024/09/18/JabCon24/
> ...

Can you provide the steps to reproduce the error using the code in this repository?

**Comment by koppor** [comment]
> Hi,
> 
> > ### Steps To Reproduce
> > 
> > 1. Open https://blog.jabref.org/2024/09/18/JabCon24/
> > ...
> 
> Can you provide the steps to reproduce the error using the code in this repository?

This will take some hours. I will try!

**Comment by subhramit** [comment]
> Can you provide the steps to reproduce the error using the code in this repository?

Hi Cotes, I am a JabRef developer. I managed to pinpoint the issue to the `toc` configuration and made minimum working examples:
**Buggy:** https://github.com/subhramit/chirpy-mwe-buggy
**Non-buggy:** https://github.com/subhramit/chirpy-mwe-ok

Difference:
The page must have a "`##`" heading tag. Now, if the following `toc` config flag is set to `true`, then there is no issue:
https://github.com/cotes2020/jekyll-theme-chirpy/blob/93f616b25d7ed6c4f090c50c8663f8c1f59947f4/_config.yml#L107-L108

However, when it is set to false, the hamburger menu doesn't work.
It is as if the presence of toc is required for the hamburger menu to work, which is a strange association:
![image](https://github.com/user-attachments/assets/77a0083f-05df-4b31-ad20-3ab8c694091e)

More details:
On the buggy pages, when the page opens, we observe the following error on inspecting:
![image](https://github.com/user-attachments/assets/4e4550cd-fd81-4ecf-92b6-3d64b86fa43a)
Which comes from the part marked "2" in the following code from `post.min.js`:
![image](https://github.com/user-attachments/assets/0ab6b7a3-c47f-4d98-b595-62f5a99bf8e3)
Part "1" bugs out when we click the hamburger menu (as described in the issue description).

It is as if the following section (in post.min.js`) is trying to initialize the headings into a toc element that does not exist (in the buggy version with toc flag set to false):
```
document.querySelector("main h2, main h3") && (tocbot.init({
    tocSelector: "#toc",
    contentSelector: ".content",
    ignoreSelector: "[data-toc-skip]",
    headingSelector: "h2, h3, h4",
    orderedList: !1,
    scrollSmooth: !1
}),
document.getElementById("toc-wrapper").classList.remove("d-none"))
```

I hope this helps!
