### ISSUE TITLE
Page is broken on mobile.

### ISSUE THREAD

**Issue by DrPleaseRespect** [cotes2020/jekyll-theme-chirpy#197]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [x] I found the bug on the latest code of `master` branch.

## Describe the bug

The sidebar is broken on mobile
The Page buttons are also broken on mobile

### To Reproduce

1. Go to chirpy.cotes.info on Realme 3.
2. Notice the missing sidebar button.
3. Be Sad
### Expected behavior

I expected it to have a sidebar and the page buttons be arranged properly
### Screenshots

![Without Desktop Site Option Enabled](https://i.imgur.com/HAfOFe9.png)
![With Desktop Site Option Enabled](https://i.imgur.com/QkVsnkx.png)
![Expected Results](https://i.imgur.com/RsOYbfD.png)

### Software

- Ruby version: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu] 
- Gem version: 3.1.2 
- Bundler version: Bundler version 2.1.4 
- Jekyll version: jekyll (4.1.1) 

### Smartphone

Device: Realme 3 Model RMX1821
OS: Android 9
Browser: Chrome Beta 88.0.4324.38 and Firefox 83.1.0 (Build #2015776403)

**Comment by cotes2020** [comment]
Hi,

Could you pleas  modify this report so that the pictures can be displayed directly？

```diff
- [img_description](imge_url)
+ ![img_description](imge_url)
```

**Comment by cotes2020** [comment]
It seems that the browser's PWA cache is not working properly. Clear your browser cache and it will display properly.
