### ISSUE TITLE
Add child items for sidebar tabs

### ISSUE THREAD

**Issue by Grahmification** [cotes2020/jekyll-theme-chirpy#1979]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

This theme is excellent! However, I've started to find the sidebar tabs rather limiting as I'd like to add a lot of custom pages. Adding the ability to nest tabs (even one layer deep) would be incredibly useful for de-cluttering all the sidebar tabs. This functionality would allow me to extend Chirpy into an extremely customizable website platform. 

### Describe the solution you'd like

I think the easiest way to implement this would be in the markdown header for a given file in the `/_tabs/` folder. I imagine adding something like this (from [categories.md](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/_tabs/categories.md)):

```markdown
layout: categories
icon: fas fa-stream
order: 1
children: [archives, tags]
```

The code in [sidebar.html](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/_includes/sidebar.html) could then be updated. If the tab has children:
- Add an expanding arrow `<i class="fas fa-fw fa-angle-down"></i>` and a collapsed user list `<ul class="collapse">`
- Populate the list with any children
- Clicking the arrow would expand the user list and show the child items

I tried to implement this but ran into problems which I believe are due to the sass code (it didn't want to highlight the active tab for any children). The core sass code on this website is pretty complex and it seemed like it would be extremely easy to break other features unintentionally by tweaking it.

One other thing worth noting is that it might be necessary to identify child markdown files with a special header tag so the primary loop doesn't add them to the top level. Another option could be to put tab children in a separate folder (ex. /_tab_child/). 

### Describe alternatives you've considered

This could also be implemented by having only a few side tabs and then putting the links inside the custom webpages. I think it would still be much cleaner to have nested tab functionality. 

### Additional context

I wouldn't worry about full recursion with this feature unless it's really easy to add. Nesting sidebar tabs one layer deep would add so much functionality! It's unlikely that most people would need more than one layer.

**Comment by cotes2020** [comment]
Thank you for reaching out! This feature is more commonly found on user manual-type websites, while the focus of this project is a blog system. The sidebar tabs do not need to incorporate this complex interaction. To avoid making the project bloated, I won't consider adding this feature.
