### ISSUE TITLE
Add rel="canonical" support

### ISSUE THREAD

**Issue by stemarks** [cotes2020/jekyll-theme-chirpy#1984]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

I can't link reposts of articles I wrote elsewhere 

### Describe the solution you'd like

Add an option to the metadata for canonical links to enable reposting of content I have created elsewhere.

**Comment by kungfux** [comment]
@stemarks Please refer to [jekyll-seo-tag documentation](https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/advanced-usage.md#setting-customized-canonical-url) as this possibility seems to be available already.
