### ISSUE TITLE
Add the ability to override the HTML/SEO title on a per-post basis to help with SEO

### ISSUE THREAD

**Issue by seanthegeek** [cotes2020/jekyll-theme-chirpy#1996]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

Search engines use the value of the HTML title as the title for the search result, so this header is often referred to as the SEO title. Currently, the HTML title for a post is always `post title | site name`. This is a problem for Search Engine Optimization (SEO), because it is often ideal to have a catchy SEO title that is shorter than the post title, [as explained in MSDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title#page_titles_and_seo).

> The contents of a page title can have significant implications for search engine optimization ([SEO](https://developer.mozilla.org/en-US/docs/Glossary/SEO)). In general, a longer, descriptive title performs better than short or generic titles. The content of the title is one of the components used by search engine algorithms to decide the order in which to list pages in search results. Also, the title is the initial "hook" by which you grab the attention of readers glancing at the search results page.

### Describe the solution you'd like

Allow the entire HTML title tag to be completely overwritten on a per-post basis by using a `seo_title` value in the Front Data.

### Additional context

I already created a PR for this before noticing the Contribution Guide because it is a very simple change. Sorry about that. Let me know if I need to do anything else.

https://github.com/cotes2020/jekyll-theme-chirpy/pull/1993

**Comment by kungfux** [comment]
IMHO, I would expect to see a page with the same title I clicked on in the search results. What prevents us from following the recommendation and using a descriptive title? It looks like you want to change the format of the title, not introduce a separate front matter parameter. However, I wonder if the pipe in the title is really a problem for search engines?

**Comment by seanthegeek** [comment]
Never mind. I was mainly looking for a feature set matching Yoast SEO and other WordPress plugins.  Looking deeper into it, even Yoast [doesn't recommend](https://yoast.com/whats-the-difference-between-an-h1-heading-and-the-seo-title/) having separate titles, even though it can do it. I just need to work on making my titles shorter. 😅

>
