### ISSUE TITLE
toc to be initially all unfolded without any animation effects

### ISSUE THREAD

**Issue by wa008** [cotes2020/jekyll-theme-chirpy#1998]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Built from `jekyll-theme-chirpy`

### Describe the bug

I have check [previous discussion](https://github.com/cotes2020/jekyll-theme-chirpy/discussions/1706) about this topic, But code `_javascript\modules\components\toc.js` have move to `_javascript/modules/components/toc/toc-desktop.js` and `_javascript/modules/components/toc/toc-mobile.js`.

So, I change the below code, But it doesn't work.

https://github.com/wa008/wa008.github.io/blob/f08f0ee777279955d5059bcc95bd64f4ade7f5a6/_javascript/modules/components/toc/toc-desktop.js#L3-L11

demo: https://informal.top/posts/try-of-torchview-to-accelerate-finetune-new/

### Steps To Reproduce

1. change code as https://github.com/wa008/wa008.github.io/blob/f08f0ee777279955d5059bcc95bd64f4ade7f5a6/_javascript/modules/components/toc/toc-desktop.js#L3-L11
2. result doesn't work

### Expected Behavior

toc to be initially all unfolded without any animation effects

### Environment

Jekyll: github pages, code: https://github.com/wa008/wa008.github.io/blob/main/.github/workflows/pages-deploy.yml

### Anything else?

Thanks for your project!!

**Comment by cotes2020** [comment]
Hi, as mentioned in the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md#reporting-a-bug), we don't have the energy to maintain a user's forked distribution.

> Chirpy is an open-source project, but that doesn't mean we will maintain other specific forks (such as yours).
