### ISSUE TITLE
I need some help for use your jekyll theme chirpy

### ISSUE THREAD

**Issue by eprj453** [cotes2020/jekyll-theme-chirpy#20]
I have some problem for using your Jekyll theme chirpy. I forked your Repository and changed variable in _config.yml

![20200111_224133](https://user-images.githubusercontent.com/52685258/72205191-9c135080-34c3-11ea-99aa-76a22d903936.png)

url: 'https://eprj453.github.io'

eprj453 is my gibhub name. and added remote-theme variable like this

![20200111_224150](https://user-images.githubusercontent.com/52685258/72205195-a1709b00-34c3-11ea-8807-b71e125c1cf4.png)

remote-theme: cotes2020/jekyll-theme-chirpy 

then I accessed my GitHub.io and it worked.I can see and approach your demo post and my post at home(main page).But I can access to post with categories and tags. It raised 404 error.

I think I should built categories and tags in _config.yml or something else but can approach with categories and tag in your demo site, so it makes me confused.I search for google lots of time but I can’t find reasonable answer.

I hope your reply. thank you

**Comment by cotes2020** [comment]
Please checkout the `README` first,  you don't have to wast times in Google.

**Comment by Pinnaclenetworking** [comment]
i have a smal issue i cant overcome.... i've figured most things out so far.... (im sure im working long hand for most things but it works for me.... the only thing i can figure out is how to get a new PAGE to add the the tabs on the left.... i created a page called HelpDesk and put it in the _sites folder where the others are.... and also in the TABs folder as well (not knowing where it should be) and its not adding.... my site is located here https://pinnaclenetworking.com i can see the page when i go http://pinnaclenetworking.com/tabs/HelpDesk/ so i know i created it right.... any ideas?

**Comment by achyutap** [comment]
How can I use Chirpy theme in github
