### ISSUE TITLE
TOC should be shown on non-post pages, too

### ISSUE THREAD

**Issue by koppor** [cotes2020/jekyll-theme-chirpy#2015]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

The TOC is shown on posts. The TOC is not shown on non-posts.

Example:

- Page as "layout: default": https://koppor.github.io/chirpy-toc-demo/test/ - source: https://github.com/koppor/chirpy-toc-demo/blob/main/_tabs/test.md\
    ![image](https://github.com/user-attachments/assets/9c5cb1d0-e0bf-4526-8df0-30f36c864276)
- Page as blog post: https://koppor.github.io/chirpy-toc-demo/test/ - source: https://github.com/koppor/chirpy-toc-demo/blob/main/_posts/2024-10-28-test.md\
    ![image](https://github.com/user-attachments/assets/59597435-c0da-4759-91a3-3b9dff1194b2)
- Source repository: https://github.com/koppor/chirpy-toc-demo

### Describe the solution you'd like

TOC should be shown on non-posts, too.

**Comment by koppor** [comment]
Workaround:

1. Use `_posts`
2. Add to `_tags` the pages one wants to have rendered with the same name as the post would generate
3. Change `permalink` of posts to `:title/`
4. At `collections:` set `output: false` for `tabs`

Result for out page:

![image](https://github.com/user-attachments/assets/b2f95a81-5639-4cdc-bbbf-e9b438979175)

**Comment by cotes2020** [comment]
Hi @koppor, thank you for your suggestion. we understand the reason behind your request, but due to we don't plan to mix up the layouts of `page`s and `post`s, so we won't be considering the implementation of this feature.
