### ISSUE TITLE
PR for checkbox possible?

### ISSUE THREAD

**Issue by alexandra-zaharia** [cotes2020/jekyll-theme-chirpy#202]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There are no similar request on existing issues (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

At the moment if I create an unordered list in my Markdown post with the github markdown syntax for checkboxes (`- [ ]`), the list item bullet is displayed and it is touching the checkbox. It's not very pleasing on the eye. :-)

## Describe the solution you'd like

I would like to be able to write blog posts and be able to use the github markdown syntax for checkboxes (`- [ ]` or `* [ ]` for todo and `- [x]` or `* [x]` for done). 

## Describe alternatives you've considered

I would like to submit a pull request to implement this solution if this is OK with you. It consists in:
* adding a checkbox add-on style in `assets/css/_addon`
* modifying the post layout to replace `<li>[ ]` and `<li>[x]` items in the `post-content` div with the checkbox style defined in the previous file
* modifying `main.scss` in `assets/_addon` to import the new checkbox add-on style

## Additional context

If it's OK with you I can submit the PR.

**Comment by cotes2020** [comment]
Hi @alexandra-zaharia,

Thanks for reminding me of the checkbox style, but can you show a screenshot of the modified checkbox?

**Comment by alexandra-zaharia** [comment]
Of course, here are the screenshots.

Old style:
![checkbox_old_style](https://user-images.githubusercontent.com/7894916/101951522-6d33bc00-3bf7-11eb-97fd-2d747d80f45a.png)

New style:
![checkbox_new_style](https://user-images.githubusercontent.com/7894916/101951519-6c9b2580-3bf7-11eb-8fa2-966733d633e8.png)

PS: oops, I said something false in the description -- my bad! I thought brackets are not rendered as checkboxes but in fact they are (I must have mis-typed when testing). I will edit the issue description now.

**Comment by cotes2020** [comment]
Looks great 👍!  Don't hesitate to submit a PR.
