### ISSUE TITLE
After forced reload of the page, normal reload should show the same page content

### ISSUE THREAD

**Issue by koppor** [cotes2020/jekyll-theme-chirpy#2020]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

(This might be an exceptional situation when using the `default` template for `index.md`)

I have updated the main page of my repository. When loading, it shows the old content. When pressing <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd>, then it shows the new content. When reloading again (<kbd>Ctrl</kbd>+<kbd>R</kbd>), it shows the old content.

### Describe the solution you'd like

After a forced reload, the storages of chirpy should be refreshed.

This helps other users not knowledable of the "Storage" conept of browsers.

### Describe alternatives you've considered

I deleted "Cache Storage" -> page -> "chiirpy-" manually in the browser - works.

### Additional context

Not sure whether this is is a browser issue not clearing everything on force reload of the page.

**Comment by cotes2020** [comment]
Hi, it looks like you haven't read the [FAQ](https://github.com/cotes2020/jekyll-theme-chirpy/wiki/FAQ) on PWA caching, if you have PWA enabled, the site will pop up an update notification window for the client's web page after redeployment.

**Comment by koppor** [comment]
@cotes2020 Thank you for your patience and taking care of all of this!
