### ISSUE TITLE
Issue displaying the new twitter X logo, either it shows nothing or the old logo, please help !

### ISSUE THREAD

**Issue by retr0-1ntell0** [cotes2020/jekyll-theme-chirpy#2025]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Built from `jekyll-theme-chirpy`

### Twitter X new Logo Issue

Here is a sample of my `contact.yml` file. This is not the only form I have tried. I have also tried other logo like the [following](https://fontawesome.com/icons/square-x-twitter?f=brands&s=solid), but still did not get any result. This is the last format that at least keep the space and shows the links but without logo.
```yml 
  type: twitter
  icon: 'fab fa-x-twitter'
```
The icon reference was taken from the following [link](https://fontawesome.com/icons/x-twitter?f=brands&s=solid). I followed the nomenclature and also tried different variant as suggested in previous issues but it kept on showing the old logo. I was wondering if there was a fix for that. Because as shown in the image below, after all trials and error the logo is still not being displayed.

![image](https://github.com/user-attachments/assets/2491e44c-3a76-4cfd-9d58-853b8f86837c)

Thanks for reading me and willing to help out.

### Steps To Reproduce

1. Modify the `contact.yml` twitter icon with the new X logo
2. run it locally `bundle exec jekyll s`
3. Icon not being displayed at all, but old one still being displayed

### Expected Behavior

After updating the logo in the `contact.yml` file the logo should be able to change and look as the logo shown in the following [link](https://fontawesome.com/icons/x-twitter?f=brands&s=solid). But nothing happens.

### Environment

Here is my development environment:
- Ruby: ruby 3.3.5
- Jekyll: jekyll 4.3.4
- Chirpy: jekyll-theme-chirpy (5.6.1)

**Comment by kungfux** [comment]
Works as expected with Chirpy 7.1.1 using default configuration:

```yml
 - type: twitter
   icon: "fa-brands fa-x-twitter"
```

Perhaps the problem is specific to older versions of Chirpy. Would you consider upgrading?

**Comment by retr0-1ntell0** [comment]
I did'ntt think of updating the theme. Works fine and thanks for your fast reply. I did not even have to change my syntax just the update was sufficient. Thank you !

Here is the test result. Problem solved !

![image](https://github.com/user-attachments/assets/36197e12-096a-4dba-afa6-d144aad250f2)
