### ISSUE TITLE
Automatically Generate ASCII URLs

### ISSUE THREAD

**Issue by WangSimiao2000** [cotes2020/jekyll-theme-chirpy#2026]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

Currently, Jekyll's Chirpy theme does not automatically generate ASCII URLs for post titles that contain non-ASCII characters (e.g., Chinese characters). This can lead to URLs that are difficult to read and less SEO-friendly, which may hinder the accessibility and shareability of the content.

### Describe the solution you'd like

I would like to see an option that automatically converts non-ASCII characters in post titles into ASCII format when generating URLs. For example, if the article title is "你好，世界", the generated URL should be "ni-hao-shijie". This feature would greatly improve the user experience and search engine optimization of the site.

**Comment by cotes2020** [comment]
The URL is defined according to the name of your file, please name the file with English letters.
