### ISSUE TITLE
Comment via LinkedIn

### ISSUE THREAD

**Issue by RuffaloLavoisier** [cotes2020/jekyll-theme-chirpy#2044]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

None

### Describe the solution you'd like

I would like to request the ability to leave comments using LinkedIn login, similar to how comments can be posted using GitHub login.

### Describe alternatives you've considered

I can't think of any ideas on how to keep comment records. Or are there any existing alternative solutions??

**Comment by cotes2020** [comment]
Hi there,

Unless you can find a commenting system that supports LinkedIn login, this feature will not be implemented.
