### ISSUE TITLE
Is there support to add a timeline of events?

### ISSUE THREAD

**Issue by g14a** [cotes2020/jekyll-theme-chirpy#205]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [ ] My question is based on the latest code of `master` branch.

## Description

Is there support to add a timeline of events like professional experience over the years?

**Comment by cotes2020** [comment]
I am not sure what effect you want, can you provide pictures to express it?

**Comment by g14a** [comment]
Something like this.

https://raw.githubusercontent.com/lukas-h/jekyll-timeline/master/screenshot.png

**Comment by cotes2020** [comment]
Currently this theme does not have this layout.
