### ISSUE TITLE
keep Title consistent with filename.

### ISSUE THREAD

**Issue by DeanLemans** [cotes2020/jekyll-theme-chirpy#2051]
### Checklist
- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?
Generated from `chirpy-starter`

### Describe the bug
keep Title consistent with filename.

right now only the first letter is capitalized in the Title, 
(please see screenshot for further clarity)

### Steps To Reproduce
1. create a .md file that with the filename "CV"
2. see Title that title name is Cv
3. be annoyed
4. report [issue](https://github.com/cotes2020/jekyll-theme-chirpy/issues/2051)
![Cv _ Dean's Site — Ablaze Floorp](https://github.com/user-attachments/assets/8faed600-c550-4f59-9264-4f5a9dcf9347)

### Expected Behavior
I expect the title of the page to stay consistent with the filename.

(the tab name could also be adjusted to be the same as the filename, but I dont want to make 2 issues)

### Environment
github actions

### Anything else?
you can see it happening in the CV tab on my fork https://deanlemans.github.io/CV/

**Comment by kungfux** [comment]
Files have their own naming conventions, so this is not possible. Instead, you can use the `title` parameter to specify the page title, while keeping the filename as simple as `cv.md`:

```markdown
---
# the default layout is 'page'
title: CV
icon: fas fa-info-circle
order: 2
---
```

**Comment by DeanLemans** [comment]
why isnt
```
title: >text<
```
included in the default front matter?

**Comment by kungfux** [comment]
This is because the built-in tabs are designed differently to support multiple languages.
Their titles are defined in the [data/locales](https://github.com/cotes2020/jekyll-theme-chirpy/tree/master/_data/locales) files.
