### ISSUE TITLE
希望能为表格添加滚动条

### ISSUE THREAD

**Issue by J-StrawHat** [cotes2020/jekyll-theme-chirpy#206]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There are no similar request on existing issues (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

当markdown表格的宽度较长的时候，英文文字或者是行内代码就会自动换行了，会影响平时的阅读体验。🥴
![现在的问题](https://gitee.com/j__strawhat/MyImages/raw/master/img/20201212200400.png)

## Describe the solution you'd like

希望作者大大能为markdown表格的样式添加滚动条。
类似于下图这样的滚动条，不过不需要太粗😁，像本主题的代码块上的小滚动条就好了~
![比如这样](https://gitee.com/j__strawhat/MyImages/raw/master/img/20201212200829.png)

**Comment by cotes2020** [comment]
提议不错，有空会跟进

**Comment by cotes2020** [comment]
@J-StrawHat 应该OK了

**Comment by J-StrawHat** [comment]
很棒，谢谢作者大大:smile:

**Comment by z2p** [comment]
我的场景相反，我并不希望变成滚动，想换行展示，请问有方法可以配置吗？
