### ISSUE TITLE
Shimer effect stays even after images loaded after upgrading to Chirpy 7.2.0

### ISSUE THREAD

**Issue by seanthegeek** [cotes2020/jekyll-theme-chirpy#2068]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

The shimmer effect stays even after the images have loaded

### Steps To Reproduce

Occurred after upgrading to Chirpy 7.2.0 

### Expected Behavior

The shimmer effect should stop once the image it loaded

### Environment

- Ruby: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-gnu]
- Jekyll: 4.3.4
- Chirpy: 7.2.0

### Anything else?

By blog: [seanthegeek.net](https://seanthegeek.net/)
GitHub repo: https://github.com/seanthegeek/seanthegeek.github.io

**Comment by seanthegeek** [comment]
Uncaught ReferenceError: Theme is not defined
    at home.min.js:4:48327
    at home.min.js:4:51505

**Comment by jamalin** [comment]
I'm also experiencing this just recently (with chirpy-starter). My last post was 24 days ago and everything was fine then. Images are loaded but the shimmering persists. I've also noticed that the "content" section on the right pane is not showing anything.

**Comment by SoumyaK4** [comment]
The reason 
https://github.com/cotes2020/jekyll-theme-chirpy/issues/2066

**Comment by SoumyaK4** [comment]
@seanthegeek @jamalin 
Till the bug is fixed if you want to use Chirpy just leave `theme_mode: ` in `_config.yml`
If you set `theme_mode: dark` or `theme_mode: light` these problems occur

**Comment by seanthegeek** [comment]
I just downgraded to 7.1.1 by pinning the version to in the `gemfile` until this is fixed, because I `theme_mode` to remain set to `dark`. I'm going to keep the version pinned at a known good version from now on. It was using `>=7.1.1`, so my site got unexpectedly upgraded to 7.2.0 when I made a change to a page and GitHub Pages deployed my site.

**Comment by SoumyaK4** [comment]
Yeah specifying the version doesn't auto upgrade @seanthegeek 
You can always keep it that way.
And whenever a new version comes just test it locally before upgrading

**Comment by kungfux** [comment]
Thank you for reporting. Let me keep the discussion in one place and close this in favour of #2066.
