### ISSUE TITLE
Table of contents is blank after upgrading to Chirpy 7.2.0

### ISSUE THREAD

**Issue by seanthegeek** [cotes2020/jekyll-theme-chirpy#2069]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

The table of contents area is blank

### Steps To Reproduce

Upgrade to Chirpy 7.2.0

### Expected Behavior

The table of content should be generated.

### Environment

- Ruby: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-gnu]
- Jekyll: 4.3.4
- Chirpy: 7.2.0

### Anything else?

By blog: [seanthegeek.net](https://seanthegeek.net/)
GitHub repo: https://github.com/seanthegeek/seanthegeek.github.io

**Comment by seanthegeek** [comment]
Uncaught ReferenceError: Theme is not defined
    at home.min.js:4:48327
    at home.min.js:4:51505

**Comment by SoumyaK4** [comment]
The reason 
https://github.com/cotes2020/jekyll-theme-chirpy/issues/2066

**Comment by kungfux** [comment]
Thank you for reporting. Let me keep the discussion in one place and close this in favour of #2066.
