### ISSUE TITLE
PR #203 breaks the archives view

### ISSUE THREAD

**Issue by alexandra-zaharia** [cotes2020/jekyll-theme-chirpy#207]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [x] I found the bug on the latest code of `master` branch.

## Describe the bug

Commit ccd51f0bdfb48ae3d075ddda7ca7c9adcedb2aab (my merged PR #203 :sob:) breaks the Archives view:
* years except for the first one (in reverse-chronological order) have an unnecessary indent to the right
* every entry in the archive is indented to the right by the same amount

### To Reproduce

1. Update up to faulty commit ccd51f0bdfb48ae3d075ddda7ca7c9adcedb2aab
2. `serve` locally
3. Click on the Archives tab

### Expected behavior

The Archives view should be unaffected.

### Screenshots

Here is how the archives look now:
![archives_bug](https://user-images.githubusercontent.com/7894916/101990532-aaf01d80-3ca7-11eb-98b6-951e8eae0ce6.png)

### Software

- Ruby version:  ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
- Gem version:  3.1.4
- Bundler version:  2.1.4
- Jekyll version:  4.1.1

**Comment by cotes2020** [comment]
😂 Thanks for the report, it should be OK now

**Comment by alexandra-zaharia** [comment]
Yes, perfect! :+1: Thanks and sorry for the botched commit...

**Comment by cotes2020** [comment]
Never mind, that's because I haven't fully tested other pages
