### ISSUE TITLE
Custom javascript files are not copied to the output folder

### ISSUE THREAD

**Issue by kungfux** [cotes2020/jekyll-theme-chirpy#2091]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

Custom javascript files are not copied to the output folder after upgrading to 7.2.1, because changes made in #2090 are promoted to the Chirpy starter template.

### Steps To Reproduce

1. Have custom scripts in `assets` folder
2. Build website

### Expected Behavior

Custom scripts are copied to the output folder.

### Environment

- Ruby: ruby 3.3.1 (2024-04-23 revision c56cd86388) [x86_64-linux]
- Jekyll: jekyll 4.3.3
- Chirpy: 7.2.1

### Anything else?

Workaround: edit `_config.yml` as follows

```diff
exclude:
- - "*.js"
+ - purgecss.js
```

**Comment by cotes2020** [comment]
> ## Steps To Reproduce
> Have custom scripts in assets folder

Can you be more specific?

**Comment by TianBoxv587** [comment]
> > ## Steps To Reproduce 复制步骤
> > Have custom scripts in assets folder在 assets 文件夹中安装自定义脚本
> 
> Can you be more specific?你能说得更具体一些吗？
![image](https://github.com/user-attachments/assets/8cb8ad5d-d075-49a4-8573-4d10abccd8c6)

**Comment by kungfux** [comment]
> Can you be more specific?

I have custom javascript files in `assets/js` folder that are being included from markdown or `metadata-hook.html` files.

```
root/
├── _includes/
│   └── metadata-hook.html
└── assets/
    └── js/
        └── my-script.js
```

```html
<script src="/assets/js/my-script.js" defer></script>
```

This worked as javascript files are copied to `_site/assets/js` folder on build. Since javascript files are excluded in the config now, they are no being copied.

If I remove the following parameter in `_config.yml`, then my javascript files will be copied.

```yml
exclude:
  - "*.js"
```

**Comment by cotes2020** [comment]
The pattern `*.js` will only exclude js files in the _root directory_ and does not apply to js files in the `assets` folder. So I'm curious how you came to this conclusion? Did you exclude the js files in the `assets/` folder after running it?

**Comment by kungfux** [comment]
I [see](https://ruby-doc.org/3.3.5/File.html#method-c-fnmatch) what you're saying.

> * Matches any file. Can be restricted by other values in the glob. Equivalent to /.*/x in regexp.

Here's what I'm observing though. When I add `*.js` to the `exclude` section, there are no js files in the `_site/assets/js` folder after the build. When I remove it, the js files are there.

OK, I will try to find the cause on my end. At the moment I have no idea why it works differently for you.

**Comment by cotes2020** [comment]
Sorry, I made a mistake. When checking the output with `ls` command, the path I entered was missing the `_site/` prefix.

Using ruby to check, it's confirmed that `*.js` can match files in subdirectories.

```rb
# test.rb
puts File.fnmatch('*.js', 'sub/script.js')        # output: true
puts File.fnmatch('*.js', 'assets/js/script.js')  # output: true
```

It seems that ruby has a different pattern than the shell and needs to be used more carefully.
