### ISSUE TITLE
File jekyll-theme-chirpy.css does not exist. yet jekyll-theme-chirpy.scss actually does 

### ISSUE THREAD

**Issue by classicrocker883** [cotes2020/jekyll-theme-chirpy#2097]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Built from `jekyll-theme-chirpy`

### Describe the bug

It seems as though these files are the wrong name or typo:

**_site\tags\writing\index.html**

```html
  <!-- Theme style -->
  <link rel="stylesheet" href="/assets/css/jekyll-theme-chirpy.css">
```

there is no file named `jekyll-theme-chirpy.css`, however it is named `jekyll-theme-chirpy.scss` instead

### Steps To Reproduce

1. go to **\\<-MainFolder->\\_site\tags\writing\index.html**
2. line ~82
3. you will see `<link rel="stylesheet" href="/assets/css/jekyll-theme-chirpy.css">`
4. however, there is no file with that name, only `jekyll-theme-chirpy.scss`
5. Even manually changing this to `.scss` will change back to `.css` once you do `bundle exec jekyll b`

### Expected Behavior

Everything else is expected run as normal, no other issues to note.
This is the only issue:
showing a file that doesn't actually exist
somehow maybe it is a typo? 

### Environment

- Ruby:  ruby 3.3.6 (2024-11-05 revision 75015d4c1f) [x64-mingw-ucrt]
- Jekyll:  jekyll 4.3.4
- Chirpy: 
-   * jekyll-theme-chirpy (7.2.1)
        Summary: A minimal, responsive, and feature-rich Jekyll theme for technical writing.
        Homepage: https://github.com/cotes2020/jekyll-theme-chirpy
        Documentation: https://github.com/cotes2020/jekyll-theme-chirpy/#readme
        Source Code: https://github.com/cotes2020/jekyll-theme-chirpy
        Wiki: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
        Bug Tracker: https://github.com/cotes2020/jekyll-theme-chirpy/issues
        Path: C:/Users/Andrew/Documents/PlatformIO/classicrocker883.github.io

**Comment by SoumyaK4** [comment]
The files in `_site` are dynamically created once you `build` thse site. 
You cannot change the file names there and expect it to work because inherently the file's content are written in different language.

It looks like you don't have much knowledge of jekyll or frontend tech, so instead of using `jekyll-theme-chirpy`
It's recommended to use `chirpy-starter` [here](https://chirpy.cotes.page/posts/getting-started/#option-1-using-the-starter-recommended)

**Comment by kungfux** [comment]
I would just add that the source stylesheet file `/assets/css/jekyll-theme-chirpy.scss` is processed to produce the output file `_site/assets/css/jekyll-theme-chirpy.css`, as `scss` files are for developers while `css` files are for browsers.

Please let us know if you experience any problems, or consider opening a discussion if you have any questions.
