### ISSUE TITLE
categories displayed but when clicked drives to 404

### ISSUE THREAD

**Issue by pipiscrew** [cotes2020/jekyll-theme-chirpy#210]
## Checklist
- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [x] I found the bug on the latest code of `master` branch.

## Describe the bug
categories displayed but when clicked drives to 404

### To Reproduce
add some posts with categories, upload the theme to github, wait for CID, browse the site

### Expected behavior
click the anchor of any category and list the articles for it.

### Screenshots
![image](https://user-images.githubusercontent.com/3852762/102010942-df1c1a80-3d49-11eb-9c48-d6e085a20b34.png)

### Software
- Ruby version: 2.6.6p146
- Gem version: 3.0.3
- Bundler version: 2.2.0
- Jekyll version: 2.6.6-2

### Desktop
- OS: windows 7 x64
- Browser: Chrome 85

### Smartphone
- Device: samsung
- OS: andoird7
- Browser: Chrome 22

### Additional context
only reproduced on github, the **bug didnt occur locally**.

**Comment by cotes2020** [comment]
> - [x] I have read the tutorials and know the correct effect of the functional design.
> - [x] There are no similar reports on existing issues (including closed ones).

😫 ...
