### ISSUE TITLE
Switching light/dark theme will crash Mermaid diagrams.

### ISSUE THREAD

**Issue by hepheir** [cotes2020/jekyll-theme-chirpy#2107]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

Toggle light/dark theme switch button on the sidebar to produce this bug.

### Steps To Reproduce

1. enable mermaid on a post
2. open a post which includes mermaid diagrams
3. switch to light/dark theme by clicking toggle button on the sidebar

### Expected Behavior

1. some or all diagrams will print error message on them: "Syntax error in text"

<table><tbody><tr><td>Before switching light/dark mode</td><td>After switching light/dark mode</td></tr><tr><td>
<img width="788" alt="Screenshot 2024-12-11 at 18 56 21" src="https://github.com/user-attachments/assets/30f9a47c-feab-4f8f-b127-e45d5443c37f">
</td><td>
<img width="788" alt="Screenshot 2024-12-11 at 18 56 26" src="https://github.com/user-attachments/assets/a139a224-a95e-4f03-9706-98867ed99291">
</td></tr></tbody></table>

### Environment

- Ruby: 3.3.0 [arm64-darwin24]
- Jekyll: 4.3.4
- Chirpy: 7.2.2

Furthermore..

- Gem: 3.5.23
- OS: macOS Sequoia 15.2
- Arch: arm64 (Apple Silicon)
- Run Command: `./tools/run`

### Anything else?

I can fix this quickly. #2108

**Comment by cotes2020** [comment]
Thank you for your report, but it lacks sufficient information.

Please provide the following details:
1. The environment where the issue occurred
2. The Mermaid code block that caused the issue

**Comment by lotusk08** [comment]
Same here too.
When you switch the theme to dark/light, the Mermaid Diagram in the blog will get syntax errors.
![IMG_1063](https://github.com/user-attachments/assets/d26383b7-bcd1-4695-bcac-89c662c003fb)

**Comment by hepheir** [comment]
@cotes2020

1. Sure. Here is the environment setup:

- Ruby: 3.3.0 [arm64-darwin24]
- Jekyll: 4.3.4
- Chirpy: 7.2.2

I’ve also updated the description with screenshots and the environment information.

2. As requested, here are the Mermaid code blocks:

<pre>
```mermaid
graph LR
1((4)) --> 2((3)) --> 3((5))
```

...

```mermaid
graph LR
1((2)) --> 2((1)) --> 3((3))
```

...

```mermaid
graph LR
1((1)) -.-x 2((0)) -.-x 3((2))
```

...

```mermaid
graph LR
1((1)) -.-x 2((0)) -.-x 3((2))
1 ---> 3
style 1 stroke-width:4px
style 3 stroke-width:4px
```
</pre>

**Comment by cotes2020** [comment]
> 1. Sure. Here is the environment setup:
> 
> * Ruby: 3.3.0 [arm64-darwin24]
> * Jekyll: 4.3.4
> * Chirpy: 7.2.2
> 
> I’ve also updated the description with screenshots and the environment information.
> 
> 2. As requested, here are the Mermaid code blocks:
> ...

Thank you, a complete bug report should be like this.

**Comment by hepheir** [comment]
> > 1. Sure. Here is the environment setup:
> > 
> > 
> > * Ruby: 3.3.0 [arm64-darwin24]
> > * Jekyll: 4.3.4
> > * Chirpy: 7.2.2
> > 
> > I’ve also updated the description with screenshots and the environment information.
> > 
> > 2. As requested, here are the Mermaid code blocks:
> >    ...
> 
> Thank you, a complete bug report should be like this.

I’ll make sure to provide more detailed information when creating issues in the future. Thank you!
