### ISSUE TITLE
_posts folder is no longer in the repository 

### ISSUE THREAD

**Issue by nescodey** [cotes2020/jekyll-theme-chirpy#211]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

Steps Followed:
Fork the repo
Changed the name to my_username.github.io
cloned on my PC
ran the init.sh
change the base url to my_username.github.io
git add .
git commit 
git push

gh-pages appeared and changed as publishing source code.

Now, I don't see any posts. Help !!

**Comment by SilleBille** [comment]
Hello @nescodey when you run the `init.sh` script, it removes all the contents from `posts/`. So, you need to write your own post to view it on your blog
