### ISSUE TITLE
how to increase the timeout for the workflow ?

### ISSUE THREAD

**Issue by pipiscrew** [cotes2020/jekyll-theme-chirpy#212]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description
hi there,

I tried the template for 1.5k posts, working fine built on 3m

once pushed 14.5k posts, on build reach the default 360 minutes (6h) timeout, wrote :
`The job running on runner Hosted Agent has exceeded the maximum execution time of 360 minutes.`

![image](https://user-images.githubusercontent.com/3852762/102051390-2e675700-3ded-11eb-985a-f5d6c26f3456.png)

I dig @ 
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes

made the needed modification on **pages-deploy.yml** as 

```
jobs:
  continuous-delivery:

    runs-on: ubuntu-latest
    timeout-minutes: 1200
```

then complain as 
`You have an error in your yaml syntax on line 15`

 :1234: 

please advise!

**Comment by lbragile** [comment]
@pipiscrew Did you manage to figure out a solution?

**Comment by pipiscrew** [comment]
finally I build it **locally** and upload to **pages** repo, took ~6h to build ;)

you can see the result at :
https://pipiscrew.github.io/

Im not happy as the search is not working, how I will find something on 14.5k articles!? ;)

**Comment by pipiscrew** [comment]
finally I built it **locally** and upload to **pages repo**, took ~6h to build ;)

you can see the result at :
https://pipiscrew.github.io/

Im not happy as the **search** is not working, how will I **find** something on 14.5k articles!? ;)
