### ISSUE TITLE
A depoly error will be reported  After run the init.sh due to  the _posts dir won't be keep

### ISSUE THREAD

**Issue by MainHanLiu** [cotes2020/jekyll-theme-chirpy#2123]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Built from `jekyll-theme-chirpy`

### Describe the bug

After run the init.sh, the _posts file all be deleted,  and the dir won't be keep, thus will report a depoly error.

error msg:
Get Pages site failed. Please verify that the repository has Pages enabled and configured to build using GitHub Actions, or consider exploring the `enablement` parameter for this action.

suggestion: add a .placehoder file in the _post dir to avoid this error

### Steps To Reproduce

run the init.sh

### Expected Behavior

After run init.sh, a basic blog  web can be preview by access the url.

### Environment

- Ruby: 
- Jekyll: 
- Chirpy:

**Comment by cotes2020** [comment]
http://www.catb.org/~esr/faqs/smart-questions.html
