### ISSUE TITLE
Add an option to sort posts on the home page by update date

### ISSUE THREAD

**Issue by eduardocasino** [cotes2020/jekyll-theme-chirpy#2124]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

No.

### Describe the solution you'd like

I would like to add an option to the `_config.yml` so that, if `the last_modified_at` variable exists in the front matter, its value is used instead of the `date` to sort the posts on the home page. This way, updated posts are given the same relevance as new ones.

### Describe alternatives you've considered

I've done an example implementation, based on what is done in `_includes/update-list.html`, modifying `_layouts/home.html`. Works for me but, as I'm a complete noob at liquid, there are probably better ways to do it:

```diff
--- home.html.orig	2024-12-16 16:56:41.182242322 +0100
+++ home.html	2024-12-16 16:43:28.212524992 +0100
@@ -5,8 +5,33 @@ refactor: true
 
 {% include lang.html %}
 
-{% assign all_pinned = site.posts | where: 'pin', 'true' %}
-{% assign all_normal = site.posts | where_exp: 'item', 'item.pin != true and item.hidden != true' %}
+{% if site.sort_by == 'updated' %}
+  {% assign sort_list = '' | split: '' %}
+
+  {% for post in site.posts %}
+    {% assign datetime = post.last_modified_at | default: post.date %}
+
+    {% capture elem %}
+      {{- datetime | date: "%Y%m%d%H%M%S" -}}::{{- forloop.index0 -}}
+    {% endcapture %}
+
+    {% assign sort_list = sort_list | push: elem %}
+  {% endfor %}
+
+  {% assign sort_list = sort_list | sort | reverse %}
+
+  {% assign all_list = '' | split: '' %}
+
+  {% for item in sort_list %}
+    {% assign index = item | split: '::' | last | plus: 0 %}
+    {% assign all_list = all_list | push: site.posts[index] %}
+  {% endfor %}
+{% else %}
+  {% assign all_list = site.posts %}
+{% endif %}
+
+{% assign all_normal = all_list | where_exp: 'item', 'item.pin != true and item.hidden != true' %}
+{% assign all_pinned = all_list | where: 'pin', 'true' %}
 
 {% assign posts = '' | split: '' %}
 
```

To activate the new sorting, add this to the `_config.yml` file:

```yaml
sort_by: updated # If set to 'updated', sorts posts on the home page using last_modified_at
```

And, for completeness, show the `last_modified_at` date also in the post summary:

```diff
--- a/_layouts/home.html
+++ b/_layouts/home.html
@@ -111,8 +111,11 @@ refactor: true
               <div class="me-auto">
                 <!-- posted date -->
                 <i class="far fa-calendar fa-fw me-1"></i>
-                {% include datetime.html date=post.date lang=lang %}
-
+                {% if site.sort_by == 'updated' and post.last_modified_at %}
+                  {% include datetime.html date=post.last_modified_at lang=lang %}
+                {% else %}
+                  {% include datetime.html date=post.date lang=lang %}
+                {% endif %}
                 <!-- categories -->
                 {% if post.categories.size > 0 %}
                   <i class="far fa-folder-open fa-fw me-1"></i>
```

**Comment by cotes2020** [comment]
If I understand correctly, the feature you want is "Recently Updated". Therefore, I will not consider having two lists sorted in the same way on the homepage.

**Comment by eduardocasino** [comment]
Not really. What I want is my posts to be sorted on the home page by their modified date, not the posted one. But I admit, then it makes little sense to also have "Recently Updated" on the right panel.

**Comment by cotes2020** [comment]
> ... it makes little sense to also have "Recently Updated" on the right panel.

You're right, so this feature will not be considered, sorry.
