### ISSUE TITLE
TOC not showing after window resize

### ISSUE THREAD

**Issue by GerardGascon** [cotes2020/jekyll-theme-chirpy#2132]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

When resizing the window from a narrow width to a wider width the TOC disappears.

### Steps To Reproduce

1. Load the website at a window width such that the TOC is using the mobile version.
2. Extend the width of the screen.

### Expected Behavior

You should see the TOC appear on the side, but instead it disappears.

### Environment

- Just using the example page

### Anything else?

In the video you can see how I refresh the website with a narrow screen size and when making it wider, the TOC disappear.

https://github.com/user-attachments/assets/b137439b-3375-428e-bf40-036889514277

**Comment by GerardGascon** [comment]
I'm using the Chirpy sample page (https://chirpy.cotes.page/posts/getting-started/) with version 7.2.3
Note that the page must be loaded with the TOC already hidden so that when making the screen wider it doesn't show up on the side. If you load the page with the sidebar visible it doesn't work.

**Comment by SoumyaK4** [comment]
@GerardGascon I see, thanks for reporting <3
