### ISSUE TITLE
Bootstrap should also be able to be "self-hosted"

### ISSUE THREAD

**Issue by Yrlish** [cotes2020/jekyll-theme-chirpy#2142]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

When I activate the self-hosted mode, bootstrap is still fetched from a cdn.

### Describe the solution you'd like

Boostrap should be part of the assets repo and also be sourced from there, so nothing is fetched from a cdn.

### Additional context

![image](https://github.com/user-attachments/assets/af8535a0-dbb3-4bb0-8370-72b68544e051)

**Comment by cotes2020** [comment]
Whether self-hosted or not, in `production` environment _Chirpy_ reads the slim Bootstrap locally. 

https://github.com/cotes2020/jekyll-theme-chirpy/blob/e44c048aef1ab3201eff05450614a32e6ce4b6bb/_sass/main.bundle.scss#L1

So it shouldn't bother you.

**Comment by Yrlish** [comment]
Interesting. If that's the case then loading bootstrap separately from a cdn shouldn't be needed, correct?

What's bothering me is a third-party cdn is being used, I don't like that.

Here is what the built and deployed production version logs looks like:
![image](https://github.com/user-attachments/assets/005ff490-3150-4dab-9f3a-f9863e61db96)

**Comment by cotes2020** [comment]
> ... in `production` environment ...

You overlooked these? If you're still in doubt check how the demo site loads the BS.

**Comment by Yrlish** [comment]
Oops, yeah I missed setting the environment variable `JEKYLL_ENV` to `production` when building it.
