### ISSUE TITLE
Will Prompts consider being compatible with GitHub writing method?

### ISSUE THREAD

**Issue by nrjycyd** [cotes2020/jekyll-theme-chirpy#2144]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Is your feature request related to a problem? Please describe

Will Prompts consider being compatible with GitHub writing method?

The Chirpy theme’s format requirements for Prompts are:

```
> An example showing the `tip` type prompt.
{: .prompt-tip }
```
![image](https://github.com/user-attachments/assets/5e491994-0397-4d72-862c-3e37732a093c)

This is different from GitHub’s format requirements for Alerts:

```
> [!TIP]
> Helpful advice for doing things better or more easily.
```
![image](https://github.com/user-attachments/assets/ec07c599-2008-4c08-8898-a7897ad92cb1)

As a creator, I often keep a copy of the documents posted to the Chirpy website locally so that I can modify them at any time. However, the different prompt syntax formats lead to a somewhat fragmented experience. Is there any plan to be compatible with the GitHub prompt format in the future? To facilitate previewing articles using local compilers.

Currently, the local editor typora already supports the GitHub prompt format:
![image](https://github.com/user-attachments/assets/32e50a89-a425-4497-89c7-0371a64c260d)

### Describe the solution you'd like

In addition to the Chirpy theme's native format, provide an option compatible with GitHub format, just like vitepress does.

https://vitepress.dev/guide/markdown#github-flavored-alerts

**Comment by cotes2020** [comment]
> Will Prompts consider being compatible with GitHub writing method?

No.

> To facilitate previewing articles using local compilers.

Perhaps you don't know that Jekyll supports running the server locally.

**Comment by NOS-AE** [comment]
> > Will Prompts consider being compatible with GitHub writing method?
> 
> No.
> 
> > To facilitate previewing articles using local compilers.
> 
> Perhaps you don't know that Jekyll supports running the server locally.

Here's a simple solution to support the github alert syntax, and make things like
> [!NOTE]
> this is a note

to have the same effect as

> this is an info
{: .prompt-info }

also to keep the original syntax compatible to comply the principle of least astonishment.
Can I create a PR for this?
