### ISSUE TITLE
Posts not showing on homepage, /posts/ 404ing

### ISSUE THREAD

**Issue by klongmore** [cotes2020/jekyll-theme-chirpy#218]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [x] I found the bug on the latest code of `master` branch.

## Describe the bug

On the homepage of my website, I cannot see the posts in the _posts folder. I can see them in recently updated, the archive, and through the tags and categories. When I try to go to url/posts/, I get a 404.
### To Reproduce

1. Fork the repository.
2. Create a post with correct format in _posts
3. Navigate to site URL
4. Posts are not shown on homepage
### Expected behavior

Expected to see posts on homepage
### Screenshots

![image](https://user-images.githubusercontent.com/14970686/102626029-64fcf300-419a-11eb-849e-5beb046c1267.png)
![image](https://user-images.githubusercontent.com/14970686/102626074-72b27880-419a-11eb-83a6-388f2bfe3268.png)
![image](https://user-images.githubusercontent.com/14970686/102626082-76de9600-419a-11eb-911b-ca02222a80b9.png)
### Software

- Ruby version: 2.7.2
- Gem version: 3.1.4
- Bundler version: 2.2.2
- Jekyll version: 4.1.1

### Additional context

Can view the site at https://klongmore.github.io/
Can view my repository at https://github.com/klongmore/klongmore.github.io/

**Comment by cotes2020** [comment]
> Steps to reproduce the behavior:
> 1. Fork the repository ...

Apparently not, your [repo](https://github.com/klongmore/klongmore.github.io/) seems to have been created by `jekyll new` and then copied from the Chirpy project files.

So your repo now has two conflicting files:

```sh
index.markdown  # created by yourself
index.html  # copied from `Chirpy` project
```

When Jekyll builds, it compiles markdown file into HTML file, overwriting the original `index.html`, so you get nothing on Homepage. You should check yourself carefully before reporting a "bug". This is good for everyone.
