### ISSUE TITLE
Wordwrap support for tables degraded?

### ISSUE THREAD

**Issue by coolhva** [cotes2020/jekyll-theme-chirpy#226]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

In the first version the row content was wrapped in tables but now I see a horizontal scrollbar. Is it possible to toggle this behaviour or to get wordwrap support in tables in any other way?

**Comment by cotes2020** [comment]
There is no need for this. A common user habit is for tables that are wider than the screen to scroll horizontally rather than wrap row. 

If you want to revert to the previous style, please modify the CSS.
