### ISSUE TITLE
GitHub page build error only when posts exist

### ISSUE THREAD

**Issue by hintfultest** [cotes2020/jekyll-theme-chirpy#228]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [x] I found the bug on the latest code of `master` branch.

## Describe the bug

I've only forked the repository and changed the `url` in `_config.yml` accordingly. No build errors up until this point.
Then, I've added one post to `_posts` directory and pushed the commit, then all of a sudden I started getting GitHub Page build error.

The site runs flawlessly on my machine locally, but I'm constantly getting GitHub Page build errors when pushing blog posts to my GitHub Page repository. Also, the site runs fine flawlessly both on my machine and on GitHub Page when there are 0 posts in `_posts` directory.

### To Reproduce
Simply add a post to `_posts` directory.

### Expected behavior
Expected the site to build successfully as I have made no other changes.

### Software

- Ruby version: `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]`
- Gem version: `2.7.6`
- Bundler version: `Bundler version 2.2.3`
- Jekyll version: `jekyll (4.1.1)`

**Comment by KRK224** [comment]
Hi hintfultest,

I have same issue as yours, any updates?

**Comment by Hummus-Ful** [comment]
Please had a look at: https://github.com/cotes2020/jekyll-theme-chirpy#deploy-on-github-pages
Changing the publishing source will fix your issue.

**Comment by m1ten** [comment]
I have the same problem even after doing everything mentioned here: https://github.com/cotes2020/jekyll-theme-chirpy#deploy-on-github-pages

**Comment by ericlesaquiles** [comment]
> Please have a look at: https://github.com/cotes2020/jekyll-theme-chirpy#deploy-on-github-pages
> Changing the publishing source will fix your issue.

I seem to be having a similar issue. I've checked the link, but it's not entirely clear what you mean by changing the publishing source. Could you clarify? 

To be more specific, the Page build fails. it runs locally. I'm using github pages, and I've asked github support for an error message, which they sent me:

```
 Liquid Exception: Liquid error (/page-build/repo/_includes/read-time.html line 4): 
 wrong number of arguments (given 2, expected 1) included in /_layouts/post.html          
 Fatal: Liquid::ArgumentError
```

Since it builds fine locally, I'd guess it has to do with the github action 
for reference, what I'm using is at github.com/ericlesaquiles/ericlesaquiles.github.io

**Comment by ericlesaquiles** [comment]
> > Please have a look at: https://github.com/cotes2020/jekyll-theme-chirpy#deploy-on-github-pages
> > Changing the publishing source will fix your issue.
> 
> I seem to be having a similar issue. I've checked the link, but it's not entirely clear what you mean by changing the publishing source. Could you clarify?
> 
> To be more specific, the Page build fails. it runs locally. I'm using github pages, and I've asked github support for an error message, which they sent me:
> 
> ```
>  Liquid Exception: Liquid error (/page-build/repo/_includes/read-time.html line 4): 
>  wrong number of arguments (given 2, expected 1) included in /_layouts/post.html          
>  Fatal: Liquid::ArgumentError
> ```
> 
> Since it builds fine locally, I'd guess it has to do with the github action
> for reference, what I'm using is at github.com/ericlesaquiles/ericlesaquiles.github.io

I've changed the theme. Not enough time to fix this. Just set a simpler theme, and later I'll figure how to improve it
