### ISSUE TITLE
Currently active tab white line doesn't align properly

### ISSUE THREAD

**Issue by user-grinch** [cotes2020/jekyll-theme-chirpy#23]
**Describe the bug**

The side panel active white line doesn't align properly if there are less than 5 tabs.

**To Reproduce**
Add less than 5 tabs to the side panel

**Expected behavior**

![https://ibb.co/2jfpThf](https://i.ibb.co/55fJP4f/image.png)

**Screenshots**

![https://ibb.co/4gDKDvF](https://i.ibb.co/BK7c7Wf/image.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Edge Chomium
 - Version: 79.0.309.71

**Comment by cotes2020** [comment]
I don't think this is a bug. If you choose to change the HTML structure of sidebar, [the relevant CSS](https://github.com/cotes2020/jekyll-theme-chirpy/blob/711b4a6bd132fb75849cf68e0e8431a016032314/assets/css/main.scss#L81-L114) should also be modified.

**Comment by user-grinch** [comment]
Okay. Thanks.

**Comment by cotes2020** [comment]
Good news, It has been improved at: aca655451335ee4b0bbffe7eabdba959c1196520
