### ISSUE TITLE
github Page build failed!

### ISSUE THREAD

**Issue by dufei99** [cotes2020/jekyll-theme-chirpy#230]
error msg: Your site is having problems building: Page build failed. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#troubleshooting-build-errors.

_config.yml:
remote_theme: https://github.com/cotes2020/jekyll-theme-chirpy

**Comment by KRK224** [comment]
> error msg: Your site is having problems building: Page build failed. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#troubleshooting-build-errors.
> 
> _config.yml:
> remote_theme: https://github.com/cotes2020/jekyll-theme-chirpy

Hello dufei99,

I've got same error as yours,
do you solve this problem yet?
