### ISSUE TITLE
Recent update is not showing

### ISSUE THREAD

**Issue by achyutap** [cotes2020/jekyll-theme-chirpy#233]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

I have forked Chirpy theme and read and work like the tutorial but in my site I can't get recent updates. I am using master branch for website because it will not create gh-pages branc. Can anyone have suggestions.

**Comment by SilleBille** [comment]
I see that your blog is working now. You still have this issue? If not, please close it :-)
