### ISSUE TITLE
Can we put the tab urls in the root instead of under /tabs/ ?

### ISSUE THREAD

**Issue by RyanTG** [cotes2020/jekyll-theme-chirpy#238]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

For the "real" tabs in the sidebar - Categories, Tags, Archives, About - can we change the tabs.url so that it doesn't include `/tabs/`? For example, instead of `/tabs/categories` it would just be `/categories`

I'm having trouble figuring out where the `tabs.url` is coming from:
https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/_includes/sidebar.html#L42

Thank you!

**Comment by cotes2020** [comment]
> can we change the tabs.url so that ...

If you want to change the output path, see [permalinks](https://jekyllrb.com/docs/permalinks/).


> I'm having trouble figuring out where the tabs.url is coming from ...

The `tabs` are implemented using Jekyll [collections](https://jekyllrb.com/docs/collections/) feature

**Comment by RyanTG** [comment]
Ah, thank you. I use permalinks on all my posts, but didn't even think to use them on these files. Duh.

Thanks for making such a nice theme! I love 3 column themes - but there aren't that many of them! Yours is very slick and well-designed.

**Comment by RyanTG** [comment]
Sorry - I have another related question, if you have time to answer it:

I would like one of my Tabs to be a link to a Category page. One of my categories is more important than the others, and so I would like to highlight it in the Tabs.

For example: I want to add a tab called Music that links to /categories/music/

What is the best way to do that? 

If I create a music.md file in the _tabs folder, and give it 

```
---
layout: category
title: Music
icon: fas fa-music
order: 4
permalink: /categories/music/
---
```
I think the `layout` line is the problem, but I'm not sure of the answer. Thanks.
