### ISSUE TITLE
Change math input symbols

### ISSUE THREAD

**Issue by LearningAlgorithms** [cotes2020/jekyll-theme-chirpy#243]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description
Hello. Is it possible to change the symbols to input a math formula? 

Now to imput an inline formula you have to use \\\( ... \\\), and, $$ ... $$ for a separated formula.

Is there any way to change this to use \\( .. \\) and \\[ ... \\], or $ ... $ and $$ ... $?

Thanks for your help and for this theme.

**Comment by cotes2020** [comment]
Hey there,

Maybe not. The mathematical formula is powered by [MathJax](https://www.mathjax.org/), so follow its syntax.

**Comment by LearningAlgorithms** [comment]
Yes, that's why I was asking it, 

![Captura de pantalla 2021-01-10 143121](https://user-images.githubusercontent.com/73430497/104124339-a8d5b900-5350-11eb-895e-38e89fc5bc49.jpg)

I was trying to use \\[ ... \\] and \\( ... \\) as its said in the [Mathjax documentation](http://docs.mathjax.org/en/latest/basic/mathematics.html) but i can't get it to work properly.

**Comment by cotes2020** [comment]
Because the post is a **Markdown** file, so you need to use the backslash character`\` to escape Markdown syntax characters `\`, i.e.,

 - `\\[ ... \\]` for displayed mathematics
- `\\( ... \\)` for in-line delimiters

**Comment by LearningAlgorithms** [comment]
Okay, i will do it. 

Thanks.

**Comment by J-StrawHat** [comment]
Hey, the problem you met also bothered me two months ago. But now here's a way I learn from other website.
From `\_includes\js-selector.html`：
```
{% if page.math %}
  <!-- MathJax -->
  <script defer src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script defer src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
{% endif %}
```
You can change the path and add some code like this：
```
{% if page.math %}
  <!-- MathJax -->
  <script type="text/x-mathjax-config">
    MathJax.Hub.Config({
      tex2jax: {
        skipTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code'],
        inlineMath: [['$','$'], ['\\(','\\)']],
        processEscapes: true
      },
      TeX: {
        equationNumbers: {
          autoNumber: "AMS"
        }
      }
    });
  </script>
  <script type="text/javascript" async
    src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_CHTML">
  </script>
{% endif %}
```
Now you can  use `$...$` for an inline formula, and, `$$ ... $$` for a separated formula. (like *LaTeX*) :smile:

**Comment by LearningAlgorithms** [comment]
Hey, thank you for your response. 

I have tried it and works great, just like _Latex_ 😄

Thanks.
