### ISSUE TITLE
Categories page joins sub-categories that do not share the same main-category

### ISSUE THREAD

**Issue by Hummus-Ful** [cotes2020/jekyll-theme-chirpy#244]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There are no similar request on existing issues (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

Yes, I created 3 categories: A,B and C, where C is a sub-category both A and B share. 
Created 2 posts with the following categories:
post_a: [A, C]
post_b: [B, C]

This makes the category page look like this:
> A (1 category, 1 post)
>> C (**2** posts)

>B (1 category, 1 post )
>> C (**2** posts)

As you can see above, C category is count is wrong and when you click on C, you get both post_a and post_b.

## Describe the solution you'd like

As each post can have up-to 2 categories, the first category should be the "main-category" and the second is "sub-category". 
The Categories page should not put together sub-categories that do not share the same "main category":
> A (1 category, 1 post)
>> C (1 post)

>B (1 category, 1 post )
>> C (1 post)

## Describe alternatives you've considered

None

## Additional context

[categories page on my site](https://hummus-ful.github.io/tabs/categories/)

**Comment by cotes2020** [comment]
By design, plese ensure that each `category` appears only once on the **Categories** page.

If you want to share some meta across different categories of posts, consider using `tag`:

```yml
# post_a
---
categories: [A]
tags: [c]
---

# post_b: 
---
categories: [B]
tags: [c]
---
```

**Comment by Hummus-Ful** [comment]
Thank you @cotes2020. Keep up the great work and thank you very much for you work so far.
