### ISSUE TITLE
Add a buymeacoffee widget to all pages?

### ISSUE THREAD

**Issue by vik-s** [cotes2020/jekyll-theme-chirpy#248]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

I would like to add a buymeacoffee widget to all my blog posts and also on all other pages, like about, categories, tags, home, etc. I can generate the widget from buymeacoffee.com but where is the best place to paste it so it is visible at all times?

thanks for your work on this by the way. It is very helpful.

**Comment by cotes2020** [comment]
Please try to add in the `default` layout

**Comment by 0xRyuzak1** [comment]
So how to do this while using jekyll-theme-chirpy template which hasn't _layout directory

**Comment by kjbtech** [comment]
Hello,
I hope you don't mind but I face same issue here.
What do you suggest?
Is there someone that already did something on his side to resolve this need (or something similar)?

**Comment by kungfux** [comment]
@kjbtech The answer depends on what exactly you want to achieve. However, in general, please refer to footer customization [discussion](https://github.com/cotes2020/jekyll-theme-chirpy/discussions/1273) as a reference on how to customize things.

**Comment by kjbtech** [comment]
That could help me to have a quick solution, thanks !

I was thinking futher and having a way to customize it easely right there for examples (yellow circles) will be nice:
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/67744786/d98f7126-f2da-4388-a7ed-18d4312afdd4)
 
Maybe, it will be more accurate to provide a generic way to add other alternatives (as Ko-Fi or Patreon).

Could this be usefull for the community?

**Comment by kungfux** [comment]
@kjbtech I personally don't need it, but that doesn't mean no one does.

I would suggest that you first post an idea discussion and suggest a general solution and design before submitting a PR to make sure it will be accepted by the maintainer. But it's up to you.
