### ISSUE TITLE
Not able to reach superProxy admin page due to HSTS

### ISSUE THREAD

**Issue by vik-s** [cotes2020/jekyll-theme-chirpy#251]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description
Hey I got through most of the steps to setup pageviews, and deployed the app to gcloud. When I try to get to the superProxy admin page, I get this error. In Firefox and Chrome, it does not let me bypass HSTS. Is there a trick to get this to work?

thanks!

id-XXXX.region-XXXX.r.appspot.com has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site.

**Comment by Cloufish** [comment]
Try setting up an SSL Certificate on Google Cloud.  https://www.ssldragon.com/blog/how-to-install-an-ssl-certificate-on-google-cloud-platform/
This issue is probably not related to chirpy theme at all, but in how you deploy the site on non-Github Pages

**Comment by vik-s** [comment]
Thanks, I'll try that out. I understand this is not related to chirpy at all. I was following the instructions on how to setup pageviews, and ran into this. If SSL certificate is needed, it will be nice to add that as part of the how-to...
