### ISSUE TITLE
Is there a gem for this theme?

### ISSUE THREAD

**Issue by atin** [cotes2020/jekyll-theme-chirpy#252]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

I want to use this theme for my website but I'm planning to make different repo for each section of my website. For example - A repo name blog for blogging section, a repo named notes for my notes, a repo named projects for the projects section and so on. So I was wondering if I can achieve that just by adding `theme: jekyll-theme-chirpy` in the _config.yml of all the repos or do I have to add this code to all repos?

**Comment by cotes2020** [comment]
So far, it is a regular theme, not a gem
