### ISSUE TITLE
Front matter block does not work

### ISSUE THREAD

**Issue by TurkischeBaklava** [cotes2020/jekyll-theme-chirpy#255]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

Front matter block does not work for my latest post. It always has been there and wrapping "title" ,"date" ,"categories" and "tag"
section.

![Screenshot from 2021-01-17 11-12-14](https://user-images.githubusercontent.com/43863818/104835080-20f23080-58b5-11eb-8437-f3c8647fd578.png)

Here is the link to the issue:

[https://github.com/TurkischeBaklava/TurkischeBaklava.github.io/blob/master/_posts/2021-01-13-TypeChecking.md](url)

It was working with previous article however does not work new ones. Any substitute HTML code works fine as well. I am pretty happy with theme.

**Comment by Cloufish** [comment]
Delete newlines above the front matter and check if that solves the issue. It seems it's the only difference between this post and the others.

**Comment by TurkischeBaklava** [comment]
> Delete newlines above the front matter and check if that solves the issue. It seems it's the only difference between this post and the others.

Well that worked just fine, the problem was redundant empty lines on top of the file as you said. Cheers !
