### ISSUE TITLE
RSS Feed (feed.xml) doesn't generate correct urls when doing Project website with baseUrl

### ISSUE THREAD

**Issue by Cloufish** [cotes2020/jekyll-theme-chirpy#259]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [x] I found the bug on the latest code of `master` branch.

## Describe the bug

RSS Feed (feed.xml) doesn't generate correct link hrefs when doing Project website
(When the website is hosted as a project with baseUrl value)

In my case, instead of generating 
```https://cloufish.github.io/blog/posts/dc4-en/```
It generates
```https://cloufish.github.io/posts/dc4-en/``` 

### Expected behavior

Every URL in rss feed (feed.xml) should have  ```https:// <URL>/<baseUrl>/posts/<post_name>/ ``` format

### Screenshots

![image](https://user-images.githubusercontent.com/32965886/104848020-5ada2b80-58e3-11eb-8e21-60116694630e.png)

### Software

- Ruby version: 2.7.2
- Gem version: 3.1.4
- Bundler version: 2.2.5
- Jekyll version: 4.2.0

**Comment by cotes2020** [comment]
Thanks for reporting this issue
