### ISSUE TITLE
How to translate dates?

### ISSUE THREAD

**Issue by mamutal91** [cotes2020/jekyll-theme-chirpy#26]
Hi, first thanks for sharing your work.

I'm trying to translate the date format, but it doesn't work, it remains in English.

Commit: https://github.com/mamutal91/mamutal91.github.io/commit/a66248921a749db25ebff49566d32bbfa1579d5e

![error](https://i.imgur.com/hSaAwbK.png)

**Comment by cotes2020** [comment]
Run `tools/js-compress.sh` to update your change( JRE required )

**Comment by mamutal91** [comment]
Hello, sorry to bother you again, I'm not able to translate the date in the list of posts.
https://mamutal91.github.io/categories/jekyll/

![date](https://i.imgur.com/2upSy6n.png)

**Comment by cotes2020** [comment]
check:  <https://github.com/cotes2020/jekyll-theme-chirpy/blob/ec60cc7a91771544c7444d4a212bd795ed4234b0/_layouts/category.html#L21>
and: <https://github.com/cotes2020/jekyll-theme-chirpy/blob/ec60cc7a91771544c7444d4a212bd795ed4234b0/_data/date_format.yml#L9>

**Comment by Coubiac** [comment]
I'm sorry to reopen this issue but I don't understand how to change the language of the dates. The answer from @cotes2020 explains how to change the format but not how to change the language.... In the same way, how can we change the "lang=en" tag in <head> ?
