### ISSUE TITLE
[FR] GDPR - cookie consent - opt-in

### ISSUE THREAD

**Issue by hidegh** [cotes2020/jekyll-theme-chirpy#265]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There are no similar request on existing issues (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [X] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

Sites that are also targeting EU citizens should implement GDPR - and thus Cookie consent is a mandatory thing, must be an opt-in. Any plans in this direction?

## Describe the solution you'd like

Any free cookie consent tool.

## Describe alternatives you've considered

Custom JS script. Currently researching the possibility to have at least Google Analytics in an anonymous mode (as the GDPR requires opt-in) and also some way for Disqus to make it clear that consent is required for it to work.

**Comment by cotes2020** [comment]
Yeah, that's a good idea, and I'll consider implementing it in a future release.

**Comment by hidegh** [comment]
@cotes2020 working on it, on my custom branch, will let you know what I got, as GDPR is quiet messy. So far what I got:

1. generated user id, IP address is considered as private data
2. you might use Google Analytics with anonymized IP and without user-id (device id is then used) - so this way you don't store any personal data, geo-location is a bit less precise and you can't "identify" recurring users (even long session ID can be considered as private) - but this is a good way to start. Unfortunately seems that GA allows to alter just the IP anonymization on the script side (need to check if same can be done with user/session ID)...
3. even if you don't store personal data, you probably still need to notify the users of cookie usage
4. and reg. disqus, you surely need to notify the users that via your site they are sending personal data to that site directly

**Comment by hidegh** [comment]
With fairly minimum changes:
![image](https://user-images.githubusercontent.com/6331063/105843516-16801700-5fd8-11eb-95a0-a348e4e07d32.png)

I managed to add a cookie consent to the solution (probably only extra it needs is a turn on/off switch inside _config).

It uses V3 https://github.com/osano/cookieconsent - V4 is not production ready yet but the main branch already contains those extra changes (and be warned: the build/coocieconsent.min.js is not the latest build version of the branch).

The V3 is avail to download from: https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js

The solution required:
1. to minimally adjust the google analytics html
2. small changes to the discuss html
3. and it requires a reload when consent is revoked 

Related commits (on my branch):
https://github.com/hidegh/hidegh.github.io/commit/6f939c6e79c67380c77c98d3d56c482cd0531c15
https://github.com/hidegh/hidegh.github.io/commit/e0e38a8baa2808616900c7f4bf1ca6393363b108
https://github.com/hidegh/hidegh.github.io/commit/67d6f498f2e0622e9356cc8d15f8277c13b57b20
https://github.com/hidegh/hidegh.github.io/commit/72c71b647bb18af34cd8132dab90cd0f184a640b

If the team finds this solution acceptable, I can implement it inside a PR.
