### ISSUE TITLE
Unable to add some code inside a text code block

### ISSUE THREAD

**Issue by bms8197** [cotes2020/jekyll-theme-chirpy#268]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

I'm using your jekyll theme and I'm trying to add a post containing the code bellow inside a code block.

`<hostdev mode='subsystem' type='scsi' managed='no'>  <source>    <adapter name='scsi_host24'/>    <address bus='0' target='0' unit='0'/>  </source>  <alias name='hostdev0'/>  <address type='drive' controller='0' bus='0' target='1' unit='0'/></hostdev>`

Unfortunatelly the code is skipped and I believe it's because of <> and </>. I tried to use text/shell/bash code blocks but nothing works!

How can I format that code to be added as text or bash or shell or whatever?

**Comment by cotes2020** [comment]
Sorry, I'm not sure what you want to express:

1. Do you want to paste blocks of XML code directly into the inside of the article?
2. Or do you want to highlight this XML code using Markdown syntax?

**Comment by bms8197** [comment]
> Sorry, I'm not sure what you want to express:
> 
> 1. Do you want to paste  XML code snippet directly into a post?
> 2. Or do you want to highlight this XML code using Markdown syntax?

I've managed to solve it. Yes it was XML code. I've added a <highlight> block and it worked just fine. You can close it, it's not an issues, I didn't know how to do it...
