### ISSUE TITLE
If search results overflow off screen, it is difficult to scroll down

### ISSUE THREAD

**Issue by RyanTG** [cotes2020/jekyll-theme-chirpy#273]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [x] I found the bug on the latest code of `master` branch.

## Describe the bug
The `.search_result_wrapper` uses `position: fixed;`, which helps situate the results at the top of the page. But there is a problem is you have many results: if the results overflow from the screen, then 1) an extra scrollbar shows up, and 2) it's awkward to scroll down to see the remaining results.

### To Reproduce

1. You need a site that has more posts than the current theme preview site.
2. Search for a term that is used on all (or many) of the pages, so that you have many results.
3. Result: The results overflow off the screen, but it is difficult to get to them.

### Expected behavior
I would expect to be able to scroll. This can be achieved with `position: absolute;` `.search_result_wrapper`, and also adding `height: 0;` to the `.hidden` class. But it changes the page design a little bit. It's not perfect (which is why I didn't make a PR with it, because you may have other preferences).

### Additional Issues with the search-loader!

I am tacking on two small search-loader issues, in case you find them compelling: It would be good to have conditionals on the `{categories}` and `{tags}` in the search-loader, so if a post does not have them, then those tags (and icons) do not show up in the results. Right now, if you have a post that doesn't have a tag, it literally says "{tags}" in the search results. I had some trouble getting a conditional to function within that `capture`.

Thanks!

### Software

- Ruby version: 
- Gem version: 
- Bundler version: 
- Jekyll version:

**Comment by cotes2020** [comment]
Hi @RyanTG,

Both issues have been fixed, thx for the report.
