### ISSUE TITLE
Template Repo First Commit Build Fails

### ISSUE THREAD

**Issue by JordieB** [cotes2020/jekyll-theme-chirpy#275]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [x] I found the bug on the latest code of `master` branch.

## Describe the bug

Build failed on first commit of starter template

`Running ["ScriptCheck", "LinkCheck", "ImageCheck", "HtmlCheck"] on ["_site"] on *.html... 

- _site/404.html
Ran on 9 files!
  *  internally linking to jordieb.github.io/404.html, which does not exist (line 0)

     <link rel="canonical" href="jordieb.github.io/404.html">

- _site/about/index.html
  *  internally linking to jordieb.github.io/about/, which does not exist (line 0)
     <link rel="canonical" href="jordieb.github.io/about/">
- _site/archives/index.html
  *  internally linking to jordieb.github.io/archives/, which does not exist (line 0)
     <link rel="canonical" href="jordieb.github.io/archives/">
- _site/assets/index.html
  *  internally linking to jordieb.github.io/404.html, which does not exist (line 0)
     <link rel="canonical" href="jordieb.github.io/404.html">
  *  internally linking to jordieb.github.io/404.html, which does not exist (line 0)
     <a href="jordieb.github.io/404.html">Click here if you are not redirected.</a>
- _site/categories/index.html
  *  internally linking to jordieb.github.io/categories/, which does not exist (line 0)
     <link rel="canonical" href="jordieb.github.io/categories/">
- _site/index.html
  *  internally linking to jordieb.github.io/, which does not exist (line 0)
     <link rel="canonical" href="jordieb.github.io/">
- _site/norobots/index.html
  *  internally linking to jordieb.github.io/404.html, which does not exist (line 0)
     <link rel="canonical" href="jordieb.github.io/404.html">
  *  internally linking to jordieb.github.io/404.html, which does not exist (line 0)
     <a href="jordieb.github.io/404.html">Click here if you are not redirected.</a>
- _site/posts/index.html
  *  internally linking to jordieb.github.io/404.html, which does not exist (line 0)
     <link rel="canonical" href="jordieb.github.io/404.html">
  *  internally linking to jordieb.github.io/404.html, which does not exist (line 0)
     <a href="jordieb.github.io/404.html">Click here if you are not redirected.</a>
- _site/tags/index.html
  *  internally linking to jordieb.github.io/tags/, which does not exist (line 0)
     <link rel="canonical" href="jordieb.github.io/tags/">

HTML-Proofer found 12 failures!
Error: Process completed with exit code 1.`

Actions URL: https://github.com/JordieB/JordieB.github.io/runs/1832124675?check_suite_focus=true

### Expected behavior

For the build to succeed and have the gh-pages branch be created

### Software

- Ruby version: 2.5.1p57
- Gem version: 2.7.6
- Bundler version: 2.2.6
- Jekyll version: 4.2.0

### Desktop
- OS: Ubuntu 18.04.2 LTS
- Browser: Brave 1.19.86 Chromium: 88.0.4324.96 (Official Build) (64-bit)

**Comment by JordieB** [comment]
https://github.com/cotes2020/jekyll-theme-chirpy/issues/178 did not help due to already having the HTML-Proofer having the proper version in the Gemfile.

https://github.com/cotes2020/jekyll-theme-chirpy/issues/199 wasn't helpful because I didn't already have posts. It's a fresh repo based off of the template

**Comment by cotes2020** [comment]
I don't understand why you can report "bugs" without looking at the documentation or comments.

<https://github.com/cotes2020/jekyll-theme-chirpy/blob/0b1c143c6e9e069d42ebbc72b800b19ba72f27c6/_config.yml#L27-L28>

**Comment by JordieB** [comment]
I can understand how frustrating it is to have people report things when it seems like they haven't gone through the docu, but my first commit shows that I changed the _config.yml file's url value. Maybe I'm missing something else in the docu?

https://github.com/JordieB/JordieB.github.io/commit/4c218453d08582d0ef9fd30fa78e61cc61823f58

**Comment by JordieB** [comment]
Just in case it was case sensitive, I even update it again, but the build fails for the same reason: https://github.com/JordieB/JordieB.github.io/commit/7bcdc15e685e6ca3ef33fdac5db2da270f6c9dd2
