### ISSUE TITLE
github builds my website incorrectly

### ISSUE THREAD

**Issue by laipuran** [cotes2020/jekyll-theme-chirpy#278]
## Checklist

- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.
- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.

## Description
 I created some directories and some files. And github, now, doesn't build my websites correctly. 
https://github.com/laipuran/laipuran.github.io
at
https://laipuran.github.io

**Comment by cotes2020** [comment]
> - [x]  I have read the tutorials and know the correct effect of the functional design.

Are you joking?

**Comment by laipuran** [comment]
Emm, I will check it again tomorrow cause I used up the time to use the computer

**Comment by laipuran** [comment]
*But I can run it locally*
