### ISSUE TITLE
作者大大新年快乐，提供两个小建议

### ISSUE THREAD

**Issue by J-StrawHat** [cotes2020/jekyll-theme-chirpy#284]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There are no similar request on existing issues (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

作者大大新年快乐，感谢你做的 Chirpy 主题，我已经使用有好几个月了，体验十分好！希望能给 Chirpy 提供两个小建议
## Describe the solution you'd like

① 在阅读博文时，如果图片看不清，只能“强制缩放页面”放大图片或者在新标签页中打开图片，不太方便。希望能增加个 Lightbox ，点击博文的图片就能够放大预览。作者大大可以考虑一下🤔，添加类似于 [Fancybox](http://fancyapps.com/fancybox/3/) 的插件吗?
![Fancybox效果](https://gitee.com/j__strawhat/MyImages/raw/master/20210222023801.png)

② 再提一个建议，在 Archives 页中，能否左侧显示月份，以及当月的**博文数量**呢？类似于下图的**布局**（非样式😂），能够清晰地知道自己在当月写了几篇博文，挺有成就感的，而且这样能更块地帮助我锁定某个月份所写的博文
![Archives页面的改进](https://gitee.com/j__strawhat/MyImages/raw/master/20210222024250.png)

**Comment by juzq** [comment]
图片放大功能确实挺实用的  (╹◡╹)

**Comment by cotes2020** [comment]
Hi @J-StrawHat,

1. 图片放大的很久之前就列在 [**Feature Pool**](https://github.com/cotes2020/jekyll-theme-chirpy/projects/1#card-33077684) 里面了
2.  文章归档外观更改请自行 DIY 吧，毕竟有关设计的细节众口难调
