### ISSUE TITLE
GitHub continuous-delivery failing due to libffi.so.6 / Ubuntu-latest

### ISSUE THREAD

**Issue by GabrielRF** [cotes2020/jekyll-theme-chirpy#289]
## Checklist
- [X] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [X] There are no similar reports on existing issues (including closed ones).
- [X] I found the bug on the latest code of `master` branch.

## Describe the bug
`ubuntu-latest` now is Ubuntu-20.04, which uses `libffi.so.7` instead of `libffi.so.6`, breaking the deployment on GitHub continuous-delivery

### To Reproduce
Allow GitHub actions to run and the error will pop-up
```
Run bundle exec jekyll b -d "_site$BASE_URL"
  bundle exec jekyll b -d "_site$BASE_URL"
  shell: /usr/bin/bash -e {0}
  env:
    GEMS_PATH: ~/vendor/bundle
    JEKYLL_ENV: production
bundler: failed to load command: jekyll (/home/runner/vendor/bundle/ruby/2.7.0/bin/jekyll)
LoadError: libffi.so.6: cannot open shared object file: No such file or directory - /home/runner/vendor/bundle/ruby/2.7.0/gems/ffi-1.14.2/lib/ffi_c.so
  /home/runner/vendor/bundle/ruby/2.7.0/gems/ffi-1.14.2/lib/ffi.rb:6:in `require'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/ffi-1.14.2/lib/ffi.rb:6:in `rescue in <top (required)>'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/ffi-1.14.2/lib/ffi.rb:3:in `<top (required)>'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc/native.rb:3:in `require'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc/native.rb:3:in `<top (required)>'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `require_relative'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `<top (required)>'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:3:in `require'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:3:in `<top (required)>'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll-sass-converter.rb:4:in `require'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll-sass-converter.rb:4:in `<top (required)>'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.0/lib/jekyll.rb:195:in `require'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.0/lib/jekyll.rb:195:in `<top (required)>'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.0/exe/jekyll:8:in `require'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.0/exe/jekyll:8:in `<top (required)>'
  /home/runner/vendor/bundle/ruby/2.7.0/bin/jekyll:23:in `load'
  /home/runner/vendor/bundle/ruby/2.7.0/bin/jekyll:23:in `<top (required)>'
Error: Process completed with exit code 1.
```

### Expected behavior
Build Site should run smoothly.

### Screenshots
* Not applicable.

### Software
- Ruby version: ruby 2.7.0p0
- Gem version: 3.1.2
- Bundler version: 2.2.6
- Jekyll version: 4.2.0

### Additional context
To fix for now, change `ubuntu-latest`  to `ubuntu-18.04` on `.github/workflows/pages-deploy.yml`

**Comment by cotes2020** [comment]
Hi @GabrielRF,

Yes, the Ubuntu latest version does cause this issue. You can either change the Ubuntu version or change the path of the bundle cache to invalidate the old cache files so that the `Ubuntu 20.04 LTS` version of the cache will be re-saved in the next build. I have already committed this [fix](063c3b94991a2edfba64a8146377a6a73533c291) earlier today.

Thanks for your report, and sorry for the issue-closing bot.

**Comment by GabrielRF** [comment]
@cotes2020 Thank you for your awesome work! :rocket:

**Comment by DuchkPy** [comment]
Setting a new Github Pages, I'm facing the same issue when sending to Github.
I have made a tryed, based (copy/paste and update `_config.yml` file) on this `3-2-stable` branch here : https://github.com/DuchkPy/myrepo
When I have the `baseurl` empty, compilation is working, but the theme is not applied (which is normal). When I define as `myrepo`, the compilation gave following issue :
```
Annotations
3 errors and 1 warning

 Process completed with exit code 1.
 The job was canceled because "ubuntu-latest" failed.
 The operation was canceled.
 Ubuntu-latest workflows will use Ubuntu-20.04 soon. For more details, see https://github.com/actions/virtual-environments/issues/1816
```

I have check, this 3.2 branch have the update mentionned above. So I don't really know what to perform to get it work.
