### ISSUE TITLE
Thumbnail of the post should show on the latest post in home page

### ISSUE THREAD

**Issue by 0xprashant** [cotes2020/jekyll-theme-chirpy#29]
![image](https://user-images.githubusercontent.com/40650455/75112147-2e427300-5684-11ea-95d0-f4890227f091.png)

it would be a good feature if i will be able to show the thumbnail of the post on the home page that shows all latest posts.
So where all the post have been shown there should be an option to add the FeatureImage/thumbnail of the post

**Comment by cotes2020** [comment]
Sorry... I won't consider modifying the design of **Recent Update** list. 

In your edition, you can do this by modifying: https://github.com/cotes2020/jekyll-theme-chirpy/blob/ec60cc7a91771544c7444d4a212bd795ed4234b0/_includes/panel.html#L37

**Comment by 0xprashant** [comment]
Can you please tell me what thing i need to modify or what i need to add in that line on panel.html


> Sorry... I won't consider modifying the design of **Recent Update** list.
> 
> In your edition, you can do this by modifying:
> 
> https://github.com/cotes2020/jekyll-theme-chirpy/blob/ec60cc7a91771544c7444d4a212bd795ed4234b0/_includes/panel.html#L37

**Comment by cotes2020** [comment]
Obviously, learn Website development & Jekyll development

**Comment by 0xprashant** [comment]
Can you tell me what i need to add
I will be very thankful to you

And Thanks for this wonderful theme cotes

**Comment by Intrusionz3r0** [comment]
What did you modify to add the image?

**Comment by mzampetakis** [comment]
I neede it so I have implemented this one in my fork. If ayone is interested it can be found [here](https://github.com/mzampetakis/mzampetakis.github.io). The specific comit adding this feature is [this](https://github.com/mzampetakis/mzampetakis.github.io/commit/08c4bfffcb337921177c4ac8eb77c2a9127994d3).

**Comment by 0xprashant** [comment]
I also done it , after opening the issue 
check it , [](https://0xprashant.github.io/)

**Comment by shivammehta25** [comment]
Sorry to revive an old thread. But is it possible to have this option/config on the gem version as well?
