### ISSUE TITLE
Theme mode changer icon not working in mobile devies.Default light theme is appearing

### ISSUE THREAD

**Issue by 0xprashant** [cotes2020/jekyll-theme-chirpy#30]
The theme changer is working fine in Desktop,Using the theme changer icon at the bottom of left menu bar.

But if we surf the Website in Smartphones the theme changer is not working.For the default the light theme is appearing and on pressing theme changer icon i m not getting the dark mode
# info about smartphone 
Android 9.0
browser-- chrome

**Comment by cotes2020** [comment]
would you pls fill the detial?

**Comment by cotes2020** [comment]
what's is your chrome version?

**Comment by 0xprashant** [comment]
Its 71.0.3578.99

**Comment by 0xprashant** [comment]
So i checked into uc browser too...
Facing the same issue

**Comment by cotes2020** [comment]
Did u heck on https://chirpy.cotes.info/ ? 

Take a screenshot here, pls.

**Comment by 0xprashant** [comment]
![Screenshot_2020-02-24-17-11-35-84](https://user-images.githubusercontent.com/40650455/75149791-d14cc880-5728-11ea-8bb5-a3710ec70073.png)
Nope...same here too
Unable to switch to dark mode

**Comment by cotes2020** [comment]
It's because your mobile chrome is too old to support [Media Queries Level 5](https://drafts.csswg.org/mediaqueries-5/). I fixed the compatibility at 4c75b3c1d86f2f0e3a431aaecfc6f4662b5685e1.

**Comment by 0xprashant** [comment]
It is resolved thanks 
Cotes

**Comment by uri3l593** [comment]
hi I have a question, I tried to change the default light mode to dark as default but for some reason it doesn't work, how can I set the dark mode as default, thanks a lot.
