### ISSUE TITLE
关于Gemfile

### ISSUE THREAD

**Issue by NagaseYami** [cotes2020/jekyll-theme-chirpy#300]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

您好，我是一个完全不懂Ruby的小白，如果我的提问过于愚蠢，请您直接关闭本Issue。

[教程](https://github.com/cotes2020/jekyll-theme-chirpy#installing-the-theme-gem)中提到如果从RubyGems安装，只需往Gemfiles中添加`gem "jekyll-theme-chirpy"`即可。于是我的`Gemfile`便只有两行。
```
source "https://rubygems.org"
gem "jekyll-theme-chirpy"
```

但是如果只有这两行，就会因为缺少`html-proofer`导致build失败。
```
Run bash tools/test.sh
bundler: command not found: htmlproofer
Install missing gem executables with `bundle install`
Error: Process completed with exit code 127.
```

于是我参考了[chirpy-starter的Gemfile](https://github.com/cotes2020/chirpy-starter/blob/main/Gemfile)，补上了三行，然后再次执行`bundle`重新生成了lock文件，就没问题了。
```
group :test do
  gem "html-proofer", "~> 3.18"
end
```

是不是应该在教程里也补上这三行比较好？

**Comment by cotes2020** [comment]
Hi @NagaseYami,

当你的 Jekyll 项目需要使用 `html-proofer` 插件才需要在 Gemfile 添加 ` gem "html-proofer"`，不是在安装主题的范畴。

正如教程提到的，对非 Web 开发需求的用户，如果希望通过 gem 安装主题，建议在 Github 上从 [**chirpy-starter**](https://github.com/cotes2020/chirpy-starter) 开始新建仓库，这对缺乏使用 Jekyll 的经验的用户比较友好。

**Comment by NagaseYami** [comment]
@cotes2020 感谢回复。
`html-proofer`确实超出了主题本身的范畴，可能写在`从RubyGems安装`里不太合适，
但是既然教程中有提到Github Action自动构建，那我觉得加一句需要添加`gem "html-proofer"`应该也比较合适。
当然，必要性并不是很高，毕竟懂得都懂，不懂的就直接Fork chirpy-starter了。
这个就您看着办吧，我关闭Issue了。
