### ISSUE TITLE
关于#22

### ISSUE THREAD

**Issue by NichtsVonChaos** [cotes2020/jekyll-theme-chirpy#301]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

根据 #22 和 #262 ，作者明确表明自己不会加入其它评论系统，并且也不会接受相关Pull Request。但是从国内用户的角度来看，替换Disqus的需求还是较多的，那么是否可以：

1. 在Demo Site或者项目的_posts文件夹中增加替换Disqus为valine的教程，此教程可以由我来完成，不麻烦作者大大。
2. 如果1不可行，是否可以在当前Issue下书写教程，并且替换当前Issue的标题为`教程：使用Valine替换Disqus`。
3. 如果1、2不可行，是否可以在我的个人博客上书写教程，并将超链接添加到当前项目的文档的Readme或Wiki页面或Getting Start中。
4. 如果均不可行，是否有其他可行的方案？

## 为什么不选择fork？

Fork的曝光度几乎等同于0，有此需求的用户很难注意到。

**Comment by cotes2020** [comment]
Hi @NichtsVonChaos,

1. 之所以不添加 Valine，是因为它依赖国内服务商 LeanCloud。个人经验是，围墙里的东西能不碰就不碰：备案、实名制是免不了的。
2. 如果有需要 Valine 的用户，自己去看 Valine 官方教程添加即可，我看了一下还是十分简单的，不需要再添加「教程」赘述。

希望理解～

**Comment by NichtsVonChaos** [comment]
@cotes2020 您好！我能明白您不添加 Valine 的想法。但是关于：

> 如果有需要 Valine 的用户，自己去看 Valine 官方教程添加即可，我看了一下还是十分简单的，不需要再添加「教程」赘述。

这一点，Valine 与当前主题的脱机服务（sw.js）有冲突，如果仅按照 Valine 官方教程来做，是无法正常使用 Valine 评论的。由于我才学疏浅，只能想到移除脱机服务这一个办法使 Valine 能够正常运作。

**Comment by cotes2020** [comment]
有什么冲突你说说？

**Comment by NichtsVonChaos** [comment]
@cotes2020 具体现象是控制台会产生报错：

```
Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Request method 'POST' is unsupported
    at sw.js:1
```

在 A设备发表的评论，只能在 A设备看到，无法在其他设备看到，同理也无法看到其他设备发表的评论。

在 LeanCloud 后台查询时发现，只有在***发表评论***时才产生了访问，而在***打开帖子***时没有访问记录，所以在***打开帖子***时应当只是读取了本地缓存的当前设备的评论。

移除与sw.js相关的代码后，Valine 能够正常工作。

**Comment by cotes2020** [comment]
1. 不说说操作系统、浏览器（还有版本号）是什么？
2. 「移除与sw.js相关的代码后，Valine 能够正常工作...」这样拆东墙补西墙的处理方式就是「教程」吗，不太稳妥吧，要处理的应该是 PWA 部分的问题，有空再跟进一下。

**Comment by NichtsVonChaos** [comment]
@cotes2020 
1. Manjaro、Win10 均出现相同情况，在我的手机（荣耀 V30）上也出现该问题，三端浏览器都是 Chrome，都是最新版本。
2. 是很不稳妥，但是这已经是我能力范围的极限了，总的来说还是我水平太低。

**Comment by NichtsVonChaos** [comment]
作为补充，如果有需要使用 Valine 的用户，并且能够接受移除脱机系统来作为临时解决方案，则可以参考[此篇教程](https://nihil.cc/posts/use_valine/)。

**Comment by NichtsVonChaos** [comment]
@cotes2020 在并入 33d4bb9 之后，出现了下面的问题：

![screenshot](https://user-images.githubusercontent.com/35688135/112075596-c4143e80-8bb3-11eb-9657-a5148ec696cd.png)

能否看一看问题出在哪里？

**Comment by cotes2020** [comment]
See a7ce47210845c8902c34d3ffe335250d860d90cb

**Comment by NichtsVonChaos** [comment]
@cotes2020 问题已解决，十分感谢
