### ISSUE TITLE
Attempting to use the "+" character in a tag causes build failure

### ISSUE THREAD

**Issue by bcaddy** [cotes2020/jekyll-theme-chirpy#303]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [x] I found the bug on the latest code of `master` branch.

## Describe the bug
Including the "+" character in a tag causes the site build to fail with the following error

```
- _site/tags/index.html
  *  internally linking to /tags/vl-%2B-ct/, which does not exist (line 1)
     <a class="tag" href="/tags/vl-%2B-ct/">VL + CT<span class="text-muted">1</span></a>
```

Attempting to escape + with quotes, slashes, HTML, and using HTML code directly all give similar errors

### To Reproduce
Put a "+" in a tag

### Expected behavior

The tags should not fail on special characters

### Software

- Ruby version:  ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]
- Gem version:  3.2.3
- Bundler version:  2.2.4
- Jekyll version:  4.2.0

### Desktop

- OS: macOS 10.15.7
- Browser: n/a

**Comment by cotes2020** [comment]
It seems that this is an error caused by copying the old code:
<https://github.com/bcaddy/bcaddy.github.io/blob/5c63329ce580286316231493ee1f4ab6984b68e7/_tabs/tags.md>

Please keep your code to the latest [`tag`](https://github.com/cotes2020/jekyll-theme-chirpy/tags) version

**Comment by bcaddy** [comment]
You're right. Thank you.
