### ISSUE TITLE
if we use more than 5 tab options for the menu tabs.The last one is overriding the social menu .Rather the scroll bar should be extended

### ISSUE THREAD

**Issue by 0xprashant** [cotes2020/jekyll-theme-chirpy#31]
![image](https://user-images.githubusercontent.com/40650455/75111425-026fbf00-567d-11ea-9f0a-45442208c63c.png)
if we add more than 5 options in the menu bar the 6 option is Covering the social menu at the bottom.Could it be that the menu scroll down if there are more than 5 options in menu.For reference see the picture.
For example i m trying to add the contact option in the menu bar.....but it is covering the twitter icon
There should be a space between them
Thanks

**Comment by cotes2020** [comment]
It's duplicated with #23

**Comment by 0xprashant** [comment]
that issue is about less than 5 tabs ...and mine is about more than 5 tabs
Could u check it again

**Comment by cotes2020** [comment]
The reason for them is similar. For browser compatibility, I fixed the tabs option to 5. If you need to modify the number (whether it is reduced or increased), you need to modify the CSS yourself.

**Comment by cotes2020** [comment]
You may want this: aca655451335ee4b0bbffe7eabdba959c1196520
