### ISSUE TITLE
Dark theme config only applies to the home page

### ISSUE THREAD

**Issue by thmPedro** [cotes2020/jekyll-theme-chirpy#311]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [x] I found the bug on the latest code of `master` branch.

## Describe the bug
When you set `theme_mode` to `dark` on the config file, only the home page gets the dark theme applied.

### To Reproduce

1. Go to the config file
2. Set the theme mode to dark
3. Go to any page other than the home page

### Expected behavior
All pages should have the dark mode applied.

### Software

- Ruby version: 
- Gem version: 
- Bundler version: 
- Jekyll version:

**Comment by cotes2020** [comment]
Hi @thmPedro, 

It doesn't seem right
