### ISSUE TITLE
Is Google Analytics still working?

### ISSUE THREAD

**Issue by mattpopovich** [cotes2020/jekyll-theme-chirpy#312]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones). (maybe #150)
- [x] I found the bug on the latest code of `master` branch.

## Describe the bug
Is Google Analytics still working or am I missing something / doing something stupid? 

### To Reproduce

1. Clone master
2. Change `google_analytics:id` in `_config.yml`
3. Build `bundle exec jekyll b`
4. Deploy to site (copy and paste `_site/`)

### Expected behavior
I expected to see tracking information show up in Google analytics. I don't see anything. I've *had* it working before so I know I had it configured correctly at one point. It looks like I don't see any tracking information since February 6, 2021. I know my site doesn't get *a ton* of traffic, but I, personally, visit it occasionally :) 🥴 

### Screenshots
I've done various sanity checks: 
* Checked https://tagassistant.google.com/
  * Looks like http://chirpy.cotes.info is working fine. Is it running the newest version of master? 
  * http://mattpopovich.com is not working. 
* Checked http://www.gachecker.com/
  * Nothing shows for http://mattpopovich.com
* Followed debugging [here](https://support.google.com/analytics/answer/1032399?hl=en)
  * I don't see `gtag.js` or `analytics.js` in page source
  * I dont' see `gtag.js` or `analytics.js` in Network tab of Developer tools in Google Chrome

### Software

- Ruby version: ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]
- Gem version: 3.2.3
- Bundler version: Bundler version 2.2.4
- Jekyll version: jekyll (4.2.0)

### Desktop
- OS: macOS 10.15.7
- Browser: Version 89.0.4389.114 (Official Build) (x86_64)

Thanks again for your work on this repo!

**Comment by cotes2020** [comment]
Hey there,

I checked the website you provided (<https://mattpopovich.com>) and found that the HTML content was not compressed, so I assume that when you build the website, you are in the develop mode, that is, the `production` environment is missing.

In develop mode, the website output will not contain **Google Analytics** code snippets (see: <https://github.com/cotes2020/jekyll-theme-chirpy/blob/3-3-stable/_includes/js-selector.html#L47-L56>). The advantage of this is to reduce the collection of local access data by **Google Analytics**.

To solve this problem, you only need to add the parameter `JEKYLL_ENV=production` before `bundle exec jekyll b`. BTW, the demo website is automatically deployed based on the latest tag, not `master` branch.

**Comment by mattpopovich** [comment]
Feel free to add the `RTFM` label. Thanks, cotes. Really appreciate your responses and their timeliness. 

> [Deploy on Other Platforms](https://github.com/cotes2020/jekyll-theme-chirpy/blob/e9b30361144761063882333d9b8f5efb1a014288/README.md#deploy-on-other-platforms)
>On platforms other than GitHub, we cannot enjoy the convenience of GitHub Actions. Therefore, we should build the site locally (or on some other 3rd-party CI platform) and then put the site files on the server.
>Go to the root of the source project, build your site by:
>`$ JEKYLL_ENV=production bundle exec jekyll b`
