### ISSUE TITLE
关于 img 的 lazy loading 逻辑上的问题

### ISSUE THREAD

**Issue by NichtsVonChaos** [cotes2020/jekyll-theme-chirpy#313]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [x] I found the bug on the latest code of `master` branch.

## Describe the bug
如果页面设置为 `dynamic_title : false`，根据 `page.html` 中的：

```html
    {% if page.dynamic_title %}
      <h1 class="dynamic-title">{{ page.title }}</h1>
      <div class="post-content">
        {{ content }}
      </div>
    {% else %}
      {{ content }}
    {% endif %}
```

内容将**不会**被 `<div class="post-content">` 包裹。

在 `refactor-content.html` 中存在 `{% if _content contains '<img src="' %}`，把所有 `img` 替换成了 lazy loading。但是在 `lozad.html` 中，由于 `const imgs = document.querySelectorAll('.post-content img');` 只会筛选 `post-content` 内的 `img`，这就导致了设置为 `dynamic_title : false` 的页面内的图像永远不会被加载。

### To Reproduce

BUG 描述应该已经很清晰了。

### Expected behavior

设置为 `dynamic_title : false` 的页面能够成功 lazy loading 图像。

### Software

- Ruby version: 2.7.2p137
- Gem version: 3.2.12
- Bundler version: 2.2.12
- Jekyll version: 4.2.0

### Desktop

- OS: Windows 10 20H2
- Browser: Chrome 89.0.4389.114 (64-bit)

**Comment by cotes2020** [comment]
谢谢，代码看的很仔细啊～
