### ISSUE TITLE
Page isn't rendered correctly

### ISSUE THREAD

**Issue by lyra95** [cotes2020/jekyll-theme-chirpy#314]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [ ] My question is based on the latest code of `master` branch.

## Description

OS: windows10 64
Version(branch): 3.3 stable

What I did:

0. Downloaded 3.3 stable branch and unzipped into my local directory
1. Created git repository [https://github.com/lyra95/lyra95.github.io](https://github.com/lyra95/lyra95.github.io)
2.  Edited `_config.yml` as follows:
`baseurl: '/lyra95.github.io'`
`title: Test `
`url: 'https://lyra95.github.io'`
Everything else unchanged.
3. Changed `.github\workflows\pages-deploy.yml.hook` to `.github\workflows\pages-deploy.yml`.
My default branch is `master`, and the value of `on.push.branches` is `master` indeed.
4. Executed `bundle exec jekyll s` and confirmed everything works perfectly on local.
5. commited and pushed. Confirmed the branch `gh-pages` generated.
6. Set the source of my github pages to `gh-page` branch.
![image](https://user-images.githubusercontent.com/65719177/115861702-12945180-a46e-11eb-9951-f5f738774bbd.png)
7. Confirmed [https://lyra95.github.io/](https://lyra95.github.io/) is not rendered correctly on both Firefox and Edge.
![image](https://user-images.githubusercontent.com/65719177/115862011-89314f00-a46e-11eb-8378-3a5d820215a7.png)
Even dark/light theme toggle button doesn't work.

Could you please give some advice on this problem?

**Comment by cotes2020** [comment]
Why set `baseurl`?

**Comment by lyra95** [comment]
> 
> 
> Why set `baseurl`?
Because that's what the comment says in the `_config.yml`?
`# Only if your site type is GitHub Project sites and doesn't have a custom domain,`
`# change below value to '/projectname'.`
`baseurl: '/lyra95.github.io'`

**Comment by lyra95** [comment]
I've rolled back `baseurl` to `''`. Still the same problem

**Comment by lyra95** [comment]
Oh, it takes time. Confirmed working successfully.

**Comment by cotes2020** [comment]
Do you really understand what `GitHub Project sites` is?

<https://docs.github.com/en/enterprise-server@2.21/pages/getting-started-with-github-pages/about-github-pages#types-of-github-pages-sites>
