### ISSUE TITLE
sw.js 报错

### ISSUE THREAD

**Issue by NichtsHsu** [cotes2020/jekyll-theme-chirpy#315]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [x] I found the bug on the latest code of `master` branch.

## Describe the bug

控制台出现以下报错：

```
Uncaught (in promise) TypeError: Failed to fetch                      sw.js:1
```

同时，控制台对 googletagmanager 发出警告：

```
The FetchEvent for "https://www.googletagmanager.com/gtag/js?id=G-RK9LRGVP0T" resulted in a network error response: the promise was rejected.
```

### Screenshots

![image](https://user-images.githubusercontent.com/35688135/117027950-c976b400-ad2f-11eb-9a62-5d1111812b27.png)

### Software

- Ruby version: 3.0.1p64
- Gem version: 3.2.15
- Bundler version: 2.2.16
- Jekyll version: 4.2.0

### Desktop

- OS: Manjaro (Lastest)
- Browser: Chrome 90.0.4430.93

**Comment by NichtsVonChaos** [comment]
merge 最新 commit 之后问题消失，关闭该 issue。

**Comment by NichtsHsu** [comment]
很抱歉重开一下issue，问题仍然存在
