### ISSUE TITLE
Questions regarding seo: in front matter of post

### ISSUE THREAD

**Issue by 0xprashant** [cotes2020/jekyll-theme-chirpy#32]
I want to ask a quick question about the seo:
That is being add automatically by your script init.sh
In the post front matter.
How can i use the seo: for better seo of my  site ??
What i need to specify in seo: row ?

**Comment by cotes2020** [comment]
You don't need to specify anything, this section is used to override the same-named field in `jekyll-seo-tag`.

**Comment by 0xprashant** [comment]
Thanks again cotes !!

**Comment by kanmeugne** [comment]
Sorry to bother, but I am struggling on this. My chirpy blog [kanmeugne.github.io](kanmeugne.github.io) does not seem to be visible on google. I have put the `{% seo %}` right before the `</head>` tag in `head.html` and I have added `jekyll-seo-tag` plugin (in `_config.yml`).

What am I missing ? Thank you for your help.
