### ISSUE TITLE
nokogumbo install error

### ISSUE THREAD

**Issue by cyberwr3nch** [cotes2020/jekyll-theme-chirpy#322]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Installation Error
![image](https://user-images.githubusercontent.com/55705969/116729859-b2ddff00-a9b5-11eb-8dde-9a473dfe4a93.png)

- When I try to execute the command, `bundle install`, every gem file is installing except this nokogumbo gem.
- Am I the only one facing this issue, please help me solve it
- Thanks.

**Comment by 5bhuv4n35h** [comment]
the nokogumbo has dependency issues in kali os  due to dependency issues. i have tired the same in ubuntu it worked with out any issue.

**Comment by cyberwr3nch** [comment]
great, its time for a distro jump then 💢 . Thanks @5bhuv4n35h
