### ISSUE TITLE
Images Only Rendering in Reader View

### ISSUE THREAD

**Issue by grantwforsythe** [cotes2020/jekyll-theme-chirpy#323]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar questions on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

Hi,

I noticed that images were no longer being displayed.

Upon further inspection, when viewing the contents of the webpage, the `src` attribute for the `img` tag is equal to `data:image/gif;base64,R01...` and the `data-src` contains the actual image URL so nothing is actually being rendered.  However, using Firefox's _reader view_, the `src` attribute is the same as the `data-src` and; therefore, displays the image. 

Please see the attached screenshots for more info.

Thanks!
## Screenshots
![image](https://user-images.githubusercontent.com/23422098/116815575-2efa5300-ab2c-11eb-9dcb-ad476faad437.png)
![image](https://user-images.githubusercontent.com/23422098/116815578-33bf0700-ab2c-11eb-8191-86f2ddfa0cb3.png)

## Desktop
- OS: Windows 10 (Latest)
- Browser: Firefox `88.0` and Chrome `90.0.4430.93` (offical build)

**Comment by NichtsVonChaos** [comment]
Sorry for using Google Translation.
I found that too. After reading the source code, I think the cause of the problem is as follows.
The theme will replace all `img` to lazy loading by using:
```liquid
{% if _content contains '<img src="' %}

  {% if site.img_cdn != '' %}
    {% assign img_path_replacement = '<img src="' | append: site.img_cdn | append: '/' %}
  {% else %}
    {% assign img_path_replacement = '<img src="' | append: site.baseurl | append: '/' %}
  {% endif %}
...
```
in `_includes/refactor-content.html`.
At the version `4.0.0`, the theme started using `_javascrpt/utils/img-extra.js` for lazy loading and popup. The theme doesn't use the files in `_javascript` in fact, but it uses `assets/js/dist/{common,home,post,page,preview,categories}.min.js` generated from `gulpfile.js/tasks/js.js` and `_javascript` folder.
You can find that only `postJs` and `pageJs` include `${JS_SRC}/utils/img-extra.js` in `gulpfile.js/tasks/js.js`, and you also can find the full code of `_javascrpt/utils/img-extra.js` only in `assets/js/dist/post.min.js` and `assets/js/dist/page.min.js`.
In the `_includes/js-selector.html` you will find:
```liquid
{% if page.layout == 'home'
    or page.layout == 'categories'
    or page.layout == 'post'
    or page.layout == 'page' %}
  {% assign type = page.layout %}
{% else %}
  {% assign type = "commons" %}
{% endif %}
```
That means that your `About` page will using `assets/js/dist/common.min.js` so that the `img` will not be load.

**Comment by grantwforsythe** [comment]
> Sorry for using Google Translation.

No need to apologize, @NichtsHsu.

Your response was very thorough. For me, I noticed that this issue persisted on pages with any layout and even for preview images defined in the front matter. 

Were you able to find a working solution for this issue?

**Comment by NichtsHsu** [comment]
I checked your blog repository [`grantwforsythe.github.io`](https://github.com/grantwforsythe/grantwforsythe.github.io) and found `js-selector.html` under your `_includes`. According to my undestanding of jekyll, if you put a file with same name in the same folder, jekyll will cover the theme's one. That means the theme's `js-selector.html` will not be used, and the lazy loading will also not be called.

**Comment by NichtsHsu** [comment]
Here is a working solution by enabling lazy loading on all pages.

* Copy the theme's [`_includes/js-selector.html`](https://raw.githubusercontent.com/cotes2020/jekyll-theme-chirpy/master/_includes/js-selector.html) and cover yours.
* At line 13 of `js-selector.html`, you will find:
  
  ```liquid
  {% if page.layout == 'post' or page.layout == 'page' %}
  <!-- image lazy-loading & popup -->
     <script async
        src="https://cdn.jsdelivr.net/combine/npm/lozad/dist/lozad.min.js,npm/magnific-popup@1/dist/jquery.magnific-popup.min.js"></script>
  {% endif %}
  ```
  
  Change it to:
  ```html
  <script async src="https://cdn.jsdelivr.net/combine/npm/lozad/dist/lozad.min.js,npm/magnific-popup@1/dist/jquery.magnific-popup.min.js"></script>
  ```

* Copy the full folder [`assets/js/dist`](https://github.com/cotes2020/jekyll-theme-chirpy/tree/master/assets/js/dist) of theme to your reposity. 
* Add a comma `,` and the content of `_javascrpt/utils/img-extra.js` (no whitespace version) to the end of `assets/js/dist/{common,home,preview,categories}.min.js` but before the last semicolon `;`. You can find the no whitespace version at the end of `page.min.js`, also can copy the following:

  ```js
  ,$(function(){var e="div.row";if(!($(`${e} img`).length<=0)){var o=document.querySelectorAll(`${e} img[data-src]`);const t=lozad(o);t.observe(),$(`${e} p > img[data-src],${e} img[data-src].preview-img`).each(function(){let e=$(this).next();var o="EM"===e.prop("tagName")?e.text():"",t=$(this).attr("data-src");$(this).wrap(`<a href="${t}" title="${o}" class="popup"></a>`)}),$(".popup").magnificPopup({type:"image",closeOnContentClick:!0,showCloseBtn:!1,zoom:{enabled:!0,duration:300,easing:"ease-in-out"}}),$(`${e} a`).has("img").addClass("img-link")}});
  ```

Anyway, I cannot guarantee whether there are side effects of enabling lazy loading on all pages.

**Comment by NichtsHsu** [comment]
You may use [gulp.js](https://gulpjs.com/) to generate `assets/js/dist/{common,home,preview,categories}.min.js`, but I haven't learned about it before.

**Comment by grantwforsythe** [comment]
> I checked your blog repository grantwforsythe.github.io and found `js-selector.html` under your `_includes`. According to my understanding of Jekyll, if you put a file with the same name in the same folder, Jekyll will cover the theme's one. That means the theme's `js-selector.html` will not be used, and the lazy loading will also not be called.

The `js-selector.html` file I have in my repo [changes the commands for `MathJax`](https://github.com/grantwforsythe/grantwforsythe.github.io/commit/3d1f823759b71c03f29a3097b2db277f11780eb6) but it doesn't appear to completely override the initial file. So this method won't work.

Enabling lazy loading on all pages did indeed solve the issue. 

Thanks for your solution.

**Comment by grantwforsythe** [comment]
Hey, @NichtsHsu. 

Sorry to bug you. I noticed a mistake because of my carelessness. 

Rather than updating each individual files in `assets/js/dist`, I just cloned your repo and made use of your files. 

![help](https://user-images.githubusercontent.com/23422098/117358901-b0cbe280-ae84-11eb-81f5-ef165c797ce6.png)

The date for a pinned post is in Chinese. Would this have been something you adjust in those asset files?

**Comment by NichtsHsu** [comment]
>  Would this have been something you adjust in those asset files?

Yes, I translated some English words in those files into Chinese. Not only that, I also changed icons from Font Awesome's to Iconfont's.

> But why wouldn't it affect the previous post?

 The theme uses a external function to generate abbreviations of months, which cannot be translated.

## Solve it

I created a pull request to your repo.

**Comment by grantwforsythe** [comment]
That is great, thank you.

**Comment by tvhahn** [comment]
> That is great, thank you.

I'm having the same problem! Are you able to get preview images showing now Grant?

If you don't mind, I'll fork your repo and repurpose it for my own site.

**Comment by grantwforsythe** [comment]
By enabling lazy loading on all pages it has resolved the issue, as was suggested by @NichtsHsu . There could potentially be some unforeseen consequences; however, as of yet, I haven't encountered any. 

> If you don't mind, I'll fork your repo and repurpose it for my own site.

Please, go right ahead @tvhahn .
