### ISSUE TITLE
Default posts still on homepage even tho i deleted them from _posts

### ISSUE THREAD

**Issue by sheeepdev** [cotes2020/jekyll-theme-chirpy#324]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [x] I found the bug on the latest code of `master` branch.

## Describe the bug
I deleted the default posts but they still appear on the home page. When I click them they give an error 404 which means they are deleted but they still don't disappear from the home page

### Expected behavior
They should have disappeared

### Software
I downloaded the source code and modified it and uploaded it to my blog repo at [sheeepdev/blog](https://github.com/sheeepdev/blog)

**Comment by grantwforsythe** [comment]
When I access your website,  I do indeed only see two posts - `Getting Started` and `First Post!` - which are both in your `_posts` directory. 

Clear your browser's cache and that should resolve your issue.

**Comment by sheeepdev** [comment]
> When I access your website, I do indeed only see two posts - `Getting Started` and `First Post!` - which are both in your `_posts` directory.
> 
> Clear your browser's cache and that should resolve your issue.

That did it, thanks.
