### ISSUE TITLE
Please provide a config entry or easy way to customize favicon

### ISSUE THREAD

**Issue by shawnlinboy** [cotes2020/jekyll-theme-chirpy#325]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There are no similar request on existing issues (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe
I created my site by [using a starter template](https://github.com/cotes2020/chirpy-starter/generate), and I've read through [this article](https://github.com/cotes2020/jekyll-theme-chirpy/wiki/Customize-the-favicon) tring to change my favicon. However, the whole `_site` folder is ignored from being commited to main branch although I know this was because this folder is auto-generated and should not be modified, so how where is the right path to modify my favicon and commit to the repository?

## Describe the solution you'd like
1. Already tried to modify icon files under `_site/assets/img/favicons` but the whole dictory is ignored from commiting to the repository.
2. Also I tried to switch to `gh-pages` branch to modify icon files under `assets/img/favicons` and commit them to  `gh-pages`, but the last `site-update` github action build will override my changes to it.

## Describe alternatives you've considered
Please provide a config entry or easy way to customize favicon.

## Additional context
No.

**Comment by NichtsVonChaos** [comment]
Why not modify icons under `assets/img/favicons` in the `master` branch?

**Comment by shawnlinboy** [comment]
> Why not modify icons under `assets/img/favicons` in the `master` branch?

Because the starter template did not come with a `assets/img/favicons` by default and my experience told me that I should not create any folders that I'm not familiar with. Maybe you missed it for the reason that an empty folder is not allowed to be added to a git commit? For now I've create a folder and put all my icons into it and it just works.

I believe [the description here in the document](https://github.com/cotes2020/jekyll-theme-chirpy/wiki/Customize-the-Favicon#download--replace) should be more specific, especially for a front-end new borns like me. I tried to modify th text to the following if you don't mind:

> Now, copy the remaining image files (`PNG` and `ICO`) to cover the original files in the folder `assets/img/favicons/` of your Jekyll site. If you can not find any  `assets` in the folder of your Jekyll site, feel free to follow the path `assets/img/favicons/` to create one.

This issue can be closed now, thanks for your great job of this theme.

**Comment by NichtsVonChaos** [comment]
Sorry but I'm not the maintainer of this theme but just a user. You may need to keep this issue open. 

By the way, according to my undestanding of jekyll, if you put the same file in a same folder, jekyll will cover the theme's one. Therefore, I think that creating a `assets/img/favicons/` folder and cover the images is the standard operation.

**Comment by shawnlinboy** [comment]
> Sorry but I'm not the maintainer of this theme but just a user. You may need to keep this issue open.
> 
> By the way, according to my undestanding of jekyll, if you put the same file in a same folder, jekyll will cover the theme's one. Therefore, I think that create a `assets/img/favicons/` folder and cover the images is the standard operation.

I can understand that, but as far as I know, many people who use jekyll to build blogs aren’t even developers, they’re probably just looking for a tutorial to do step by step, copy and paste those commands to build a persnal site, and jekyll is a smart choice. For me as I'm a android developer, I even do not know much about jekyll, so I believe the document should treat the reader even as a none-developer, the more detailed the better.

**Comment by j1mmyson** [comment]
Did you solve this problem??
I had the same problem as you, but I solved it by not creating copy of `browserconfig.xml`, `site.webmanifest` files.
So creating `assets/img/favicons/` folder at root and paste `*.png`, `favicon.ico` files. and it works well :)

**Comment by shawnlinboy** [comment]
> Did you solve this problem?? I had the same problem as you, but I solved it by not creating copy of `browserconfig.xml`, `site.webmanifest` files. So creating `assets/img/favicons/` folder at root and paste `*.png`, `favicon.ico` files. and it works well :)

No, and what you did is absolutely correct.

**Comment by RyuZinOh** [comment]
make sure while zipping its cote-name.png i guess, the file names that comes out decompressed changes so jekyll cant grasp it basically this chirpy theme, other just make a assets/img/favicons and place all thse decompressed items and build it, works !!
if u wanted to change tab icons
