### ISSUE TITLE
Post preview images broken after update to 4.0

### ISSUE THREAD

**Issue by zweilosec** [cotes2020/jekyll-theme-chirpy#327]
## Checklist

- [X] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [X] There are no similar reports on existing issues (including closed ones).
- [X] I found the bug on the latest code of `master` branch.

## Describe the bug

After updating my site from Chirpy 3.0.2 to 4.0.0 the images I had as post previews on the home page are now broken.  The post previews are enabled by two simple pieces of code that simply take the value of the `{{post.image}}` attribute and put into a small container in front of the post preview text.

in home.html:
```html
<div id="post-list">

{% for post in posts %}

  <div class="post-preview">
    <h1>
      <a href="{{ post.url | relative_url }}">{{ post.title }}</a>
    </h1>
    <!-- enable post preview images -->
    <div class="post-content">
      <div class="post-img-cnt">
        <a href="{{ post.url | relative_url }}">
          <img src="{{post.image}}" alt="{{post.title}} image" class="post-img">
        </a>
      </div>
      <!-- end post image preview -->
      <p>
        {% include no-linenos.html content=post.content %}
        {{ content | markdownify | strip_html | truncate: 200 }}
      </p>
    </div>
```

in home.scss
```css
    /* enable post preview images */
    .post-img-cnt{
      width:20%;
      float:left;
      padding:10px;
    }

    .post-img{
      max-width: 100%;
    }
    /* end post preview images */
```

I noticed after inspecting my page after it builds that the `src` attribute for each of the post preview images is a generic base64 1 pixel gif, while the true image source file is listed under the `src-data` attribute now, which is causing it to not be displayed.

![src vs src-data](https://user-images.githubusercontent.com/61819873/117515801-50f93880-af65-11eb-8e08-6d1b84b07f32.png)

### To Reproduce

1. Open the homepage of my website.

### Expected behavior

I expect the image I specify in the `{{post.image}}` attribute of each post to appear in the post preview on the home pages; 20% width, to the left of the preview text.

### Screenshots

Broken version:
![post preview](https://user-images.githubusercontent.com/61819873/117516215-818da200-af66-11eb-8ca8-cadeef706a1a.png)

mockup of working version:
![post preview2](https://user-images.githubusercontent.com/61819873/117516302-bd286c00-af66-11eb-9941-c6cb3f0e123e.png)

### Software

- Ruby version: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-gnu]
- Gem version: 3.1.2
- Bundler version: Bundler version 2.2.16
- Jekyll version:  * jekyll (4.2.0)

### Desktop

All OS, all browser

### Smartphone

All OS, all browser

### Additional context
Please look into this and let me know if this is something you can fix (or add as a feature to Chirpy! 😁).  Thank you!

**Comment by NichtsHsu** [comment]
Maybe this can help you: https://github.com/cotes2020/jekyll-theme-chirpy/issues/323#issuecomment-831362313
