### ISSUE TITLE
Error on GitHub: The jekyll-theme-chirpy theme is not currently supported on GitHub Pages.

### ISSUE THREAD

**Issue by salmanfarisvp** [cotes2020/jekyll-theme-chirpy#329]
## Checklist

- [X] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [X] There are no similar question on existing issues (including closed ones).
- [X] I searched the Internet for related problems, but still couldn't solve it.
- [X] My question is based on the latest code of `master` branch.

## Description
 
Error while running the GitHub action. 

![image](https://user-images.githubusercontent.com/11945360/117535557-f834a900-b013-11eb-9a65-858e11af618b.png)

**Comment by sys41x4** [comment]
Facing the same issue for around 7 hours of build and uploading in github.

**Comment by NichtsHsu** [comment]
Use `remote-theme: cotes2020/jekyll-theme-chirpy` instead of `theme: jekyll-theme-chirpy`.

**Comment by salmanfarisvp** [comment]
> Use `remote_theme: cotes2020/jekyll-theme-chirpy` instead of `theme: jekyll-theme-chirpy`.

Thanks, I tried it but same error while page building.

**Comment by NichtsHsu** [comment]
Sorry I can't figure out the reason. [My repo](https://github.com/NichtsHsu/nichtshsu.github.io) is a fork of [`cotes2020/jekyll-theme-chirpy`](https://github.com/cotes2020/jekyll-theme-chirpy) and works well, maybe you can try that if you are urgent.

**Comment by salmanfarisvp** [comment]
This is my repo, https://github.com/salmanfarisvp/salmanfarisvp.github.io I didn't used a fork.

**Comment by NichtsHsu** [comment]
I finally understand what happened to you. This theme use an "Action" to build site, but [this action in your site](https://github.com/salmanfarisvp/salmanfarisvp.github.io/actions/workflows/pages-deploy.yml) has never worked. The reason is that it uses `main` as branch name but your repo uses `master`. Finally, you should use the `gh-pages` branch which generated by action as your github pages -- I guess you are using `master` branch as your github pages currently.

**Comment by salmanfarisvp** [comment]
> you are suggested to fork it but not create a new repo

Yes, that's true. but is there any way to make it without having the fork. it should work, right?

**Comment by NichtsHsu** [comment]
Fork is a easy way to avoid problems and get future updates. Your new repo will work, but you may encounter some unpredictable problems like this time.

**Comment by salmanfarisvp** [comment]
> Fork is an easy way to avoid problems and get future updates

Sorry, how it will get future updates? since it's forked.

Thanks, and now the page is live, just change the CI into main to master.

**Comment by NichtsHsu** [comment]
If you fork the [chirpy-starter](https://github.com/cotes2020/chirpy-starter) as your repo and clone your repo to local, you can set chirpy-starter as upstream of your local repo by using:

```sh
git remote add upstream https://github.com/cotes2020/chirpy-starter
```

Then you can get future updates by `pull` operation:

```sh
git pull upstream master
```
