### ISSUE TITLE
How can i add the GA pageviews.

### ISSUE THREAD

**Issue by 0xprashant** [cotes2020/jekyll-theme-chirpy#33]
I want the numbers the time post has been viewed ?
If i am not wrong you provided a GA pageviews feature .But didnt find a way how can i enable the feature
This is on your website --
![IMG_20200226_193049](https://user-images.githubusercontent.com/40650455/75351741-a3a18400-58ce-11ea-8780-927d57c535af.jpg)

Currently this is on website --
![IMG_20200226_193714](https://user-images.githubusercontent.com/40650455/75352250-74d7dd80-58cf-11ea-8976-1298926c46cd.jpg)

Here is my website [0xprashant.github.io](http://0xprashant.github.io) 

If u need more information tell me

**Comment by cotes2020** [comment]
This is not a easy job, please read [the fucking comment](https://github.com/cotes2020/jekyll-theme-chirpy/blob/6d9c17a4824e2c826d04ae2e17caeb33b0fc6191/_config.yml#L58) in the `_config.yml`.

Here is the [post](https://blog.cotes.info/posts/fetch-pageviews-from-google-analytics/) I wrote while developing this feature.

**Comment by cotes2020** [comment]
see #1
