### ISSUE TITLE
Using starter package seems not to work on github pages

### ISSUE THREAD

**Issue by Calteo** [cotes2020/jekyll-theme-chirpy#332]
## Checklist

- [X] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [X] There are no similar reports on existing issues (including closed ones).
- [ ] I found the bug on the latest code of `master` branch.

## Describe the bug

Using the starter template and made url changes does not render a exspected result in the gh-pages output.

### To Reproduce

1. Create a respository from the starter template to https://github.com/Calteo/ChripStarter
2. Changed baseurl to '/ChripStarter'
3. Change url to https://calteo.github.io/ChripStarter
4. gh-pages get build
5. Output does only read "--- layout: home # Index page --" in index.html

### Expected behavior

To see at least an empty template.

### Software

- Ruby version: 
- Gem version: 
- Bundler version: 
- Jekyll version:

**Comment by cotes2020** [comment]
> - [x] I have read the tutorials and know the correct effect of the functional design.
> - [x] There are no similar reports on existing issues (including closed ones).

I don't buy it 😞

**Comment by ppd0523** [comment]
> > * [x]  I have read the tutorials and know the correct effect of the functional design.
> > * [x]  There are no similar reports on existing issues (including closed ones).
> 
> I don't buy it 😞

I have same problem. Only rendering "--- layout: home # Index page --"

**Comment by Repo-Kristx** [comment]
Same Problem me too

**Comment by PipeItToDevNull** [comment]
This is still an issue
