### ISSUE TITLE
关于光标定位的一点小问题

### ISSUE THREAD

**Issue by NichtsHsu** [cotes2020/jekyll-theme-chirpy#338]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

commons.scss 是这样定位左侧边栏的光标的位置的：

```scss
$top: -$offset * $tab-height + $tab-cursor-height / 2;
```

按照我的理解，如果要让光标居中，向下偏移的量应该是以 tab 的高度减去光标的高度后，剩下的空白位置的一半，也就是：

```scss
$top: -$offset * $tab-height + ($tab-height - $tab-cursor-height) / 2;
```

当然，在当前主题中，由于 `$tab-height: 3.2rem`，`$tab-cursor-height: 1.6rem`，刚好光标的高度占 tab 的一半，所以 `$tab-cursor-height / 2` 在数值上等于 `($tab-height - $tab-cursor-height) / 2`，使得二者的效果完全一样，但是从逻辑上来说，我认为后者才是正确的。

**Comment by cotes2020** [comment]
没错，的确是酱紫，这是计算方法上的漏洞。谢谢报告问题 ~
