### ISSUE TITLE
Gitignore

### ISSUE THREAD

**Issue by ianyepan** [cotes2020/jekyll-theme-chirpy#343]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [x] I found the bug on the latest code of `master` branch.

## Describe the bug

The `.gitignore` file specifies to not track `.*` with an exception for `.github`. I believe `.gitignore` itself should also be an exception to the `.*` list. This means the `.gitignore` should start like this:

```text
# hidden files
.*
!.github
!.gitignore  # this line was missing, I believe it was a mistake!

# bundler cache
...
...
```

**Comment by cotes2020** [comment]
The file `.gitignore` is already in the repo, so there is no need to add this line:

```
!.gitignore 
```

But `!.github` is necessary because the entry `.github` is a folder and Git will automatically keep track of changes when files inside it are added/removed.

**Comment by ianyepan** [comment]
Thanks for getting back.

> The file .gitignore is already in the repo, so there is no need to add this line.

That's true, but for people who forked (or copy the files from) the repo and later cloned to local machines, there could be problems of git tracking unnecessary files.

**Comment by cotes2020** [comment]
Fork this repo and then clone it locally will not cause file tracking problems.

And You mentioned that "copying files from this repository" is an interesting detail. If I understand correctly, this should mean downloading the zip from github, uncompressing it, and creating a new repo with the `git init` command. There is indeed the possibility of missing `.gitignore`.

**Comment by ianyepan** [comment]
> If I understand correctly, this should mean downloading the zip from github, uncompressing it, and creating a new repo with the git init command. There is indeed the possibility of missing .gitignore.

Yes, that would be an edge case indeed.

By the way, thank you very much for maintaining this theme. Chirpy is truly practical and lovely at the same time!
