### ISSUE TITLE
Lastmod panel doesn't show

### ISSUE THREAD

**Issue by T-Mux** [cotes2020/jekyll-theme-chirpy#346]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [ ] My question is based on the latest code of `master` branch.

## Description

I've built my blog for a long time and written a few posts, but there's no lastmod panel on my page. Confusing...

**Comment by jimmitchell** [comment]
Was curious about this myself and found that Post front matter must include a "last_modified_at" value. E.g. "last_modified_at: 2021-06-05 11:20:00 +/-0800"

**Comment by T-Mux** [comment]
@jimmitchell Thx man, but I don't think it's a good way... I failed 🤣

**Comment by T-Mux** [comment]
Just run `dump_lastmod.sh` file, this ques will be closed.
