### ISSUE TITLE
How to disable scroll animation when user tap TOC in a post

### ISSUE THREAD

**Issue by Huang-Libo** [cotes2020/jekyll-theme-chirpy#351]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

If a _blog post_ has a lot of images , when the user clicks TOC, however, it didn't jump to the right position.

The reason for this problem is that the loading of the image changes the frame of the page during the scrolling animation. 

This issue can be avoided if the page can jump without animation. 

So, here's my question: how to turn off the scrolling animation when user tap TOC ? 

- Demo post (Using  _chirpy theme_ **with** scroll animation )：
    - <https://huang-libo.github.io/posts/Objective-C-Runtime-Changes-in-iOS-14/> ,  you can try to recurrence the issue by clicking the last item in the TOC.
    - On GitHub, there is no animation for the jump inside the page, so you can jump to the exact location, demo ： <https://github.com/Huang-Libo/Huang-Libo.github.io/blob/master/_posts/2021-05-17-Objective-C-Runtime-Changes-in-iOS-14.md> 
- Demo post (Using  _chirpy theme_ **without** scroll animation ): 
    - <https://onevcat.com/2019/12/2019-final/>

Lastly, thanks for the amazing theme, really appreciate your hard work!

**Comment by NichtsHsu** [comment]
平滑滚动是写在 `_javascript/utils/smooth-scroll.js` 里的，要禁用该脚本，可以先把 `gulpfile.js/tasks/js.js` 里

```js
const postJs = () => {
  return concatJs([
    `${JS_SRC}/commons/*.js`,
    `${JS_SRC}/utils/img-extra.js`,
    `${JS_SRC}/utils/timeago.js`,
    `${JS_SRC}/utils/lang-badge.js`,
    `${JS_SRC}/utils/checkbox.js`,
    `${JS_SRC}/utils/copy-link.js`,
    // 'smooth-scroll.js' must be called after ToC is ready
    `${JS_SRC}/utils/smooth-scroll.js`
  ], 'post'
  );
};
```

的 `${JS_SRC}/utils/smooth-scroll.js` 删掉，然后用 `npm install -g gulp-cli` 安装 gulp.js，使用 `gulp` 命令重新生成 `assets/js/dist` 目录下的那几个 `*.min.js` 文件。

**Comment by Huang-Libo** [comment]
基于 @NichtsHsu  的回答做补充：

如果 theme 是使用 gem 添加的，则先在自己项目的根目录添加 `_javascript` 和 `gulpfile.js` 目录，然后修改 `gulpfile.js/tasks/js.js`，删除 `${JS_SRC}/utils/smooth-scroll.js` 这一行。

如果没安装 `gulp` ，先安装相关 npm 包：
```
npm install gulp-cli -g
npm install gulp -D
npm install --save-dev gulp-concat
npm install --save-dev  gulp-rename
npm install --save-dev  gulp-uglify
npm install --save-dev  gulp-insert
```

最后，在项目的根目录执行 `gulp` 命令，即可重新生成 `assets/js/dist `目录下的那几个 `*.min.js` 文件。

**Comment by Huang-Libo** [comment]
上述方法需要改 theme 源码，有没有什么方法可以把 smooth scroll 设置成可配的呢？

比如在 `_config.yml` 中通过一个布尔值来设置，不知是否可行？

还有，如果用户真想用 smooth scroll，图片较多时，滚动的位置就不准确，这个 bug 该怎么解呢？

**Comment by cotes2020** [comment]
Hi @Huang-Libo, 平滑滚动是可以明显提升用户体验的一个特性，所以不曾想过、当然将来也不会关闭它，假如做为配置项那就是等于开倒车了。。。

滚动位置不准这个是由于图片加载后浏览器会重绘页面元素，导致滚动部分的逻辑计算位置也会跟着出现偏差，目前我已经有思路去改进这个体验了，请关注后续的 commit。
