### ISSUE TITLE
override variables.scss in chirpy-starter template

### ISSUE THREAD

**Issue by adrien-perello** [cotes2020/jekyll-theme-chirpy#355]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

**How can I override the ```$sidebar-width``` variables?**

I managed to change some of the css style by doing:
> Creare a new file /assets/css/style.scss
> And then add the following content:
>   ```@import "{{ site.theme }}";```
>   ```// add your style below```

but if i can't override ```/_sass/addon/variables.scss```, either through the above manipulation or by manually creating  ```/_sass/addon/variables.scss```

Do i have to copy all the code that contains```$sidebar-width``` in ```/assets/css/style.scss``` and then modify it manually? Is there not an easier way?

**Comment by cotes2020** [comment]
Hi @adrien-perello,

I'm sorry to tell you that so far there is no easier way to do this, but in the future I will add a file to make it easier for users to change CSS variables.

**Comment by adrien-perello** [comment]
Thank you so much for your reactivity 😊
Just to make sure I understand properly:
**To change the sidebar dimension**, we have to:
1) create a ```assets/css/variables-hook.scss```
2) add ```$sidebar-width:``` **[new size here];**

Or do we have to add the line in ```assets/css/style.scss```?

I tried both, but it did not seem to work (I'm using the chirpy-starter template) Do I have to change anything in ```_config.yml``` maybe?

**Comment by cotes2020** [comment]
> I'm using the chirpy-starter template...

This new feature will not be available until the next release (possibly in `v4.1.0`).
