### ISSUE TITLE
Bundle install ruby version issue

### ISSUE THREAD

**Issue by Fierythunder** [cotes2020/jekyll-theme-chirpy#357]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [x] I found the bug on the latest code of `master` branch.

## Describe the bug

Bundler found conflicting requirements for the
Ruby version:
  In Gemfile:
    Ruby

jekyll-theme-chirpy was resolved to 4.0.2,
which depends on
      Ruby (>= 2.4, < 3.0)

Ruby (>= 2.4, < 3.0), which is required by gem
'jekyll-theme-chirpy', is not available in the
local ruby installation

### To Reproduce
bundle install

### Expected behavior

To install successfully

### Software

- Ruby version: 3.0.1p64 
- Gem version: 3.2.15
- Bundler version: 2.2.21
- Jekyll version: 4.2.0

**Comment by cotes2020** [comment]
The log has already told you that the local Ruby version is out of the specified range (>= 2.4, < 3.0), so how can you ignore it and think it's a bug?

**Comment by Fierythunder** [comment]
The error was resolved when i changed this from
```
spec.required_ruby_version = [">= 2.4", "< 3.0"]
```
to
```
spec.required_ruby_version = [">= 2.4", "< 3.1"]
```

**Comment by Maytha8** [comment]
I just removed the version requirement from `jekyll-theme-chirpy`; inside the Gemfile, replace the following:
```
gem "jekyll-theme-chirpy", "~> 4.1", ">= 4.1.0"
```
with this:
```
gem "jekyll-theme-chirpy"
```
