### ISSUE TITLE
How to remove the Trending Tags and recent update ?

### ISSUE THREAD

**Issue by kavishgr** [cotes2020/jekyll-theme-chirpy#36]
I only need the table of contents on the right side of a post. I grepped for 'trending tags' and if i remove one of them, jekyll won't serve.

**Comment by kavishgr** [comment]
I figured it out.

**Comment by AwlsomeAlex** [comment]
@kavishgr How'd you do it?

**Comment by kavishgr** [comment]
I don't remember what i did back then. I don't use that theme anymore. Sorry man.

**Comment by cotes2020** [comment]
@AwlsomeAlex by commenting the following:
https://github.com/cotes2020/jekyll-theme-chirpy/blob/0899a151b92d3c751204a516fc2f9863969d601d/_layouts/page.html#L24

https://github.com/cotes2020/jekyll-theme-chirpy/blob/0899a151b92d3c751204a516fc2f9863969d601d/_layouts/post.html#L122
