### ISSUE TITLE
Selected tab effect does not align with tab name

### ISSUE THREAD

**Issue by mitsufune** [cotes2020/jekyll-theme-chirpy#363]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description
I added 3 new tabs but the selected tab effect does not align with the tab name. Is there a way to put them back in alignment?
![image](https://user-images.githubusercontent.com/85979326/125368952-e7a30500-e3ad-11eb-8204-0f2973225e66.png)

**Comment by mitsufune** [comment]
On top of that, is there also a way to wrap the data in the table itself rather than the whole table getting a horizontal scroll?
![image](https://user-images.githubusercontent.com/85979326/125386249-8a6b7b80-e3ce-11eb-8504-83c393baab22.png)

**Comment by NichtsHsu** [comment]
Just now I cloned the lastest code of master branch and added two tabs to test, no bug appeared.
![image](https://user-images.githubusercontent.com/35688135/125797931-68865883-954b-4087-a320-a3008b222739.png)

Maybe you need to provide more informations about your site.

**Comment by mitsufune** [comment]
The site can be accessed at https://animeaudioarchive.github.io and the code is available at https://github.com/animeaudioarchive/animeaudioarchive.github.io if you wish to scrutinize the code and see where I went wrong.

**Comment by NichtsHsu** [comment]
I noticed `$tab-count: {{ site.tabs | size | plus: 8 }};` in your `assets/css/style.scss` which defaults `$tab-count: {{ site.tabs | size | plus: 1 }};`. You may think that you have 8 tabs so you need to call `plus` with 8. But no, that's wrong. In any case, `site.tabs | size` means the number of your tabs under `_tabs` folder, therefore, it will be 7 in your case. Just keep the default `plus: 1` for home page, and all will be OK.

**Comment by mitsufune** [comment]
Okay. I'll implement the change and report back.

**Comment by mitsufune** [comment]
It works. The effect is now synced with the tab names. 

I still need help with the table and how to wrap the data inside it similar to this:

![image](https://user-images.githubusercontent.com/85979326/126060077-3d914ffa-0565-451e-ba1e-1a0dcaba31f4.png)

**Comment by NichtsHsu** [comment]
There is not a simple way to change build-in styles of this theme. If you want to change css, please download and copy the full [`_sass`](https://github.com/cotes2020/jekyll-theme-chirpy/tree/master/_sass) folder to your own repo, and then delete line 21 `white-space: nowrap;` at the file `_sass/addon/module.scss`.

**Comment by mitsufune** [comment]
Okay thanks! I'll implement the change and report back.

**Comment by mitsufune** [comment]
Thanks a lot for the assist! This issue can be closed now.
