### ISSUE TITLE
Multi-line formula are not supported.

### ISSUE THREAD

**Issue by cabinz** [cotes2020/jekyll-theme-chirpy#370]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [x] I found the bug on the latest code of `master` branch.

## Describe the bug

The multi-line formula are not supported by the template.
I use typora with Katex where "\\" can produce a new line switching, which doesn't work in MathJax.
Then I tried "\\\\" which works for MathJax on Hexo, but still got nothing work.

* complete MathJax code:
  `\begin{equation} \boldsymbol{q^i} = W^q \boldsymbol{a^i} \\\\ \boldsymbol{k^i} = W^k \boldsymbol{a^i} \\\\ \boldsymbol{v^i} = W^v \boldsymbol{a^i} \end{equation}`

### To Reproduce

''\\\\" and "\\" cannot produce a new line switching.

### Expected behavior

''\\\\" or "\\" can produce a new line switching in the blog post page.

### Screenshots

![image](https://user-images.githubusercontent.com/60537086/125740628-0f14fcff-75dc-4d37-9ad4-c75cc9318f7a.png)

### Software

- Ruby version: 
- Gem version: 
- Bundler version: 
- Jekyll version:

**Comment by cotes2020** [comment]
Hi @cabinz, 

Please provide a complete MathJax code to reproduce the problem, otherwise your report will be considered invalid

**Comment by cabinz** [comment]
> Hi @cabinz,
> 
> Please provide a complete MathJax code to reproduce the problem, otherwise your report will be considered invalid

Thx 4 reply. I've update the complete MathJax code onto the issue. Plz check it out.

**Comment by cotes2020** [comment]
Change the environment `equation` to [`eqnarray`](http://www.emerson.emory.edu/services/latex/latex_34.html#SEC34) and it will work.

My test code:

```
$$
\begin{eqnarray}
\boldsymbol{q^i} = W^q \boldsymbol{a^i} \\\\ \boldsymbol{k^i} = W^k \boldsymbol{a^i} \\\\ \boldsymbol{v^i} = W^v \boldsymbol{a^i}
\end{eqnarray}
$$
```

**Comment by cabinz** [comment]
> Change the environment `equation` to [`eqnarray`](http://www.emerson.emory.edu/services/latex/latex_34.html#SEC34) and it will work.
> 
> My test code:
> 
> ```
> \begin{eqnarray}
> \boldsymbol{q^i} = W^q \boldsymbol{a^i} \\\\ \boldsymbol{k^i} = W^k \boldsymbol{a^i} \\\\ \boldsymbol{v^i} = W^v \boldsymbol{a^i}
> \end{eqnarray}
> ```

This environment `eqnarray` seems to cause the formula to align to the right (same as environment `align`).
What if i want to center the multi-line formula？
Thx a lot.

**Comment by cotes2020** [comment]
I don't see that it's aligned to the right, it's centered when I test the code on the `master` branch

**Comment by cabinz** [comment]
> I don't see that it's aligned to the right, it's centered when I test the code on the `master` branch

Try the MathJax code below:
```
\begin{eqnarray}
    E[m] = E[\frac{1}{N}\sum_n x^n] = \frac{1}{N}\sum_n E[x^n] = \mu \\
    Var[m] = \frac{\sigma^2}{N}
\end{eqnarray}
```

![image](https://user-images.githubusercontent.com/60537086/125775131-6fb7d37c-9769-4947-91af-f203c0804b87.png)

**Comment by cotes2020** [comment]
You should learn to find answers from Google for such questions:

For center alignment, add an `&` at the beginning of each math formula,

```
\begin{eqnarray}
 &  math formula 1 \\
 &  math formula 2
\end{eqnarray}
```

BTW,  for left alignment, add double `&` before each formula.

```
\begin{eqnarray}
 &&  math formula 1 \\
 &&  math formula 2
\end{eqnarray}
```

**Comment by cabinz** [comment]
> You should learn to find answers from Google for such questions:
> 
> For center alignment, add an `&` at the beginning of each math formula,
> 
> ```
> \begin{eqnarray}
>  &  math formula 1 \\
>  &  math formula 2
> \end{eqnarray}
> ```
> 
> BTW, for left alignment, add double `&` before each formula.
> 
> ```
> \begin{eqnarray}
>  &&  math formula 1 \\
>  &&  math formula 2
> \end{eqnarray}
> ```

Thx u so much.
I've always thought that a single '&' was left-aligned operation lol.
