### ISSUE TITLE
Can't change copy post link alert.

### ISSUE THREAD

**Issue by cobosdev8** [cotes2020/jekyll-theme-chirpy#371]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [x] I found the bug on the latest code of `master` branch.

## Describe the bug
In /_javascript/utils/copy-link.js file, i have replaced line 16 's code from `alert("Link copied succesfully!")` with `alert("Copiado")`, just because mi website is in Spanish. When i run 'bundle exec jekyll s' and then i go to my webpage and copy the link, the alert is still <<Link copied succesfully!>>. Thanks for reading

### To Reproduce

1. Go to line 16 in '/_javascript/utils/copy-link.js' .
2. Replace <<Link copied succesfully!>> with <<Copiado>> and save.
3. Run a test server with `bundle exec jekyll s`.
4. Go to a post, copy a link, and see how the alert is still <<Link copied successfully!>>.

### Expected behavior
The alert in the browser should be <<Copiado>> instead of <<Link copied succesfully!>>.

### Screenshots
Not necessary.

### Software
- Ruby version: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
- Gem version: 3.1.2
- Bundler version: 2.2.23
- Jekyll version: 4.2.0

### Desktop
- OS: [Windows 10 Home 20H2]
- Browser: [Brave 1.26.77 (64-bit)]

**Comment by cotes2020** [comment]
Hi @cobosdev8,

Changing the source code is not enough, you also need to compile the new JS file using [`Gulp`](https://gulpjs.com/)
