### ISSUE TITLE
Progressive Web Apps

### ISSUE THREAD

**Issue by Fierythunder** [cotes2020/jekyll-theme-chirpy#376]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

Can you please add Progressive Web Apps (PWA) so that we can install our website as app
https://web.dev/progressive-web-apps

**Comment by cotes2020** [comment]
https://github.com/cotes2020/jekyll-theme-chirpy/releases/tag/v2.2 😓

**Comment by Fierythunder** [comment]
> https://github.com/cotes2020/jekyll-theme-chirpy/releases/tag/v2.2 😓

I mean it is showing only add to homescreen not install
