### ISSUE TITLE
Can't parse the content of the home page

### ISSUE THREAD

**Issue by goibright** [cotes2020/jekyll-theme-chirpy#378]
## Checklist

- [ ] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [ ] There are no similar question on existing issues (including closed ones).
- [ ] I searched the Internet for related problems, but still couldn't solve it.
- [ ] My question is based on the latest code of `master` branch.

## Description

Deployed to GitHub to access * *. GitHub. IO, the home page cannot be displayed normally, only the following fonts are displayed. What's wrong:
--- layout: home # Index page ---

**Comment by NichtsHsu** [comment]
Did you finish [these](https://github.com/cotes2020/jekyll-theme-chirpy#deployment)?
