### ISSUE TITLE
Disqus not load

### ISSUE THREAD

**Issue by hacker342** [cotes2020/jekyll-theme-chirpy#379]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

Hello. If i turn on disqus on your template. I see message: Unable to load disqus. If you moderator please read docs. I dont know how to turn on disqus(

**Comment by hacker342** [comment]
i fix it.

**Comment by safinakib** [comment]
> i fix it.

how
