### ISSUE TITLE
缩小比例较高时，左侧边栏文字下沉比较严重

### ISSUE THREAD

**Issue by NichtsHsu** [cotes2020/jekyll-theme-chirpy#380]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [x] I found the bug on the latest code of `master` branch.

## Describe the bug

缩小页面比例，左侧边栏中的文字不会居中，会比图标更矮一点，如图所示：
![image](https://user-images.githubusercontent.com/35688135/126819231-0f338fba-8aae-4edb-9c70-c9bda927ad5d.png)![image](https://user-images.githubusercontent.com/35688135/126819248-1b28fb1e-ced1-4e2d-a9e7-057b669bf09d.png)

改成中文就更明显了：
![image](https://user-images.githubusercontent.com/35688135/126819332-5286ef3f-36a4-4ddc-b9be-24fa4ecd2bfd.png)

虽然一般人不会真的缩这么小，不过强迫症有点难受，作者大大有时间修一下就再感激不过了，懒得修倒也无所谓就是了

### Software

- Ruby version:  2.7.2p137
- Gem version:  3.2.12
- Bundler version:  2.2.16
- Jekyll version:  4.2.0

### Desktop
- OS: [e.g. macOS 10.15.6] Windows 10
- Browser: [e.g. Chrome 85.0.4183.83 (64-bit)] Chrome 92.0.4515.107

**Comment by cotes2020** [comment]
我缩放到 Chrome 最的小比例 25% 都没发现这个问题，应该是你自定义 CSS 导致的，请自行改善

![zoom-out](https://user-images.githubusercontent.com/11371340/126938158-7fa2f65d-909c-455c-9afa-5792eadd4fa6.png)

**Comment by NichtsHsu** [comment]
@cotes2020 您好，图一和图二是使用您的 Live Demo 截图的，并非是我自己的网页，只有图三是我自己的

**Comment by NichtsHsu** [comment]
> 我缩放到 Chrome 最的小比例 25% 都没发现这个问题，应该是你自定义 CSS 导致的，请自行改善

对的，我最后发现问题所在是我调整了 `#sidebar ul .nav-item .nav-link>i` 的 `font-size: 0.6rem` 到 `font-size: 1rem` 造成的，如果将 live demo 的对应属性也调整成 1rem 也能复现：

![image](https://user-images.githubusercontent.com/35688135/127019640-a6328dc2-e15e-4b56-aaa5-3810480f56af.png)

虽然找到的问题所在，但是我还是不太明白为什么
