### ISSUE TITLE
index.html not render. how to fix it?

### ISSUE THREAD

**Issue by XerosLab** [cotes2020/jekyll-theme-chirpy#383]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description
my GitHub Pages link : https://xeroslab.github.io
this GitHub Pages repository link : https://github.com/XerosLab/xeroslab.github.io

if I connect index page, just show "--- layout: home # Index page ---"
![Screen Shot 2021-07-28 at 12 35 27 PM](https://user-images.githubusercontent.com/77450463/127259566-039d8275-371e-424c-a1d1-7de00a7078e1.png)

but if i connect local server, its work
![Screen Shot 2021-07-28 at 12 38 33 PM](https://user-images.githubusercontent.com/77450463/127259829-a09395fb-0269-4a61-ab0f-859591b2c5e3.png)

What's wrong this?

**Comment by NichtsHsu** [comment]
Firstly, change your branch name from `main` to `master`, also you can modify `.github/workflows/pages-deploy.yml` line 5 from `- master` to `- main`.

Then, push some commits to trigger action and automatically generate `gh-pages` branch, and set `gh-pages` branch as the source of your github pages.

**Comment by XerosLab** [comment]
```
name: 'Automatic build'
on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
...
```
 I modified file `/.github/workflows/pages-deploy.yml` as above.

![Screen Shot 2021-07-28 at 1 31 23 PM](https://user-images.githubusercontent.com/77450463/127264045-d89ce7d3-2259-444c-b14c-3c6997a2c999.png)

I think i have a new branch. What am I supposed to do now?

**Comment by XerosLab** [comment]
sorry my bad English.. and I'm not good at using github.

**Comment by cotes2020** [comment]
> - [x]  I have read the tutorials and know the correct effect of the functional design.

Don't lie, okay? Please finish the tutorial.
