### ISSUE TITLE
Website builds but home is blank and many links are broken

### ISSUE THREAD

**Issue by ImperialSquid** [cotes2020/jekyll-theme-chirpy#385]
## Checklist
- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [x] I found the bug on the latest code of `master` branch.

## Describe the bug
The website builds correctly. However, the homepage has no content in it. The sidebar is empty excluding a link to home. Pages work however posts and tags are both missing (the tags links on the side are broken links) See screenshot below.

### To Reproduce
Followed the tutorial in full. (Had to edit htmlproofer parameter in test.sh to get past test phase, added --url_ignore "/")
Added some test pages and posts to test
Repo is at https://github.com/ImperialSquid/ImperialSquid.github.io
Website is https://imperialsquid.github.io/

### Expected behavior
Pages should be built correctly

### Screenshots
![Screenshot(18)](https://user-images.githubusercontent.com/44560551/127293470-8e62ac7d-28a0-4122-99a2-d465643b0216.png)

### Software

- Ruby version: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x64-mingw32]
- Gem version: 3.2.22
- Bundler version: Bundler version 2.2.24
- Jekyll version: jekyll 4.2.0 (ran with jekyll -v instead)

### Desktop
- OS: Windows 10
- Browser: Firefox 90.0.2

### Smartphone
NA

**Comment by cotes2020** [comment]
> Followed the tutorial in full ...

You haven't even completed the steps in the first section "Installation", your repo is almost blank, so there is no doubt that your website is also blank
