### ISSUE TITLE
Modifying the top navigation bar more intuitively

### ISSUE THREAD

**Issue by XerosLab** [cotes2020/jekyll-theme-chirpy#386]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There are no similar request on existing issues (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Describe the solution you'd like
When view posts that are currently written to  blog, they appear in the top bar as the "Home > Post Name"

![Screen Shot 2021-07-29 at 17 00 06](https://user-images.githubusercontent.com/77450463/127455069-1a044cba-f8c2-47b0-8c7d-8fd2b294ec13.png)

I'd like to change the top navigation bar a little more intuitively as shown below.

![Screen Shot 2021-07-29 at 17 04 56](https://user-images.githubusercontent.com/77450463/127456599-6b330dac-9f23-405a-961b-34fe3f5d4307.png)

**Comment by cotes2020** [comment]
Personalization is not our business, please read the source code to achieve it.
