### ISSUE TITLE
Hyphens and Incorrect Rendering on Tab

### ISSUE THREAD

**Issue by mitsufune** [cotes2020/jekyll-theme-chirpy#387]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

![image](https://user-images.githubusercontent.com/85979326/127496207-33c37d43-283d-4e26-b299-b53a5bc00d65.png)

Since a few days ago, the tab would start to render hyphens and failed to render the Japanese characters correctly. If there a way to fix this?

Source code on https://github.com/animeaudioarchive/animeaudioarchive.github.io

**Comment by NichtsHsu** [comment]
Do not use cjk file name such as `日本語.md`, just `japanese.md` and use `title: 日本語` on front matter.

**Comment by mitsufune** [comment]
CJK filenames rendered fine 11 days ago and I want native speakers to be able to read in kanji. Furthermore, this doesn't solve the hyphen issue.

**Comment by NichtsHsu** [comment]
> Furthermore, this doesn't solve the hyphen issue.

No, it works well.

![image](https://user-images.githubusercontent.com/35688135/127518464-7dfd9eb5-fd1f-4931-8b07-7955cbd4c179.png)

**Comment by NichtsHsu** [comment]
Sorry for my mistakes.

Here is a non-compatible update ["Add layout localization"](https://github.com/cotes2020/jekyll-theme-chirpy/commit/a4debef8f231fe85eff4b1fc2fa17be3027720ba) which was commited 8 days ago. In this commit, the theme turned to use `data/locales/[lang].yml` for localization. You need to write a `ja.yaml` based on `en.yml` and add your tabs into this file, and then use `lang: ja` at `_config.yml`.

**Comment by mitsufune** [comment]
Got it. I'll apply changes and report back.

**Comment by mitsufune** [comment]
Issue fixed. Thanks a lot!
