### ISSUE TITLE
Adding a link to the tabs menu on left

### ISSUE THREAD

**Issue by Pinnaclenetworking** [cotes2020/jekyll-theme-chirpy#39]
I have worked with this theme for a while and getting most features to work properly, however on the site http://pinnaclenetworking.com I cannot get http://pinnaclenetworking.com/tabs/HelpDesk to appear in the menu..... I'm not exactly sure why.... The sidebar page seems to look for the tab folder and use what ever is there and lists them..... Is there a trick?

**Comment by cotes2020** [comment]
If you read the source code, you can easily find out the "trick": add the new tab meta into `_data/tabs.yml`.

**Comment by Pinnaclenetworking** [comment]
Thank you for this, this was all I was looking for, sorry for bothering, just learning this markup now

**Comment by faisaldarbar** [comment]
Could not find `_data/tabs.yml` in the source code

**Comment by sublimeclemency** [comment]
yes, faisaldarbar. i'm confused

**Comment by NichtsHsu** [comment]
Tabs are moved to `_tabs/`.
