### ISSUE TITLE
Automatic build failed during Setup Ruby phase

### ISSUE THREAD

**Issue by ijleesw** [cotes2020/jekyll-theme-chirpy#393]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

TL;DR
After following the tutorial, automatic build failed during `Setup Ruby` phase. Error log is on the first screenshot.
My `pages-deploy.yml` is at https://github.com/ijleesw/ijleesw.github.io/blob/master/.github/workflows/pages-deploy.yml

--

I cloned master branch of the repo and followed tutorial from `Fork on GitHub` to `Deployment`.
But continuous-delivery failed during `Setup Ruby` phase.
<img width="1055" alt="스크린샷 2021-08-08 오후 11 19 10" src="https://user-images.githubusercontent.com/30719198/128635230-e5e700d9-ee93-4293-b2be-1765e43dc342.png">

I checked `pages-deploy.yml` and changed `bundler-cache` to false (while not knowing what it means) but then the process failed during `Build Site`.
<img width="1053" alt="스크린샷 2021-08-08 오후 11 21 42" src="https://user-images.githubusercontent.com/30719198/128635304-ffe7c93f-55b6-455e-90ee-41f81311f380.png">

It seems like something's wrong with github side but I'm not sure - I could have done something wrong.
Could anyone check what's the problem?

**Comment by arunshariharan** [comment]
Hey it might be too late, but if you expand on the `Setup Ruby` option in your first image you might know more details about the issue. I had the same when I ran it for the first time, and I had to run `bundle lock  --add-platform x86_64-linux` since by default it supports only `["x64-mingw32"]` if you are developing from windows. 

Once you do that, you also have to run `bundle install` locally, so the newly added gems will be written to `gemfile.lock` 

Try those 2 things and see if that helps? Cheers!

**Comment by ijleesw** [comment]
@arunshariharan 
In fact, I didn't notice I can expand command output in `Setup Ruby`. Thanks to your comment, I could fix it :)

For those who might have the same problem; Expand and you will see more descriptions...
<img width="1032" alt="스크린샷 2021-09-06 오후 11 05 31" src="https://user-images.githubusercontent.com/30719198/132232543-65536864-dbde-43e1-b597-13ea30b3d89e.png">

**Comment by SilentGlasses** [comment]
Just ran into this issue.  Would be nice to have this in the documentation so it can be addressed from the onset. Thanks for the solution.
