### ISSUE TITLE
Adding a 'Copy' button for the Code Snippet

### ISSUE THREAD

**Issue by NiallLDY** [cotes2020/jekyll-theme-chirpy#396]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There are no similar request on existing issues (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

Sometimes there are multiple lines of code in the code snippet. When I want to copy these codes, I need to manually select them and then click 'Copy'. Moreover, when the width of a line of code exceeds the width of the code snippet block, copying will become very troublesome, especially on mobile devices, where we need to drag with our fingers.

## Describe the solution you'd like

I think it would be better to add a **copy button** for the code snippet. For example, add a small copy Icon on the upper right side of the code block. When we click it, the corresponding code will be copied to the clipboard.

## Describe alternatives you've considered

No.

## Additional context

For example, this is a website generated by [mkdocs-material](https://github.com/squidfunk/mkdocs-material), and its code snippet provides a copy button. 

<img width="709" alt="example" src="https://user-images.githubusercontent.com/37976199/129162454-7579f92f-7da1-4d40-8690-22a817a5b022.png">

Of course, for better user interaction, after clicking the copy button, relevant prompts should pop up at the bottom right of the website, such as:

<img width="1487" alt="prompts" src="https://user-images.githubusercontent.com/37976199/129162794-d1dc0d8a-1c45-4e89-80d5-c6f9e7285e85.png">

**Comment by NichtsHsu** [comment]
I am with it

**Comment by sp00ks-git** [comment]
I would also like this feature to be added very much also.
