### ISSUE TITLE
Remove email link/icon from sidebar

### ISSUE THREAD

**Issue by k0nze** [cotes2020/jekyll-theme-chirpy#399]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

I would like to remove the email link/icon from the sidebar. However, removing the `email` from `_config.yml` does not remove the icon. I also tried removing the email elsif clause from `_includes/sidebar.html` but this didn't work either. I tired it on the master branch and on v4.1.1.

**Comment by cotes2020** [comment]
The e-mail comes from here: https://github.com/cotes2020/jekyll-theme-chirpy/blob/14c439055ff251474841a0154e5381e9b2eb7165/_data/contact.yml#L9-L12

**Comment by k0nze** [comment]
Perfect, thank you!
