### ISSUE TITLE
Category Page Redirect Error

### ISSUE THREAD

**Issue by mindlabcore** [cotes2020/jekyll-theme-chirpy#4]
Hello! First of all I want say thank you for develop and share this template.
I created my own blog on www.virgul.co, when I follow Categories > click any category it redirect me to 404 page suddenly. But If I work on my local, It doesn't happend so everything is normal. Weird huh?

You can find my source code: https://github.com/virgulco/virgulco.github.io.git

**Comment by cotes2020** [comment]
Update the your template code first and follow the tutorial to use the tools `init.sh` :
<https://chirpy.cotes.info/posts/getting-started/#option-2-build-by-github-pages>

**Comment by imcloudfloating** [comment]
Run build.sh, and copy the tags dir in the _site dir to the root dir, then commit,  you can see the catagories.

**Comment by mindlabcore** [comment]
> Update the your template code first and follow the tutorial to use the tools `init.sh` :
> https://chirpy.cotes.info/posts/getting-started/#option-2-build-by-github-pages

Thank you so much!
