### ISSUE TITLE
Increase Snippet's Truncate number to higher value, or remove that if possible from search.json

### ISSUE THREAD

**Issue by arunshariharan** [cotes2020/jekyll-theme-chirpy#401]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There are no similar request on existing issues (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

I am writing posts that are longer than 300 words, but the search functionality limits the `snippet` to `truncate:300`, which means only 1/3rd of my content in each post is searchable. 

## Describe the solution you'd like

Can we remove the truncate option form `search.json`  or increase the limit around `1000`? 

## Describe alternatives you've considered

If it is not feasible due to optimization concerns, I was thinking of modifying the search.json locally myself for my build (create assets/js/data/search.json), but unfortunately jekyll does not pickup the changes and replace it while building. I am happy to know if there are any other options to go about it, if changing this is not feasible.

**Comment by cotes2020** [comment]
Hi @arunshariharan,

If you want full text search, you can actually remove the filter`truncate`. I used the filter in the project to prevent too much post content from being displayed in the search results (in fact, this can be restricted by CSS, and it has already been implemented).

In addition, I checked the latest version of [**Simple-Jekyll-Search**](https://github.com/christian-fei/Simple-Jekyll-Search). The docs also listed the usage of [full-text search](https://github.com/christian-fei/Simple-Jekyll-Search#enabling-full-text-search). I will upgrade the version of it later. Thanks for your report :)

**Comment by arunshariharan** [comment]
@cotes2020 Thanks so much for this! Can't wait for the update to roll out :) 

Also if I remove the `truncate` locally it works fine locally. But when I push to github, wouldn't it pull the latest gem and compile that anyway? So all changes locally I do will be lost when I push to github right? Is there a way to override this?

**Comment by cotes2020** [comment]
Until the next gem release, you can temporarily overwrite the contents of the theme's gem with a file of the same name. See: <https://jekyllrb.com/docs/themes/#overriding-theme-defaults>

**Comment by arunshariharan** [comment]
Thanks so much 😄
