### ISSUE TITLE
email button not always for me.

### ISSUE THREAD

**Issue by darkRaspberry** [cotes2020/jekyll-theme-chirpy#410]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

souce - https://github.com/darkBlogger/blog
live - https://blog.darkraspberry.ga

I have noticed that email button doesn't work for me. when normally clicked but.
IF i copy paste the whole link in console (developer option) it works file.

link - `javascript:location.href = 'mailto:' + ['insidedarkpit','gmail.com'].join('@')` after pasting in developer tool console it works but directly clicking it pop a webpage with `about:blank#blocked` link.

Also Is this API is deprecated? why can't we simply insert the email here?

**Comment by cotes2020** [comment]
If you haven't modified the HTML structure of the theme, please check the options in the critical files yourself, it must be modified somewhere to cause this problem.

**Comment by darkRaspberry** [comment]
I have modified files and deleted and modified many. And i don't remember anything.
Can you please tell me which files probably need to be checked.?

Also
pasting the line is browser console works normally. (If this is a error then why that works.)

**Comment by NichtsHsu** [comment]
Check `_data/contact.yml`:

```yaml
-
  type: email
  icon: 'fas fa-envelope'
  noblank: true            # open link in current tab
```

of the original theme and:

```yaml
-
  type: email
  icon: 'fas fa-envelope'
```

of your blogs.

**Comment by darkRaspberry** [comment]
@NichtsHsu thanks,
>  noblank: true

works. and now it successfully open the mail handler. But in the same windows not in new tab. Right
Well this is good but can i open it in new tab.

**Comment by NichtsHsu** [comment]
> Well this is good but can i open it in new tab.

According to [this topic](https://stackoverflow.com/questions/19234680/mailto-link-not-working-within-a-frame-chrome-over-https) you need use `target='_top'` instead of `target='_blank'` for email. You may have to modify the `_includes/post-sharing.html` file for your requirement.

**Comment by darkRaspberry** [comment]
Thanks.
