### ISSUE TITLE
Getting undefined in post publish date in Github Pages

### ISSUE THREAD

**Issue by molitona** [cotes2020/jekyll-theme-chirpy#412]
## Checklist
- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [x] I found the bug on the latest code of `master` branch.

## Describe the bug
I got undefined in post publish date where I push to github pages.
![Screenshot from 2021-09-23 20-48-34](https://user-images.githubusercontent.com/35532337/134574323-6019eeda-cb51-4fb6-a0d4-3bb363d532ac.png)
Despite, it works fine when I test the theme locally.
![Screenshot from 2021-09-23 20-48-39](https://user-images.githubusercontent.com/35532337/134574425-311c80b2-f205-422d-9380-958113383b8a.png)

### To Reproduce

1. Publish theme to github pages.
2. Check publish date.

### Expected behavior
The date is shown as it is when tested locally.
![Screenshot from 2021-09-23 20-48-39](https://user-images.githubusercontent.com/35532337/134574425-311c80b2-f205-422d-9380-958113383b8a.png)

### Software
- Ruby version: 2.6.8
- Gem version: 3.2.21
- Bundler version: 2.1.4

### Desktop
- OS: Any system
- Browser: Any one

**Comment by NichtsHsu** [comment]
Hi, it will be helpful if you post your repo's link so that we can know what you have modified.

**Comment by timothystewart6** [comment]
I am also seeing this

https://techno-tim.github.io/posts/crowdsec-traefik/

`Posted 1 undefined  Updated 3 undefined  4 min read`

**Comment by timothystewart6** [comment]
did this, probably note right and I don't have the fancy timeago date but at least it's not undefined now https://github.com/techno-tim/techno-tim.github.io/commit/12c16e750e8305e76253f173b8084bd28ca3ee49
