### ISSUE TITLE
Hide code block scroll bar until cursor is in block?

### ISSUE THREAD

**Issue by joshjohanning** [cotes2020/jekyll-theme-chirpy#414]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There are no similar request on existing issues (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

No - suggesting functionality after updating to `4.2.1`

## Describe the solution you'd like

- if it's simple, it would be more aesthetically pleasing to only show the left/right scroll bar on the code block when the cursor is inside the block. Otherwise, it looks a little busy on the screen.  See the below examples. 

### WITH 4.2.1 updates:
![image](https://user-images.githubusercontent.com/19912012/134822935-f2bb5b47-bff0-4baa-8d48-9fa9817fbff9.png)

### BEFORE 4.2.1:
![image](https://user-images.githubusercontent.com/19912012/134822981-4d6f258a-f320-454b-b7d2-e997c12e39f0.png)

If you scroll with your cursor, mouse, it shows the scroll bar as expected
![Screen Recording 2021-09-26 at 3 33 38 PM](https://user-images.githubusercontent.com/19912012/134823354-a807c63a-e9e0-474c-a556-7530d9cfb2ef.gif)

## Describe alternatives you've considered

- removing the scroll bar entirely

**Comment by NichtsHsu** [comment]
I don’t know if your opinion will be adopted, but if needed, here is a simple way to implement it: NichtsHsu@352533f3af1dfa3f301f31927c0e010fb3da3d41

**Comment by joshjohanning** [comment]
> I don’t know if your opinion will be adopted, but if needed, here is a simple way to implement it: [NichtsHsu/nichtshsu.github.io@352533f](https://github.com/NichtsHsu/nichtshsu.github.io/commit/352533f3af1dfa3f301f31927c0e010fb3da3d41)

@NichtsHsu that's awesome, I think this is much better

![image](https://user-images.githubusercontent.com/19912012/134836442-2372bd4a-af85-4bcc-b84e-5d8a35ad665e.png)

**Comment by cotes2020** [comment]
Hi @joshjohanning, I think you are talking about scroll bar on macOS. Well, I will add this feature in the next release.

**Comment by joshjohanning** [comment]
Awesome, looks great, thanks @cotes2020 and @NichtsHsu !
