### ISSUE TITLE
continuous-delivery job failed

### ISSUE THREAD

**Issue by remonsec** [cotes2020/jekyll-theme-chirpy#417]
Hello I am having this issue while deploying this theme on github pages 

![Capture](https://user-images.githubusercontent.com/54717234/135243844-ed7214b2-94f2-44b9-9a7e-e14fdbd158c7.PNG)

**Comment by NichtsHsu** [comment]
It will be helpful if you are willing to post your `_config.yml` file

**Comment by remonsec** [comment]
I am facing this new error 
![Capture](https://user-images.githubusercontent.com/54717234/135395911-3214705d-aeb5-48d2-a7bd-9c58a26c0f24.PNG)

Here is the config
[config.txt](https://github.com/cotes2020/jekyll-theme-chirpy/files/7257031/config.txt)

**Comment by NichtsHsu** [comment]
See #418
