### ISSUE TITLE
After first commit only shows --- layout: home # Index page ---

### ISSUE THREAD

**Issue by thevinirocks** [cotes2020/jekyll-theme-chirpy#418]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

In github-pages "username".github.io this is what is shown:
`--- layout: home # Index page --- `
and keep getting an error on deploy
`- _site/404.html
Ran on 9 files!
  *  image has no src or srcset attribute (line 1)
- _site/about/index.html
  *  image has no src or srcset attribute (line 1)
- _site/archives/index.html

  *  image has no src or srcset attribute (line 1)
- _site/categories/index.html
  *  image has no src or srcset attribute (line 1)
- _site/index.html
  *  image has no src or srcset attribute (line 1)
- _site/tags/index.html
  *  image has no src or srcset attribute (line 1)

HTML-Proofer found 6 failures!
Error: Process completed with exit code 1.`

what I could be doing wrong? On selfhosting works normally

**Comment by gloryVine** [comment]
Why was this closed? I'm facing the same problem.

**Comment by Can1425** [comment]
me too
