### ISSUE TITLE
Creating posts

### ISSUE THREAD

**Issue by 5uttercan3** [cotes2020/jekyll-theme-chirpy#419]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

Hi,
really sorry for the noob question but I'm having an issue creating a post. I created a new repo from Chirpy Starter, I've published it to github and my gh-pages branch is live.
The issue I'm having is that in the documentation I'm instructed to `Create a new file named YYYY-MM-DD-TITLE.EXTENSION and put it in the _posts/ of the root directory.` However I can't locate that directory. There is a `posts` folder under `_sites` in the file tree, and I attempted to edit that, but everything within `_sites` is greyed out and I'm unable to push any changes to github.
I'm quite certain that's not the correct way to do this, but I can't see any other way of adding a post. The Chirpy & Jekyll documentation isn't matching up with the Chirpy Starter clone I have in front of me, as in there isn't a `_posts` directory to add a file to.
Sorry for the query to what is probably a very simple solution, any help would be appreciated :)

**Comment by NichtsHsu** [comment]
Just create the folder `_post` at root directory and put files in.

**Comment by 5uttercan3** [comment]
Oh okay, sorry I thought as it wasn't already in there there was an issue. As I said, very simple, sorry for taking your time.
Thanks for the swift response!

**Comment by 5uttercan3** [comment]
Do I need to run anything after, i.e bundle, or does Jekyll/git take care of that when it's pushed?

**Comment by 5uttercan3** [comment]
Sorry, it just took about 2 hours to update. All sorted. Thanks for the help!!

**Comment by NichtsHsu** [comment]
The `gh-pages` branch is automatically generated/updated by Github Actions (configured by `.github/workflows/pages-deploy.yml`), and is triggered when you push commits to the repo.
