### ISSUE TITLE
Post excerpts: Use post.excerpt syntax for home page content

### ISSUE THREAD

**Issue by ppipada** [cotes2020/jekyll-theme-chirpy#42]
**Is your feature request related to a problem? Please describe.**

For posts that have < 200 chars first paragraphs, or posts with headings and bulleted points, or posts with headings and code snippets, current per-post content (i.e stripped excerpts) on home page get incomprehensible. 

This is mainly because the current post content is take as `{{ post.content | strip_html | truncate: 200 | replace: '&', '&amp;' }}`  in `_layouts/home.html`.

**Describe the solution you'd like**

Use Jekyll` {{ post.excerpt }}` syntax for getting the post summary: https://jekyllrb.com/docs/posts/#post-excerpts. 

This would also allow use of `excerpt_separator ` in `_config.yml` as needed. 

**Solution**
In `_layouts/home.html` line 18
```
<<< {{ post.content | strip_html | truncate: 200 | replace: '&', '&amp;' }}
>>> {{ post.excerpt }}
``` 

I have tried and tested the solution at my [personal site](https://ppipada.github.io/) at [github repo](https://github.com/ppipada/ppipada.github.io)

**Comment by cotes2020** [comment]
Jekyll tag `excerpt` is good, but, truncate the 200 words of posts could make the layout of homepage more neat.

**Comment by ppipada** [comment]
Truncate the 200 words of posts definitely becomes neat for posts that are paragraphs of text. For posts that are brief heading and then bullet list or numerical numbered lists it absolutely messes up.

**Comment by jexxers** [comment]
@cotes2020 - in what situations would `post.content` look more tidy than `post.excerpt`?

I was about to submit a PR, but saw others have also encountered this issue.

**Comment by joce** [comment]
Could we make it optional? If your post doesn't have a defined `excerpt_separator`, truncate to 200 words, otherwise, use `excerpt`?

**Comment by abd3lraouf** [comment]
Created a PR with a solution to this #619

**Comment by Seblor** [comment]
Any update on that ? I saw that #619 was closed, but It's still an issue.

**Comment by abd3lraouf** [comment]
@Seblor please feel free to take what I did and add it here :-) 💯

**Comment by bobrocke** [comment]
@cotes2020 I know I am very late to this discussion, but I just started working with Chirpy and find the lack of excerpt functionality a problem. Yes, poor use of such an option could make the home page messy, but that's sort of up to the Blog writer and not so much the theme.

Would you reconsider the PR?

**Comment by cotes2020** [comment]
> Would you reconsider the PR?

Hi @bobrocke, won't accept PR, you can use [description][desc] as an alternative. 

[desc]: https://chirpy.cotes.page/posts/write-a-new-post/#post-description

**Comment by bobrocke** [comment]
> > Would you reconsider the PR?
> 
> Hi [@bobrocke](https://github.com/bobrocke), won't accept PR, you can use [description](https://chirpy.cotes.page/posts/write-a-new-post/#post-description) as an alternative.

I see that you are firm on this. So I can only say that using the description field means edits have to be done in two places - once for the description and once for the body of the post. And something like `<!--more-->` is pretty common and completely optional for the writer.

**Comment by cotes2020** [comment]
The current homepage design only provides two to three lines of vertical space for each post, so the text that can be displayed by the Jekyll `expert` will be very limited. In contrast, the `description` can not only be customized with content different from the content, but it can also be embedded into the meta element, which is beneficial for SEO.

So pls don't dwell on this old issue anymore; not using expert is a consideration of the UI design logic. If you're not satisfied with it, feel free to branch off and build your own personalized version. :)
