### ISSUE TITLE
Display the featured image of each post on the home page

### ISSUE THREAD

**Issue by NiallLDY** [cotes2020/jekyll-theme-chirpy#421]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There is no similar request on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

Chirpy is a great theme that makes the blog site look very concise and elegant. But I think the home page is a little monotonous, so I wonder if it would be better to display the featured image of each post on the home page so that the home page will become more vivid. 

I think this idea is worth discussing whether it is suitable for this project, because I have also consulted many mainstream blog frameworks, and many themes have such a design.

I have also checked the issue #327 and #358. I think it would be better to provide this function natively or provide a configuration option for users to decide whether to display the image, especially for those who are not familiar with Jekyll and front-end development.

## Describe the solution you'd like

The featured image of each post can be added next to the title and truncated content. When facing a narrower screen, the image can be placed above the title, as shown in the figure below.

## Additional context

<img width="1236" alt="Wide-screen" src="https://user-images.githubusercontent.com/37976199/135880502-7ff1861d-45ce-4dd6-96fd-f9d47113785d.png">

<img width="423" alt="Narrow-screen" src="https://user-images.githubusercontent.com/37976199/135880521-cc199069-f30c-4dec-97ac-fa98b7ffee90.png">

The picture above is just a preliminary idea and design.

**Comment by cotes2020** [comment]
Please see [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md)

**Comment by 5uttercan3** [comment]
I just started using this theme, I really like it! This would be cool to have as a default feature though.

**Comment by NiallLDY** [comment]
> I just started using this theme, I really like it! This would be cool to have as a default feature though.

Sadly, this project doesn't accept any suggestions for design changes. :(
