### ISSUE TITLE
How to go the root of the repo?

### ISSUE THREAD

**Issue by boaz-s** [cotes2020/jekyll-theme-chirpy#44]
The instructions in the readme say to 

> Go to the root of repo and run:
> 
> `$ bundle install`

I'm not very familiar with terminal, I don't know how to go to the root of a repo before running something.

Help please?

Also, consider updating the readme so that the instructions are a bit clearer.

**Comment by cotes2020** [comment]
It means: Go to the root of the repo you cloned from github.
