### ISSUE TITLE
image files location

### ISSUE THREAD

**Issue by am-root** [cotes2020/jekyll-theme-chirpy#441]
- [x] I have read the [newlest tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).

Can anyone please help me understand what path should I put for images mentioned inside a .md file? because Every time I run `bundle exec jekyll s` images inside `_site/post/folder` (mentioned inside .md file) gets deleted. 

I tried creating `images` / '_images' folder and put all .png files there but they are not getting copied to `_site/post/folder`.

I do not understand this works. Please help me understand.

**Comment by am-root** [comment]
Nevermind found the way!

**Comment by Nat-Arslan** [comment]
> Nevermind found the way!

I'm having the same issue. I bet Im missing something obvious but I exhausted my options. What was your solution? @am-root
