### ISSUE TITLE
Improve the style under large screens

### ISSUE THREAD

**Issue by SericaLaw** [cotes2020/jekyll-theme-chirpy#445]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There is no similar request on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

The current style has a visual effect below expectation, which cannot utilize the large screen and also leave huge margins on the right.

Also, the elements in the sidebar are not center-aligned.

![1637113289(1)](https://user-images.githubusercontent.com/29623818/142093677-6d85fd8c-7440-461d-a575-538da9bf8a1e.jpg)

## Describe the solution you'd like

If the current style under large screens is not intended, I hope it can be fixed to use the large screen well and correct the alignments.

**Comment by cotes2020** [comment]
The maximum horizontal width in the theme design is 1080 pixels because even if the content is centered on an ultra-wide screen, there will be a huge blank space, so moving these blanks to the right can prompt the user to use a full-screen window in an ultra-wide screen is meaningless.
