### ISSUE TITLE
Pageviews update

### ISSUE THREAD

**Issue by challenger128** [cotes2020/jekyll-theme-chirpy#451]
## Checklist

- [x] I have read the [newlest tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

Could you update your guide about enabling pageviews? I stuck on making query due to google analytics update. Now I can not make query via Query Explorer.

**Comment by larsvansoest** [comment]
@challenger128 I also encountered the same issue, and found a fix, it's mentioned here: https://vansoest.dev/posts/creating-a-dev-blog/#cdn-and-analytics--google-cloud.

**Comment by challenger128** [comment]
@larsvansoest Hmm, I've tried to create ga4 & ua and still getting errors on query exlporer

**Comment by challenger128** [comment]
Oh, sorry, @larsvansoest, some of my browser's extensions blocked UA query explorer. Your idea to solve is great. I guess you should pull request updates on this guide.
