### ISSUE TITLE
Some css styles are not compatible with IE

### ISSUE THREAD

**Issue by zhaowcheng** [cotes2020/jekyll-theme-chirpy#455]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug

The background color of the sidebar and code block cannot be displayed on IE.  
And the dark mode is not available. 

### To Reproduce

1. Open https://chirpy.cotes.info/ in IE.

### Expected behavior

The style should be the same as in chrome

### Screenshots

![image](https://user-images.githubusercontent.com/4382523/144166257-0adb7007-6a61-475e-8980-1f2dede539a9.png)

### Software

- Ruby version:  ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]
- Gem version:  3.2.32
- Bundler version:  Bundler version 2.2.32
- Jekyll version:  jekyll (4.2.1)
- Theme version:  jekyll-theme-chirpy (4.3.3)

### Desktop

- OS:  Windows 10 19042.1348
- Browser: Internet Explore 20H2

**Comment by cotes2020** [comment]
IE is an outdated browser and will expire next year(on June 15, 2022). Therefore, this theme will not be compatible with IE.
