### ISSUE TITLE
How to always center the sidebar elements at any resolution?

### ISSUE THREAD

**Issue by zhaowcheng** [cotes2020/jekyll-theme-chirpy#456]
## Checklist

- [x] I have read the [newlest tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

When the display resolution is 1920 x 1080, the elements of the sidebar are left-aligned:  
![image](https://user-images.githubusercontent.com/4382523/144179469-ac9f84d1-a39f-4563-9b05-80a5a6a506ba.png)

But when the display resolution is 1600 x 900 or lower, the elements in the sidebar are center-aligned:  
![image](https://user-images.githubusercontent.com/4382523/144179715-4200e908-5244-430d-aac7-2618141ea9a2.png)

Is there any way to make the elements of the sidebar always be center-aligned at any resolution?

**Comment by NichtsHsu** [comment]
Most easy way:

Search `@media all and (min-width: 1650px)` in `_sass/addon/commons.scss`, delete the whole block (from line 1560 to 1722, if you are using latest master code).

**Comment by zhaowcheng** [comment]
> Most easy way:
> 
> Search `@media all and (min-width: 1650px)` in `_sass/addon/commons.scss`, delete the whole block (from line 1560 to 1722, if you are using latest master code).

that works, thank you very much!
