### ISSUE TITLE
Support: How to get left-aligned text in menu column?

### ISSUE THREAD

**Issue by tactlessfish** [cotes2020/jekyll-theme-chirpy#457]
## Checklist

- [x] I have read the [newlest tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description
The text of my menu column is centered. I would like it to be left-aligned, like this screenshot:
![Screenshot](https://camo.githubusercontent.com/0ab638e6fc47f9f3a9fc2731ceb975977af486b8c68e9a061ba2af690d71768c/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f636f746573323032302f6368697270792d696d6167657340306130303336383363306333636135343964313263333039663962336530336561323039383165352f636f6d6d6f6e732f646576696365732d6d6f636b75702e706e67)

Is there a config option for this?

**Comment by cotes2020** [comment]
This is a responsive design: when the screen width is greater than 1650px, the tab(menu) text will be aligned to the left, otherwise, it will be centered and the tab icon will be hidden.

**Comment by tactlessfish** [comment]
Ah, I see. Can I override this behavior so that it's always aligned to the left?

**Comment by SilentGlasses** [comment]
You'd need to play with the settings in the **Responsive Design** section in _sass -> addons -> common.scss
For reference:
https://github.com/cotes2020/jekyll-theme-chirpy/blob/ecf31ff3085d1f8267ce15b422bf1707560c25b8/_sass/addon/commons.scss#L1124

**Comment by digitigradeit** [comment]
FWIW: I prefer (value?) left-aligned nav menu *with* icons showing well over the showing of the right panel on pages, which is both handled different. interesting to note that even a 13" MacBook Pro at the default scale resolution shows TOC but not left-aligned sidebar or sidebar icons. chrome won't show it until you zoom out to 80%; Safari 85%.

left-aligned nav items:
.nav-item in /_sass/addon/commons.scss

forcing icons to show as well (this doesn't look great when the menu is centered btw)
literally remove the word "unloaded" (I believe there are two occurrences) from _includes/sidebar.html
