### ISSUE TITLE
Search Results Limited to 10

### ISSUE THREAD

**Issue by timothystewart6** [cotes2020/jekyll-theme-chirpy#458]
## Checklist

- [x] I have read the [newlest tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description
Search results are limited to 10 and not paginated.

Hi.  Is there a way to extend search results so that it shows more than 10 results, or a way to paginate the results?

**Comment by cotes2020** [comment]
The search function is provided by [_Simple-Jekyll-Search_](https://github.com/christian-fei/Simple-Jekyll-Search), please go to its homepage to check the configuration parameters

**Comment by timothystewart6** [comment]
Thank you!  To anyone else trying to figure this out, you'll need to add `limit: 12` or some other number.  I thought `undefined`, `null`, or `-1` wouldn't limit it but turns out it does.
