### ISSUE TITLE
How to let user choose between languages ?

### ISSUE THREAD

**Issue by Alimjoo** [cotes2020/jekyll-theme-chirpy#461]
There is have multiple language ‘.yml’ file in locals directory , so I am thinking how to make a button and let user choose site language through click that button ?

**Comment by Indomet** [comment]
> I build the site myself with this [multi language](https://github.com/untra/polyglot) plugin, then got the same question.

I still haven't been able to figure out how to display my website in different languages. Any progress?

**Comment by ameaninglessname** [comment]
> > I build the site myself with this [multi language](https://github.com/untra/polyglot) plugin, then got the same question.
> 
> I still haven't been able to figure out how to display my website in different languages. Any progress?

#593 You could refer to the link in the description

**Comment by Indomet** [comment]
> > > I build the site myself with this [multi language](https://github.com/untra/polyglot) plugin, then got the same question.
> > 
> > 
> > I still haven't been able to figure out how to display my website in different languages. Any progress?
> 
> #593 You could refer to the link in the description

thanks but I unfortunately couldn't make it work for this template, I will try again
