### ISSUE TITLE
Update theme

### ISSUE THREAD

**Issue by challenger128** [cotes2020/jekyll-theme-chirpy#463]
## Checklist

- [x] I have read the [newlest tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

I've used a chirpy theme starter. However, I didn't know that I would want to update the theme in the future. I think Disqus comments are disgusting and want to enable telegram comments due to it is free and has no ads. But I don't have some source of code in repo which is required to update. Is there a way to update theme without forking the repository?

**Comment by NichtsHsu** [comment]
See the chapter [**Overriding theme defaultsPermalink**](https://jekyllrb.com/docs/themes/#overriding-theme-defaults) of Jekyll Theme Doc

**Comment by challenger128** [comment]
@NichtsHsu Thank you. This is exactly what I need.
