### ISSUE TITLE
"_site does not exist (ArgumentError)" in GitHub Actions

### ISSUE THREAD

**Issue by walterlv** [cotes2020/jekyll-theme-chirpy#465]
## Checklist

- [x] I have read the [newlest tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

### What happened?

When I push my changes to the master branch and wait for the GitHub Actions, it failed because of the error "_site does not exist". But everything works fine on my own computer.

I tried the basic `bundle exec jekyll s` and it works fine. After I notice the failure of the GitHub Action, I run another script of the `deploy.sh` file `bundle exec jekyll b -d "_site" --config "_config.yml"` and it generates the `_site` folder correctly.

By the way, the base url is empty and I've verified this by running `grep '^baseurl:' _config.yml | sed "s/.*: *//;s/['\"]//g;s/#.*//"`.

My GitHub Action is here:

* https://github.com/walterlv/walterlv.github.io/runs/4577510946?check_suite_focus=true

My local ruby version is exactly the same as the GitHub Action one.

Ruby: 3.0.3
gems: 3.0.0
bundle: 2.2.33

### What did I do?

1. Clone the repo, run the init.sh
2. Change some styles to fit my design prototypes.
3. execute `bundle lock --add-platform x86_64-linux`

### The Logs

```bash
Configuration file: /home/runner/work/walterlv.github.io/walterlv.github.io/_config.yml
 Theme Config file: /home/runner/work/walterlv.github.io/walterlv.github.io/_config.yml
            Source: /home/runner/work/walterlv.github.io/walterlv.github.io
       Destination: /home/runner/work/walterlv.github.io/walterlv.github.io/_site 
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 152.221 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
NOTE: nokogumbo: Using Nokogiri::HTML5 provided by Nokogiri. See https://github.com/sparklemotion/nokogiri/issues/2205 for more information.
/home/runner/work/walterlv.github.io/walterlv.github.io/vendor/bundle/ruby/3.0.0/gems/html-proofer-3.19.2/lib/html-proofer.rb:25:in `check_file': _site does not exist (ArgumentError)
htmlproofer 3.19.2 | Error:  _site does not exist
	from /home/runner/work/walterlv.github.io/walterlv.github.io/vendor/bundle/ruby/3.0.0/gems/html-proofer-3.19.2/bin/htmlproofer:113:in `block (2 levels) in <top (required)>'
	from /home/runner/work/walterlv.github.io/walterlv.github.io/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /home/runner/work/walterlv.github.io/walterlv.github.io/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /home/runner/work/walterlv.github.io/walterlv.github.io/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /home/runner/work/walterlv.github.io/walterlv.github.io/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /home/runner/work/walterlv.github.io/walterlv.github.io/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /home/runner/work/walterlv.github.io/walterlv.github.io/vendor/bundle/ruby/3.0.0/gems/html-proofer-3.19.2/bin/htmlproofer:11:in `<top (required)>'
	from /home/runner/work/walterlv.github.io/walterlv.github.io/vendor/bundle/ruby/3.0.0/bin/htmlproofer:25:in `load'
	from /home/runner/work/walterlv.github.io/walterlv.github.io/vendor/bundle/ruby/3.0.0/bin/htmlproofer:25:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:58:in `load'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:23:in `run'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/cli.rb:479:in `exec'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/cli.rb:31:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/cli.rb:25:in `start'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/exe/bundle:49:in `block in <top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/exe/bundle:37:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/bin/bundle:23:in `load'
	from /opt/hostedtoolcache/Ruby/3.0.3/x64/bin/bundle:23:in `<main>'
Error: Process completed with exit code 1.
```

**Comment by walterlv** [comment]
I've tried to change the runs-on to windows-latest, and get another different error. Perhaps I should fix the libcurl dependency issue.

```bash
……
      Generating... 
                    done in 306.507 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
NOTE: nokogumbo: Using Nokogiri::HTML5 provided by Nokogiri. See https://github.com/sparklemotion/nokogiri/issues/2205 for more information.
D:/a/walterlv.github.io/walterlv.github.io/vendor/bundle/ruby/3.0.0/gems/ffi-1.15.4-x64-mingw32/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library 'libcurl': The specified module could not be found.\r (LoadError)
.
Could not open library 'libcurl.dll': The specified module could not be found.\r
.
Could not open library 'libcurl.so.4': The specified module could not be found.\r
.
Could not open library 'libcurl.so.4.dll': The specified module could not be found.\r
	from D:/a/walterlv.github.io/walterlv.github.io/vendor/bundle/ruby/3.0.0/gems/ffi-1.15.4-x64-mingw32/lib/ffi/library.rb:99:in `map'
	from D:/a/walterlv.github.io/walterlv.github.io/vendor/bundle/ruby/3.0.0/gems/ffi-1.15.4-x64-mingw32/lib/ffi/library.rb:99:in `ffi_lib'
……
```

**Comment by walterlv** [comment]
I've found the critical reason and the correct solution by bisecting the original master and my modified repo.

## Reason

The `test` command uses the html-proofer to verify all the html files. But unfortunately, some of my posts cannot pass the verification because I use the URL without the `.html` extension as my link but the real post URL has the `.html` extension. The browser can open the clean URL correctly so I didn't add the .html postfix of my links.

The output of the GitHub Action doesn't show up the real reason for this situation. It just complains about the disappearance of the `_site` folder, without any help.

## Solution

I've removed the `test` command of the `deploy.sh` temporarily to let my new version blog work normally online. I'll try to satisfy the test progressively a few days later and restore the useful `test` of your excellent theme.

## Thanks

Chirpy is the most beautiful theme I've ever used, both in the UI designing and the code structure. I learn a lot from your coding, including the separated colors and layouts, the details all over the texts and buttons, the animations and interactions everywhere.

**Comment by kiw6024** [comment]
Thank you, I was really stressed with same issue. I almost burned my computer, and it got solved. Thank you again :>
