### ISSUE TITLE
Categories/tags generator issue if a post has same formatted lines

### ISSUE THREAD

**Issue by nhvu1988** [cotes2020/jekyll-theme-chirpy#47]
**Steps to reproduce**
I just write a blog post and having the codes that luckily have the same format with category/tag definition line 

```
---
categories: ['coding']
---

## I have a code example as below
[```]
blab blab categories: ['test', 'ok']
[```]
```
2. Run the init.sh to generate categories automatically
3. There are 3 categories (`test.html`, `ok.html` and `coding.html`) generated

**Expected behavior**
Only one category `coding.html` is generated.

**Additional context**
It also has an issue with category/tag name parsing, for example if the category in the code is
```
categories: ['test', 'ok'] },
```
a filenamed `ok}.html` will be generated

**Suggestion**
I think we should check and parse categories/tags from first ten (or few) lines or content inside 2 `---` lines?

**Comment by cotes2020** [comment]
1. Did you work with the newlest code on `master`, I mean the [create_pages.sh](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/_scripts/sh/create_pages.sh) ?

2. What's your OS type, version, and the `bash` version?

**Comment by nhvu1988** [comment]
1. Did you work with the newlest code on master, I mean the create_pages.sh ?
 -> Yes, I'm using the latest code on master branch.

2. What's your OS type, version, and the bash version?
-> I'm using windows 10 and run on cmd, but it has the same issue on linux since I have tried to run it on github action as well

```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build categories and tags
      run: |
        bash tools/init.sh
```

3. The " issue with category/tag name parsing" you mentioned above in Additional context is a bad idea, because you should comply with the YAML syntax when writing the Front Matter block of a post in Jekyll.
-> It's not YAML, exactly it's just javascript (json) code in my blog post and it's parsed wrongly 😊

![image](https://user-images.githubusercontent.com/13212737/80779431-d0576d80-8b95-11ea-9030-f88f84c2e023.png)

**Comment by cotes2020** [comment]
The code snippet you showed for the first time did not hit the bug:

```
---
categories: ['coding']
---

## I have a code example as below
[```]
blab blab categories: ['test', 'ok']
[```]
````

But the screenshot did it. 

The key to hit the bug is to use variable `categoy` in the YAML(FrontMatter) block, and one or more "categories" words in the post body.

The issue has now been fixed, and thank you for your reporting.

**Comment by nhvu1988** [comment]
yeah, thank you. Sorry for the inconvenience in my code snippet! I will test soon
