### ISSUE TITLE
当标题以数字开头时，右侧导航栏无法聚焦该标题

### ISSUE THREAD

**Issue by NichtsHsu** [cotes2020/jekyll-theme-chirpy#470]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug

当标题以数字开头时，右侧导航栏无法聚焦该标题

### To Reproduce

在一个已有大量文本的帖子中，加入任意一个以数字开头的标题，如 `## 123456`，为它增加一些文本内容填充。之后，无论是拖动滚动条，进入到该标题覆盖的文本区域，还是直接点击右侧导航栏跳转到该标题的位置，右侧的导航栏都无法聚焦该标题，而是聚焦上一个标题。

### Expected behavior

导航栏聚焦当前标题

### Screenshots

![screenshot-20211230-171804](https://user-images.githubusercontent.com/35688135/147738384-a97d4615-4015-412f-abf4-55701ee9a2e7.png)

### Software

- Ruby version:  ruby 2.7.0p0
- Gem version:  3.1.2
- Bundler version:  2.2.30
- Jekyll version:  4.2.1
- Theme version:  None

### Desktop

- OS: Ubuntu 20.04 (Win 11 也复现）
- Browser: Chrome 96.0.4664.110 (64-bit)

**Comment by cotes2020** [comment]
This behavior is caused by the [_bootstrap-toc_](https://github.com/afeld/bootstrap-toc), you can send an issue to there.

**Comment by NichtsHsu** [comment]
似乎也是个上古问题了：afeld/bootstrap-toc#64
