### ISSUE TITLE
Link rendering bug when link name and header name are the same

### ISSUE THREAD

**Issue by joshjohanning** [cotes2020/jekyll-theme-chirpy#474]
## Checklist

- [X] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [X] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [X] I found the bug on the latest code of the `master` branch.

## Describe the bug

With links that have hyphens (`-`) in them, it renders incorrectly.

Started in 5.0.0. Did not encounter in 4.3.4.

Content in post:

`I originally tested out trac2github and was going to write about that, but I think I might like this [trac-hub](https://github.com/joshjohanning/trac-hub) tool a little better. When comparing the two, trac-hub might be better in that it uses the [Import Issues API](https://gist.github.com/jonmagic/5282384165e0f86ef105).`

What is rendered:

> I originally tested out trac2github and was going to write about that, but I think I might like this [Import Issues API](https://github.com/joshjohanning/%3C/a%3E%20tool%20a%20little%20better.%20When%20comparing%20the%20two,%20trac-hub%20might%20be%20better%20in%20that%20it%20uses%20the%20%3Ca%20href=). 

This is the output of `bash ./tools/deploy.sh --dry-run`:

> Attribute set `<a href="https://github.com/joshjohanning/</a> tool a little better. When comparing the two, trac-hub might be better in that it uses the <a href=" https:="" gist.github.com="" jonmagic="" 5282384165e0f86ef105"="">Import Issues API</a>` contains an error!
htmlproofer 3.19.2 | Error:  invalid attribute name `5282384165e0f86ef105"'
Traceback (most recent call last):
        45: from /home/codespace/.ruby/current/bin/bundle:23:in `<main>'
        44: from /home/codespace/.ruby/current/bin/bundle:23:in `load'
        43: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.26/exe/bundle:37:in `<top (required)>'
        42: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.26/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
        41: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.26/exe/bundle:49:in `block in <top (required)>'
        40: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.26/lib/bundler/cli.rb:25:in `start'
        39: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        38: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.26/lib/bundler/cli.rb:31:in `dispatch'
        37: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        36: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        35: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        34: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.26/lib/bundler/cli.rb:477:in `exec'
        33: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.26/lib/bundler/cli/exec.rb:23:in `run'
        32: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.26/lib/bundler/cli/exec.rb:58:in `kernel_load'
        31: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.26/lib/bundler/cli/exec.rb:58:in `load'
        30: from /home/codespace/.ruby/current/bin/htmlproofer:23:in `<top (required)>'
        29: from /home/codespace/.ruby/current/bin/htmlproofer:23:in `load'
        28: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/html-proofer-3.19.2/bin/htmlproofer:11:in `<top (required)>'
        27: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        26: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        25: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        24: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        23: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        22: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/html-proofer-3.19.2/bin/htmlproofer:111:in `block (2 levels) in <top (required)>'
        21: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/runner.rb:48:in `run'
        20: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/runner.rb:76:in `check_files'
        19: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/runner.rb:98:in `process_files'
        18: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/runner.rb:98:in `map'
        17: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/runner.rb:98:in `block in process_files'
        16: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/runner.rb:137:in `check_path'
        15: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/runner.rb:109:in `check_parsed'
        14: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/runner.rb:109:in `each'
        13: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/runner.rb:110:in `block in check_parsed'
        12: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/runner.rb:110:in `each'
        11: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/runner.rb:113:in `block (2 levels) in check_parsed'
        10: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/check/links.rb:17:in `run'
         9: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/nokogiri-1.12.5-x86_64-linux/lib/nokogiri/xml/node_set.rb:238:in `each'
         8: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/nokogiri-1.12.5-x86_64-linux/lib/nokogiri/xml/node_set.rb:238:in `upto'
         7: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/nokogiri-1.12.5-x86_64-linux/lib/nokogiri/xml/node_set.rb:239:in `block in each'
         6: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/check/links.rb:18:in `block in run'
         5: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/check.rb:22:in `create_element'
         4: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/check.rb:22:in `new'
         3: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/element.rb:17:in `initialize'
         2: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/element.rb:17:in `each_pair'
         1: from /opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/element.rb:19:in `block in initialize'
/opt/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/html-proofer-3.19.2/lib/html-proofer/element.rb:19:in `attr_reader': invalid attribute name `5282384165e0f86ef105"' (NameError)

### To Reproduce

* Create a markdown link with a hyphen (`-`) - or at least two links in a single paragraph where the first has a hyphen. 
* If I remove the hyphen (`-`) from the link name, the link displays as normal. 

### Screenshots

Markdown:

![image](https://user-images.githubusercontent.com/19912012/147990355-3b25d30c-5834-43d4-8fad-dc286706d5af.png)

Output:

![image](https://user-images.githubusercontent.com/19912012/147990293-82743487-437b-4f45-9ca8-cb280c423c77.png)

Once you remove the hyphen, back to normal:

![image](https://user-images.githubusercontent.com/19912012/147990824-b17e1ab5-1bdb-4b65-8ad2-15735b21eec2.png)

### Software

- Ruby version: `ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]`
- Gem version: n/a
- Bundler version: `Bundler version 2.2.26`
- Jekyll version: `* jekyll (4.2.1)`
- Theme version: `5.0.0`

### Desktop

- OS: `macOS 12.6.2`
- Browser: `Brave (chromium) 1.33.106`

**Comment by NichtsHsu** [comment]
If you clone [this repo](https://github.com/cotes2020/jekyll-theme-chirpy.git) and add your content in it, you may find that it works well than you think. Maybe some other problem caused by you self?

**Comment by joshjohanning** [comment]
I cloned the repo from scratch and just copied in my post - same thing on Linux and macOS:

![image](https://user-images.githubusercontent.com/19912012/148080798-856270a5-ce61-4886-8e07-2efa18090cb4.png)

![image](https://user-images.githubusercontent.com/19912012/148081045-75ad45f6-4cb9-4035-9e22-d4015d3bbe59.png)

**Comment by joshjohanning** [comment]
@cotes2020 @NichtsHsu 

I found the bug / how to re-create - it's when the `link name` is the same as the `header` text that it is under.

ie:

```md
## trac-hub

### trac-hub Overview

text... [trac-hub](https://github.com/joshjohanning/trac-hub) more text .... [Import Issues API](https://gist.github.com/jonmagic/5282384165e0f86ef105).
```

the key part is the `## trac-hub` and `[trac-hub]` are the same.  If I change the header to `## whatever` then my link renders correctly.

Hopefully this helps

**Comment by cotes2020** [comment]
> the key part is the `## trac-hub` and `[trac-hub]` are the same. If I change the header to `## whatever` then my link renders correctly.
> 

Successfully reproduced, will work it

**Comment by cotes2020** [comment]
After a more in-depth analysis, there are 3 trigger conditions for this bug:

1.  The header is a lowercase string
2. The beginning of the link name in the paragraph is the same as the header
3. The linked URL ends with the same string as the header

Will trigger the bug:

```md
## header

[header](https://domain/header)
```

```md
## header

[headerxxxxx](https://domain/xxxxxxxxxheader)

```

Will not trigger the bug:

```md

## header

[xxheader](https://domain/header)
```

```md
## header

[header](https://domain/headerxx)

```

**Comment by joshjohanning** [comment]
Happy to report that `5.0.1` fixed this :) 

Thank you!
