### ISSUE TITLE
"data-proofer-ignore" text in each post

### ISSUE THREAD

**Issue by joshjohanning** [cotes2020/jekyll-theme-chirpy#476]
## Checklist

- [X] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [X] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [X] I found the bug on the latest code of the `master` branch.

## Describe the bug

Seeing `data-proofer-ignore` in each post - usually it's next to an image, like so:
![image](https://user-images.githubusercontent.com/19912012/148070037-d922ec96-f68b-4200-9f06-c43673ab3ae4.png)

In a post without an image, it is in the footer:
![image](https://user-images.githubusercontent.com/19912012/147989868-c3d34bba-d74c-448d-b591-c9a21c541cd7.png)

See example markdown files to re-create the error:

* on image: https://gist.github.com/joshjohanning/44d8ff78390058a29d32644bb82360e1
* in footer: https://gist.github.com/joshjohanning/554cf16fa42ffc98ff1d6a7bf9c8951a

Started in 5.0.0. Did not encounter in 4.3.4.

### To Reproduce

* Clone repo fresh
* create posts with the above linked markdown 
* launch site and ctrl-f `data-proofer-ignore`

### Expected behavior

Not show `data-proofer-ignore`

### Screenshots

See above

### Software

- Ruby version: `ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]`
- Gem version: n/a
- Bundler version: `Bundler version 2.2.26`
- Jekyll version: `* jekyll (4.2.1)`
- Theme version: `5.0.0`

### Desktop

- OS: `Ubuntu 20.04.3 LTS` and `macOS 12.6.2`
- Browser: `Brave (chromium) 1.33.106`

**Comment by cotes2020** [comment]
I have found a way to reproduce this bug. Defining a _preview image_ in a post will definitely cause a `data-proofer-ignore` string to escape.

The reason is that the HTML elements of the image compiled by Jekyll end with `/>` (`<img src=... />`), and the HTML of  _preview image_ is created by `post` layout, and end with `>` (`<img src=... >`) according to the standard format, then this bug will appear when _\_includes/refactor.html_ changes the HTML structure.

**Comment by joshjohanning** [comment]
@cotes2020 so since the `.. />` is not part of the standard format...I'm guessing you don't want to approve #477 ? :)

**Comment by cotes2020** [comment]
I also wanted to do this, using `/>` at the end of the preview image HTML element, but this solution is not elegant enough 😂

**Comment by joshjohanning** [comment]
fair. But it works for me for now :)

**Comment by joshjohanning** [comment]
Happy to report that `5.0.1` fixed this :)  948356d7d632feae1e694e0a6ce20f7e975c7e50

Thank you!
