### ISSUE TITLE
theme switching doesn't work

### ISSUE THREAD

**Issue by SiriusHsh** [cotes2020/jekyll-theme-chirpy#479]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

Yesterday when I followed the  [upgrade guide](https://github.com/cotes2020/jekyll-theme-chirpy/wiki/Upgrade-Guide) , Upgrading from 4.3.4 to 5.0.0, then the theme switch button on the sidebar doesn't respond when I clicked.

**Comment by legiahuyy** [comment]
I also get the same issue after upgrading to the lastest (4.3.4 to 5.0.0) version.

**Comment by NichtsHsu** [comment]
Hi @SiriusHsh ,

The theme switching feature is provided by js scripts under `/assets/js/`.

I found that you have this folder in your repo, it will cover the theme's default scripts. If you remove this folders, theme switch will work well.

**Comment by SiriusHsh** [comment]
hi, @NichtsHsu ,
It didn't work. I have deleted the `/assets/js` folder, then the webpage will display abnormally due to losing the JS. I tried using the `bundle update jekyll-theme-chirpy` command in an attempt to download the JS folder, but it didn't work. 

should i clone the `/assets/js/` folder from this URL ? (https://github.com/cotes2020/jekyll-theme-chirpy/tree/master/assets/js)

**Comment by NichtsHsu** [comment]
> It didn't work.

It works on my enviroments.

```shell
╒▍nihil@ubuntu.5f076.ts Projects/Github-Repos/SiriusHsh.github.io ‹main› 10:28:28 
└─▶ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    assets/js/data/search.json
        deleted:    assets/js/data/swcache.js
        deleted:    assets/js/dist/categories.min.js
        deleted:    assets/js/dist/commons.min.js
        deleted:    assets/js/dist/home.min.js
        deleted:    assets/js/dist/page.min.js
        deleted:    assets/js/dist/post.min.js
        deleted:    assets/js/dist/pvreport.min.js
        deleted:    assets/js/pwa/app.js
        deleted:    assets/js/pwa/sw.js

no changes added to commit (use "git add" and/or "git commit -a")
```

![screenshot-20220112-102915](https://user-images.githubusercontent.com/35688135/149053151-284d1546-7228-4b30-a2f9-a92cf9c23208.png)

> should i clone the /assets/js/ folder from this URL ? 

No, unless you want to cover the default scripts, otherwise you should not create this folder.

**Comment by SiriusHsh** [comment]
@NichtsHsu  sorry... it's my mistake. I tried again, it is work now. 
thx very much：）
