### ISSUE TITLE
jekyll 3.8.6 | Error:  Liquid error (line 18): comparison of NilClass with String failed

### ISSUE THREAD

**Issue by stefanstranger** [cotes2020/jekyll-theme-chirpy#48]
When running bash ./tools/run.sh on my Windows 10 within WSL Debian I get the following error:

jekyll 3.8.6 | Error:  Liquid error (line 18): comparison of NilClass with String failed

Detailed info:

Liquid Exception: Liquid error (line 18): comparison of NilClass with String failed in tabs/categories.md

Regards,
Stefan

**Comment by cotes2020** [comment]
Sorry to tell you that this doesn't seem right. The Jekyll 3.8.6 works fine.

**Comment by stefanstranger** [comment]
Thanks for your investigation. I will again try to figure out why I get the error message.

Regards,
Stefan

**Comment by cotes2020** [comment]
Sorry for the `invalid` tag. This bug appears when a post has only one category, now it has been fixed at e87e1f5e9bae068ffe1d3d356430fcf4e31ee83b.
