### ISSUE TITLE
Is Git a necessary prerequisite?

### ISSUE THREAD

**Issue by SpaceAttorney** [cotes2020/jekyll-theme-chirpy#484]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

After setting up my blog on my home computer, I cloned the repository to my work laptop so I could write posts on both systems. However, when I attempted to build the site on my laptop I got the following error:
```
no such file or directory - git rev-list --count head "c:/users/<me>/documents/<the local repo>/_posts/2022-01-14-sample-post.md" (errno::enoent)
```
After some googling I was able to solve the issue by installing Git and adding it to my path environment. I didn't see Git listed as a prerequisite on either this theme or Jekyll in general, and I didn't already have it installed because I use Sourcetree. If Git is necessary to run the site locally, I think this should be made clear in the tutorial. Thanks!

**Comment by cotes2020** [comment]
Yes, `_plugins/posts-lastmod-hook.rb` requires Git
