### ISSUE TITLE
{{ }} issue

### ISSUE THREAD

**Issue by gudszent** [cotes2020/jekyll-theme-chirpy#487]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug
The code part remove {{ }}  part

### To Reproduce 

If try to use this 
```yaml
.
.
backendAzureRmResourceGroupName: ${{variables.backendAzureRmResourceGroupName }}
.
.
```

always remove the double bracket part, so in the site I will get:
backendAzureRmResourceGroupName: $

### Screenshots

vscode:
![image](https://user-images.githubusercontent.com/6563633/149641123-22d96d5b-ec5c-48a6-8b78-1e6265af4963.png)
site:
![image](https://user-images.githubusercontent.com/6563633/149641107-aeb8a0f0-9127-4280-9428-33ea46a4fca7.png)

Is it possible to avoid to remove that part?

**Comment by NichtsHsu** [comment]
```liquid
{% raw %}
{{ Whatever you write}}
{% will be kept %}
{% endraw %}
```

**Comment by gudszent** [comment]
> ```
> {% endraw %}
> ```

Thank you!
the final version, where the row number and the row high on the same level:
{% raw %}
```yaml
.
.
```  
{% endraw %}
