### ISSUE TITLE
Broken telegram sharing function on mobile phone

### ISSUE THREAD

**Issue by brootware** [cotes2020/jekyll-theme-chirpy#488]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug

Unable to share a blog post via telegram sharing function. The bug is found on telegram sharing link function of a blog post hosted using chirpy theme via safari ios browser. Same behaviour is observed in chrome ios browser. 

### To Reproduce

1. Go to a blog post hosted by jekyll-theme-chirpy via a mobile browser. For.eg : https://brootware.github.io/posts/picomini22pwcrack5/
2. Click on share via telegram icon.
3. You will be redirected to the telegram app and see the break.

### Expected behavior

**_Sorry, this user doesn't seem to exist_**
The above message pops up and you will be unable to share the blog post.

### Screenshots

https://user-images.githubusercontent.com/7734956/149685302-95d349c4-d243-4c5d-831c-7af2dce5e9d7.MP4

### Software

- Ruby version: ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
- Gem version: 3.0.3.1
- Bundler version: Bundler version 2.3.5
- Jekyll version:   * jekyll (4.2.1)
- Theme version: jekyll-theme-chirpy (5.0.2)

### Desktop

- [x] Not applicable

### Smartphone

- Device: iPhone X
- OS: iOS 15.1
- Browser: Safari, Chrome

### Additional context

After researching into this, I found the work around to fix the problem by changing the original URL from

`https://telegram.me/share?text=TITLE&url=URL`

to

`https://telegram.me/share/url?url=URL&text=TITLE`

source: https://stackoverflow.com/questions/31356360/share-a-link-via-url-scheme-to-telegram
https://github.com/brootware/brootware.github.io/blob/main/_data/share.yml

For now I have reverted my blog to broken telegram sharing function for users to reproduce on their phone. If the bug is valid and reproducible, will submit a PR for a fix.

**Comment by cotes2020** [comment]
It seems that Telegram has modified the sharing API. If you want to submit a PR for this, please modify the above link according to [the official docs](https://core.telegram.org/widgets/share#custom-buttons) and use the domain name `t.me` instead of `telegram.me`.
