### ISSUE TITLE
Is there a way to add TOC to the About page?

### ISSUE THREAD

**Issue by wapenshaw** [cotes2020/jekyll-theme-chirpy#49]
I have changed the layout in the About page to page/post etc but can't seem to get the Table of contents on the right panel like I do for posts. 

I even tinkered around if condition in panel.html and set this to if true and still I can't seem to get the TOC. 
  {% if page.layout == 'post' and site.toc and page.toc %}

Halp!

**Comment by cotes2020** [comment]
Simply add the contents below to the Front Matter block of `tabs/about.md` and then the ToC will display:

```
---
layout: post
toc: true
---
```

But please note that this only uses the layout of `post`, the most elegant way is to create a new layout yourself, similar to the `post` layout, but there is no other unnecessary elements such as *date*, *lastmod*, *categories* and *tags*.. etc. Then you can use this new layout on the About page.

**Comment by wapenshaw** [comment]
Oh wow! I feel stoopid now, 

I added layout: post but didn't add toc: true

Thank you! it worked. I am new to this and learning. I will attempt to create the layout on my own!
