### ISSUE TITLE
The TOC generation failed when the post contains only H1-heading

### ISSUE THREAD

**Issue by zhaowcheng** [cotes2020/jekyll-theme-chirpy#491]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug

The TOC generation failed when the post contains only H1-heading

### To Reproduce

1. Write a post contains only H1-heading and build it.

![image](https://user-images.githubusercontent.com/4382523/149895603-94e05f6c-8b13-4b3f-9ea2-2738388eff2c.png)

### Expected behavior

The TOC should be displayed on the right panel, but it doesn't.

![image](https://user-images.githubusercontent.com/4382523/149892304-4d7e6c3c-c344-4572-9310-597d603daece.png)

### Screenshots

But if i add a H2-heading, the TOC will display.

![image](https://user-images.githubusercontent.com/4382523/149895405-653b0b6a-189e-475e-b867-9c24003cacb9.png)

![image](https://user-images.githubusercontent.com/4382523/149895462-b84d84be-a7e5-4176-a704-50a7d7c8fde5.png)

### Software

- Ruby version:  ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]
- Gem version:  3.2.32
- Bundler version:  Bundler version 2.2.32
- Jekyll version:  jekyll (4.2.1)
- Theme version:  jekyll-theme-chirpy (4.3.3)

### Desktop

- OS:  Windows 10 19042.1348
- Browser: Chrome 97.0.4692.71

**Comment by cotes2020** [comment]
Before you report finding a bug, please understand the functional design first: without H2 or H3, ToC generation is skipped. 

Good writing habits are: H1 is unique and only used for the post title.
