### ISSUE TITLE
tabs icon

### ISSUE THREAD

**Issue by hazemkya** [cotes2020/jekyll-theme-chirpy#497]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [ ] My question is based on the latest code of the `master` branch.

## Description

I tried to create a new tab inside _tabs, it worked, I changed it's icon, but it only works in home page.
here is what I did, I copied about.md inside _tabs, renamed it to certificate.md changed it's details, title, icon, order to 4(above about), changed about order to 5, so the problem is whenever I go to any other path in my website(other than root), the icon becomes the same as about(explanation mark icon).
how can fix this?

**Comment by hazemkya** [comment]
I fixed it, I just added a custom layout with the name of my tab

**Comment by CoderOldSix** [comment]
> I fixed it, I just added a custom layout with the name of my tab

can u have supply more details ? I have a same issue. I can not understand your way to resolve it.
