### ISSUE TITLE
Change Inline codeblock color 

### ISSUE THREAD

**Issue by gaeunchoi** [cotes2020/jekyll-theme-chirpy#498]
## Checklist

- [ x ] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [ x ] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [ x ] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [ x ] My question is based on the latest code of the `master` branch.

## Description

![image](https://user-images.githubusercontent.com/56152020/151654206-af85e97f-ba39-4f7f-9126-9e261d2a73af.png)

The background color of the currently set inline code block is gray.
How can I change the font color and background color of the inline code block?

Another question is, can't I use the `<br>` tag in the markdown file?

**Comment by aphive** [comment]
You can overwrite with custom css at `assets/css/style.scss` or edit the theme settings in the files located at `_sass/colors`
