### ISSUE TITLE
Cant not support Chinese file name.

### ISSUE THREAD

**Issue by imcloudfloating** [cotes2020/jekyll-theme-chirpy#5]
subprocess.getoutput() cant not execute when the post contains Chinese character.

**Comment by cotes2020** [comment]
Show me more detials about the issue, please:
1.  What's your system locale encode type ?
2. Would you paste the Python error logs here ?

**Comment by cotes2020** [comment]
Fixed at 71328bd055d155b010f6ef378cd9f924be0045df.
