### ISSUE TITLE
Resize Post page

### ISSUE THREAD

**Issue by stefanstranger** [cotes2020/jekyll-theme-chirpy#50]
Hi Cotes Chung,

I like the Jekyll Theme you created but I would like to have the post pages a bit wider.

![image](https://user-images.githubusercontent.com/2125385/80914602-d17ecb00-8d4c-11ea-88ad-095fba528fb3.png)

Is this something I can easily change myself?

Thanks for your help.

Stefan

**Comment by cotes2020** [comment]
When it comes to modifying post width, you can use **DevTool** to look for CSS variables that need to be modified, which are defined in the file `main.scss` and `post.scss` of `assets/css/`, but please be careful to modify them as this will affect the layout of adjacent elements.
