### ISSUE TITLE
Support giscus as an alternative for comment systems

### ISSUE THREAD

**Issue by nhvu1988** [cotes2020/jekyll-theme-chirpy#501]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There is no similar request on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

No, but it makes more sense to use GitHub discussion rather than the Github issue.

## Describe the solution you'd like

Since GitHub has a discussion feature that is really nice and available public now. The author of utterances also made a plugin for that as [giscus](https://giscus.app/). So it's nice if we can choose it as an alternative for comment systems

## Describe alternatives you've considered

No.

## Additional context

No.

**Comment by cotes2020** [comment]
alright :)
