### ISSUE TITLE
blank page after pushing to github

### ISSUE THREAD

**Issue by molitona** [cotes2020/jekyll-theme-chirpy#502]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug

when I test the template locally it works fine, when I push it to github, I get:
![s](https://user-images.githubusercontent.com/35532337/153241989-6095a22a-a0e3-462f-b3b6-7613949d657b.png)

### Expected behavior
My template appears.
NB: CI/CD worked fine on ubuntu and mac.

## Software

- Ruby version: 3.0.3p157 
- Gem version: 3.3.5
- Bundler version: 2.3.5
- Jekyll version: 4.2.1
- Theme version:  5.0.2

**Comment by NichtsHsu** [comment]
Did you follow steps in the turtorial?
> Now publish your Jekyll site by:
>
> 1. Push any commit to remote to trigger the GitHub Actions workflow. Once the build is complete and successful, a new remote branch named `gh-pages` will appear to store the built site files.
>
> 2. Browse to your repository on GitHub. Select the tab Settings, then click Pages in the left navigation bar, and then in the section **Source** of GitHub Pages, select the `/(root)` directory of branch `gh-pages` as the [publishing source](https://docs.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site)[](https://raw.githubusercontent.com/cotes2020/chirpy-images/main/posts/20190809/gh-pages-sources.png). Remember to click Save before leaving.
>
> ![gh-pages-sources](https://raw.githubusercontent.com/cotes2020/chirpy-images/main/posts/20190809/gh-pages-sources.png)

**Comment by xcodephile** [comment]
I faced the same issue. The solution is only [run this](https://chirpy.cotes.page/posts/getting-started/#deploy-by-using-github-actions):
```bundle lock --add-platform x86_64-linux```
![image](https://user-images.githubusercontent.com/11676357/153573287-b194166c-71f2-417c-a29f-748d52cd024b.png)

That command is only executed if your local machine is not linux, like mine, so Github Action can run properly.
![image](https://user-images.githubusercontent.com/11676357/153573789-74bd6a7c-4858-4490-a222-fd9af2efec0e.png)

**Comment by molitona** [comment]
> I faced the same issue. The solution is only [run this](https://chirpy.cotes.page/posts/getting-started/#deploy-by-using-github-actions): `bundle lock --add-platform x86_64-linux` ![image](https://user-images.githubusercontent.com/11676357/153573287-b194166c-71f2-417c-a29f-748d52cd024b.png)
> 
> That command is only executed if your local machine is not linux, like mine, so Github Action can run properly. ![image](https://user-images.githubusercontent.com/11676357/153573789-74bd6a7c-4858-4490-a222-fd9af2efec0e.png)

I've .github/workflows/pages-deploy.yml.hook not .github/workflows/pages-deploy.yml on my folder. Is it fine ?

**Comment by molitona** [comment]
> Did you follow steps in the [turtorial](https://chirpy.cotes.page/posts/getting-started/#deploy-by-using-github-actions)?
> 
> > Now publish your Jekyll site by:
> > 
> > 1. Push any commit to remote to trigger the GitHub Actions workflow. Once the build is complete and successful, a new remote branch named `gh-pages` will appear to store the built site files.
> > 2. Browse to your repository on GitHub. Select the tab Settings, then click Pages in the left navigation bar, and then in the section **Source** of GitHub Pages, select the `/(root)` directory of branch `gh-pages` as the [publishing source](https://docs.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site). Remember to click Save before leaving.
> > 
> > ![gh-pages-sources](https://raw.githubusercontent.com/cotes2020/chirpy-images/main/posts/20190809/gh-pages-sources.png)

It's same as mine.

**Comment by zhnzhang** [comment]
This may helps
![image](https://user-images.githubusercontent.com/46393174/154644216-112b2aa6-edaa-4e1b-adb4-839502fe919e.png)

**Comment by molitona** [comment]
> This may helps. ![image](https://user-images.githubusercontent.com/46393174/154644216-112b2aa6-edaa-4e1b-adb4-839502fe919e.png)

it's correct

**Comment by LeguizamonLuciano** [comment]
I had the same issue and solved it by going to my website and pressing ctrl+f5 to force cache update.

The browser for some reason gets stuck with an old version and shows that as the website

**Comment by CompetitiveLin** [comment]
I had the same issue and solved it by switching `main` to `master` in **both**  `pages-deploy.yml`**and** branch name. Although both of them were `main`. It's a bug, I suppose.
```
name: 'Automatic build'
on:
  push:
    branches:
      - master  # main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
```

**Comment by kangsangyeon** [comment]
> I had the same issue and solved it by switching `main` to `master` in **both** `pages-deploy.yml`**and** branch name. Although both of them were `main`. It's a bug, I suppose.
> 
> ```
> name: 'Automatic build'
> on:
>   push:
>     branches:
>       - master  # main
>     paths-ignore:
>       - .gitignore
>       - README.md
>       - LICENSE
> ```

You're awesome! I think it's absurd, but it's a real solution.
If you're ok, may I ask how did you found it?

**Comment by CompetitiveLin** [comment]
It's literally coincidental. I fount out there was no `gh-pages` branch in my repo after pushing any commits. So I think it must be something wrong when generating a new branch.

**Comment by Trimad** [comment]
> It's literally coincidental. I fount out there was no `gh-pages` branch in my repo after pushing any commits. So I think it must be something wrong when generating a new branch.

I've just come to the same conclusion. Came across this project today; attempted to publish to gh-pages but the branch was never created during the build process. All I see when I navigate to my forked jekyll blog is the contents of index.html:

```
---
layout: home
# Index page
---
```

**Comment by Jebearssica** [comment]
Same issue, I will try the solution mentioned above when my github action unblock by official

**Comment by securingdev** [comment]
For some reason my page continues to act dysfunctionally. The theme itself doesn't seem to show up either when I build locally and push to my pages site, or when I use the action. I've followed all of the advise above to try to get this to work 😞 

It's too bad really, I love this theme but no matter what I do it seems like the theme doesn't want to work with GitHub Pages.

**Comment by Jebearssica** [comment]
> 

have you try to switch the branch as it mentioned in the tutorial? Or have you check your action services work fine?

**Comment by Jebearssica** [comment]
> For some reason my page continues to act dysfunctionally. The theme itself doesn't seem to show up either when I build locally and push to my pages site, or when I use the action. I've followed all of the advice above to try to get this to work 😞 The really annoying part for me is that a locally served-up site looks exactly how I want it to look.
> 
> It's too bad really, I love this theme but no matter what I do it seems like the theme doesn't want to work with GitHub Pages.

have you try to switch the branch as it mentioned in the tutorial? Or have you check your action services work fine?

**Comment by securingdev** [comment]
So, as it turns out there were two configuration settings that weren't quite right. The way this section of the configuration reads caused me to enter `'/securingdev.github.io'` when actually I should have left it blank:

```
# Change the following value to '/PROJECT_NAME' ONLY IF your site type is GitHub Pages Project sites
# and doesn't have a custom domain.
baseurl: ''
```

I also changed the theme modeto `#[dark|light]` instead of leaving it as the default, which was causing an issue. It's now set back to:

```
theme_mode: # [light|dark]
```

**Comment by aungthurhahein** [comment]
After the first successful push and gh-pages branch is created, the 2nd push will failed in GitHub workflows. Delete gh-pages branch  and re-run workflow to get last update. I'll dig into the deploy script to find the issues more.

**Comment by 0xJs** [comment]
Having the same issues gh-pages branch is not being created.

**Comment by stantonwong** [comment]
If anyone is encountering a Permissions issue for the Actions:

Go to Settings > Actions > General, then scroll all the way down to "Workflow Permissions" and make sure that "Read and write permissions" is selected.

![Screen Shot 2022-05-01 at 5 22 09 PM](https://user-images.githubusercontent.com/3292593/166139942-6eb094d9-7091-41b7-bf0f-76b8044e08b9.png)

If "Read and write permissions" is greyed out, then you need to go to Organization level Settings > Actions > General, and make sure that is set first.
