### ISSUE TITLE
TOC: won't move when i scroll the page

### ISSUE THREAD

**Issue by lincolnlyj** [cotes2020/jekyll-theme-chirpy#507]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

When I scroll the page the TOC just stay in place, and won't focus on the desired heading when reading the article. It only happens when I deploy it on github. There's no problem with the local server.

**Comment by fxg** [comment]
Me too.
