### ISSUE TITLE
PWA: Do not cache subprojects

### ISSUE THREAD

**Issue by znlbwo** [cotes2020/jekyll-theme-chirpy#508]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There is no similar request on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

Use PWA under root path, but don't want to apply to subpaths.

## Describe the solution you'd like

Add judgment here:
https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/assets/js/pwa/sw.js#L52-L56

**Comment by znlbwo** [comment]
Set uncached subpaths in config files

**Comment by clearbluejar** [comment]
Still running into issues here. Would like an option to configure uncached subpaths.  This somewhat exists with `denyUrls` https://github.com/cotes2020/jekyll-theme-chirpy/blob/e107a2e759836510216ea8567aa8b203decace31/assets/js/data/swcache.js#L50-L54 . But no defaults in the config exist...
