### ISSUE TITLE
How can I change the default theme to light? Thank you.

### ISSUE THREAD

**Issue by i-hamdan** [cotes2020/jekyll-theme-chirpy#510]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

Dear Cotes,
First of all I would like to thank you so very much for this wonderful work. I am very new to web-dev and the thought of making something so elegant from scratch used to give me nightmares.

This is my query and it would be amazing if you could help me with this-
**Is there a way to change the default theme to the light one, but still keep the toggle functionality?**
I've tried swapping the files in sass folder, and other such rudimentary hacks with my limited knowledge, but they didn't work.

Thank you so much once again. Hope you are having a great year!

**Comment by NichtsHsu** [comment]
Hi @i-hamdan,

https://github.com/cotes2020/jekyll-theme-chirpy/blob/3969b28743392bb47de2365651df0e9b11d50c71/_includes/sidebar.html#L56-L64

This code block determines whether the theme toggle button should show.

https://github.com/cotes2020/jekyll-theme-chirpy/blob/3969b28743392bb47de2365651df0e9b11d50c71/_layouts/default.html#L22-L24

This code block determines whether the theme toggle functionality shoule be enabled.

Remove both `{% unless site.theme_mode %} ` and `{% endunless %}` to enable theme toggle always.

**Comment by hamdan-ai** [comment]
@NichtsHsu 
You are amazing! I am so grateful to you for taking the time to answer this so patiently. I was finally able to add the toggle on the light theme. Thanks! :))

**Comment by matt-goldman** [comment]
I'm using this theme based on the chirpy-starter and I don't see those files. I would like to achieve this too, do I need to start again?

**Comment by matt-goldman** [comment]
> I'm using this theme based on the chirpy-starter and I don't see those files. I would like to achieve this too, do I need to start again?

Nevermind, read the jekyll docs about overriding.
