### ISSUE TITLE
How can I customize/extend my site's functionality from chirpy starter?

### ISSUE THREAD

**Issue by raffertyuy** [cotes2020/jekyll-theme-chirpy#522]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

Hi, I'm new to jekyll and chirpy. I created my first site using the [chirpy starter](https://github.com/cotes2020/chirpy-starter/generate) and am hoping to customize/extend it. But I noticed that the chirpy starter doesn't have the `/_include` and '/_layout` folders while this repo has it.

Am I supposed to copy the files from here into my site?
Suggestions on where to learn how to extend will be helpful too (searching for "extending jekyll chirpy" isn't fruitful).

This is for a blog site where I'm trying to add:
1. An image carousell
2. A good source-code text widget

Thank you in advance!

**Comment by cotes2020** [comment]
See: <https://jekyllrb.com/docs/themes/>

**Comment by raffertyuy** [comment]
Thank you! Worked by copying the files from this repo :)

**Comment by jakre1234** [comment]
Hey @raffertyuy ,
Can you help how you did it? I needed to change the footer text, so I created a new folder _includes in my starter project and added a new footer.html file with my custom text. Is this the correct way of doing it ??

Thanks

**Comment by jakre1234** [comment]
Hey @raffertyuy ,
Thanks for your response. Yeah I have figured it long time back and I am really sorry for not updating the comments here. Once again thanks for the super awesome work you guys do ;)

Thanks and Regards,

**Comment by raffertyuy** [comment]
Awesome! I'm also just a user here, but agree with you, the contributors to this repo are awesome!
