### ISSUE TITLE
Avatar image not found in github action

### ISSUE THREAD

**Issue by jhaos** [cotes2020/jekyll-theme-chirpy#539]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

Hi, I started using `chirpy-started` and I've succeed adding an avatar image in my local deployment but when I try to upload into Github actions some errors appears 

```
Run bash tools/deploy.sh
Configuration file: /home/runner/work/jhaos.github.io/jhaos.github.io/_config.yml
 Theme Config file: /home/runner/work/jhaos.github.io/jhaos.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-theme-chirpy-5.1.0/_config.yml
            Source: /home/runner/work/jhaos.github.io/jhaos.github.io
       Destination: /home/runner/work/jhaos.github.io/jhaos.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.476 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
Running ["ScriptCheck", "LinkCheck", "ImageCheck", "HtmlCheck"] on ["_site"] on *.html... 


Ran on 17 files!
- _site/404.html

  *  internal image /assets/lib/me.jpg does not exist (line 1)

- _site/about/index.html
  *  internal image /assets/lib/me.jpg does not exist (line 1)
- _site/archives/index.html
  *  internal image /assets/lib/me.jpg does not exist (line 1)
- _site/categories/bash/index.html
  *  internal image /assets/lib/me.jpg does not exist (line 1)
- _site/categories/devops/index.html
  *  internal image /assets/lib/me.jpg does not exist (line 1)
- _site/categories/index.html
  *  internal image /assets/lib/me.jpg does not exist (line 1)
- _site/categories/kubernetes/index.html
  *  internal image /assets/lib/me.jpg does not exist (line 1)
- _site/categories/scripting/index.html
  *  internal image /assets/lib/me.jpg does not exist (line 1)
- _site/index.html
  *  internal image /assets/lib/me.jpg does not exist (line 1)
- _site/posts/Simple-k8s-scripts-to-test/index.html
  *  internal image /assets/lib/me.jpg does not exist (line 1)
- _site/posts/simple_bash/index.html
  *  internal image /assets/lib/me.jpg does not exist (line 1)
- _site/tags/bash/index.html
  *  internal image /assets/lib/me.jpg does not exist (line 1)
- _site/tags/index.html
  *  internal image /assets/lib/me.jpg does not exist (line 1)
- _site/tags/k8s/index.html
  *  internal image /assets/lib/me.jpg does not exist (line 1)

HTML-Proofer found 14 failures!
Error: Process completed with exit code 1.
```
After checking in the repo after the pull for the image I've seen that there is like a symbolic link to a branch in the same pathing where I placed the image `/assets/lib/me.jpg`. I also realize that a copy of the image has been place into `/_sites/assets/lib` but not sure what it means. Should I put it in another folder or create an specific one in order to make it work?

Thanks in advance.

### Update

I've changed the path of the image to the root of my folder and the copy inside /_sites/ and the github action worked correctly. Why inside assets folder it doesn't work?

**Comment by NichtsHsu** [comment]
Althought it cannot be reproduced in my enviroment, but I can answer some question.

1.  there is like a symbolic link to a branch ...

    No, not symbolic, it was called submodule.

     ```console
    $ git submodule--helper list
    160000 d1d2ec17c88176753d4dd2a1296620021dcc22fd 0       assets/lib
    ```

    You can learn more about it by `git help submodule`.

2. I also realize that a copy of the image has been place into /_sites/assets/lib but not sure what it means.

    The `_site` folder is the real location of your site, it was generated by all other folders and files, so you can find copies of almost all your assets. You have no need to add `/_site/...` as the prefix of image path, the `_site` folder will automatically be set as the root directory of your site.

**Comment by jhaos** [comment]
Thanks for the response,I will try again with this. Thanks for the clarifications, you can close the issue if you require.
