### ISSUE TITLE
404 page not formatted

### ISSUE THREAD

**Issue by m-peko** [cotes2020/jekyll-theme-chirpy#54]
**Describe the bug**

I am using Chirpy theme but, once I enter invalid URL, I get 404 page not formatted.

**To Reproduce**
1. Go to https://m-peko.github.io/craft-cpp/aa

**Expected behavior**

I would like to get the formatted 404 page.

**Comment by cotes2020** [comment]
Update your framework code please, I'm sure the 404 page will render properly.

**Comment by m-peko** [comment]
@cotes2020 what do you mean by update framework code? I have forked your repo few days ago.

**Comment by cotes2020** [comment]
I mean, keep your forked repo up to date. This issue no more existed.
