### ISSUE TITLE
Main content is not centred on ultra-wide displays

### ISSUE THREAD

**Issue by ZakKemble** [cotes2020/jekyll-theme-chirpy#540]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [ ] There is no similar request on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

@laitco ~~opened a issue a few days ago but it wasn't following the template and it looks like they might have abandoned it~~ - https://github.com/cotes2020/jekyll-theme-chirpy/issues/538
Nevermind, they wanted full-width rather than centred, but it's kinda related.

Most websites (GitHub, reddit, Twitter etc) keep the main content centred on ultra-wide displays, but Chirpy limits how far to the right it moves which gives you a bit of a sore neck after a while.

Chirpy not centred:
![ultrawide](https://user-images.githubusercontent.com/3110616/160294629-b4f219ca-09cd-4124-b1b6-f2406b90ee46.png)

GitHub centred:
![ultrawide2](https://user-images.githubusercontent.com/3110616/160294632-20b914c9-52d5-4ff9-8acc-abba0d66b8b0.png)

## Describe the solution you'd like

Main content should be centred.

**Comment by laitco** [comment]
Centered would also be fine for me!

**Comment by ZakKemble** [comment]
Just found this - https://github.com/cotes2020/jekyll-theme-chirpy/issues/445

However I don't understand @cotes2020 reasoning for not making the content centred :/

**Comment by laitco** [comment]
Maybe @cotes2020 can implement a optional configuration via config.yml to center the main content. Would be very nice!

**Comment by laitco** [comment]
Anything new ?

**Comment by ZakKemble** [comment]
Bump

**Comment by ZakKemble** [comment]
🚗

**Comment by Mixie-12** [comment]
Also wish the template was center alligned
