### ISSUE TITLE
A link with char '|' parsed as table

### ISSUE THREAD

**Issue by whuwangyong** [cotes2020/jekyll-theme-chirpy#542]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [ ] I found the bug on the latest code of the `master` branch.

## Describe the bug

if you put this in your md:
```
## Reference

1. [Getting Started | Chirpy (cotes.page)](https://chirpy.cotes.page/posts/getting-started/)
```
it displayed as a table row：
![image](https://user-images.githubusercontent.com/5968678/160649566-2a0f849d-7d5f-443d-b56e-b9f32f7d8e75.png)

### To Reproduce

just write a link with '|'.

### Expected behavior
![image](https://user-images.githubusercontent.com/5968678/160650740-31340cea-0dc2-442e-8a42-5f5a65916f04.png)

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |   ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x64-mingw-ucrt]   |
| `gem -v`                          |     3.3.7    |
| `bundle -v`                       |     Bundler version 2.3.10    |
| `bundle exec jekyll -v`           |    jekyll 4.2.2     |
| `bundle info jekyll-theme-chirpy` |     jekyll-theme-chirpy (5.1.0) 
        Summary: Chirpy is a minimal, sidebar, responsive web design Jekyll theme that focuses on text presentation.
        Homepage: https://github.com/cotes2020/jekyll-theme-chirpy
        Documentation: https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/README.md
        Source Code: https://github.com/cotes2020/jekyll-theme-chirpy
        Wiki: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
        Bug Tracker: https://github.com/cotes2020/jekyll-theme-chirpy/issues
        Path: D:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-theme-chirpy-5.1.0    |

### Desktop

- OS: Windows 10 21H1 
- Browser: Microsoft Edge 99.0.1150.55 (64 bit)

**Comment by whuwangyong** [comment]
> It is a simple Markdown syntax question. Use `\|` instead of `|`.

Yeah, but that's unreasonable. `|` can be used as  a normal character in typora, vscode, and here without `\`.
eg:
```
[foo | bar](#)
```
[foo | bar](#)

**Comment by NichtsHsu** [comment]
Jekyll defaultly uses [kramdown](https://kramdown.gettalong.org/index.html) as the Markdown parser, which is different with those you mentioned.

**Comment by whuwangyong** [comment]
Thank you! I got it!

**Comment by whuwangyong** [comment]
I read all issue of kramdown, the author said that the bug will be fixed on version 2.x in 2017 ([here](https://github.com/gettalong/kramdown/issues/431)).

I try to change markdown processor from kramdown to [commonmark](https://jekyllrb.com/docs/configuration/markdown/#commonmark), but they all have problems.

**Comment by gettalong** [comment]
@whuwangyong Yeah, version 2.x was meant to be the new major version with backward-incompatible syntax. However, 2.0 was done due to another reason and (mostly) kept being backwards compatible, especially syntax-wise.
