### ISSUE TITLE
Github Actions build failure after enabling gisqus support

### ISSUE THREAD

**Issue by allenphilip93** [cotes2020/jekyll-theme-chirpy#550]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug

Build fails after enabling **gisqus** with `comments/gisqus.html` not found error

### To Reproduce

1. Check for eligibility for gisqus integration and configured the same from https://giscus.app 
2. Configured the giscus repo, repoId, category & categoryId from _config.yml
3. Push changes to branch
4. See error in Github actions
5. Checked jekyll-theme-chirpy-5.1.0 package and it has the comments/gisqus.html
6. Works fine after reverting to disqus

```
Configuration file: /home/runner/work/allenphilip93.github.io/allenphilip93.github.io/_config.yml
 Theme Config file: /home/runner/work/allenphilip93.github.io/allenphilip93.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-theme-chirpy-[5](https://github.com/allenphilip93/allenphilip93.github.io/runs/5845078697?check_suite_focus=true#step:4:5).1.0/_config.yml
            Source: /home/runner/work/allenphilip93.github.io/allenphilip93.github.io
       Destination: /home/runner/work/allenphilip93.github.io/allenphilip93.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Could not locate the included file 'comments/gisqus.html' in any of ["/home/runner/work/allenphilip93.github.io/allenphilip93.github.io/_includes", "/home/runner/work/allenphilip93.github.io/allenphilip93.github.io/vendor/bundle/ruby/2.[7](https://github.com/allenphilip93/allenphilip93.github.io/runs/5845078697?check_suite_focus=true#step:4:7).0/gems/jekyll-theme-chirpy-5.1.0/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. in /home/runner/work/allenphilip[9](https://github.com/allenphilip93/allenphilip93.github.io/runs/5845078697?check_suite_focus=true#step:4:9)3.github.io/allenphilip93.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-theme-chirpy-5.1.0/_layouts/page.html
                    ------------------------------------------------
      Jekyll 4.2.2   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/home/runner/work/allenphilip93.github.io/allenphilip93.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.2/lib/jekyll/tags/include.rb:219:in `locate_include_file': Could not locate the included file 'comments/gisqus.html' in any of ["/home/runner/work/allenphilip93.github.io/allenphilip93.github.io/_includes", "/home/runner/work/allenphilip93.github.io/allenphilip93.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-theme-chirpy-5.1.0/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. (IOError)
```

### Expected behavior

No error

### Screenshots

![image](https://user-images.githubusercontent.com/20537002/161898367-0b8b50d4-369b-4010-aa87-e264944936f9.png)

### Environment

**Repo**: https://github.com/allenphilip93/allenphilip93.github.io 

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |         |
| `gem -v`                          |         |
| `bundle -v`                       |         |
| `bundle exec jekyll -v`           |    4.2.2     |
| `bundle info jekyll-theme-chirpy` |    5.1.0     |

**Comment by NichtsHsu** [comment]
Not `gisqus`, it is `giscus`. Please check it.
