### ISSUE TITLE
Google Analytics doesn't work with 'G-XXXXXXXXXX' tag id. 

### ISSUE THREAD

**Issue by jintak0401** [cotes2020/jekyll-theme-chirpy#551]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug
Google Analytics doesn't work with 'G-XXXXXXXXXX' tag id. I insert my own 'G-XXXXXXXX' tag and wait for a long time, but google analytics says there is no website having my own tag. 

I know there is a [Enable Google Page Views](https://chirpy.cotes.page/posts/enable-google-pv/) tutorial. This tutorial also use 'G-XXXXXXXXXX' format id. But unlike that, my blog doesn't connect Google Analytics.

### To Reproduce
1. insert 'G-XXXXXX' tag in _config.yml file.
  e.g.) google_analytics:
              id: 'G-J9DD336B3H'   # I also insert G-J9DD336B3H, without quote, but also not works. 

2. waiting
3. I found it doesn't work.

### Expected behavior
Google Analytics works with 'G-XXXXXXXXXX' format id.

### Screenshots
![image](https://user-images.githubusercontent.com/32933980/162023707-c882f376-2b39-4804-95eb-4047dc119c1b.png)
<Figure1. devtools of [my blog](https://jintak0401.github.io)>

![image](https://user-images.githubusercontent.com/32933980/162025051-9f4bf5d2-f4de-4c49-af61-f003a1c6b575.png)
<Figure2. Google Analytics page of [my blog](https://jintak0401.github.io)>

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |    3.1.1p18     |
| `gem -v`                          |   3.3.7      |
| `bundle -v`                       |     2.3.10     |
| `bundle exec jekyll -v`           |   4.2.2      |
| `bundle info jekyll-theme-chirpy` |  5.1.0       |

### Desktop
OS: Windows 10 Version 21H2
Browser: Chrome 100.0.4896.75

**Comment by chom3** [comment]
FYI This might be incorrect in the guide section 

```
Now, click on the new data stream and grab the Measurement ID. It should look something like G-V6XXXXXXXX. Copy this to your _config.yml file:
```

My GA works after using the Tracking ID under "Tracking Code" - something like UA-*********-*.

**Comment by vendra** [comment]
Same for me, I can't find a UA-like ID, but I think maybe it can be requested?

**Comment by rexdivakar** [comment]
Even I'm facing the same problem, tried updating templates too but so far no good and even my Tracking code starts with GA

**Comment by rexdivakar** [comment]
Hey @cotes2020  can you please advice solution to this issue ?

**Comment by cotes2020** [comment]
@rexdivakar The template only guarantees that the output content contains GA (Google Analytics) code blocks. As for "why the information cannot be collected", there are various reasons, the most common is that the ad-block plugin of your browser prohibits the GA code from working, or your GA account has set a filter condition. So, do a Google search for "google analytics not working" and here's my advice.
