### ISSUE TITLE
Can't disable social icon?

### ISSUE THREAD

**Issue by xiaod-dev** [cotes2020/jekyll-theme-chirpy#556]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

I tried comment the twitter username lines in `config.yaml`, 

```yaml
# twitter:
#   username:             # change to your twitter username
```

and even remove those two line, after execute `jekyll clean` and `jekyll s`, It still show the twitter icon on the left bottom of page with link https://twitter.com/twitter_username. Is there any way that I can fix this issue?

**Comment by NichtsHsu** [comment]
Commit or remove these lines.

https://github.com/xiaod-dev/xiaod-dev.github.io/blob/ae6914c05918a1d26486a3d624c250677899390e/_data/contact.yml#L6-L8

**Comment by xiaod-dev** [comment]
> Comment or remove these lines.
> 
> https://github.com/xiaod-dev/xiaod-dev.github.io/blob/ae6914c05918a1d26486a3d624c250677899390e/_data/contact.yml#L6-L8

It works! Thanks a lot buddy!
