### ISSUE TITLE
Html from

### ISSUE THREAD

**Issue by ankit0183** [cotes2020/jekyll-theme-chirpy#559]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [ ] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |         |
| `gem -v`                          |         |
| `bundle -v`                       |         |
| `bundle exec jekyll -v`           |         |
| `bundle info jekyll-theme-chirpy` |         |

### Additional context

How to save post in html formet? its only in md formet

**Comment by ankit0183** [comment]
need html from insted of html

**Comment by nav272** [comment]
I have a similar issue, where I am trying to use the chirpy-starter theme, I can get it to work on my Windows host machine, but when I deploy the same on Github pages, I get a plaintext output of the index.html file which looks something like this: 

![image](https://user-images.githubusercontent.com/23533076/163331604-56659add-7dec-4f04-904e-54e9eafb68db.png)

I followed the similar steps described in the tutorial, but I am not getting the same output as my localhost which looks like this: 

![image](https://user-images.githubusercontent.com/23533076/163331905-32f66f26-42bc-44a4-919d-5b01cefa15f6.png)

Is this a known issue or am I doing something wrong while configuring it? 

Any feedback will be appreciated.

**Comment by Avijneyam** [comment]
sorry for posting here but can u check this @cotes2020 
https://github.com/cotes2020/jekyll-theme-chirpy/issues/564#issue-1225464876
