### ISSUE TITLE
How to make multilanguage posts?

### ISSUE THREAD

**Issue by cotur** [cotes2020/jekyll-theme-chirpy#56]
Hi, it is really awesome repository, thx to all who contributed and developed.

I just wondering how I can make it multilanguage website? It does not necessary for translation all components like layout etc. I just want to do share my posts in different languages.

Is it possible? Any suggestion?

**Comment by cotes2020** [comment]
Maybe this [post](https://forestry.io/blog/creating-a-multilingual-blog-with-jekyll/) will give you inspiration. :)

**Comment by cotur** [comment]
Thx, it's exactly what i need. :)

**Comment by thamara** [comment]
Hey @cotes2020, do you think a built-in solution based on this suggested post would be a fit for the theme? Do you think it's feasible?
I'm interested in this feature, specially if this could be included in the starter template. I would be willing to work on this too (not only asking for the feature), but I'm not sure if this really fits the theme.

**Comment by cotes2020** [comment]
Hi @thamara, 

As an indicator of modern websites, i18n is undoubtedly suitable for every website, including this theme. If you are willing to take the time to implement this feature, I would be very grateful.

**Comment by Renardjojo** [comment]
Hey, any news on this topic? I'm interested in this feature and may try to implement it if no one else does.

**Comment by asandikci** [comment]
any update on this?
