### ISSUE TITLE
Giscus comment section isn't enabled

### ISSUE THREAD

**Issue by EhsanAramide** [cotes2020/jekyll-theme-chirpy#560]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [ ] I found the bug on the latest code of the `master` branch.

## Describe the bug

I clone the repo about 3 days ago and I wanted to add comment feature with `giscus`, but after I added the settings to `_config.yml` the comment section wasn't enabled.
I did all step by step based on the tutorials.
Necessary links:
[Comment configs](https://github.com/EhsanAramide/ehsanaramide.github.io/blob/f70902a71bfad707626ed9f2a21a4c3548d50b64/_config.yml#L91)

I wrote some test posts you can [check them online](https://ehsanaramide.github.io)

**Comment by NichtsHsu** [comment]
You should config `active: 'giscus'`.

https://github.com/EhsanAramide/ehsanaramide.github.io/blob/f70902a71bfad707626ed9f2a21a4c3548d50b64/_config.yml#L91-L92

**Comment by EhsanAramide** [comment]
Thank you 🙏🌹
