### ISSUE TITLE
Error "_mv: cannot stat 'site/*': No such file or directory" at deploy step at GitHub workflow

### ISSUE THREAD

**Issue by aungthurhahein** [cotes2020/jekyll-theme-chirpy#561]
## Checklist

- [x ] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x ] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [ x] I found the bug on the latest code of the `master` branch.

## Describe the bug

The error "_mv: cannot stat '_site/*': No such file or directory_" at deploy step of GitHub deploy workflow to gh-pages.
If there is no gh-pages, it don't make error and deploy to gh-pages successfully.
I dry-run local deploy.sh script at local and there is no error as such.

Please help. I am really settle down with this theme.

### Expected behavior
To deploy new updated content to gh-pages from main branch.

### Screenshots
<img width="865" alt="Screen Shot 2022-04-22 at 2 48 08 PM" src="https://user-images.githubusercontent.com/2157987/164721797-87bc61a6-344a-4e70-a6a4-90e4acf6b6a3.png">

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |    3.1.1p18   |
| `gem -v`                          |     3.3.7    |
| `bundle -v`                       |    2.3.11     |
| `bundle exec jekyll -v`           |    4.2.2     |
| `bundle info jekyll-theme-chirpy` |  5.1.0  |

### Additional context
my GitHub repo: https://github.com/aungthurhahein/aungthurhahein.github.io

**Comment by NichtsHsu** [comment]
Please delete the `_site` folder on your repo.

**Comment by aungthurhahein** [comment]
@NichtsHsu  Thanks. it seems to be the reason. should i include '_site/' in .gitignore or just "_site"?
