### ISSUE TITLE
Alignment issue

### ISSUE THREAD

**Issue by Avijneyam** [cotes2020/jekyll-theme-chirpy#564]
In half windows alignment is ok:
![image](https://user-images.githubusercontent.com/72083951/166704603-8651b03a-0804-4dd2-93d3-82a2b345621a.png)
But in full windows is not ok:
![image](https://user-images.githubusercontent.com/72083951/166704927-44e8e9ad-398c-4f2f-9d13-9e29f24ecf78.png)

**Comment by NichtsHsu** [comment]
Hi @Avijneyam,

I think it is not a issue but a feature.

If you don't like it, you can keep it centered by remove following lines:

https://github.com/cotes2020/jekyll-theme-chirpy/blob/b7ad538ce2d4db5409778bbfb43c8edc456cb924/_sass/addon/commons.scss#L1587-L1628

**Comment by Avijneyam** [comment]
> Hi @Avijneyam,
> 
> I think it is not a issue but a feature.
> 
> If you don't like it, you can keep it centered by remove following lines:
> 
> https://github.com/cotes2020/jekyll-theme-chirpy/blob/b7ad538ce2d4db5409778bbfb43c8edc456cb924/_sass/addon/commons.scss#L1587-L1628

Thanks i fixed that do u know how to remove this extra space 
![image](https://user-images.githubusercontent.com/72083951/166982773-0afd56af-dc6c-4bee-bac1-b56e39e4f995.png)

**Comment by DylanDijk** [comment]
How would you make the avatar bigger?

**Comment by Fancy-Tomato** [comment]
> Hi @Avijneyam,
> 
> https://github.com/cotes2020/jekyll-theme-chirpy/blob/b7ad538ce2d4db5409778bbfb43c8edc456cb924/_sass/addon/commons.scss#L1587-L1628

I think the code has been changed.😭
I am also having a problem that avatar, profile is not aligned in the center.
Could you help me?
thank you
