### ISSUE TITLE
Content sidebar not working properly due to numbered sections

### ISSUE THREAD

**Issue by marcosruiz** [cotes2020/jekyll-theme-chirpy#572]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug

As you can see in [this article](https://marcosruiz.github.io/posts/clasificacion-de-redes/)  the content sidebar (table of content) does not work properly. This is due the numbered sections.

### To Reproduce

1. Create a markdown post.
2. Create sections numbered like this "1. Header", "1.1. Subheader", etc.
3. `bundle exec jekyll serve`
4. See error on the table of content of the sidebar (right). No animations. It is like you always are in the begining of the document.

### Expected behavior

I expect that the table of content shows subsections of the section I am reading.

### Screenshots

How it should be:

![imagen](https://user-images.githubusercontent.com/7647613/168986010-7592dc43-7687-461c-b900-cf94c996486e.png)

How it is:

![imagen](https://user-images.githubusercontent.com/7647613/168986189-8481d418-6fe4-4a14-b16a-b82fd227209c.png)

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |    ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]     |
| `gem -v`                          |     3.2.32    |
| `bundle -v`                       |      Bundler version 2.3.4   |
| `bundle exec jekyll -v`           |     jekyll 4.2.2    |
| `bundle info jekyll-theme-chirpy` |   jekyll-theme-chirpy (5.1.0)      |

### Desktop

- OS: Windows 11 Home. Version: 10.0.22000
- Browser: Firefox 100.0 (64-bit)

**Comment by cotes2020** [comment]
It's a limitation (or bug) of plugin [bootstrap-toc](https://github.com/afeld/bootstrap-toc), see https://github.com/afeld/bootstrap-toc/issues/64
