### ISSUE TITLE
How can I remove tabs?

### ISSUE THREAD

**Issue by vendra** [cotes2020/jekyll-theme-chirpy#576]
## Checklist

- [X] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [X] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [X] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [X] My question is based on the latest code of the `master` branch.

## Description

I'd like to remove the Tag and Archives tabs from the left menu, I tried deleting the .md files and locally, it works. But when I upload it to github I get 

```
Ran on 9 files!
- _site/404.html

  *  internally linking to /archives, which does not exist (line 1)

     <a href="/archives">Archives page</a>

HTML-Proofer found 1 failure!
```

How can i fix this? It looks like 404.html is linking to it, should I change that? 

Moreover, is there a way to run the same pipeline as github pages, locally, so that I catch these kind of errors beforehand?

Thanks

**Comment by cotes2020** [comment]
>  It looks like 404.html is linking to it, should I change that?

Yes, remove the link to _Archives_ in  file `404.html`

> is there a way to run the same pipeline as github pages, locally ...

Run `bash ./tools/deploy.sh --dry-run`
