### ISSUE TITLE
Site not deploy

### ISSUE THREAD

**Issue by pwndumb** [cotes2020/jekyll-theme-chirpy#578]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description
The site works fine in local with docker but after  change my _config.yml and setup all variables according the tutorial, the github web page only show this in my web page: 

https://pwndumb.github.io//
--- layout: home # Index page ---

PS: I really sorry If this is a simple question but I cant found the solution.

**Comment by Bharatummadi** [comment]
I'm facing the same issue.
https://bharatummadi.github.io/
![image](https://user-images.githubusercontent.com/41880719/169641645-2f8a0d0c-04ff-4ab3-8677-cfe1073c3c10.png)

**Comment by CompetitiveLin** [comment]
See [here](https://github.com/cotes2020/jekyll-theme-chirpy/issues/502)

**Comment by CompetitiveLin** [comment]
#502

**Comment by CompetitiveLin** [comment]
See #502

**Comment by Bharatummadi** [comment]
I just figured out the solution. I have missed changing the baseurl in _config.yml file. Thanks @CompetitiveLin

**Comment by pwndumb** [comment]
> I just figured out the solution. I have missed changing the baseurl in _config.yml file. Thanks @CompetitiveLin

Can you show me how ? Because I change and not work for me.

**Comment by pwndumb** [comment]
> See #502

![image](https://user-images.githubusercontent.com/6491534/169657996-1953433d-a873-4cf7-a2fa-bf1d03074291.png)


> See #502

I changed branch to master, setup baseurl but my site is not deploy. I clone https://chirpy.cotes.page/ but even this work.

**Comment by pwndumb** [comment]
I not found any solution.
