### ISSUE TITLE
Is it possible to replace Twitter icon with something else (for example: LinkedIn)?

### ISSUE THREAD

**Issue by bdolewski** [cotes2020/jekyll-theme-chirpy#58]
Hi!
I'm trying to customize the icon in the bottom left corner. I was playing with `_config.yml` file, trying to uncomment LinkedIn link in the `social:` part or simply removing `twitter:` part from this config file. 
Unfortunately nothing changed. Is it possible at all to replace some of those social website icons (buttons?) to something else or simply remove one of them?

**Comment by cotes2020** [comment]
The `social` of file `_config.yml` is used for [jekyll-seo-tag](https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md), so as you do, it won't work. 

You should change these:
https://github.com/cotes2020/jekyll-theme-chirpy/blob/062f009400e62470ed9a75a04315ece953fba3b5/_includes/sidebar.html#L67-L79

And the replaced icon could be found at <https://fontawesome.com/>.

**Comment by bdolewski** [comment]
That was instant, precise help - thank you very much!

**Comment by cotes2020** [comment]
I've made it much easier to configure. See 054a769e551640ca68d15df3da5ccb06ba3e1e44.

**Comment by bdolewski** [comment]
> I've made it much easier to configure. See 054a769.
It does look better. I fixed code for my needs but will revert it and follow your version.
