### ISSUE TITLE
The URL path in the tag is missing

### ISSUE THREAD

**Issue by Cc360428** [cotes2020/jekyll-theme-chirpy#580]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

### Expected behavior
My project repository name ("Cc360428.github.io"), I set it in _config.yaml,
url: "https://cc360428.github.io" and baseurl: "/" ;
In tags, the display is normal, but if you select the article URL in it, the url will be missing. If I don't set the baseurl, all the displays will show errors, and there will be more blogs.

### Screenshots
<img width="619" alt="image" src="https://user-images.githubusercontent.com/46546968/169642142-799bbce5-f861-4576-8e48-c12964261d9c.png">

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         | 2.6.3p62|
| `gem -v`                          | 3.0.3   |
| `bundle -v`                       |2.3.13   |
| `bundle exec jekyll -v`           |         |
| `bundle info jekyll-theme-chirpy` |         |

**Comment by CompetitiveLin** [comment]
I checked your repo, and I don't think you're following the tutorials.😂
