### ISSUE TITLE
Unexpected token '<' and failed to get JSON at some file .min.js

### ISSUE THREAD

**Issue by th13ntc** [cotes2020/jekyll-theme-chirpy#584]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

I have just deploy Github page following tutorial. But I have problem with bug `Unexpected token '<'` at `home.min.js`, `app.js` and `SimpleJekyllSearch --- failed to get JSON` at `simple-jekyll-search.min.js`.
I don't have custom anything

![image](https://user-images.githubusercontent.com/47786126/170478604-9ea9bb6b-7ba6-42ca-8be0-bdb5b0f09bd1.png)

Thanks for help

**Comment by plzprayme** [comment]
same issue

**Comment by th13ntc** [comment]
I hope some one have solution for this issue :<

**Comment by th13ntc** [comment]
More info:
I read `.js`, `.webmanifest` and response is different with `.js`, `.webmanifest` in `gh-pages`.
Someone please explain to me :< thank you so much

![image](https://user-images.githubusercontent.com/47786126/170829795-afe52697-2d70-4bb6-8b34-c312db271b62.png)
![image](https://user-images.githubusercontent.com/47786126/170829928-fc04e7e7-4d15-4a72-b374-20a98336929f.png)
![image](https://user-images.githubusercontent.com/47786126/170829983-a637adf5-aab8-4fbf-a32f-b2b6476ad3dc.png)

**Comment by hkamel** [comment]
I had the same issue, you need to update the following line in your _config.yml
From 
`
baseurl: '/RepoName'`
To 
`
baseurl: '/'`

**Comment by th13ntc** [comment]
> I had the same issue, you need to update the following line in your _config.yml From ` baseurl: '/RepoName'` To ` baseurl: '/'`

Thanks for help <3 It work
