### ISSUE TITLE
Problems upgrading from 5.0.0 to 5.1.0

### ISSUE THREAD

**Issue by serrapa** [cotes2020/jekyll-theme-chirpy#587]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

I updated from `gem "jekyll-theme-chirpy", "~> 5.0", ">= 5.0.0"` to `gem "jekyll-theme-chirpy", "~> 5.1", ">= 5.1.0"`, but it seems assets are not loaded when I request any page. I also noticed that the **_Upgrading from 5.0.x to 5.1.0_** update in the Upgrade Guide goes from 5.0.2 to 5.1.0, so I don't know how to find the changes from 5.0.0 to 5.0.2 (maybe for this reason my upgrade didn't work properly)

ps: I followed all steps mentioned on the Upgrading chapter, in particularly for the first method (I didn't forked from the source project and don't have `gemspec` in the Gemfile of my site). Moreover, I also followed the steps on https://github.com/cotes2020/chirpy-static-assets, but it didn't help

![Screenshot 2022-05-28 at 00 48 47](https://user-images.githubusercontent.com/26407305/170797974-9c137364-e734-4a13-b015-215a41cd4529.png)

**Comment by cotes2020** [comment]
Hey @serrapa, _5.0.0_ to _5.0.2_ changes nothing but the version number in `Gemfile`.  You can view the file changes by <https://github.com/cotes2020/chirpy-starter/compare/bf93d13...main>

Format: `https://github.com/cotes2020/chirpy-starter/compare/<basic_commit>...<targer_commit>`

Reference: <https://docs.github.com/en/pull-requests/committing-changes-to-your-project/viewing-and-comparing-commits/comparing-commits>

**Comment by serrapa** [comment]
Thanks @cotes2020, so if nothing changed except for the version number, why assets are not loaded after getting the page requested? I applied all changes did from 5.0.0 to 5.1.0 as showed in the Upgrading Guide page in the wiki page
