### ISSUE TITLE
Light mode styles are not being loaded

### ISSUE THREAD

**Issue by vendra** [cotes2020/jekyll-theme-chirpy#588]
## Checklist

- [X] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [X] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [X] I found the bug on the latest code of the `master` branch.

## Describe the bug

The sidebar style is not working when I select `theme_mode: light` in the _config.yml and when building it locally, the avatar is not rendered.

But if I left `theme_mode: `  blank or dark, it works without problems. 

### To Reproduce

just switching between empty and light theme is enough

### Expected behavior

To display the sidebar style correctly 

### Screenshots

[Screenshots](https://postimg.cc/gallery/PdC8k53)

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |      3.1.1p18 (2022-02-18 revision 53f5fc4236) [x64-mingw-ucrt]   |
| `gem -v`                          |    3.3.7     |
| `bundle -v`                       |    2.3.9     |
| `bundle exec jekyll -v`           |     4.2.2    |
| `bundle info jekyll-theme-chirpy` |    5.1.0     |

### Desktop

I tried chrome, firefox

### Smartphone

It's working fine on smartphone

**Comment by cotes2020** [comment]
Thanks for the report!

**Comment by vendra** [comment]
@cotes2020 how can I fix it as well on my repo?
