### ISSUE TITLE
Change homepage

### ISSUE THREAD

**Issue by justlucdewit** [cotes2020/jekyll-theme-chirpy#589]
## Checklist

- [X] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [X] There is no similar request on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [X] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [X] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

I would like to be able to change the home page, right now it is just an empty page with the post feed, but i would like to be able to put custom text there to greet people to my website and introduce myself, however, from what I could see this is not possible.

## Describe the solution you'd like

I would like to see a way to change the home page somehow, maybe it would be possible to make it able to overwrite when u create a home.md page, or trough some other way. Maybe its possible to change the starting page in the _config.yml

## Describe alternatives you've considered

I would really like to have a custom home page however i really dont see any way to do this or have some kind of work around, for now im going to have to deal with having no proper home page :(

## Additional context
![image](https://user-images.githubusercontent.com/37410843/171184362-2f5cc57c-f980-41cd-887a-ee21da9177e3.png)

**Comment by LawssssCat** [comment]
What i think you should modify is the file `./_layouts/home.html` because what the homepage shows is based on it
