### ISSUE TITLE
How can I add LinkedIn share button to each post?

### ISSUE THREAD

**Issue by Hamzablm** [cotes2020/jekyll-theme-chirpy#60]
First, I want to thank you for building this awesome theme. I am wondering how can I add LinkedIn share button to my posts?
![image](https://user-images.githubusercontent.com/32052228/82821450-0e496800-9e9c-11ea-8c6c-964be7c5c4da.png)

**Comment by cotes2020** [comment]
Please refer to the existing content on [`_data/share.yml`](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/_data/share.yml) to add new options.

**Comment by Hamzablm** [comment]
Many thanks! Works fine.
