### ISSUE TITLE
Default layout content slides under topbar

### ISSUE THREAD

**Issue by borosbence** [cotes2020/jekyll-theme-chirpy#600]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug

If I choose the default theme as my home page (to make the right panel disappear), the content slides below the top menu.

### To Reproduce

1. Change index.html or another page layout to _default_
2. Add a content to the site.
3. Examine it in Developer Tools

### Expected behavior

The content of the page must start in the same place as the other pages.
These 3 divs before the _{{ content }}_ in the default.html solves the problem:
```
<div class="row">
    <div id="core-wrapper">
        <div class="mt-5">
```

### Screenshots

![image](https://user-images.githubusercontent.com/39780892/173124474-7200cd27-7db4-4ef6-a047-3474fba8b8ce.png)

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |  ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x64-mingw-ucrt]  |
| `gem -v`                          | 3.3.7 |
| `bundle -v`                       | 2.3.15 |
| `bundle exec jekyll -v`           | jekyll 4.2.2 |
| `bundle info jekyll-theme-chirpy` | jekyll-theme-chirpy (5.2.0) |

### Desktop

- OS: Windows 10
- Browser: Microsoft Edge 102.0.1245.33

**Comment by cotes2020** [comment]
Please don't call exceptions caused by your code changes as bugs. Take the time to learn the basics of Jekyll and understand the code for this project.
