### ISSUE TITLE
Chirpy theme multilingual

### ISSUE THREAD

**Issue by mojex** [cotes2020/jekyll-theme-chirpy#604]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

How can I make the Chirpy theme multilingual so that the visitor can click on a link and see all the layouts and post changes in another language?

**Comment by PlexSheep** [comment]
I'd be interested in this too. I'm a german and want to have my site in german, but I also want to offer an english version for international visitors. Blog Posts might be written in either language, in cases where only one language exists, the post should say something like "this post is only available in german".

**Comment by yunseo-kim** [comment]
@PlexSheep I'm a Korean who had the same interest, and in my case, I utilized the [Polyglot](https://github.com/untra/polyglot) plugin to implement a multilingual blog. [I've summarized the implementation process on my blog](https://www.yunseo.kim/de/posts/how-to-support-multi-language-on-jekyll-blog-with-polyglot-1/), which might be helpful for you.

**Comment by PlexSheep** [comment]
@yunseo-kim Thank you. I will have a read.

**Comment by geekifan** [comment]
To enable i18n support for Chirpy without the hassle of relying on third-party plugins, my [hugo-theme-chirpy](https://github.com/geekifan/hugo-theme-chirpy) project migrated the Chirpy theme to [Hugo](https://gohugo.io/) with minimal adaptations. All features of Chirpy are available in hugo-theme-chirpy (though some functionalities may operate differently within the Hugo framework).
