### ISSUE TITLE
I have an idea to make this theme better for OCD people!

### ISSUE THREAD

**Issue by Kizuo** [cotes2020/jekyll-theme-chirpy#607]
## Checklist

- [ x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [ x] There is no similar request on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [ x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [ x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe
It isn't really a problem, but I just have OCD. 

## Describe the solution you'd like

Can you please move the RSS feed button all the way to the right on the theme? After that, can you reply to this issue and talk about what changes you made so I can add them to my website? Thank you!

## Describe alternatives you've considered

I just tried to live with it, but I couldn't. 

## Additional context

I don't really have any!

**Comment by SilentGlasses** [comment]
Not sure if this is right but I think you can just remove the RSS section on the `_includes/sidebar.html` template.
