### ISSUE TITLE
Problem with Footnotes

### ISSUE THREAD

**Issue by PhDane** [cotes2020/jekyll-theme-chirpy#608]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones). _There is one open issue regarding footnotes, but this is truly a different issue._
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug
For some reason, despite following the markdown on the ["Text and Typography" post](https://chirpy.cotes.page/posts/text-and-typography/#fnref:footnote), my footnotes are appearing as text.

### To Reproduce
Go to this [post](https://www.phdane.com/posts/merton-1942-a-note-on-science-and-democracy/#organized-scepticism-1).  Scroll down to the paragraph on Organized Scepticism.  In this case, the footnote is in a header and is rendering as text, but the problem remained when I had it in the body as well.  Adding a leading space made no difference either.

### Expected behavior
I expect there to be a superscript 1 that links to a footnote, but instead I'm getting "[^1]".  The footnote at the bottom of the doc is also displayed as text.

### Screenshots

Not necessary.

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |      ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x64-mingw-ucrt]   |
| `gem -v`                          |   3.3.7      |
| `bundle -v`                       |  Bundler version 2.3.15   |
| `bundle exec jekyll -v`           |    jekyll 4.2.2     |
| `bundle info jekyll-theme-chirpy` |   jekyll-theme-chirpy (5.2.0)      |

### Desktop

- OS: Windows 10
- Browser: Chrome Version 102.0.5005.115 (Official Build) (64-bit)

### Additional context
I'm not sure what I'm doing wrong, but hopefully someone who later has this same problem will find this issue!

**Comment by cotes2020** [comment]
You can't add a corner note to the title, it's a markdown syntax error

**Comment by PhDane** [comment]
Thanks for the response!  I've amended the previously linked post to include the footnote in the body and it still exhibits the same behavior.
