### ISSUE TITLE
Organizing the Toc and Categories to be more intuitive for viewer

### ISSUE THREAD

**Issue by Cloufisz** [cotes2020/jekyll-theme-chirpy#61]
First. I am really greatful for your work. And the effort you put into managing issues :+1: 
**Is your feature request related to a problem? Please describe.**

I don't see the point of having the tags in the Toc without the number of how many posts with particular tag there are (After hoover)
The same thing goes to categories.

And maybe I'm bias, but I prefer sorting the articles by categories first AND THEN looking at tags for particular post

**Describe the solution you'd like**

- Adding the number of how many posts there are in each category
- Having the listed tags next to posts titles not only in search results

**Describe alternatives you've considered**

**Additional context**

The great example of this is HyG's blog theme:

![Having listed tags next to posts](https://user-images.githubusercontent.com/32965886/82843661-1e823700-9ede-11ea-8b2e-803bdee2809b.png)

![Having the number of how many posts there are in each category](https://user-images.githubusercontent.com/32965886/82843693-3b1e6f00-9ede-11ea-864e-bcfcdafb365d.png)

Again I thank you for this amazing project :)

**Comment by cotes2020** [comment]
> - Adding the number of how many posts there are in each category
![categories](https://user-images.githubusercontent.com/11371340/82845097-b3eced80-9f15-11ea-906f-79cd22fee433.png)

> -  Having the listed tags next to posts titles not only in search results
![meta-of-postsl](https://user-images.githubusercontent.com/11371340/82845100-b8190b00-9f15-11ea-9930-b4ca2717548c.png)
