### ISSUE TITLE
Bulgarian Translation

### ISSUE THREAD

**Issue by MrEddX** [cotes2020/jekyll-theme-chirpy#610]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

I can help with Bulgarian translation if you wish.

**Comment by cotes2020** [comment]
Alright : )

**Comment by MrEddX** [comment]
I plan to approach it this way:

- Fork this repo
- Copy `/_data/locales/en.yml` as `/_data/locales/bg-BG.yml`
- Translate all fields
- Self review
- Commit into a new branch, for example `bulgarian`
- I will test it to see if it generates errors during the build and deployment 
- Create Pull Request

Any recommendations?

**Comment by cotes2020** [comment]
That would be totally enough.
