### ISSUE TITLE
Font awesome icons not showing in menu when using firefox

### ISSUE THREAD

**Issue by martyca** [cotes2020/jekyll-theme-chirpy#618]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug

The font awesome icons on the left hand side of the menu items [Home, Categories, Tags, Archives, About] are not showing when using firefox.

### To Reproduce
1. use firefox 101.0.1 and open https://chirpy.cotes.page/ the icons will not appear on the left hand side of the menu items

### Expected behavior

Im expecting to see the font awesome icons when using firefox.

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |         |
| `gem -v`                          |         |
| `bundle -v`                       |         |
| `bundle exec jekyll -v`           |         |
| `bundle info jekyll-theme-chirpy` |         |

### Desktop

- OS: macOS Monterey12.1 (21C52)
- Browser: Firefox 101.0.1 (64 bit)

### Additional context

the font awesome icons are appearing in other parts when defined explicitely in markdown
when inspecting the element that creates the icon seems to be hidden
```html
<i class="fa-fw fas fa-home ml-xl-3 mr-xl-3 unloaded"></i>
```

This behaviour does not happen in chrome or safari.

**Comment by SilentGlasses** [comment]
Do you have any plugins installed? Try disabling them and see if it helps, then enable them one by one and see which one if affecting how the site is displayed.

Also, FF is now on 102.0.1, see if updating fixes it.

I am not able to duplicate your issue on Firefox, either on my MacBook or my Linux laptop.

**Comment by martyca** [comment]
I have updated FF and the icons are showing.
![image](https://user-images.githubusercontent.com/5071366/178597820-84ca4084-cec0-4260-b235-d493b09ade9a.png)

I am not 100% sure if this is related to FF, but if the icons are showing for you I am convinced the problem is at my end.
Closing.
