### ISSUE TITLE
TOC won't show on small screen

### ISSUE THREAD

**Issue by liblaf** [cotes2020/jekyll-theme-chirpy#620]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There is no similar request on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

TOC won't show on small screens like iPad and mobile phones. This may be designed on purpose. However, I think iPad is large enough to display an extra column of TOC.

## Describe the solution you'd like

I'm not familiar with frontend, just a little bit modification on `*.css` conditions would do?

## Describe alternatives you've considered

Collapsing the left sidebar on small screens may also be a good choice.

**Comment by SilentGlasses** [comment]
I may be wrong but I think this will help you out, adjust these `media` options to what you need:

https://github.com/cotes2020/jekyll-theme-chirpy/blob/ad137fa2945b1870b9c1dd5e9212a5f4af7c3580/_sass/layout/home.scss#L119

**Comment by SilentGlasses** [comment]
DO you have any plugins installed? Try disabling them and see if it helps, then enable them one by one and see which one if affecting how the site is displayed.

Also, FF is now on 102.0.1, see if updating fixes it.

I am not able to duplicate your issue on Firefox, either on my MacBook or my Linux laptop.

**Comment by lnfel** [comment]
I would strongly advise against changing Chirpy's actual source code. We can extend the layout page instead by doing the following:

1. Create a `_layouts` directory in the root of project folder, should be similar to:
```
your-folder/_layouts
```
2. The TOC is part of Chirpy's own `_layouts/page.html` template. Copy the file over to your own project under `your-project/_layouts/page.html`.
3. After copying `page.html`, find the following lines:
```html
  <!-- core -->
  <div id="core-wrapper" class="col-12 col-lg-11 col-xl-9 pr-xl-4">
```
and
```html
  <!-- pannel -->
  <div id="panel-wrapper" class="col-xl-3 pl-2 text-muted">
```
4. All you have to do is change them into:
```html
  <!-- core -->
  <div id="core-wrapper" class="col-12 col-md-9 pr-xl-4">
```
and
```html
  <!-- pannel -->
  <div id="panel-wrapper" class="col-md-3 pl-2 text-muted">
```
5. The result would be like this:
<img width="782" alt="image" src="https://user-images.githubusercontent.com/47680867/181813959-c3996d3f-3e9b-4b68-8931-5876f54a2955.png">

### Context
Chirpy uses [Bootstrap CSS Framework](https://getbootstrap.com/docs/4.0/getting-started/introduction/) under the hood. The [Grid](https://getbootstrap.com/docs/4.0/layout/grid/) can be controlled according to current device screen width, namely `sm` for small screens `md` for medium sized devices then `lg` and `xl` for large and extra large screens respectively. A grid consists of 12 columns and the `core-wrapper` div starts with `col-12` on the lowest screen width possible. We then set the `core-wrapper` to `col-md-9` (become 9 columns on at least medium sized screen and above) and `panel-wrapper` to `col-md-3` (3 columns starting from medium screens and above). More about responsive grids on the official [docs](https://getbootstrap.com/docs/4.0/layout/grid/#mix-and-match).
