### ISSUE TITLE
support algolia for fast and relevant search

### ISSUE THREAD

**Issue by liblaf** [cotes2020/jekyll-theme-chirpy#621]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There is no similar request on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

Support [Algolia](https://www.algolia.com/) as search provider.

## Describe the solution you'd like

[Algolia](https://www.algolia.com/) provides an generous free plan. It is convenient to use [`jekyll-algolia`](https://github.com/algolia/jekyll-algolia) plugin to generate and upload search index. Besides, Algolia also provides easy-to-use tools to build search UI ([InstantSearch.js](https://community.algolia.com/instantsearch.js/)).

**Comment by lnfel** [comment]
Algolia already have an implementation on this. You can add `jekyll-algolia` plugin to your blog (and build the search component from there).
> The plugin only takes care of extracting your data and pushing it to an Algolia index. Building the front-end that will allow your users to search into that data is not part of the plugin.
>
> As it would depend too much on the theme you applied to Jekyll, we could not create a one-size-fits-all solution. Instead, the best solution is to use our [InstantSearch.js](https://community.algolia.com/instantsearch.js/) library (also available for [Vue.js](https://community.algolia.com/vue-instantsearch/), [React](https://community.algolia.com/react-instantsearch/) and [Angular](https://community.algolia.com/angular-instantsearch/)). It’s an easy-to-use set of UI widgets you can use to build your own search in a matter of minutes.


or follow their [tutorial](https://community.algolia.com/jekyll-algolia/blog.html) on how to add `InstantSearch.js` to your blog. The only thing to be mindful of is that Algolia free tier does have a `limited quota` which is fine for small content but you risk of using it all up if you have a huge number of blog posts.
