### ISSUE TITLE
Please add "assembly" as a supported language in code blocks.

### ISSUE THREAD

**Issue by GRX78FL** [cotes2020/jekyll-theme-chirpy#623]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There is no similar request on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

Purely esthetic reasons, the same way it would be a problem if all of a sudden \`\`\`python\`\`\` wasn't supported and the \`\`\`liquid\`\`\`
tag were necessary to have at least a non-highlighted code block:

![image](https://user-images.githubusercontent.com/20095224/176160828-a8d5ba58-a693-4e6f-b0c8-54204b013d02.png)

## Describe the solution you'd like

I'd like to se \`\`\`assembly \<newline\> \<code\> \`\`\` to look as good as:

```assembly
; Code
_TEXT SEGMENT
    
    ; Entry point
    start PROC
        sub     rsp, 8
        call    setup
        call    main
        mov     rcx, rax
        call    ExitProcessPtr
        add     rsp, 8
        ret
    start ENDP
```

## Describe alternatives you've considered

I don't have an alternative, sorry it's just a feature GH and GH-Pages supports as part of Markdown.

## Additional context

While \`\`\`nasm \<newline\> \<code\> \`\`\` works, it is horrible to look at and it's not a compatible solution with other x86 assembly syntax variations:

![image](https://user-images.githubusercontent.com/20095224/176161259-be3966ad-b60e-409b-b5dc-26afebcd4a22.png)

---

If you sat through my whining I guess it's time to thank you for this amazing template! 😄 ❤️

**Comment by NichtsHsu** [comment]
As far as I know, highlighting support is provided by [rouge](https://github.com/rouge-ruby/rouge). You can find a [supported language list here](https://github.com/rouge-ruby/rouge/blob/master/docs/Languages.md). If you want a new language to be supported, I think you might need to creating a issue there.
