### ISSUE TITLE
modified javascript file is not being applied

### ISSUE THREAD

**Issue by junvue** [cotes2020/jekyll-theme-chirpy#627]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `main` branch.

## Description

I just modified `_javascript/commons/search-display.js`.

to try addClass "visible" on some tag that I added.
But It seems like doesn't work.

So I add "console.log("hi");" to check, But It doesn't work.

How do I apply modified javascript?
Do I need to rebuild or something?

**Comment by junvue** [comment]
solved

**Comment by NichtsHsu** [comment]
The scripts that actually work are these "*.min.js" under `assets/js/dist/`. Update them by:

```bash
npm install    # for install gulp
gulp
```

**Comment by junvue** [comment]
ah, It's using gulp. I see.

I didn't know it. 😂
Thx:)
