### ISSUE TITLE
Github pages not deploying

### ISSUE THREAD

**Issue by AyushKoul00** [cotes2020/jekyll-theme-chirpy#628]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug
I have the same issue as this one: #624 but this issue was auto closed
I am using the chirpy-starter to create a repo and then I clone it locally. I then commit the changes and then push it to remote.
The auto deploy first gives an error at Setup Ruby because of some missing platform. I added the command that the error suggested and then it was successful.

However, when I go to the deployed website, it just shows: `--- layout: home # Index page ---`

### To Reproduce

1. Create repo using chirpy-starter
2. Clone it locally
3. Run bundle
4. Add and commit all new changes and push it to the remote repo
5. Auto deployment gives error in Actions (on `Setup Ruby`)
6. recommit and see error: webpage shows this: `--- layout: home # Index page ---`

### Screenshots

![image](https://user-images.githubusercontent.com/46340004/176496515-000b66ca-05ec-4c10-b9bd-93172b335b77.png)

![image](https://user-images.githubusercontent.com/46340004/176496636-b2a0c916-f05e-4504-904b-acd7ccd6f9c6.png)

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |  `ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x64-mingw-ucrt] `     |
| `gem -v`                          |     `3.3.7`    |
| `bundle -v`                       |    ` Bundler version 2.3.16  `  |
| `bundle exec jekyll -v`           |    `  jekyll 4.2.2 `  |
| `bundle info jekyll-theme-chirpy` |   `jekyll-theme-chirpy (5.2.1)`  |

### Desktop

- OS: Windows 10
- Browser: Chrome (64 bit)

**Comment by albertocorrales** [comment]
I'm having the same issue. I can load it locally, but when I navigate to the github URL, it displays the same screen you posted.

**Comment by cowdex** [comment]
I have the same problem, and I tried to deploy it from my Mac as well as my Windows machine and it gives me the same problem as the one in your screenshot.

**Comment by AyushKoul00** [comment]
I resolved this issue. One thing i did was clone the repo recursively. And second is, we need to add a Linux platform to the bundle - that is a big on the repo's part i guess

**Comment by albertocorrales** [comment]
> I resolved this issue. One thing i did was clone the repo recursively. And second is, we need to add a Linux platform to the bundle - that is a bug on the repo's part i guess

Sorry, I'm new to Jekyll. How do you add a Linux platform to the bundle?

**Comment by AyushKoul00** [comment]
@albertocorrales run this locally: `bundle lock --add-platform x86_64-linux`

Then commit the changes to your remote repo. It should create a gh-pages branch automatically and then you just set that as the branch for your GitHub page in the settings

**Comment by albertocorrales** [comment]
> @albertocorrales run this locally: `bundle lock --add-platform x86_64-linux`
> 
> Then commit the changes to your remote repo. It should create a gh-pages branch automatically and then you just set that as the branch for your GitHub page in the settings

It worked fine, thanks!! I think they should add this piece in their documentation because it is not very obvious

**Comment by Parad0x84** [comment]
> @albertocorrales run this locally: `bundle lock --add-platform x86_64-linux`
> 
> Then commit the changes to your remote repo. It should create a gh-pages branch automatically and then you just set that as the branch for your GitHub page in the settings


I'm also having same issue and it doesn't works for me. Is there any steps with repository config probably i'm missing?

Also this code doesn't generate anything new as far as i know since github cannot find any changes to commit

**Comment by ariutti** [comment]
I'm also having same issue and it doesn't works for me.
I also notice that the phase called "Setup Ruby" does not appear in the actions. I do not know whether this could be the source of the problem.

![compo](https://user-images.githubusercontent.com/6818509/180976024-1e2cb1d9-ad8a-4a73-be97-bc2264197874.png)

**Comment by optpants** [comment]
I'm also having this issue in an Ubuntu 22.04 environment, though I can build/serve fine locally, I get the empty index page when I deploy to github pages.

**Comment by Ntf-Sadnan** [comment]
Hey @AyushKoul00 ! It's not working for me. Can you please explain me the full procedure please .

**Comment by NichtsHsu** [comment]
For me, it works with configuring Source as Github Actions.

![image](https://user-images.githubusercontent.com/35688135/198170582-74d61ca9-22c8-4671-9131-977db2d0cfca.png)

**Comment by Ntf-Sadnan** [comment]
Hey , can you tell me why is this?!

![image](https://user-images.githubusercontent.com/79263493/198228573-1b9607a8-6d8f-42ca-ae18-71b1d54c7f7d.png)

**Comment by Azer-prog** [comment]
Can anyone help with a fix for the issue ?

**Comment by tmaiorca** [comment]
Does anyone else have a working solution to this issue?

**Comment by heraldcod** [comment]
> I resolved this issue. One thing i did was clone the repo recursively. And second is, we need to add a Linux platform to the bundle - that is a bug on the repo's part i guess

Thanks @AyushKoul00

**Comment by ryanjones** [comment]
Can confirm the following 2 fixes work:

1. Problem 1: Build fails on bundler step. Run `bundle lock --add-platform x86_64-linux`. This is will setup bundler for the right environment (ubuntu, as defined in pages-deploy.yml). Make sure to run 'bundle install' locally after (it'll likely add nokogiri to your Gemfile.lock) before checking it in.
2. Problem 2: The following is rendered when going to the site: `--- layout: home # Index page ---`. Manually updating my github 'Build and deployment' to 'Github Actions' fixes it. If you have the default setting 'Deploy from branch' it'll try and render index.html which contains `--- layout: home # Index page ---` (which you don't want).

**Comment by drunkrhin0** [comment]
> Can confirm the following 2 fixes work:
> 
>     1. Problem 1: Build fails on bundler step. Run `bundle lock --add-platform x86_64-linux`. This is will setup bundler for the right environment (ubuntu, as defined in pages-deploy.yml). Make sure to run 'bundle install' locally after (it'll likely add nokogiri to your Gemfile.lock) before checking it in.
> 
>     2. Problem 2: The following is rendered when going to the site: `--- layout: home # Index page ---`. Manually updating my github 'Build and deployment' to 'Github Actions' fixes it. If you have the default setting 'Deploy from branch' it'll try and render index.html which contains `--- layout: home # Index page ---` (which you don't want).
> 
> 
> I found that this is also fully covered [here](https://chirpy.cotes.page/posts/getting-started/#deploy-by-using-github-actions) in the documentation.

This worked thank you so much @ryanjones

**Comment by anupdsouza** [comment]
> Can confirm the following 2 fixes work:
> 
> 1. Problem 1: Build fails on bundler step. Run `bundle lock --add-platform x86_64-linux`. This is will setup bundler for the right environment (ubuntu, as defined in pages-deploy.yml). Make sure to run 'bundle install' locally after (it'll likely add nokogiri to your Gemfile.lock) before checking it in.
> 2. Problem 2: The following is rendered when going to the site: `--- layout: home # Index page ---`. Manually updating my github 'Build and deployment' to 'Github Actions' fixes it. If you have the default setting 'Deploy from branch' it'll try and render index.html which contains `--- layout: home # Index page ---` (which you don't want).
> 
> I found that this is also fully covered [here](https://chirpy.cotes.page/posts/getting-started/#deploy-by-using-github-actions) in the documentation.

Worked for me, thanks!

**Comment by Guy-Sela** [comment]
Make sure you include the proper urls in _config.yml.

To deploy on Github pages the **base url** should stay empty (""), and the **url** should be something along this line: https://username.github.io.

**Comment by eeevvaaa** [comment]
> For me, it works fine with configuring Source as Github Actions.
> 
> ![image](https://user-images.githubusercontent.com/35688135/198170582-74d61ca9-22c8-4671-9131-977db2d0cfca.png)

Works like a charm. Thank you!
Make sure to follow the link to configure jekyll. It will create a jekyll.yml file in the `.github/workflows` directory. Committed that and I was all set!

**Comment by ENTPRESTIGIOUS** [comment]
> For me, it works fine with configuring Source as Github Actions.
> 
> ![image](https://user-images.githubusercontent.com/35688135/198170582-74d61ca9-22c8-4671-9131-977db2d0cfca.png)

thank you man

**Comment by Emmental1230** [comment]
> For me, it works fine with configuring Source as Github Actions.
> 
> ![image](https://user-images.githubusercontent.com/35688135/198170582-74d61ca9-22c8-4671-9131-977db2d0cfca.png)

I re-run all jobs after setting like this image, and it works thx 👍

**Comment by FireHaven** [comment]
> bundle lock --add-platform x86_64-linux

This worked for me all, you will not see a gh-pages action like some older YT walk-throughs show, just set it to actions and it will work. 

I also noticed that under the actions tab of your repo that it now only uploads one file instead of two and trying to verify the site as basic HTML which leads me to believe that is why it kept giving HTML errors when there is much more to the jekyll sites with Ruby and such.

**Comment by jakebrown188** [comment]
In case it helps anyone else, I realized that the cause of me seeing the `--- layout: home # Index page ---` page was because I placed a trailing `/` in the `url` field of the `_config.yaml` file.  

For example, this is bad:
`url: "https://www.example.com/"`

This is good:
`url: "https://www.example.com"`

**Comment by snousias** [comment]
Great job! Thank you

**Comment by VLTisME** [comment]
> [@albertocorrales](https://github.com/albertocorrales) run this locally: `bundle lock --add-platform x86_64-linux`
> 
> Then commit the changes to your remote repo. It should create a gh-pages branch automatically and then you just set that as the branch for your GitHub page in the settings

I've tried many other ways, but only this works! Thanks a lot man!
