### ISSUE TITLE
Having mess with css after hosting on GitHub Pages, but not having these issues while hosting website locally (localhost)

### ISSUE THREAD

**Issue by Cloufish** [cotes2020/jekyll-theme-chirpy#63]
Just as the title says.

I think I've followed every step in your tutorial.

And it looks simply like this:

![image](https://user-images.githubusercontent.com/32965886/83050390-cfa6df80-a04c-11ea-9481-22100ff102f6.png)

Thanks for help in advance!

**Comment by cotes2020** [comment]
> I think I've followed every step in your tutorial.

No, you're not. Please read carefully.

**Comment by Cloufish** [comment]
Could you give me a hint why this happens? ;-;
Is it about plugins?

**Comment by cotes2020** [comment]
> I've seriously followed everything in #Deploying to GitHub Pages like three times.

Then you should read the 4th time:

<img width="763" alt="Screen Shot 2020-05-28 at 12 26 31 PM" src="https://user-images.githubusercontent.com/11371340/83099201-47bde580-a0df-11ea-8ebd-610ba81b994e.png">

And look what I found in your repository:

https://github.com/Cloufish/Blog/blob/gh-pages/_config.yml#L49-L50

**Comment by Cloufish** [comment]
Right, thank you so much!
