### ISSUE TITLE
Website Update Box Text

### ISSUE THREAD

**Issue by luismrguimaraes** [cotes2020/jekyll-theme-chirpy#635]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

After pushing a new update to my website, it doesn't refresh right away and after some time, a box with a button appears:

![box](https://user-images.githubusercontent.com/100025288/177343727-b6f8f552-3c44-4e59-8edb-9f1eefb94062.PNG)

The blue button seems to update the browser's cache with the new version of the website, and the box has some space for text.\
I can't figure out how to change its text but I'm almost certain it's possible, since I remember seeing the demo website's box with different text than none.

**Comment by NichtsHsu** [comment]
Yes, you can custom the text at `_data/locales/{lang}.yml`, for an example, `en.yml`:

```yaml
notification:
  update_found: A new version of content is available.
  update: Update
```

BTW, this notification box is defined at `_layouts/default.html`:

```liquid
    {% if site.pwa.enabled %}
      <div id="notification" class="toast" role="alert" aria-live="assertive" aria-atomic="true"
        data-animation="true" data-autohide="false">
        <div class="toast-header">
          <button type="button" class="ml-2 ml-auto close" data-dismiss="toast" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="toast-body text-center pt-0">
          <p class="pl-2 pr-2 mb-3">{{ site.data.locales[lang].notification.update_found }}</p>
          <button type="button" class="btn btn-primary" aria-label="Update">
            {{ site.data.locales[lang].notification.update }}
          </button>
        </div>
      </div>
    {% endif %}
```
