### ISSUE TITLE
How to remove favicon

### ISSUE THREAD

**Issue by flexelem** [cotes2020/jekyll-theme-chirpy#636]
## Checklist

- [X] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [X] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [X] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [X] My question is based on the latest code of the `master` branch.

## Description

Hi there,

First of all, thanks a lot for the awesome jekyll framework! I have a minor question which is about removing favicon. How I can disable or remove favicon?

Thanks,
Burak

![Screen Shot 2022-07-07 at 15 57 19](https://user-images.githubusercontent.com/6500753/177779018-eac5f2b1-6378-4ea5-acb0-f4c598edd47a.png)

**Comment by SilentGlasses** [comment]
Here you go:
https://chirpy.cotes.page/posts/customize-the-favicon/

**Comment by flexelem** [comment]
Awesome thanks @SilentGlasses !
