### ISSUE TITLE
Actions failes on "conitnuous-delivery" on M1 Macs

### ISSUE THREAD

**Issue by LucEast** [cotes2020/jekyll-theme-chirpy#637]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug

My continuous-delivery failes at "bundle install". 
I'm on the new M1 pro MacBook pro and already added "x86_64-linux" to the bundle lock file. 

### To Reproduce

Use M1 based System 

### Expected behavior

I expected that everything runs normal

### Screenshots

<img width="978" alt="Bildschirmfoto 2022-07-07 um 09 00 52" src="https://user-images.githubusercontent.com/47122750/177711945-b9379df5-b85b-4826-9d3e-1356c02602a7.png">

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |     2.6.8p205    |
| `gem -v`                          |     3.0.3.1    |
| `bundle -v`                       |     2.3.17    |
| `bundle exec jekyll -v`           |    Bus Error at 0x0000000102804000    |
| `bundle info jekyll-theme-chirpy` |     5.2.1    |

### Desktop

- OS: [MacOS 12.4]
- Browser: [Chrome 103.0.5060.53 (arm64)]

**Comment by sobrienti** [comment]
I have the same issue but running the CD with Github Actions.

**Comment by SilentGlasses** [comment]
I am hearing lots of people are experiencing issues with the M1 macs, Seems like Line 29 in your screenshot gives you a hint.

It mainly seems to be around the fact that the M1 uses `ARM` architecture and most things are still default to `x86_64`.

I do not thinkg this issue has anything to do with the theme.

**Comment by NichtsHsu** [comment]
Have you tried Line 29 `bundle lock --add-platform x86_64-darwin-19`?

**Comment by phanmn1** [comment]
> Have you tried Line 29 `bundle lock --add-platform x86_64-darwin-19`?

This worked for me! Thank you!!

**Comment by aphive** [comment]
Remember to resolve your issues if the solution offered helped out.

**Comment by LucEast** [comment]
Hey, 
thanks for your patience. 
> Have you tried Line 29 `bundle lock --add-platform x86_64-darwin-19`?
Sadly it still doesn't work.
