### ISSUE TITLE
Error when stopping tools/run.sh locally: "Prepending `bundle exec` to your command may solve this Error"

### ISSUE THREAD

**Issue by Cloufish** [cotes2020/jekyll-theme-chirpy#64]
Steps to reproduce:

1. I'm trying to execute tools/run.sh to host locally. But it seems to not bundle blog.

![image](https://user-images.githubusercontent.com/32965886/83135264-dafa1980-a0e5-11ea-986f-c5c770bfb35e.png)

1. Because of that, i'm stopping the script.  But then I'm getting an error with plugins.

![image](https://user-images.githubusercontent.com/32965886/83135370-07159a80-a0e6-11ea-9fd9-58fe6300fb3a.png)
 
1. Looking at the script I see that there is ' bundle exec ' before jekyll serve.

![image](https://user-images.githubusercontent.com/32965886/83135451-23b1d280-a0e6-11ea-900d-3dd8436cecd6.png)

What might be causing this?

>I've executed many times ```tools/init.sh``` and ```tools/build.sh```. Before executing tools/run.sh

**These errors does not happen when I'm executing the ```bundle exec jekyll serve``` command alone.  However I know that your script is way better. So I want to fix this error.**

**Additional Question**

is there a way to contact you via Discord? I have so many questions related to this template's "infrastructure" but don't want to spam the issues.

**Comment by cotes2020** [comment]
see this: <https://coderwall.com/p/y6xraq/prepending-bundle-exec-to-your-command-may-solve-this-error>

**Comment by Cloufish** [comment]
Works now thanks!
