### ISSUE TITLE
How can I globally modify the contents of headers in all pages?

### ISSUE THREAD

**Issue by diyanqi** [cotes2020/jekyll-theme-chirpy#641]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [ ] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

I want to change a MathJax source because it doesn't work on my blog whenever I type `$...$` or `$$...$$`. And sometimes I think there just isn't any MathJax render in the Chirpy Theme. However, when I tried to edit the JS file by means of [this](https://github.com/cotes2020/jekyll-theme-chirpy/issues/243#issuecomment-758052828), I could not find a folder named `_includes`. So I created one but it still didn't work.  

How can I solve it? What file should I edit?

**Comment by Raynirs** [comment]
Just set `math: true` in the frontmatter of pages, then `$...$` and `$$...$$` will work. The CDN is listed in `_data/assets/cross_origin.yml` and can be modified by yourself.

BTW, Mathjax3 disables the use of `$` by default, and chirpy enables it in `_includes/js-selector.html`:

```js
MathJax = {
  tex: {
    inlineMath: [              /* start/end delimiter pairs for in-line math */
      ['$','$'],
      ['\\(','\\)']
    ],
    displayMath: [             /* start/end delimiter pairs for display math */
      ['$$', '$$'],
      ['\\[', '\\]']
    ]
  }
};
```

If you really want to change the head, just copy `_includes/head.html` to your project (only if you are using the chirpy starter with a gem theme) from the repository and modified it.

**Comment by diyanqi** [comment]
> 

I’m new with Jekyll. How can I edit the `frontmatter` of posts🤣? I just couldn’t find such a file. Maybe I should edit the meta data of each passage? Then how to set math for true?

**Comment by Raynirs** [comment]
Frontmatter is the yaml part of a markdown file wrapped with `---`, so you can just write something like

```markdown
---
title: 文章
date: 2022-07-16 10:28:00 +0800
math: true
# Other configurations
---

## 一个标题

一个段落

## 另一个标题

另一个段落
```

When Jekyll renders this markdown file to an HTML, the data can be accessed by `page.xxx` in liquid, such as `<h1>{{ page.title }}<h1>`. Chirpy checks `page.math` to decide whether to link Mathjax.

**Comment by diyanqi** [comment]
> Just set `math: true` in the frontmatter of posts, then `$...$` and `$$...$$` will work. The CDN is listed in `_data/assets/cross_origin.yml` and can be modified by yourself.
> 
> BTW, Mathjax3 disables the use of `$` by default, and chirpy enables it in `_includes/js-selector.html`:
> 
> ```js
> MathJax = {
>   tex: {
>     inlineMath: [              /* start/end delimiter pairs for in-line math */
>       ['$','$'],
>       ['\\(','\\)']
>     ],
>     displayMath: [             /* start/end delimiter pairs for display math */
>       ['$$', '$$'],
>       ['\\[', '\\]']
>     ]
>   }
> };
> ```
> 
> If you really want to change the head, just copy `_includes/head.html` to your project (only if you are using the chirpy starter with a gem theme) from the repository and modify it.

Thanks for you answering. 您回答得好快啊（

By following your steps, I’ve already succeeded in rendering the MathJax blocks. However, it’s inconvenient to set `math: true` for each passage as some of the Jekyll passage editors do not support editing frontmatter data. Also, the heading content of the passage will be presented in the homepage as well, which contains some math formulas. So I wonder if there is a way to set MathJax active globally?

**Comment by diyanqi** [comment]
Something like this:
![39002504-540B-4A53-920F-86B23354FC16](https://user-images.githubusercontent.com/60802943/179336214-d8bfdb19-9164-423c-a362-19001a04ca4e.jpeg)

**Comment by diyanqi** [comment]
This picture is captured from the homepage.

**Comment by Raynirs** [comment]
> > Just set `math: true` in the frontmatter of posts, then `$...$` and `$$...$$` will work. The CDN is listed in `_data/assets/cross_origin.yml` and can be modified by yourself.
> > BTW, Mathjax3 disables the use of `$` by default, and chirpy enables it in `_includes/js-selector.html`:
> > ```js
> > MathJax = {
> >   tex: {
> >     inlineMath: [              /* start/end delimiter pairs for in-line math */
> >       ['$','$'],
> >       ['\\(','\\)']
> >     ],
> >     displayMath: [             /* start/end delimiter pairs for display math */
> >       ['$$', '$$'],
> >       ['\\[', '\\]']
> >     ]
> >   }
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If you really want to change the head, just copy `_includes/head.html` to your project (only if you are using the chirpy starter with a gem theme) from the repository and modify it.
> 
> Thanks for you answering. 您回答得好快啊（
> 
> By following your steps, I’ve already succeeded in rendering the MathJax blocks. However, it’s inconvenient to set `math: true` for each passage as some of the Jekyll passage editors do not support editing frontmatter data. Also, the heading content of the passage will be presented in the homepage as well, which contains some math formulas. So I wonder if there is a way to set MathJax active globally?

（正好在线，邮箱收到回复了而已 2333）
It seems that there is no perfect solution to display maths in excerpt (or maybe you need to write a ruby plugin) even if you enable Mathjax globally:

![](https://user-images.githubusercontent.com/22890511/179336571-e96809eb-90a3-425a-a397-77005903f669.jpg)

```markdown
---
title: 测试
date: 2022-07-15 20:10:00 +0800
math: true
---

你 $a = 1$

$$
    \sqrt{b^2 + c}
$$
```

> Found a solution: use `\\[ ... \\]` instead of `$$ ... $$` for block maths will work.
![](https://user-images.githubusercontent.com/22890511/179336713-0bec895b-cae8-4b41-a06a-7cbabf85f92f.jpg)



Check `_includes/js-selector.html`:

```html
{% if page.math %}
  <!-- MathJax -->
  <script>
  /* see: <https://docs.mathjax.org/en/latest/options/input/tex.html#tex-options> */
  MathJax = {
    tex: {
      inlineMath: [              /* start/end delimiter pairs for in-line math */
        ['$','$'],
        ['\\(','\\)']
      ],
      displayMath: [             /* start/end delimiter pairs for display math */
        ['$$', '$$'],
        ['\\[', '\\]']
      ]
    }
  };
  </script>
  <script src="{{ site.data.assets[origin].polyfill.js | relative_url }}"></script>
  <script id="MathJax-script" async src="{{ site.data.assets[origin].mathjax.js | relative_url }}">
  </script>
{% endif %}
```

The code between `{% if page.math %}` and `{% endif %}` is what imports Mathjax. Copy `_layouts/home.html` to your project with the same path, and paste the code at the last. Mathjax should be imported in homepage.

> I guess you are using Chirpy Starter which is based on a ruby gem theme. Your local file with the same path will completely override the file of the theme, so you need to copy the original file and then modify it.

**Comment by diyanqi** [comment]
我滴任务完成啦！

Thanks for your answering. I achieved my goal now.

**Comment by sukhjinder-kumar** [comment]
I followed the above instructions, however, I don't seem to get desired results. I tried using `\\( ... \\)`, and `\\[ ... \\]` instead of `$ ... $` and `$$ ... $$` as well as downloaded `_layouts/home.html` and appended the code snippet mentioned at the end. But nothing changed, still, posts on the home page don't render math equations. Any suggestion as to what I am doing wrong?
