### ISSUE TITLE
Custom CSS (/assets/css/style.css) conflicting

### ISSUE THREAD

**Issue by serafdev** [cotes2020/jekyll-theme-chirpy#648]
## Checklist

- [X] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [X] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [X] I found the bug on the latest code of the `master` branch.

## Describe the bug

I'm trying to add a `background-image` to the body by adding a file on `/assets/css/style.css` but I'm getting this error:
```
      Regenerating: 1 file(s) changed at 2022-07-25 15:51:57                                                                                                                          [64/175]
                    assets/css/style.css                                                                                                                                                      
          Conflict: The following destination is shared by multiple files.                                                                                                                    
                    The written file may end up with unexpected contents.                                                                                                                     
                    /home/seraf/code/personal/ccil-kbw.github.io/_site/assets/css/style.css                                                                                                   
                     - assets/css/style.scss                                                                                                                                                  
                     - /home/seraf/code/personal/ccil-kbw.github.io/assets/css/style.css 
```

I'm not sure if I'm doing it properly but from reading other issues it seems like that's where I need to add custom css

### To Reproduce

1. Add `assets/css/style.css`
2. See error

### Expected behavior

Accept custom CSS

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         | 3.0.2p107 |
| `gem -v`                          | 3.3.5 |
| `bundle -v`                       | 2.3.15 |
| `bundle exec jekyll -v`           | 4.2.2 |
| `bundle info jekyll-theme-chirpy` | 5.2.1|

**Comment by NichtsHsu** [comment]
Name it `style.scss` instead of `style.css`.

Also, please copy the original code of this file to yours.

https://github.com/cotes2020/jekyll-theme-chirpy/blob/3fa1bf305451f645a7f3aa93863b076463c8f165/assets/css/style.scss#L1-L12

**Comment by serafdev** [comment]
I might be a noob but it's not being applied @NichtsHsu https://ccil-kbw.github.io : https://github.com/ccil-kbw/ccil-kbw.github.io/blob/main/assets/css/style.scss

Do you know why?

**Comment by NichtsHsu** [comment]
@serafdev Could you try like this:

```
#main-wrapper {
  background: center/cover url("/assets/img/bg/mosque_8fcec6.png") no-repeat;
}
```

**Comment by serafdev** [comment]
That worked thanks @NichtsHsu!

Do you know if there's a palette I can play with to change theme colors?

**Comment by NichtsHsu** [comment]
@serafdev Colors are all defined in [`_sass/colors/light-typography.scss`](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/_sass/colors/light-typography.scss).
