### ISSUE TITLE
chirpy github pages with custom domain issue

### ISSUE THREAD

**Issue by Dr4m9s1b16** [cotes2020/jekyll-theme-chirpy#649]
## Checklist
 -  I have read the documentation  and issue related to this throughly
 - My question is it works perfectly in loca host , but in github pages it doesn't serve as local host 
 -  Platform` windows 10 intel i7` , `ruby 2.6.8p205 (2021-07-07 revision 67951) [x64-mingw32]` , `Bundler version 2.3.7`
 -  Previous issues state that , it happened in M1,M2 apple chips but it is  happening in other platforms also.

## Description
- while serving in the github pages with custom domain can't load theme
- shows like this

![image](https://user-images.githubusercontent.com/28673595/181280682-b9e30b37-69fb-42dc-a85f-d476b89361ff.png)

**Comment by properlyabsurd** [comment]
I am having what I believe to be the same issue. I have attempted to use chirpy-starter to deploy a site using the repo format of <GH_USERNAME>.github.io.

After GitHub runs the automation, the site page loads with "**--- layout: home # Index page ---**"

I have also done the following - 

- Cloned the Repo to a Ubuntu Server 20.04.4 LTS x86_64 environment.
- Ran `bundle`
- Pushed the changes to Github and had the same issue after the automation ran.

____________

- ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
- gem -v 3.1.2
- Bundler version 2.3.15
- jekyll 4.2.2
- jekyll-theme-chirpy (5.2.1)
