### ISSUE TITLE
Conflict between 127.0.0.1:4000 and localhost:4000 adresses

### ISSUE THREAD

**Issue by Cloufish** [cotes2020/jekyll-theme-chirpy#65]
As the title says.
To give you a better idea of what I mean I've uploaded a video to youtube. 
https://www.youtube.com/watch?v=8NLTTF3VG3s&feature=youtu.be

As you can see the site in the 127.0.0.1:4000 looks normal with markdown compiled and front matter. However, in the localhost, the case is completely different. 

I didn't show in the video categories and tag tabs. They are empty (it's not 404 on the page, but these pages are empty)

I would normally ignore it and just always see the page content in 127.0.0.1:4000 although I think it may relate to mine 404 errors on pages in categories and tags on the **GitHub Pages hosting**. 

I'm running locally webpage with ```tools/run.sh``` script

**Comment by cotes2020** [comment]
Done 😪

**Comment by Cloufish** [comment]
I'm so happy I found something useful this time xD
