### ISSUE TITLE
Hide pages from tabs

### ISSUE THREAD

**Issue by epklein** [cotes2020/jekyll-theme-chirpy#651]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

I'm wishing to migrate my blog to chirpy theme.

I have many pages that are not posts and I want to keep. But I don't want it to be listed as a tab. Is there a way to hide it from tabs, but still keeping it so that it can be accessed through links?

My idea is to have my website main pages as tabs, but other pages accessible through navigation links inside main pages.

**Comment by lnfel** [comment]
Jekyll already have a guide on this. Please check the [complete guide](https://jekyllrb.com/docs/permalinks/) on the documentation.

#### Recommendations:
1. Read how [Pages](https://jekyllrb.com/docs/pages/) in Jekyll works.
2. Once you understand it, go and follow instructions in the [documentation](https://jekyllrb.com/docs/permalinks/)

**Comment by nshidqi** [comment]
HI @epklein 
I did a workaround for this by modifying _includes\sidebar.html and filtering out the tab_names so they won't be listed as tab list items
