### ISSUE TITLE
Changing HOME to PORTFOLIO

### ISSUE THREAD

**Issue by raul-bermejo** [cotes2020/jekyll-theme-chirpy#654]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

I would like to change the name of HOME to something like PORTFOLIO
<img width="258" alt="Screen Shot 2022-08-03 at 10 21 05 PM" src="https://user-images.githubusercontent.com/71199946/182606430-ea5975dd-b99e-4eed-817b-f5421d86ce3c.png">

I've tried to change that on `_site/index.html`:
>    

    <li class="nav-item">
      <a href="/" class="nav-link">
        <i class="fa-fw fas fa-home ml-xl-3 mr-xl-3 unloaded"></i>
        <span>PORTFOLIO</span>
      </a>
    </li>
    

but everytime I run the website locally `_site/index.html` seems to be overwritten with HOME again.

I'm also having the same issue when trying to change Trending Tags to tags. Any thoughts?

**Comment by MichaelTan9999** [comment]
Hi Raul, I guess you need a new layout to replace the home page layout.
And modifying contents in `_site/` is unnecessary since Jekyll will generate it every time you run it. The documentation of Jekyll [Directory Structure](https://jekyllrb.com/docs/structure/) explains it.

**Comment by raul-bermejo** [comment]
thanks for your help Michael, will close this now :)
