### ISSUE TITLE
Multiple Language

### ISSUE THREAD

**Issue by muratsuzen** [cotes2020/jekyll-theme-chirpy#660]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There is no similar request on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Additional context

Will there be multi-language support on articles and pages?

**Comment by tpougy** [comment]
Any news about this? I`m very interested in multi language support with chirpy

**Comment by m1ndcr4ck** [comment]
Hi there, I'd like to know if there is any plan to implement multi-language support?  @cotes2020

**Comment by wwwGeneral** [comment]
I think a lot of people will love to have this feature.
Several plugins for multi-language exist but difficult to implement within the theme.

**Comment by PlexSheep** [comment]
I'm interested in this too, see #604

**Comment by asandikci** [comment]
I'm also interested. Could we please re-open the issue @cotes2020

**Comment by lijierr** [comment]
Very much interested too.
