### ISSUE TITLE
Error:  The jekyll-theme-chirpy theme could not be found.

### ISSUE THREAD

**Issue by raul-bermejo** [cotes2020/jekyll-theme-chirpy#667]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

My site is working fine locally, but when I push it to the remote repo and activate the build, I get the following error:

> /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:84:in `rescue in gemspec': The jekyll-theme-chirpy theme could not be found. (Jekyll::Errors::MissingDependencyException)
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:81:in `gemspec'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:19:in `root'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:12:in `initialize'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:439:in `new'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:439:in `configure_theme'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:55:in `config='
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:23:in `initialize'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:30:in `new'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:30:in `process'
	from /usr/local/bundle/gems/github-pages-227/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/github-pages-227/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:23:in `load'
	from /usr/local/bundle/bin/github-pages:23:in `<main>'
/usr/local/lib/ruby/2.7.0/rubygems/dependency.rb:3[11](https://github.com/raul-bermejo/raul-bermejo.github.io/runs/7837680507?check_suite_focus=true#step:4:12):in `to_specs': Could not find 'jekyll-theme-chirpy' (>= 0) among 148 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/github/home/.gem/ruby/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/local/bundle', execute `gem env` for more information
	from /usr/local/lib/ruby/2.7.0/rubygems/dependency.rb:323:in `to_spec'
	from /usr/local/lib/ruby/2.7.0/rubygems/specification.rb:986:in `find_by_name'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:82:in `gemspec'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:19:in `root'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:[12](https://github.com/raul-bermejo/raul-bermejo.github.io/runs/7837680507?check_suite_focus=true#step:4:13):in `initialize'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:439:in `new'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:439:in `configure_theme'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:55:in `config='
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:23:in `initialize'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:30:in `new'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:30:in `process'
	from /usr/local/bundle/gems/github-pages-227/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:[19](https://github.com/raul-bermejo/raul-bermejo.github.io/runs/7837680507?check_suite_focus=true#step:4:20):in `program'
	from /usr/local/bundle/gems/github-pages-[22](https://github.com/raul-bermejo/raul-bermejo.github.io/runs/7837680507?check_suite_focus=true#step:4:23)7/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:[23](https://github.com/raul-bermejo/raul-bermejo.github.io/runs/7837680507?check_suite_focus=true#step:4:24):in `load'
	from /usr/local/bundle/bin/github-pages:23:in `<main>'
  Logging at level: debug
Configuration file: /github/workspace/./_config.yml
             Theme: jekyll-theme-chirpy
github-pages 2[27](https://github.com/raul-bermejo/raul-bermejo.github.io/runs/7837680507?check_suite_focus=true#step:4:28) | Error:  The jekyll-theme-chirpy theme could not be found.

- I have checked the `Gemfile` and validated that I see `gem "jekyll-theme-chirpy", "~> 5.2", ">= 5.2.1"`

- I have also tried to change `theme: jekyll-theme-chirpy` to `remote-theme: cotes2020/jekyll-theme-chirpy` but that brings a set of errors

- I cloned `chirpy-starter` so it's not a fork - I do have a M1 Mac but I tried to run `bundle lock --add-platform x86_64-darwin-19` and that's still didn't solve the problem.

## Replication

You can [see the error here](https://github.com/raul-bermejo/raul-bermejo.github.io/runs/7837680507?check_suite_focus=true). To re-create the problem, clone the repo and make any dummy commit to push and activate the build.

## Environment 

- ruby: 3.1.2p2
- gem: 3.3.7
- bundle info jekyll-theme-chirpy: 5.2.1

Thanks in advance!

**Comment by raul-bermejo** [comment]
It's surprising that there's no proposed solution to this issue, given that it seems to be a MBP M1X related issue. Any leads on this?

**Comment by jaehuiui** [comment]
Hi I use M1 Mac and I have same issue with you. 

In my case, I solved this issue with two ways

* Modifed `_config.yml` -> To use theme and remote theme together
```
# Import the theme  
theme: jekyll-theme-chirpy   
remote-theme: cotes2020/jekyll-theme-chirpy
```
* Use Github Action (in repo -> settting -> pages -> Build and Deployment)
  - From `Deploy from branch` to `Github Action`
  - Also, change Github Action's default Ruby version 3.0 to 2.7 (Since I use 2.7 in my local machine)
  
Don't forget to check all the instructions in the **Reference**
Such as do not delete the `tools/deploy.sh`

Reference : https://chirpy.cotes.page/posts/getting-started/

Thanks!

**Comment by Uphie** [comment]
@jaehuiui It doesn't work, I still encountered failure below:
```
github-pages 228 | Error:  The jekyll-theme-chirpy theme could not be found.
```

**Comment by PhotonYan** [comment]
> try just: `theme: chirpy`

It doesn't work :(
Build end up with "Error: The process '/opt/hostedtoolcache/Ruby/3.1.4/x64/bin/bundle' failed with exit code 4"
