### ISSUE TITLE
Remember selected color scheme

### ISSUE THREAD

**Issue by DukeDukeEm** [cotes2020/jekyll-theme-chirpy#668]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There is no similar request on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

The color scheme switch works fine, but when opening the page in a new tab or window (tested in Firefox and Chromium) the scheme does not seem to be remembered.

## Describe the solution you'd like

It would be great if the setting would be stored as a cookie or local storage setting.

**Comment by MichaelTan9999** [comment]
https://github.com/cotes2020/jekyll-theme-chirpy/blob/940b2810e95065e30600ae8d5e4612e7183da60e/_includes/mode-toggle.html#L61-L86

Hi Duke,
if you change the `sessionStorage` to `localStorage` in the code above, the browser will remember the selected theme.
