### ISSUE TITLE
Using template tags in HTML Markdown code box not showing on front end.

### ISSUE THREAD

**Issue by BGTECH-PRO** [cotes2020/jekyll-theme-chirpy#672]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug

The theme is wonderful. My issue is: I am writing about Golang and I added some template tags to a blog using ```html to make it a html code box and it will not render the code tags.

### To Reproduce

Steps to reproduce the behavior: just try to write a blog with the tags below in a code box
```html
  {{template "partials/header" .}}
  <h1>{{.Title}}</h1>
  <p>Hello world of worlds!.</p>
          
  {{template "partials/footer" .}}
```
### Expected behavior

I think it is because the theme itself uses templates. Not sure, though.
### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         | 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux] |
| `gem -v`                          | 3.3.7 |
| `bundle -v`                       | 2.3.18 |
| `bundle exec jekyll -v`           | 4.2.2 |
| `bundle info jekyll-theme-chirpy` | 5.2.1 |

### Desktop
Arch Linux 

### Browser
Latest Firefox Browser

### Smartphone
Android  11

### Additional context
non

**Comment by NichtsHsu** [comment]
See [Tags Filters](https://jekyllrb.com/docs/liquid/tags/) section of Jekyll doc:

> If you are using a language that contains curly braces, you will likely need to place `{% raw %}` and `{% endraw %}` tags around your code. Since Jekyll `4.0` , you can add `render_with_liquid: false` in your front matter to disable Liquid entirely for a particular document.

**Comment by BGTECH-PRO** [comment]
Thanks so much for your response even though it was actually a Jekyll think.
