### ISSUE TITLE
Table of contents is not included if the post only has "top level" titles

### ISSUE THREAD

**Issue by acdoussan** [cotes2020/jekyll-theme-chirpy#679]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug

Table of contents is not included if the post only has "top level" titles. AKA the post only has `# example section`

### To Reproduce

1. Create a post with multiple top level (# only) headers
2. See that there is no table of contents on the right

### Expected behavior

There should still be a table of contents, even if there are no sub headers (## or ### ...)

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |      ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]   |
| `gem -v`                          |     3.0.3.1    |
| `bundle -v`                       |     Bundler version 2.1.4    |
| `bundle exec jekyll -v`           |      jekyll 4.2.2   |
| `bundle info jekyll-theme-chirpy` |    jekyll-theme-chirpy (5.2.1)     |

**Comment by MichaelTan9999** [comment]
Hi acdoussan, I belive what you mentioned is not a bug but a design. According to the related code, toc is deliberately hidden when there are only top level headers.

https://github.com/cotes2020/jekyll-theme-chirpy/blob/940b2810e95065e30600ae8d5e4612e7183da60e/_includes/toc.html#L1-L6

**Comment by MattsBos** [comment]
Hi acdoussan,

Like @MichaelTan9999 said, it's by design. To give you some more background, from a website building perspective, it's best practice to only have a single H1 tag on a page. You want your pages to be structured and focus around a single topic, having multiple topics per page is possible but absolutely not recommended as it's confusing and generally too much info for a single page. 

Having said that, you can still edit the code to also include h1 tags for the ToC if you for any reason have to deviate from the above explanation simply add `or page.content contains '<h1'` after the h2 and h3 code in the if statement.

**Comment by acdoussan** [comment]
Hmm, so, the main thing here is that the post already has a title, so having another `# some title` followed by `## the first section` to start my post seems a little weird / redundant. Should I just start with `## the first section` in my post? Should the markdown parser just start with `h2` instead of `h1` for `# a title`? Something else?

**Comment by MattsBos** [comment]
Generally you would use the page/post title as the main description of your topic, that's the default h1 that's being added. Continuing from there you can start typing directly to give some introduction to your content, it will be under the h1 from the post title. After that you would split up the contents with h2 tags as the sections of your topic.

Maybe to illustrate it, the following setup is what most websites, blogs, articles etc. use (and I've been using for over 20 years):
```
# Title of your page/post, the only h1
A little explanation right below as the content to let readers know what's going to follow.

## First section of your topic, this will be the first header you create yourself and it's h2.
Text for section.

## Second section, h2
Text for section
### Sub section1, h3
Text for sub
### Sub section2, h3
Text for sub
#### Sub sub, h4
Text for sub sub

## Third section, h2
etc. etc.
```

This will give you a perfect ToC on the side.
Hope that makes it clear and makes sense!

**Comment by acdoussan** [comment]
Gotcha, that makes sense, thanks! Think this can probably be closed, might be good to add what you just put in that message to the https://chirpy.cotes.page/posts/write-a-new-post/ post at the top though
