### ISSUE TITLE
Provide the option to exclude the avatar

### ISSUE THREAD

**Issue by paulschuetz** [cotes2020/jekyll-theme-chirpy#689]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There is no similar request on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

For my blog I want to be anonymous and therefore I do not want to have an avatar displayed. Currently I think there is no way to exclude the avatar without overwriting the `_includes/sidebar.html`. By default the empty placeholder is always rendered.

## Describe the solution you'd like

I would like to have the option in the `_config.yaml` to define that I do not want to render an avatar or that the default behavior (when no url is provided) is that no placeholder is presented at first. 

## Describe alternatives you've considered

Alternatively I can overwrite the `_includes/sidebar.html` but I think that will make updating to newer versions of the template always more complex. However I am quite new to jekyll.

## Additional context

Thank you all for your great work on this beautiful project :heart:

**Comment by cotes2020** [comment]
As a blog site, it's a design trend to keep avatars in the sidebar, so I'm not going to add this option.

You can keep a modified `sidebar.html` file in the project, and your modifications will be used in future updates, unless the content of the update involves `sidebar.html`, which requires you to check the changelog.

See: <https://jekyllrb.com/docs/themes/#overriding-theme-defaults>
