### ISSUE TITLE
Github Emoji Support for posts (which are written in markdown)

### ISSUE THREAD

**Issue by TheSharpOwl** [cotes2020/jekyll-theme-chirpy#698]
## Checklist

- [x ] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x ] There is no similar request on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x ] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x ] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe
I am just suggesting a feature no problems for me )

## Describe the solution you'd like

Just add the feature for example in a post I wrote `:smile:` and it will show like this in the blog post:😄 

## Describe alternatives you've considered
I didn't find a way to do it other than using pictures and stuff...

**Comment by Darkcybe** [comment]
Hey @TheSharpOwl, Jekyll has functionality to include Font Awesome Icons, there could be something similar for the [smile emoji](https://fontawesome.com/search?q=smile&o=r) here. The [Link Here](https://idratherbewriting.com/documentation-theme-jekyll/mydoc_icons.html) is a great reference for adding the icons to a markdown post.

**Comment by NichtsHsu** [comment]
Hi, [jemoji](https://github.com/jekyll/jemoji) may be a good plugin for your case.

**Comment by TheSharpOwl** [comment]
Thank you )) @NichtsHsu @Darkcybe
