### ISSUE TITLE
How to make the left-shown title  and the website title different?

### ISSUE THREAD

**Issue by PPPerry** [cotes2020/jekyll-theme-chirpy#699]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [ ] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description
if i change the title content, both of them will be changed. Could i change them respectively?

**Comment by NichtsHsu** [comment]
Hi @PPPerry ,

The title shown in siderbar is defined here:

https://github.com/cotes2020/jekyll-theme-chirpy/blob/65f722fb040bd61df28b3d7c1fd95c370454a8de/_includes/sidebar.html#L24-L26

You can change `{{ site.title }}` to anything you want shows in sierbar. For example, change to `{{ site.siderbar_title }}`, then you can add `siderbar_title: XXXX` at `_config.yml` to config it.
