### ISSUE TITLE
Error Page http://127.0.0.1:4000/categories/blogging/

### ISSUE THREAD

**Issue by techslam** [cotes2020/jekyll-theme-chirpy#7]
I am getting 404: Page not found whenever i try browsing any Category/* or tags/*

**Comment by techslam** [comment]
![Screenshot 2019-10-11 13:06:27](https://user-images.githubusercontent.com/166223/66651358-bd497400-ec2a-11e9-9634-cc08b22da8ae.png)

**Comment by cotes2020** [comment]
The `run.sh` invokes the python scripts to generate the HTML pages for Categories and Tags, so if you run `jekyll serve` only, you will missing the Categories and Tags.

To solve this issues, just upgrade your Python to 3.5 or above, then use the `run.sh`.

**Comment by techslam** [comment]
I have installed python 3.6 , however , not sure why it doesn't reflect :

~/Documents/jekyll-theme-chirpy$ python --version
Python 2.7.15+

**Comment by cotes2020** [comment]
Switch the default python version to 3.6 on your machine.

**Comment by techslam** [comment]
Thanks Cotes.. After playing around with Python and Pip, finally managed it to work on my local machine. Awesome.

So , Is there a tutorial to get this working on custom domain using githu pages ? Or can I assume GitHub pages wont give this python related error ?

**Comment by cotes2020** [comment]
Basically, follow the tutorial [Deploying to GitHub Pages](https://chirpy.cotes.info/posts/getting-started/#deploying-to-github-pages) to complete the deployment.

In addition, the GitHub official docs has detailed instructions for adding custom domain:
<https://help.github.com/en/articles/about-custom-domains-and-github-pages>

**Comment by techslam2** [comment]
Hi Cotes,
Thanks for your reply.

I have published the page at https://techslam2.github.io/
and I can see same problem with categories and tags.

How do we make this work now that its live on Github page ?

**Comment by techslam2** [comment]
Please ignore, I guess i should have followed the post properly. Its working perfectly fine now.

Much Thanks for this awesome template.

**Comment by techslam2** [comment]
Hi,

Can see one anotehr issue. If you check the link in https://techslam2.github.io/categories/blogging/  you can see that they all point to www.example.com

Though my local pc its linking to correct posts. Any idea whats wrong here ?

**Comment by cotes2020** [comment]
>If you check the link in https://techslam2.github.io/categories/blogging/ you can see that they all point to www.example.com

Because the variable `url` in `_config.yml` is not set. Change it to your domain URI `https://techslam2.github.io`.

**Comment by techslam2** [comment]
Thanks Cotes. I guess everything is working now. Will play around a bit. I am new to Jekyll and Git. So I had some basic doubts.

Lastly, probably it's bug, but can see a bottom scroll bar in the side menu. 

![side-bar-scroll](https://user-images.githubusercontent.com/56445851/66680646-e4bf3180-ec68-11e9-88e6-c6c65e69f935.png)
Not sure if that is a bug or with purpose ?

**Comment by cotes2020** [comment]
>... can see a bottom scroll bar in the side menu.

By design, the sidebar should not slide horizontally. So  would you like to give me more information to  understand the situation?

* The brower type and version
* The screen resolution

**Comment by techslam** [comment]
Firefox Quantun 69.0.2
Screen Resolution : 16:9

**Comment by cotes2020** [comment]
This is due to Firefox compatibility. So far, **Chirpy** has worked well in Chrome, Safari, Opera, and Edge. I will fix compatibility issues with Firefox later.

**Comment by techslam** [comment]
Thanks Cotes. Highly appreciate the help with this template. My blog is live at https://techslam.net/

Did some changes to suit my needs - 
- Bio.html to include in my posts
- Subscribe.html for email subscription on the right panel.
- Tweet button at the end of each post.

Additional improvement suggestion -
Its difficult to manually add 'Also See' links in each post. I guess we could do some tweeks  to pull the related posts by 'tags' and list 3 or more items?
