### ISSUE TITLE
Issue with my tag & category

### ISSUE THREAD

**Issue by techslam** [cotes2020/jekyll-theme-chirpy#70]
Hi Cotes,
Thanks again for this wonderful template.
I have recently tweaked my blog to include your latest template changes.
Post that, my individual category and tags pages are showing 404.
home page - https://techslam.net/
example tag page - https://techslam.net/tags/autosys/ >> showing 404
example category page - https://techslam.net/categories/scheduler/   >> showing 404

Seems , I must have missed something while pushing to github repo as locally these pages are working fine.
Appreciate any guidance to fix this.
Thanks,
Aslam

**Comment by techslam** [comment]
Hi Cotes,
Well, so I was able to get this sorted out by executing bash/tools/init.sh , which then created all the respective categories and tag pages for me.
Does this mean , I will have to run this init.sh everytime there is a new post/category/tag created ?

Thanks a lot.
Aslam

**Comment by cotes2020** [comment]
> Does this mean , I will have to run this init.sh everytime there is a new post/category/tag created ?

That's right. For more details,  see: [Deploying to GitHub Pages](https://chirpy.cotes.info/posts/getting-started/#deploying-to-github-pages).

**Comment by techslam** [comment]
Thanks cotes. Highly appreciate your quick response. 
Also, if you see in my website, there is no view count after the post date. Did I miss some configuration to enable it?

Thanks 
Aslam

**Comment by cotes2020** [comment]
>  there is no view count after the post date. Did I miss some configuration to enable it?

It's a repetitive question, same as #33.

**Comment by techslam** [comment]
Thanks for your help.
