### ISSUE TITLE
How to set center alignment on caption for the cover image in the front matter?

### ISSUE THREAD

**Issue by Biplab-Dutta** [cotes2020/jekyll-theme-chirpy#701]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [ ] My question is based on the latest code of the `master` branch.

## Description
![image](https://user-images.githubusercontent.com/63902683/193480634-c5ed4a13-81ce-49a0-a599-b8657e7d88bf.png)
In the above image, the caption for the preview image is centered. How can I achieve that? When I use `alt` inside my front matter, the image description is left-aligned.

**Comment by cotes2020** [comment]
Upgrading your site's theme to version _5.3.0_.

**Comment by Biplab-Dutta** [comment]
@cotes2020 I shall check on how to upgrade and let you know if that worked. Also, is it possible to add a caption with hyperlink as `alt` in the preview image?
