### ISSUE TITLE
Add markdown content to home page.

### ISSUE THREAD

**Issue by ticaboo** [cotes2020/jekyll-theme-chirpy#708]
## Checklist

- [√] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [√] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [√] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [√] My question is based on the latest code of the `master` branch.

## Description

Sorry to ask here, spent hours on this, cant find an answer. Its probably Too Obvious! 

All I want to do is have an md file that renders in Home page - above the posts list.

Could be worth adding solution to documentation, seems a standard task. Thx.

**Comment by BaldMonster33** [comment]
Posting a feasible solution if anyone else has this double:

Renaming the index.html in the root folder into index.md,
Add below to start. 
```
---
layout: page
---
```

**Comment by ticaboo** [comment]
Thanks #BaidMonster33. That helps a lot. 

The complete solution I desire is that still it shows the list of posts as well as the index.md generated markup.
When I change index.html to index.md it shows the index.md content, but not the list of posts as well.
When I change index.md back to 

```
---
layout: home
---
```

and to layout/home.html add 
```
{{ content }}
````

get warning:
```
Pagination: Pagination is enabled, but I couldn't find an index.html page to use as the pagination template. Skipping pagination.
```
and the post list does not show.

95% of the way there I think/hope!

**Comment by NichtsHsu** [comment]
Hi @ticaboo , using index.md is not feasible due to [pagination](https://jekyllrb.com/docs/pagination/):

> ### Pagination only works within HTML files
> Pagination does not work from within Markdown files from your Jekyll site. Pagination works when called from within the HTML file, named `index.html`, which optionally may reside in and produce pagination from within a subdirectory, via the `paginate_path` configuration value.

**Comment by timermachine** [comment]
Thanks, works for me. Appreciate knowing this now - its a tad counterintuitive, so thanks again. both repsondants.
