### ISSUE TITLE
Does chirpy support <!--more--> to separate contents for homepage and detailed page?

### ISSUE THREAD

**Issue by sirlis** [cotes2020/jekyll-theme-chirpy#709]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

In the early version of chirpy, I can use `<!--more-->` to separate contents and automatically generate an abstract for homepage. Contents before it will show on the homepage after the post title  just like an abstract, contents after that will show only in the detailed post. However, after updating the theme to the latest version, this function seems to be unsupported.

**Comment by sirlis** [comment]
Just leave a comment to see if this question can be solved.

**Comment by dineshkoravi** [comment]
I have not used the previous versions, but the latest version does not separate content from excerpt on the home page. It would be nice to have this because first Heading of the post is visible in front page and does not look nice to be in description of post.

**Comment by sirlis** [comment]
> I have not used the previous versions, but the latest version does not separate content from excerpt on the home page. It would be nice to have this because first Heading of the post is visible in front page and does not look nice to be in description of post.

I hope this function could be supported in the future release.

**Comment by sirlis** [comment]
> Support of `excerpt_separator` will be very appreciated.

I've managed to solve the problem by modifying the original code. However I forgot how to do it...
See my blog [here](https://sirlis.cn) if it is helpful. 

In addition, Jekyll supports `excerpt_separator` (according to [here](https://cjshelton.github.io/blog/2019/05/27/customising-jekyll-excerpt-start.html)), however chirpy doesn't support it.

**Comment by dineshkoravi** [comment]
could i get this commit and still get updates from chirpy with out issues ?

**Comment by sirlis** [comment]
> could i get this commit and still get updates from chirpy with out issues ?

recently I updated my blog through chirpy starter and lost the `excerpt_separator` ability. I think I should modify  `_layouts/home.html` after each update.

```html
  <div class="card-text post-content mt-0 mb-2">
    <p>
      <!-- {% include no-linenos.html content=post.content %} -->
      {% include no-linenos.html content=post.excerpt %}
      {{ content | markdownify | strip_html | truncate: 200 | escape }}
    </p>
  </div>
```

may work.
