### ISSUE TITLE
404 with .dev custom domain if there is "/" at the end of url. Working without last "/"

### ISSUE THREAD

**Issue by bajicdusko** [cotes2020/jekyll-theme-chirpy#71]
**Not sure if it's a bug**
I'm one of 404 folks, however, I really think there is something else here that isn't covered with other issues in the past.
Locally, of course, it works. On Github Pages it isn't working unless I remove last `/` in the URL.
So I played a bit with sidebar.html and made [this change](https://github.com/bajicdusko/bajicdusko.github.io/commit/63c73b9a0c444cf3d28f73c2b12624847e95e538). With this change all of menu items in sidebar are working, however, some deeper URLs (like clicking on a specific tag) still shows 404.
Example of non-working URL: https://dusko.dev/tags/android/
Example of working URL: https://dusko.dev/tags/android

I've executed the steps from the readme. Commit. execute init.sh, push, multiple times. I've even tried local build and deployment. No luck. Removed all generated files and did init.sh again, everything generated properly and successful.

Is it possible that `.dev` TLD could cause this issue?
You can see in my repo that I have a proper CNAME file and Github Pages is setup to target `dusko.dev` domain. On my DNS side, I have a `www` as CNAME for `bajicdusko.github.io` as well.

This is my [config file](https://github.com/bajicdusko/bajicdusko.github.io/blob/master/_config.yml).
This is my [blog](https://dusko.dev)

Any comments appreciated. If I'm missing something stupid, this issue deserves a double RTFM tag.

**Kudos**
Hey man, this is really a cool theme, with a bunch of details. I wouldn't mind paying for your work if it happens that you go commercial. Until then, coffee time.

**Comment by cotes2020** [comment]
When you change the `permalinks` settings for the template and the other URL links are not taken care of, you are likely to get a lot of strange "bugs".

The [`permalinks of your repo`](https://github.com/bajicdusko/bajicdusko.github.io/blob/bb8c903c20cfa5f37ec4f0458fa241c6a03349c3/_config.yml#L90) is waiting for its little friend `/` to come home, so let's get them together:

```diff
- permalink: /posts/:year/:month/:title
+ permalink: /posts/:year/:month/:title/
```

And don't forget to resume the modification in file `_indlucde/sidebar.html` for it's innocent.

For more information, see: <https://jekyllrb.com/docs/permalinks/>

**Comment by bajicdusko** [comment]
It had to be something tiny ain't it :). Good catch @cotes2020 . Fixed permalink fixes the problem. 
I've just left a coffee for you. Keep up with good work!
