### ISSUE TITLE
Move homepage to 'posts' tab, About me as homepage

### ISSUE THREAD

**Issue by adrianmnh** [cotes2020/jekyll-theme-chirpy#711]
## Checklist

- [X] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [X] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [X] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [X] My question is based on the latest code of the `master` branch.

## Description

What I'm trying to do is move the default homepage to something like url/posts
so that I can make the about me tab the homepage
![image](https://user-images.githubusercontent.com/21344144/195188816-f6ac4c5e-0071-4264-9dcd-2456aad5e17e.png)

What happens when I do this is that the posts page looses all functionality and only shows pinned posts

I managed to to this by changing some tabs and layouts, but the end product is this
![image](https://user-images.githubusercontent.com/21344144/195188916-eb561af7-e5c6-4359-8d30-fbb2a235ebab.png)

The pseudo 'home' page only shows pinned posts, there is not paginator.

**Comment by NichtsHsu** [comment]
Hi @adrianmnh ,

It maybe difficult because [pagination](https://jekyllrb.com/docs/pagination/) only works within `index.html`.

**Comment by emads3** [comment]
I hope you find a way around it since it's really bad not to be able to customize home page.

**Comment by nouinou** [comment]
I did it successfully by overwriting the homepage layout `home.html`. Then created a new layout called `posts-page.html`, a copy of the default home page + a small change. ` {% assign posts = sites.posts | push: default[i] %}` instead of  `{% assign posts = posts | push: default[i] %}`. Finally, I added a new tab called `blog.md` and specified its layout as posts-page but left its content empty.

**Comment by adrianmnh** [comment]
> I did it successfully by overwriting the homepage layout `home.html`. Then created a new layout called `posts-page.html`, a copy of the default home page + a small change. ` {% assign posts = sites.posts | push: default[i] %}` instead of `{% assign posts = posts | push: default[i] %}`. Finally, I added a new tab called `blog.md` and specified its layout as posts-page but left its content empty.

Hey.. I tested your fix, however the `blog` tab does not have a paginator

**Comment by nouinou** [comment]
> Hey.. I tested your fix, however the `blog` tab does not have a paginator

True. I found another way.

1- Delete `blog.md`. In the root folder create a new directory called `blog` and create `index.html` inside it.

<img width="302" alt="Screen Shot 2022-12-18 at 5 50 19 AM" src="https://user-images.githubusercontent.com/11968907/208282057-4a3eda51-f4ae-45a2-b774-e8d486e65dec.png">

2- In `post-pages.html` change that line back to `{% assign posts = posts | push: default[i] %}`

3- In `_config.yaml` add `paginate_path: "/blog/:num/"`

4- Overwrite `post-paginator.html` and change `{% else %}{{ '/' | relative_url }}{% endif %}` to be `{% else %}{{ site.paginate_path | replace: '/:num', '' | relative_url }}{% endif %}"` This will solve the issue with redirecting to the home page when clicking on page 1.

Now when you serve and go to /blog you can see the pagination but there is no link on the sidbar.
Simply overwrite `sidebar.html` and add a new list item like this:

<img width="863" alt="Screen Shot 2022-12-18 at 5 52 22 AM" src="https://user-images.githubusercontent.com/11968907/208282088-4f02fc0c-9042-4136-a96c-b0be6bfe34d8.png">

**Comment by adrianmnh** [comment]
> > Hey.. I tested your fix, however the `blog` tab does not have a paginator
> 
> 
> 
> True. I found another way.
> 
> 
> 
> 1- Delete `blog.md`. In the root folder create a new directory called `blog` and create `index.html` inside it.
> 
> 
> 
> <img width="302" alt="Screen Shot 2022-12-18 at 5 50 19 AM" src="https://user-images.githubusercontent.com/11968907/208282057-4a3eda51-f4ae-45a2-b774-e8d486e65dec.png">
> 
> 
> 
> 2- In `post-pages.html` change that line back to `{% assign posts = posts | push: default[i] %}`
> 
> 
> 
> 3- In `_config.yaml` add `paginate_path: "/blog/:num/"`
> 
> 
> 
> 4- Overwrite `post-paginator.html` and change `{% else %}{{ '/' | relative_url }}{% endif %}` to be `{% else %}{{ site.paginate_path | replace: '/:num', '' | relative_url }}{% endif %}"` This will solve the issue with redirecting to the home page when clicking on page 1.
> 
> 
> 
> Now when you serve and go to /blog you can see the pagination but there is no link on the sidbar.
> 
> Simply overwrite `sidebar.html` and add a new list item like this:
> 
> 
> 
> <img width="863" alt="Screen Shot 2022-12-18 at 5 52 22 AM" src="https://user-images.githubusercontent.com/11968907/208282088-4f02fc0c-9042-4136-a96c-b0be6bfe34d8.png">

Oh man I can't wait to try this fix
Thank you for this. I was considering rebuilding or square lol. Tysm

**Comment by nouinou** [comment]
> Oh man I can't wait to try this fix Thank you for this. I was considering rebuilding or square lol. Tysm

Let me know if it works for you. I found this issue because I was trying to do the same thing 😄

**Comment by adrianmnh** [comment]
@nouinou it worked.
You sir are, the best. :D
I almost got stuck unable to render the blog page on the side bar using the "tabs" but the side bar link to the blog/index works perfectly.
I'll let you know if I encounter any bugs
Thank you again

**Comment by adrianmnh** [comment]
@nouinou hey!! the fix works great
there's a new bug i just encountered i'm not sure where the problem is

![image](https://user-images.githubusercontent.com/21344144/209847947-4a7b32a7-b736-48f5-b591-c80dfab5087e.png)

the slider on the sidebar doesnt move as expected, and when any tab other than the new "home" is clicked on, the new paginated tab projects is highlighted

**Comment by nouinou** [comment]
> @nouinou hey!! the fix works great there's a new bug i just encountered i'm not sure where the problem is
> 
> ![image](https://user-images.githubusercontent.com/21344144/209847947-4a7b32a7-b736-48f5-b591-c80dfab5087e.png)
> 
> the slider on the sidebar doesnt move as expected, and when any tab other than the new "home" is clicked on, the new paginated tab projects is highlighted

Nice catch! you can fix that by overwriting the scss tab-count variable 
`$tab-count: 6;` if you have 6 tabs
Adding it in `jekyll-theme-chirpy.scss` after the import worked for me

**Comment by adrianmnh** [comment]
Yes, that worked for me too!
I found that changing the tab count on variable.scss to "6"
and 
changing this line to "plus 2"
$tab-count: {{ site.tabs | size | plus: 2 }}; // plus 1 for home tab, 1 for projects tab
on style.scss has a similar effect. 
Thank you for your help Hamza. I can finally start adding projects to my portfolio. my OCD wouldn't let me continue until the bug was taken care of!
thank you again, and
HAPPY NEW YEAR! :D

**Comment by JinchaoLove** [comment]
Another solution (see my [demo](https://jekyll-theme-chirpy-taupe.vercel.app/)):
1. Modify the front matters with `permalink`:
    - Create a new folder, e.g. `/blog/`, and a new index.html inside it, with front matter:
        ```html
        ---
        layout: home
        permalink: /blog/
        title: Blog
        ---
    - Add `permalink: /` in the front matter of `/_tabs/about.md`.
2. Modify `/_config.yml` to point to the folder `/blog/`
    ```diff
    + paginate_path: "/blog/page:num/"
    ...
    - permalink: /posts/:title/
    + permalink: /blog/:title/
    ```
3. Add BLOG as a new tab or navigation item, refer to issue #855.

More details could be found in my [post](https://jekyll-theme-chirpy-taupe.vercel.app/blog/exchange-homepage-and-about/) or [repo](https://github.com/JinchaoLove/jekyll-theme-chirpy).

**Comment by adrianmnh** [comment]
@JinchaoLove Thank you Jinchao, I will test those changes out locally, it looks like a  much easier fix though

**Comment by patrykpalej** [comment]
> @JinchaoLove Thank you Jinchao, I will test those changes out locally, it looks like a much easier fix though

I deal with the same problem. I moved main posts to another tab and set layouts just like in your case, but the pagination numbers still appear on the main page, even though the posts are on another one. Did you have the same problem?

**Comment by JinchaoLove** [comment]
> > @JinchaoLove Thank you Jinchao, I will test those changes out locally, it looks like a much easier fix though
> 
> I deal with the same problem. I moved main posts to another tab and set layouts just like in your case, but the pagination numbers still appear on the main page, even though the posts are on another one. Did you have the same problem?

@patrykpalej No. The [website](https://jekyll-theme-chirpy-taupe.vercel.app) is fine. Have you set `paginate_path: "/blog/page:num/"` in `/_config.yml`?

BTW, this repository from cotes2020 has many conditional statements that are related to layout names, such as `{% if page.layout == 'home' %}`. I think this is not very elegant, and easy to cause problems when you're creating a new layout.
