### ISSUE TITLE
Can't deploy the website on Githubs. 

### ISSUE THREAD

**Issue by coherently** [cotes2020/jekyll-theme-chirpy#715]
I am trying to use the chirpy theme for my personal blogging. And all I see is the following. 
--- layout: home # Index page --- 
I know that this issue has been raised multiple times here, which I have tried all but still to no avail.

**Comment by AhmedElwerdany** [comment]
in `_config.yml` file
```yml
# Change the following value to '/PROJECT_NAME' ONLY IF your site type is GitHub Pages Project sites
# and doesn't have a custom domain.
baseurl: '/blog'
```

make sure to make `baseurl` equal to the name of your repo.
in my case my repo was `blog`
