### ISSUE TITLE
Forcing Dark Theme on older version

### ISSUE THREAD

**Issue by ozgunozerk** [cotes2020/jekyll-theme-chirpy#72]
Hello, I'm using an older version of this theme, and since I've done so much configurations, I don't want to update it. 

In my version, there is no toggle button between light and dark, also adding "theme_mode: dark" in config.yml does not help.

I want to force dark theme, how can I do this manually? Where is the theme selection located at? I couldn't find it :)

Thanks

**Comment by bajicdusko** [comment]
What you're looking for is a `mode-toggle.html` in `_includes` directory. It is referenced in `sidebar.html`, same directory. It's a good starting point.

**Comment by ozgunozerk** [comment]
I've already discovered that but thank you very much for your time.

In my version, mode-toggle.html does not exits, I've tried to search "theme" "light" and "dark" keywords in all js and css files but couldn't find a clue. Yet, my website manages to load light theme in my windows and dark theme in my macOS. Which css or js file controling that?

**Comment by ozgunozerk** [comment]
Ugh, i guess i have to update it to the newer code... The structure changed a lot :D

**Comment by cotes2020** [comment]
@ozgunozerk It is not possible to get the "force dark theme" feature by simply copying some files or adding a few parameters to the `_config.yml` file. I suggest that you should only keep the content under `_posts` and upgrade the rest of the template code.

But, if you want to review the logic of dark mode switching, check [`this`](https://github.com/cotes2020/jekyll-theme-chirpy/blob/1493d41921b99a82a8074d4c25a1d861afdf7331/assets/css/_addon/main.scss#L35-L51) :).

**Comment by ozgunozerk** [comment]
In my version (maybe 6-7 months old, maybe more), there is no "light" mode, there is only "dark mode" in the css files, so I figured out, the light version comes from the default settings, dark version is forced only if the system settings are dark, and I've copied some code for applying dark mode if the system settings are light too, it worked :)

I've tried to update to the new version though, but with the configurations I've made, it did not work, I guess this solution was easier, thanks everyone for your time to respond me :)
