### ISSUE TITLE
having problem deploying pages

### ISSUE THREAD

**Issue by Ntf-Sadnan** [cotes2020/jekyll-theme-chirpy#721]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description
i have just commanded `get push` and it showed this error! please help 
![image](https://user-images.githubusercontent.com/79263493/197223693-cd5c764c-d2d2-4ae9-98c2-c21a8552a9ab.png)

i have tried it many time! but in past it showed 
`--- layout: home # Index page ---`
and now this! ,,please help! I'm trying this for whole day !

**Comment by sharonwoo** [comment]
1. Run `bundle lock --add-platform x86_64-linux` on your local copy of the repository.
2. Add the modified gemlock to your repo and commit.

**Comment by myHobbyBest** [comment]
I'd  been troubled similar error as follow.
It's solved  with same command (Run bundle lock --add-platform x86_64-linux) now.
![error code16 - 2022-11-04 143534](https://user-images.githubusercontent.com/117243771/200979433-5a37e9a7-35e1-4f9f-92d5-25cca99a5da1.png)

I found  important comments ,that might related to these errors, are deleted at README.MD file during simolifying .

![simplify-the-README](https://user-images.githubusercontent.com/117243771/200981784-93b3a86b-32ef-4e5e-b11d-406e595f6d28.png)

**Comment by myHobbyBest** [comment]
Wow, it's my first contribution to one of the open source projects by first
comments.

Thanks , Mr. Cotes.

2022년 11월 12일 (토) 오후 7:32, Cotes ***@***.***>님이 작성:

**Comment by CoolJosh0221** [comment]
> 

I have the same issue, but `bundle lock --add-platform x86_64-linux` does not solve for me.

**Comment by CoolJosh0221** [comment]
> 

I have the same issue, but `bundle lock --add-platform x86_64-linux` does not solve for me.
