### ISSUE TITLE
Open links in New Tab by default instead of same tab.

### ISSUE THREAD

**Issue by sbkv1** [cotes2020/jekyll-theme-chirpy#722]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There is no similar request on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

Let say I am reading a blog and I click a link mentioned there. The link is opened in the same tab, but the user was reading the content. So, it would a great if the link is opened in a new tab by default.

**Comment by NichtsHsu** [comment]
You can use [IAL]((https://kramdown.gettalong.org/syntax.html#inline-attribute-lists)) to achieve this.

For an example:

```markdown
Click [here](https://github.com){:target="_blank"} to open Github.
```

**Comment by sbkv1** [comment]
> You can use [IAL](https://kramdown.gettalong.org/syntax.html#inline-attribute-lists) to achieve this.
> 
> For an example:
> 
> ```gfm
> Click [here](https://github.com){:target="_blank"} to open Github.
> ```

I am creating the blog from some of my markdown notes. It would be a lot of work to change all the links like that.

**Comment by NichtsHsu** [comment]
There doesn't seem to be such an option inside Jekyll to configure. You can do this with the plugin [jekyll-target-blank](https://github.com/keithmifsud/jekyll-target-blank).
