### ISSUE TITLE
Can I use username.github.io/blog instead of username.github.io

### ISSUE THREAD

**Issue by sbkv1** [cotes2020/jekyll-theme-chirpy#724]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

I already have a website at username.github.io and I want to use this template at username.github.io/blog. But in the getting started page the format is <GH_USERNAME>.github.io. I don't have domain so I can not use a subdomain for the blog.

**Comment by NichtsHsu** [comment]
When you enable github pages for your second repository (assuming that first is `<GH_USERNAME>.github.io`), that repository will be deployed on `<GH_USERNAME>.github.io/repo_name`. So in your case you just need to create a repo named`blog` and enable github pages for it. Finally, config `baseurl: '/blog'` in your `_config.yml`.

**Comment by SamirPaul1** [comment]
> When you enable github pages for your second repository (assuming that first is `<GH_USERNAME>.github.io`), that repository will be deployed on `<GH_USERNAME>.github.io/repo_name`. So in your case you just need to create a repo named`blog` and enable github pages for it. Finally, configure `baseurl: '/blog'` in your `_config.yml`.

@NichtsHsu The sitemap does not work for baseurl: '/blog'
<img width="312" alt="image" src="https://user-images.githubusercontent.com/77569653/197847814-6317c7b0-d9ef-4408-8727-2b4b8b08d4c6.png">

**Comment by NichtsHsu** [comment]
@SamirPaul1 Do you configure `url: https://<GH_USERNAME>.github.io`?

**Comment by SamirPaul1** [comment]
> @SamirPaul1 Do you configure `url: https://<GH_USERNAME>.github.io` in `_config.yml`?

Thanks a lot, @NichtsHsu. Now it is working!
