### ISSUE TITLE
How to hide "Powered by Jekyll with Chirpy theme."

### ISSUE THREAD

**Issue by sbkv1** [cotes2020/jekyll-theme-chirpy#726]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description
Hide Powered by [Jekyll](https://jekyllrb.com/) with [Chirpy](https://github.com/cotes2020/jekyll-theme-chirpy) theme from bottom of the page.
![image](https://user-images.githubusercontent.com/93185814/197850278-90a27736-cac6-4d62-8fdb-0e5b56e79e89.png)

**Comment by sbkv1** [comment]
@NichtsHsu I tried keeping it empty but still not working.

<img width="167" alt="image" src="https://user-images.githubusercontent.com/93185814/197937610-5f26bf97-e041-45f0-8c9d-2c6233ed532c.png">
![image](https://user-images.githubusercontent.com/93185814/197937735-7bc4c9fc-81e0-45ed-b2af-01ba969a16c9.png)

**Comment by NichtsHsu** [comment]
Well, there is a default value for this config.

https://github.com/cotes2020/jekyll-theme-chirpy/blob/e107a2e759836510216ea8567aa8b203decace31/_includes/footer.html#L28-L31

So we need to set some specific contents to cover it, such as a space: `meta: ' '`. Or, simply remove the above codes.

**Comment by sbkv1** [comment]
Thanks for helping! 🙌✅

**Comment by jakre1234** [comment]
Any idea how to do it in website made me starter-template? I don't see any folder _includes in my repo. I would like to change the footer text and add some more social icons but I don't see any option, no foler _includes neither sidebar.html file in my repo.
