### ISSUE TITLE
Can I update any file of '_includes' if I use Chirpy Starter?

### ISSUE THREAD

**Issue by SamirPaul1** [cotes2020/jekyll-theme-chirpy#728]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

I am using the [Chirpy Starter](https://github.com/cotes2020/chirpy-starter/generate). I want to customise some HTML files of /_includes directory. How can I do that?

**Comment by NichtsHsu** [comment]
Please check the section [Overriding theme defaults](https://jekyllrb.com/docs/themes/#overriding-theme-defaults) of Jekyll documentation.
