### ISSUE TITLE
Social preview image not showing while link sharing

### ISSUE THREAD

**Issue by SamirPaul1** [cotes2020/jekyll-theme-chirpy#730]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug
**while sharing links on social media the preview image is not showing.** 

### Screenshots
<img width="532" alt="image" src="https://user-images.githubusercontent.com/77569653/198023742-c6ee23ca-6a64-4d64-9b9e-52eebe927899.png">

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |         |
| `gem -v`                          |         |
| `bundle -v`                       |         |
| `bundle exec jekyll -v`           |         |
| `bundle info jekyll-theme-chirpy` |         |

**Comment by SamirPaul1** [comment]
![og:image](https://user-images.githubusercontent.com/77569653/198299751-bccef7d4-3e4e-4e66-8c53-d65f1e735648.jpeg)
```blog/blog``` is generating 2 times that's why social preview is not working. @NichtsHsu can you help me to resolve this issue?

**Comment by awt-tom** [comment]
Having the same issue. been on some changes but no succes yet.
