### ISSUE TITLE
How to use AMP versions of Jekyll posts?

### ISSUE THREAD

**Issue by SamirPaul1** [cotes2020/jekyll-theme-chirpy#733]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description
I have tried using the [amp-jekyll](https://github.com/juusaw/amp-jekyll) plugin but the permalink is not generating correctly and showing an error.

<img width="568" alt="image" src="https://user-images.githubusercontent.com/77569653/198144104-d8450ff4-8947-41d4-8493-7e55b15f065a.png">

**Comment by sbkv1** [comment]
@cotes2020 @NichtsHsu

**Comment by sbkv1** [comment]
Can anyone help with this issue?
