### ISSUE TITLE
How to add {% seo %} tag in site’s template in Chirpy Starter??

### ISSUE THREAD

**Issue by SamirPaul1** [cotes2020/jekyll-theme-chirpy#735]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

I am using [Chirpy Starter](https://github.com/cotes2020/chirpy-starter). I want to add [jekyll-seo-tag](https://jekyll.github.io/jekyll-seo-tag/installation/) plugin for which I need to add {% seo %} right before ```</head>``` in site’s template(s).
Can anyone help me with how to do this?

**Comment by qureshiaquib** [comment]
Is there a way to do this? Or is this now integrated by default?

**Comment by kungfux** [comment]
@qureshiaquib  I assume it is integrated by default and is being configured in [_config.yml](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/_config.yml#L14).

**Comment by qureshiaquib** [comment]
Thanks kungfux, I thought this seo tag is suppose to be there in every post.but it seems we've single place to configure this. 
Is this through jekyll seo plugin?
