### ISSUE TITLE
Can Chirpy be used on Github Enterprise?

### ISSUE THREAD

**Issue by SilentGlasses** [cotes2020/jekyll-theme-chirpy#737]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

Not sure if I was using wrong terms but I could not find the answer on the other sites listed above.

What I'm trying to do is to host a blog for myself on our internal Github enterprise but it's not clear if that is allowed as the tutorial calls for a username.github.io url:

Create a new repository from the [Chirpy Starter](https://github.com/cotes2020/chirpy-starter/generate) and name it <GH_USERNAME>.github.io, where GH_USERNAME represents your GitHub username.

I would really like to use Chirpy to host a blog on our internal git.domain.com setup...   The URL would be something link:  git.domain.com/username/repo_name

**Comment by cotes2020** [comment]
Sorry, I have no experience with Github enterprise, maybe you can find clues in the [official docs](https://docs.github.com/en/enterprise-cloud@latest/pages/getting-started-with-github-pages/about-github-pages#limitations-for-enterprise-managed-users), if it still doesn't solve your problem, please [ask the GitHub community](https://github.community/) or contact the _GitHub Support_ directly.

**Comment by SilentGlasses** [comment]
Sad. I will see what I can find. Thanks for replying so fast.
