### ISSUE TITLE
How to use default browser's Webfonts and disable mathjax ??

### ISSUE THREAD

**Issue by sbkv1** [cotes2020/jekyll-theme-chirpy#739]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description
**From https://pagespeed.web.dev report I have seen disabling the fonts.googleapis.com and mathjax  could save almost 1 second of  mobile loading time. I want to use the default OS and browser's front.**

**Comment by sbkv1** [comment]
@cotes2020 @NichtsHsu Could you please help in this regard?

**Comment by li6in9muyou** [comment]
You may try disabling loading webfont from google. One way to do that is commenting out the webfont entry in `/_data/assets/cross_origin.yml`. See an example in [this commit](https://github.com/li6in9muyou/issue-not-triggering-mermiad-render/commit/c29110f14b5dcb9830454d6d03999adc168c29f2#diff-8b94df9bd5e31e5b172911788af7dd64cdb37948edef3ca208ab2e9444adab84)

**Comment by li6in9muyou** [comment]
You are right, comment that out does not work. And, I find that setting its value to hashtag will work. See [this commit](https://github.com/li6in9muyou/li6in9muyou.github.io/commit/b23c64c8d95eb426ed3f8a3756e848270f79e10a)

Alternatively, you can enable non-blocking webfonts loads using [this commit](https://github.com/li6in9muyou/issue-not-triggering-mermiad-render/commit/c76012b26c5fc12bf5110daeae599eafab705c98). I learnt this method [here](https://web.dev/i18n/en/defer-non-critical-css/#optimize).

**Comment by sbkv1** [comment]
@cotes2020 @NichtsHsu

**Comment by sbkv1** [comment]
> You are right, comment that out does not work. And, I find that setting its value to hashtag will work. See [this commit](https://github.com/li6in9muyou/li6in9muyou.github.io/commit/b23c64c8d95eb426ed3f8a3756e848270f79e10a)
> 
> Alternatively, you can enable non-blocking webfonts loads using [this commit](https://github.com/li6in9muyou/issue-not-triggering-mermiad-render/commit/c76012b26c5fc12bf5110daeae599eafab705c98). I learnt this method [here](https://web.dev/i18n/en/defer-non-critical-css/#optimize).

Thanks!
