### ISSUE TITLE
Truncating search

### ISSUE THREAD

**Issue by joshjohanning** [cotes2020/jekyll-theme-chirpy#741]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

Hello,

I was wondering why in this issue https://github.com/cotes2020/jekyll-theme-chirpy/issues/401 and commit https://github.com/cotes2020/jekyll-theme-chirpy/commit/fa333efa41bb20203829410c752fce543ca1250b, the search results / truncation was fixed (from a user suggestion). 

But in 5.3.1, we're truncating again (200). https://github.com/cotes2020/jekyll-theme-chirpy/commit/647eea8dbd716f9d3cb8330c3139fa753903f51d

I was just curious if this was performance related or other? 

Maybe it makes more sense to make this a configuration option and let users define if search results should have truncated posts, and if so, how much?

**Comment by cotes2020** [comment]
No need to add a config option, truncate it just to reduce the output of invisible content inside HTML, but I forgot the need for full-text search, will restore this feature later. 😂

**Comment by joshjohanning** [comment]
thanks 😄
