### ISSUE TITLE
Bundles all the styles in one single asset and use asset minification

### ISSUE THREAD

**Issue by SamirPaul1** [cotes2020/jekyll-theme-chirpy#743]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There is no similar request on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe
Delivering critical JS/CSS from third-party sites increasing the number of HTTP calls. If we use self-hosted assets and bundle all the styles in one single asset and use asset minification then we could reduce loading time.

## Describe the solution you'd like
With the help of the following plugins, we can optimize the mobile performance of the blog.
1. https://github.com/envygeeks/jekyll-assets#configuration
2. https://github.com/rails/sprockets
3. https://guides.rubyonrails.org/asset_pipeline.html

## Additional context

![image](https://user-images.githubusercontent.com/93185814/199254210-af9b72b4-6019-458d-b8af-22ba0533ebcc.png)
If we can minify all these assets, we can reduce the loading time.

**Comment by sbkv1** [comment]
@cotes2020
