### ISSUE TITLE
Table of Contents -- Section Expansion

### ISSUE THREAD

**Issue by dan3093** [cotes2020/jekyll-theme-chirpy#744]
## Checklist

- [ x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x ] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [ x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x ] My question is based on the latest code of the `master` branch.

## Description

On your demo site -- when you click on the TOC items in a post, sub headings get expanded out like so:

![image](https://user-images.githubusercontent.com/78299891/199281946-b350c4e4-afad-4a00-894d-2bc3f8999674.png)

But when I fork the chirpy starter and the main chirpy branch and run the site locally, my sub headings never get expanded:

![image](https://user-images.githubusercontent.com/78299891/199282219-35b4f3be-d67e-4591-ae9d-f7de70beb909.png)

How can I make subheadings show in the toc?

**Comment by dan3093** [comment]
My bad -- I did not realize that the static assets were not pulled. Got it working.

**Comment by dan3093** [comment]
Sorry -- I spoke too soon.

After adding the assets one of my pages is loading the sub headers in the toc, but all other pages do not seem to do it.

**Comment by pyorot** [comment]
> My bad -- I did not realize that the static assets were not pulled. Got it working.

I made some progress with my own issue (#695) thanks to this tip. My installation procedure is now (on Win10 WSL2 Ubuntu 22.04 w/ Ruby 3.0 and Jeykll 4.3.1)
- ` git clone --recursive https://github.com/cotes2020/chirpy-starter.git mySite` (now copies assets)
- `bundle install`
- `jekyll s`

The panel shows up only if there are posts, but I have the same issue as here with the ToC. Testing by copying over some of [these posts](https://github.com/cotes2020/jekyll-theme-chirpy/tree/master/_posts), I find that:
- `[2019-08-08-text-and-typography.md](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/_posts/2019-08-08-text-and-typography.md)` works as expected – ToC dynamically expands into subsections and highlights the part being read.
- `[2019-08-08-write-a-new-post.md](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/_posts/2019-08-08-write-a-new-post.md)` does not react to page scroll, is only highlighted by clicking (but still doesn't expand into subsections), and then doesn't update with scroll. I removed links to missing files until Jekyll CLI stopped complaining, but it didn't help.

**Comment by pyorot** [comment]
Continuing the above investigation with [2019-08-08-text-and-typography.md](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/_posts/2019-08-08-text-and-typography.md): when I delete the part of this page from the Mathematics section to the end, the dynamic ToC still works, but when I then further delete the Mermaid SVG section, it malfunctions as in the [2019-08-08-write-a-new-post.md](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/_posts/2019-08-08-write-a-new-post.md) example.

**Comment by dan3093** [comment]
I have noticed that sometimes when I adjust my browser's zoom setting after the page is loaded, sometimes that seems to enable the subcategories in the TOC.

**Comment by matrix-morpheus** [comment]
Yes i can confirm in ubuntu/Firefox at 100% scaling the TOC does not expand but at 140% it expands.

**Comment by Starwarsfan2099** [comment]
Greetings @matrix-morpheus @dan3093! I am having this same issue with the TOC not expanding, for me it happened after adding image sizes to my site. Were either of you able to find a fix or workaround for this issue?
