### ISSUE TITLE
Why are sidebar icons hardcoded as unloaded

### ISSUE THREAD

**Issue by pacyfist** [cotes2020/jekyll-theme-chirpy#745]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

It seems like Chirpy is ready to display icons next to tabs in sidebar by default

![obraz](https://user-images.githubusercontent.com/2545509/199576435-2fbc4934-5637-4f96-b991-3b6314b865a7.png)

But those icons have a hardcoded class "unloaded" that just gives them `display: none !important;` 

https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/_includes/sidebar.html

```
{% for tab in site.tabs %}
<li class="nav-item{% if tab.url == page.url %}{{ " active" }}{% endif %}">
  <a href="{{ tab.url | relative_url }}" class="nav-link">
    <i class="fa-fw {{ tab.icon }} ml-xl-3 mr-xl-3 unloaded"></i>
    {% capture tab_name %}{{ tab.url | split: '/' }}{% endcapture %}

    <span>{{ site.data.locales[site.lang].tabs.[tab_name] | default: tab.title | upcase }}</span>
  </a>
</li> <!-- .nav-item -->
{% endfor %}
```

Can this be controllable from the configuration?
Or maybe show the icon only when `tab.icon` is explicitly set?

**Comment by joshjohanning** [comment]
I think they show up depending on screen resolution / how big the screen is? On my laptop, I don't see the icons unless I zoom out on the page, but on my monitor, I do.

**Comment by NichtsHsu** [comment]
> But those icons have a hardcoded class "unloaded" that just gives them display: none !important;

Not always. It depends on your screen resolution.

https://github.com/cotes2020/jekyll-theme-chirpy/blob/1fd665bf4990c26ae23635c511c5abc9640184d1/_sass/addon/commons.scss#L1532

https://github.com/cotes2020/jekyll-theme-chirpy/blob/1fd665bf4990c26ae23635c511c5abc9640184d1/_sass/addon/commons.scss#L1617-L1630
