### ISSUE TITLE
How to fix missing post updated time?

### ISSUE THREAD

**Issue by douer423** [cotes2020/jekyll-theme-chirpy#748]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

On your demo site -- it display both Posted time and Updated time of the posts
![image](https://user-images.githubusercontent.com/68940984/200368806-b84ecaa2-4ca8-4bee-8791-24dc9ce2cf64.png)
However,it only display Posted time on my site.May I know how to config it? or some items should added in the yaml part?thanks

**Comment by NichtsHsu** [comment]
Have you ever updated your post? This means that after you committed for a post, you edited and committed it one more time.

If you care about how this field is generated:

https://github.com/cotes2020/jekyll-theme-chirpy/blob/48f14e39ac81bbfb3b9913ea3ee789d775b2d1ae/_plugins/posts-lastmod-hook.rb#L10-L11

https://github.com/cotes2020/jekyll-theme-chirpy/blob/48f14e39ac81bbfb3b9913ea3ee789d775b2d1ae/_layouts/post.html#L22-L27

**Comment by douer423** [comment]
the issue is solved
