### ISSUE TITLE
Having an issue getting pages to deploy

### ISSUE THREAD

**Issue by EnderRookwood** [cotes2020/jekyll-theme-chirpy#749]
# Checklist
  * I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.

 * There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
 * I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
 * My question is based on the latest code of the main branch

## Description

So i think i have everthing right so far in terms of install but when i got to push it will give me an error

![image](https://user-images.githubusercontent.com/110946690/200710132-9585be4e-fd16-4e7c-bd00-b2001a99d947.png)

please help ive been at this for hours

NOTE: IVE SOLVED THE ISSUE..

**Comment by evan-lahr** [comment]
How did you fix this issue?
