### ISSUE TITLE
tags使用空格分隔时，生成的tag页面有问题

### ISSUE THREAD

**Issue by handbye** [cotes2020/jekyll-theme-chirpy#75]
文章中中是这么写的

```
---
layout: post
title: 蚁剑自定义编码器和解码器来bypass waf
categories: web安全
tags: AntSword 蚁剑
---
```

tag页面看到的tag是正确的：

![image](https://user-images.githubusercontent.com/26617058/83717267-e6f55680-a664-11ea-8508-7fa977a4a715.png)

但是生成的tag页面是：

![image](https://user-images.githubusercontent.com/26617058/83717410-39367780-a665-11ea-9af2-88c7951f02b6.png)

导致了无法访问对应的tag页面

![image](https://user-images.githubusercontent.com/26617058/83717546-8dd9f280-a665-11ea-96cd-94adfbe172fc.png)

**Comment by handbye** [comment]
经测试，使用下面这种格式的tag没有问题：
```

---
layout: post
title: 蚁剑自定义编码器和解码器来bypass waf
categories: web安全
tags: [AntSword,蚁剑]
---
```

**Comment by cotes2020** [comment]
先学学 YAML 语法再来报告 “bug” 吧，不教而杀谓之虐，要知道你的 issuse 为什么会被我鄙视，请先学会怎么提问:
<https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way>

**Comment by handbye** [comment]
> 先学学 YAML 语法再来报告 “bug” 吧，不教而杀谓之虐，要知道你的 issuse 为什么会被我鄙视，请先学会怎么提问:
> https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way

谢谢，这就去学习

**Comment by cotes2020** [comment]
@handbye  我好像有点曲解你的意思了，这部分`tags: AntSword 蚁剑` 是想表达有两个 tag，用空格分开？

**Comment by handbye** [comment]
> @handbye 我好像有点曲解你的意思了，这部分`tags: AntSword 蚁剑` 是想表达有两个 tag，用空格分开？

是的，用空格分开代表两个tag

**Comment by cotes2020** [comment]
Jekyll 的`tags`原生支持这种奇葩的方式去声明YAML集合，但是标准的YAML语法下，这样相当于声明一个字符串，我的工具脚本也是按标准语法处理，所以会出现视图和实际生成页面有差异。

之前被你几个issues搞烦了，没细看你这条内容，抱歉了😂。文档我会加个备注这个区别。你在这个项目内就用标准语法来声明`tags`和`categories`吧，同一个单词之间支持空格分开，如标签`blue sky`是允许的

**Comment by handbye** [comment]
好的，我也把文章全部改为标准的YAMl语法的格式了。
