### ISSUE TITLE
links to non-existing external URLs in chirpy

### ISSUE THREAD

**Issue by ruzickap** [cotes2020/jekyll-theme-chirpy#758]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug

I'm using link checker [lychee](https://github.com/lycheeverse/lychee) to validate links on the page created by Jekyll + Chirpy.

Currently it seems like pages generated chirpy contains links to non-existing web pages like:

* <https://fonts.googleapis.com/>
* <https://www.googletagmanager.com/>
* <https://fonts.gstatic.com/>

### To Reproduce

```bash
❯ lychee  --no-progress https://chirpy.cotes.page/
✗ [400] https://www.googletagmanager.com/ | Failed: Network error: Bad Request
✗ [404] https://fonts.googleapis.com/ | Failed: Network error: Not Found
✗ [404] https://fonts.gstatic.com/ | Failed: Network error: Not Found
Issues found in 1 input. Find details below.

[https://chirpy.cotes.page/]:
✗ [404] https://fonts.gstatic.com/ | Failed: Network error: Not Found
✗ [400] https://www.googletagmanager.com/ | Failed: Network error: Bad Request
✗ [404] https://fonts.googleapis.com/ | Failed: Network error: Not Found

🔍 51 Total ✅ 48 OK 🚫 3 Errors (HTTP:3)
```

or

```bash
curl -s https://chirpy.cotes.page/ | grep -E '(https://fonts.googleapis.com|https://www.googletagmanager.com|https://fonts.gstatic.com)'

curl -s https://chirpy.cotes.page/ | less --pattern='https://fonts.googleapis.com|https://www.googletagmanager.com|https://fonts.gstatic.com/'
```

### Expected behavior

When running link checker against chirpy generated web page (like <https://chirpy.cotes.page/>) there should be no links to non-existing web pages (404).

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |         |
| `gem -v`                          |         |
| `bundle -v`                       |         |
| `bundle exec jekyll -v`           |         |
| `bundle info jekyll-theme-chirpy` |         |

> I used <https://chirpy.cotes.page> as the reference...

### Desktop

macOS latest
Chrome latest

### Smartphone

n/a

**Comment by cotes2020** [comment]
Hi @ruzickap, these links are used for [`preconnect`](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preconnect) and [`dns-prefetch`](https://developer.mozilla.org/en-US/docs/Web/Performance/dns-prefetch), so no 404 detection is required.

See also:

https://github.com/cotes2020/jekyll-theme-chirpy/blob/782a930fdf298739cd205de7708598ba96b3d276/_includes/head.html#L60-L63

https://github.com/cotes2020/jekyll-theme-chirpy/blob/782a930fdf298739cd205de7708598ba96b3d276/_includes/head.html#L78-L83

**Comment by ruzickap** [comment]
Ok...

Looks like it is common to just "ignore" it: https://github.com/filiph/linkcheck/issues/49

Another answer: https://generatepress.com/forums/topic/https-fonts-gstatic-com/

Maybe it be possible to use some "existing" URLs in this case:

* <https://fonts.googleapis.com/css2?family=Lato>
* <https://www.googletagmanager.com/gtag/js>

Anyway... 

I'm going to close it and configure the "link checker" to ignore these URLs.

Thank you

**Comment by cotes2020** [comment]
My understanding is that the values specified by `preconnect ` and `dns-prefetch` are usually domain names (not including the file path), and these domain names are used by the browser to communicate with the resource server at the _Transport Layer_(TCP), and the detection of 404 is performed at the _Application Layer_ (HTTP).

Checking the validity of HTTP resource links is already done with Html-Proofer, I'm not sure why you would use an additional test action like the [linkcheck](https://github.com/filiph/linkcheck/).
