### ISSUE TITLE
Pin posts to the top on the home page

### ISSUE THREAD

**Issue by MananSoni42** [cotes2020/jekyll-theme-chirpy#76]
I would like it if I could select some posts that new visitors see first on my home page (similar to the pinned repositories that GitHub has).  
Essentially, I would like to pin certain posts to the top of my home page.

**Solution**
* Introduce a new variable 'pin' in each post's front matter set it to false by default. To pin a particular post to the top of my home page, set that posts' pin variable to true. Multiple posts can be pinned to the top 
* The home layout loops through the list of posts twice - first listing all the pinned posts (if any) and then the regular posts
* Maybe add icons (like [this](https://fontawesome.com/icons/thumbtack?style=solid) one) to distinguish pinned posts from regular posts

**Comment by cotes2020** [comment]
> The home layout loops through the list of posts twice - first listing all the pinned posts (if any) and then the regular posts...

If simply looping twice can solve the problem, I will have implemented this function long time ago :). 

The difficulty in implementing **Pin** is to reorder the contents of the pagination. Jekyll pagination currently does not support the pin feature, so it is necessary to fictionally create a new list of posts for each pagination through an algorithm.

As you can see, I have put this feature in [Feature Pool](https://github.com/cotes2020/jekyll-theme-chirpy/projects/1#card-33076238) before, maybe I will implement it in a future version, but there is no guarantee that it will be completed.

**Comment by MananSoni42** [comment]
Bummer.
For now, I have disabled pagination on my page and reverse sorted all pages by the pin variable. That seems to be a somewhat hacky fix, but it works.
Another potential solution I found was to use jekyll-paginate-v2 / stickyposts ([1](https://github.com/sverrirs/jekyll-paginate-v2/pull/54), [2](https://github.com/ibrado/jekyll-stickyposts)) but these are not supported by GitHub pages yet :(
Hope this helps!

**Comment by cotes2020** [comment]
> Bummer.

Are you saying I'm a fool?

> For now, I have disabled pagination on my page and reverse sorted all pages by the pin variable.

If you have a lot of posts on your site, guess what happens? Without a doubt, the Home page will load slowly.

> Another potential solution I found was to use jekyll-paginate-v2 / stickyposts (1, 2) but these are not supported by GitHub pages yet :(

The first goal of this project is to ensure that it can run on GitHub Pages, which is why I wrote some scripting tools to replace some third-party Jekyll plugins here.

**Comment by MananSoni42** [comment]
I am sorry if my post offended you, I only meant it as:
"Not getting pinned posts to work is a bit of a bummer (disappointing)"
I could not imagine my site running without your awesome theme and am grateful for it.

**Comment by cotes2020** [comment]
There was a rough solution in my mind a long time ago (while keeping Jekyll paging), but needed more complicated liquid logic to implement, and I had to consider UI design. If you're expecting this new feature, please pay attention to the version update 🤘.

**Comment by MananSoni42** [comment]
Okay. I look forward to a version update.
Thanks for the quick response! :v:

**Comment by cotes2020** [comment]
Tonight, I have finished developing the function. Now I am designing the layout of the pinned post. I will release the code in a few days. Keep watching the commits :)
