### ISSUE TITLE
Long equations do not display completely in digital devices.

### ISSUE THREAD

**Issue by PoeticGenius** [cotes2020/jekyll-theme-chirpy#760]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [ ] I found the bug on the latest code of the `master` branch.

## Describe the bug

Long equations do not display completely in digital devices.

### To Reproduce

Just visit [my website](https://sherlcok314159.github.io/posts/Back-propagation/) to find out more.

### Expected behavior

Maybe we can scroll horizontally across the equation.

### Screenshots
![154252706258e43de7813e18d79d7af](https://user-images.githubusercontent.com/76043326/202850703-f73ce01a-c9f1-4dbd-9b96-82729dbac236.jpg)

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |      2.7.0   |
| `gem -v`                          |      3.1.2   |
| `bundle -v`                       |      2.1.2   |
| `bundle exec jekyll -v`           |      4.2.2   |
| `bundle info jekyll-theme-chirpy` |     5.2.1    |

### Smartphone

- OS: [HarmonyOS 2.0.0]
- Browser: [Quark]

**Comment by cotes2020** [comment]
It seems that you modified the CSS to cause this issue. In the original edition, the mathematical formula supports horizontal scrolling.

**Comment by PoeticGenius** [comment]
Thanks for your generous reply. It seems that this situation is not caused by customizing css because I just change my css to original and only use another font: `PlayFair`. The horizontal bar can show but can not be moved. Please dive in and provide a solution. 

Maybe you can try this formula in your theme and view it from phones:
```
$$
\frac{\partial E(\boldsymbol{w})}{\partial w_{kj}^{(2)}} = \frac{\partial E(\boldsymbol{w})}{\partial y_{k}} \frac{\partial y_k}{\partial w_{kj}^{(2)}} = (y_{k}- \hat{y}_k)z_{j} \tag{5.9}
$$
```
Any help is well appreciated!

**Comment by DylanDijk** [comment]
@PoeticGenius Was just wondering if you ended up managing to find a solution for this.

**Comment by cotes2020** [comment]
So @PoeticGenius I used the formula you provided to reproduce this issue and found that it was caused by the inline style generated by _MathJax_.
