### ISSUE TITLE
Recently Updated <- does not appear, but works well in local

### ISSUE THREAD

**Issue by hooneychoi** [cotes2020/jekyll-theme-chirpy#766]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

![image](https://user-images.githubusercontent.com/63895345/203807630-1140cad2-2c4e-4c52-b54d-db5dda70d372.png)
This area does not appear on my github.io page, but works fine when it's running on my local.
File name doesn't seem to be a problem.
I deleted my own posts and leave the original ones which came with the chirpy theme in '/_posts' .
Still same result. 

Which files should I take a look inside to find what's causing this problem?

**Comment by sbkv1** [comment]
delete the ```Gemfile.lock``` file and push to github.

**Comment by hooneychoi** [comment]
> delete the `Gemfile.lock` file and push to github.


I deleted that file and tried next command:


`bundle exec jekyll s`


and got this error message:


`Could not find gem 'tzinfo (~> 1.2)' in locally installed gems.
Run `bundle install` to install missing gems.`


So I couldn't run the website from my local.


What is the reason you told me to delete that file?

**Comment by sbkv1** [comment]
Recently Updated is not showing for forked repositories. Recently Updated is only working with [Chirpy Starter](https://github.com/cotes2020/chirpy-starter/generate).

**Comment by sbkv1** [comment]
@cotes2020 , @NichtsHsu can you help in this I am also facing the same issue for forked repository and [latest tag](https://github.com/cotes2020/jekyll-theme-chirpy/tags).
