### ISSUE TITLE
Where is the '--site-title-color' defined?

### ISSUE THREAD

**Issue by zuzhaoye** [cotes2020/jekyll-theme-chirpy#77]
Thank you for creating this wonderful jekyll theme. I am trying to tailor the colors of my site, for example, the color of the title, which I found is defined by var(--site-title-color). However, I can not locate this parameter in any of the css files. So, may I know where is it defined? Thx!

**Comment by cotes2020** [comment]
> the color of the title, which I found is defined by var(--site-title-color)...

I don't understand how you came to this judgment (maybe you visited another project). If you use **DevTool** of the browser, you will find the position of the title color definition in a few seconds. 
However, if you don't know how to use **DevTool**, it means that you don't understand web development, so please don't modify the CSS yourself.

**Comment by cotes2020** [comment]
> the color of the title, which I found is defined by var(--site-title-color)...

I don't understand how you came to this judgment (maybe you visited another project). If you use **DevTool** of the browser, you will find the position of the title color definition in a few seconds. 
However, if you don't know how to use **DevTool**, it means that you don't understand web development, so please don't modify the CSS yourself.
