### ISSUE TITLE
Is there a way to use Chirpy as remote theme

### ISSUE THREAD

**Issue by create3000** [cotes2020/jekyll-theme-chirpy#771]
## Checklist

- [ x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [ x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [ x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x ] My question is based on the latest code of the `master` branch.

## Description

Other themes like https://github.com/mmistakes/minimal-mistakes can be used as remote theme. 
In the _config.yml I would write: `remote_theme: "cotes2020/jekyll-theme-chirpy"`

* Is this possible with Chirpy?
* What to do?
* Can you do this?
* When will it possible?

**Comment by NichtsHsu** [comment]
Of course it can. But before that, I'd like to know the reason for using `remote_theme: cotes2020/jekyll-theme-chirpy` instead of `theme: jekyll-theme-chirpy`.

**Comment by create3000** [comment]
Because I can divide the theme itself from my site, and if you change or fix something I'll be up to date.

**Comment by NichtsHsu** [comment]
> Because I can divide the theme itself from my site, and if you change or fix something I'll be up to date.

So is `theme: jekyll-theme-chirpy`.

If anyone still wants to use `remote-theme`, please modify according to the following patch based on [chirpy-starter](https://github.com/cotes2020/chirpy-starter):

```diff
diff --git a/Gemfile b/Gemfile
index 2c06e0a..b8ad217 100644
--- a/Gemfile
+++ b/Gemfile
@@ -2,6 +2,7 @@
 
 source "https://rubygems.org"
 
+gem "jekyll-remote-theme"
 gem "jekyll-theme-chirpy", "~> 5.3", ">= 5.3.2"
 
 group :test do
diff --git a/_config.yml b/_config.yml
index f3a1229..dbfec95 100644
--- a/_config.yml
+++ b/_config.yml
@@ -1,7 +1,15 @@
 # The Site Configuration
 
+plugins:
+  - jekyll-remote-theme
+  - jekyll-paginate
+  - jekyll-redirect-from
+  - jekyll-seo-tag
+  - jekyll-archives
+  - jekyll-sitemap
+
 # Import the theme
-theme: jekyll-theme-chirpy
+remote_theme: cotes2020/jekyll-theme-chirpy
 
 # Change the following value to '/PROJECT_NAME' ONLY IF your site type is GitHub Pages Project sites
 # and doesn't have a custom domain.
```

**Comment by nemkin** [comment]
You have additional javascript assets that get built when you release your gem package:

https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/tools/release#L161

When I modified the chirpy starter, like in the comment above the Test site phase in the build github action returned these errors:

```
For the Scripts check, the following failures were found:

* At _site/chirpy-test/[40](https://github.com/nemkin/chirpy-test/actions/runs/6441087308/job/17490568355#step:6:41)4.html:1:
  internal script reference /chirpy-test/assets/js/dist/page.min.js does not exist
* At _site/chirpy-test/about/index.html:1:
  internal script reference /chirpy-test/assets/js/dist/page.min.js does not exist
* At _site/chirpy-test/archives/index.html:1:
  internal script reference /chirpy-test/assets/js/dist/misc.min.js does not exist
* At _site/chirpy-test/categories/index.html:1:
  internal script reference /chirpy-test/assets/js/dist/categories.min.js does not exist
* At _site/chirpy-test/categories/test/index.html:1:
  internal script reference /chirpy-test/assets/js/dist/misc.min.js does not exist
* At _site/chirpy-test/index.html:1:
  internal script reference /chirpy-test/assets/js/dist/home.min.js does not exist
* At _site/chirpy-test/posts/pelda-post/index.html:1:
  internal script reference /chirpy-test/assets/js/dist/post.min.js does not exist
* At _site/chirpy-test/tags/ezek/index.html:1:
  internal script reference /chirpy-test/assets/js/dist/misc.min.js does not exist
* At _site/chirpy-test/tags/index.html:1:
  internal script reference /chirpy-test/assets/js/dist/commons.min.js does not exist
* At _site/chirpy-test/tags/tagek/index.html:1:
  internal script reference /chirpy-test/assets/js/dist/misc.min.js does not exist
* At _site/chirpy-test/tags/teszt/index.html:1:
  internal script reference /chirpy-test/assets/js/dist/misc.min.js does not exist
```

I believe you can't use remote theme with chirpy, or you would need to fork the repository, build the javascript assets, commit them to your fork and set the fork's url as the remote theme.
