### ISSUE TITLE
Headings with numbers makes the TOC on the right panel fail to expand.

### ISSUE THREAD

**Issue by sirlis** [cotes2020/jekyll-theme-chirpy#774]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug

Adding numbers to each level of headings makes the TOC on the right fail to expand.

### To Reproduce

1. new a markdown file `111.md` and write contents with headings like:
   ```
   ## 1. A

   contents ....

   ## 2. B

   contents ....

   ### 2.1. BB
   
   contents ....

   ### 2.2. BBB
   
   contents ....

   ## 3. C
   ```
6. See error

The automatically generated TOC on the right panel won't expand to the 2nd level correctly.

### Expected behavior

The TOC expanded as expected.

### Screenshots

examples link: http://sirlis.cn/posts/reinforcement-learning-Monte-Carlo/

In fact, almost all posts of the blog cannot experience a auto-expanded TOC.

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `chrispy`                         |     latest    |

### Desktop

- OS: windows 11
- Browser: Edge latest version

**Comment by NichtsHsu** [comment]
See #572 and https://github.com/afeld/bootstrap-toc/issues/64

**Comment by sirlis** [comment]
> See #572 and [afeld/bootstrap-toc#64](https://github.com/afeld/bootstrap-toc/issues/64)

Thank you.
