### ISSUE TITLE
Option for lazy load of images

### ISSUE THREAD

**Issue by create3000** [cotes2020/jekyll-theme-chirpy#775]
## Checklist

- [x ] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x ] There is no similar request on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x ] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x ] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

Sometimes it is not needed that a page lazy loads the images.

## Describe the solution you'd like

It would be nice if there is an option per page to disable/enable lazy load of images.

**Comment by lab3** [comment]
Is there a recommended way to disable lazy loading without this?

**Comment by abuturabofficial** [comment]
> Is there a recommended way to disable lazy loading without this?

Did you find a way?
