### ISSUE TITLE
Getting error "github-pages 227 | Error:  The jekyll-theme-chirpy theme could not be found."

### ISSUE THREAD

**Issue by wadingthrulogs** [cotes2020/jekyll-theme-chirpy#789]
I've been able to get the theme to work locally on my ubuntu box, but once I push GitHub the "pages build and deployment" action fails and I get a miss theme error. 

/usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:84:in `rescue in gemspec': The jekyll-theme-chirpy theme could not be found. (Jekyll::Errors::MissingDependencyException)
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:81:in `gemspec'

I was hoping someone could help me with this. I've built some other pages but I've never had this error.

**Comment by NichtsHsu** [comment]
Try to remove the `Gemfile.lock` from your remote repo and add it to `.gitignore`.

**Comment by nheidloff** [comment]
I had the same issue. Why does this happen?

**Comment by daofeih** [comment]
The solution is setting the build and deployment method as [GitHub Actions](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow).

https://chirpy.cotes.page/posts/getting-started/#deploy-by-using-github-actions
