### ISSUE TITLE
URL Chirpy Starter

### ISSUE THREAD

**Issue by erwinkersten** [cotes2020/jekyll-theme-chirpy#791]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug

[Chirpy Starter](https://github.com/cotes2020/chirpy-starter/generate) is not found (404)

### To Reproduce

1. Go to [Chirpy Starter](https://github.com/cotes2020/chirpy-starter/generate)
2. Results in 404

### Expected behavior

Chirpy Starter is avilable at the link https://github.com/cotes2020/chirpy-starter/generate

### Screenshots

N/A

### Environment

N/A

### Desktop

N/A

### Smartphone

N/A

### Additional context

N/A

**Comment by cotes2020** [comment]
I believe GitHub has prompted you to log in to your account.
