### ISSUE TITLE
Adding custom head on all pages

### ISSUE THREAD

**Issue by awt-tom** [cotes2020/jekyll-theme-chirpy#795]
## Checklist

- [X ] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [X ] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [X ] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [X ] My question is based on the latest code of the `master` branch.

## Description

Hi there, 

I have been looking on multiple places to see if I can resolve this myself. 

From what I understand the website which gets generated picks some files from the Chirpy static assets git to build the pages. 

I want to add a script into the head of each page being created. I tried doing this with the assets, but ofcourse this is not going to be pickedup while building the files. Could anyone point me into a direction on how I could add this to each head of a page? 

<script async defer data-website-id="randomID" src="Serverwhichhoststhejs"></script>

Thanks in advance for the effort.

**Comment by cotes2020** [comment]
The `<head>` is defined in [_includes/head.html](https://github.com/cotes2020/jekyll-theme-chirpy/blob/ec98f07aca0b80a9c07fbcdc8e0d7d66dba98ed2/_includes/head.html), where you can apply the JS to site-wide pages.

**Comment by awt-tom** [comment]
Downloading the  _includes and edit the head resolved my question. I was not aware that I could just download the folder without defining it somewhere. 

Thanks Cotes for the support. Much appriciated!
