### ISSUE TITLE
HTML entity "&ldquo;" "&rdquo;" displayed literally on excerpt home page

### ISSUE THREAD

**Issue by sati-bodhi** [cotes2020/jekyll-theme-chirpy#799]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug

HTML entities "&ldquo;" "&rdquo;" are displayed as literals on the  home page as excerpts, though they display correctly in the post itself. 

### To Reproduce

1. Put the following text in a file named `test.md` and save in the `_posts` folder.
```
<p>
&ldquo;These quote entities are displayed literally!&rdquo;
</p>
```
2. `jekyll serve`

### Expected behavior

Entities should be displayed properly. 

### Screenshots

![Screenshot from 2022-12-15 13-08-52](https://user-images.githubusercontent.com/7592695/207777472-44976540-8969-4bf3-845a-a7a5d13834c6.png)

![Screenshot from 2022-12-15 13-10-22](https://user-images.githubusercontent.com/7592695/207777634-af0a9a61-32a2-46d1-b068-de5c75af98bf.png)

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]|
| `gem -v`                          |3.1.4 |
| `bundle -v`                       |Bundler version 2.3.16 |
| `bundle exec jekyll -v`           |jekyll 4.2.2|
| `bundle info jekyll-theme-chirpy` |jekyll-theme-chirpy (5.2.0)|

### Desktop

- OS: Ubuntu 22.04
- Browser: Firefox 108.0 (64-bit)

**Comment by NichtsHsu** [comment]
> Put the following text in a file named `test.html` and save in the `_posts` folder.

Chirpy theme mainly handles markdown files for your posts instead of HTML files.

**Comment by sati-bodhi** [comment]
> > Put the following text in a file named `test.html` and save in the `_posts` folder.
> 
> Chirpy theme mainly handles markdown files for your posts instead of HTML files.

Same issue with `test.md` instead of `html`. 

We are supposed to be able to use [literal `html` code within Markdown](https://daringfireball.net/projects/markdown/syntax#html) itself:

>For any markup that is not covered by Markdown’s syntax, you simply use HTML itself. There’s no need to preface it or delimit it to indicate that you’re switching from Markdown to HTML; you just use the tags.

**Comment by NichtsHsu** [comment]
It was because this commit: 415f11ecb8d53ce4eb7b623fa12235bdd8c81e61

Please revert this commit carefully if you really need this feature. I'm not sure if this will cause html-proofer issues.

**Comment by sati-bodhi** [comment]
Can there be a patch to make it work?

**Comment by NichtsHsu** [comment]
If you forked the `jekyll-theme-chirpy`, just execute `git revert 415f11ecb8d53ce4eb7b623fa12235bdd8c81e61`. Otherwise, download `_includes/related-posts.html` and `_layouts/home.html` to your repo then modify them manually.

**Comment by sati-bodhi** [comment]
I installed `chirpy` as a gem.
