### ISSUE TITLE
Firefox Archive page alignment issue.

### ISSUE THREAD

**Issue by techslam** [cotes2020/jekyll-theme-chirpy#8]
Hi ,

One more bug specific to Firefox browser can be seen in the archive page. Attaching a screenshot here where you can see the dates are not aligned when the ate part is 2 digits.

![firefox-archive-page-issue](https://user-images.githubusercontent.com/166223/66722443-83809500-ee05-11e9-9ca1-a186ab7b15b6.png)

**Comment by cotes2020** [comment]
It was fixed at 8a7353631cbc2f939e63ff7fbec1087f91730c94, and the sidebar compatibility mentioned in #7 was also resolved.

**Comment by techslam** [comment]
Thanks Cotes. 
As a newbie to Github , I must ask, How do i incorporate this change into my website ?

**Comment by cotes2020** [comment]
You should learn basic knowledge of **Git** first and then refer to the tutorial:

<https://stefanbauer.me/articles/how-to-keep-your-git-fork-up-to-date>
