### ISSUE TITLE
Recently Updated <- does not show the last post.

### ISSUE THREAD

**Issue by hooneychoi** [cotes2020/jekyll-theme-chirpy#800]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug

I added new posts and it won't show in the "Recently Updated".
Only the posts which were uploaded before the version 5.3.2 are showing in the "Recently Updated".
I assume it has to to with https://github.com/cotes2020/jekyll-theme-chirpy/issues/766 

### To Reproduce

1. add a new post

### Expected behavior

"Recently Updated" shows the title of recently updated posts.

### Screenshots

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/63895345/207870166-bb0c2757-2950-4c1c-88dc-e70450351f07.png">

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin22]|
| `gem -v`                          |3.3.7|
| `bundle -v`                       |Bundler version 2.3.25|
| `bundle exec jekyll -v`           |jekyll 4.3.1|
| `bundle info jekyll-theme-chirpy` |5.3.2|

**Comment by NichtsHsu** [comment]
New posts always appear at the front of the home page, so it's pointless to have them appear again in the "Recently Updated".

**Comment by hooneychoi** [comment]
> New posts always appear at the front of the home page, so it's pointless to have them appear again in the "Recently Updated".

Yes I think you are right.
I understand very well and will close the issue.
Thank you!
