### ISSUE TITLE
If anyone know how to set device specific cover image

### ISSUE THREAD

**Issue by Nexus-Gits** [cotes2020/jekyll-theme-chirpy#801]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description
If anyone know how to set device specific cover image. Mean that under specific device width the cover thumbnail image dont show. It good for Reduce the Lcp score in mobile devices.
If anyone know the trick let me know. I need the solution please.

**Comment by NichtsHsu** [comment]
Hi @Nexus-Gits 

You are looking for [CSS @media Rule](https://www.w3schools.com/cssref/css3_pr_mediaquery.php).

It maybe looks like:

```css
@media screen and (max-width: 1200px) {
  img.dev-spec {
    display: none;
  }
} 
```
