### ISSUE TITLE
How to tag mathjax equation on the right?

### ISSUE THREAD

**Issue by jhss** [cotes2020/jekyll-theme-chirpy#809]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

I added the below line in the post. with '$$'

\min _Q\|Q(r)-r\|^2 \tag{4}

I want to tag the equation number on the right, but it appear in the left as belows.

![1](https://user-images.githubusercontent.com/8586144/209462199-136206ae-d616-47fe-8e37-4ecbcd67079b.PNG)

**Comment by DylanDijk** [comment]
I have a problem related to this.  When adding equation tags or labels the scrolling feature, that appears when opening the web page on your phone, no longer appears.
