### ISSUE TITLE
I cannot create a new site by following the tutorial.

### ISSUE THREAD

**Issue by haliliceylan** [cotes2020/jekyll-theme-chirpy#811]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug

I cannot create a new site by following the tutorial.

### To Reproduce

1. Go to 'https://github.com/cotes2020/chirpy-starter/generate'
2. Click on 'Create Repository'

### Expected behavior

new website

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |         |
| `gem -v`                          |         |
| `bundle -v`                       |         |
| `bundle exec jekyll -v`           |         |
| `bundle info jekyll-theme-chirpy` |         |

**Comment by haliliceylan** [comment]
if you follow tutorial and create lock file you faced this error (this issue closed by github bot so i am referring directly, i use github workspaces and faced same problem).
see: #802

**Comment by NichtsHsu** [comment]
Hi @haliliceylan ,

It looks like something broke from Ruby 3.1.3 to Ruby 3.2 causing the failure. Try to limit the Ruby version to 3.1 may fix your problem.

```diff
diff --git a/.github/workflows/pages-deploy.yml b/.github/workflows/pages-deploy.yml
index b2da8d9..00380f6 100644
--- a/.github/workflows/pages-deploy.yml
+++ b/.github/workflows/pages-deploy.yml
@@ -42,7 +42,7 @@ jobs:
       - name: Setup Ruby
         uses: ruby/setup-ruby@v1
         with:
-          ruby-version: 3 # reads from a '.ruby-version' or '.tools-version' file if 'ruby-version' is omitted
+          ruby-version: 3.1 # reads from a '.ruby-version' or '.tools-version' file if 'ruby-version' is omitted
           bundler-cache: true
 
       - name: Build site
```

**Comment by haliliceylan** [comment]
Thanks ! I will try asap

**Comment by haliliceylan** [comment]
it worked perfectly, thank you !

**Comment by sunnamed434** [comment]
I had the same problem, thanks for the help!

**Comment by sunnamed434** [comment]
Idk but the workflow seems to be dead for me, changing the version didn't help.... #818
