### ISSUE TITLE
"failed with exit code 5" occured when building

### ISSUE THREAD

**Issue by hooneychoi** [cotes2020/jekyll-theme-chirpy#812]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

How to solve the error:
`nokogiri-1.13.10-x86_64-linux requires ruby version < 3.2.dev, >= 2.6, which is incompatible with the current version, 3.2.0`

It's been happening ever since the new verison of ruby is installed by the process:
![image](https://user-images.githubusercontent.com/63895345/209554133-c7b18191-6c8c-42cd-ae13-a9d22fc10f67.png)

Below is the last successful build looks like:
![image](https://user-images.githubusercontent.com/63895345/209554533-b631c4d6-d73b-4d82-b358-780650d4a8e5.png)

**Comment by NichtsHsu** [comment]
Could you try to limit the Ruby version to 3.1?

```diff
diff --git a/.github/workflows/pages-deploy.yml b/.github/workflows/pages-deploy.yml
index b2da8d9..00380f6 100644
--- a/.github/workflows/pages-deploy.yml
+++ b/.github/workflows/pages-deploy.yml
@@ -42,7 +42,7 @@ jobs:
       - name: Setup Ruby
         uses: ruby/setup-ruby@v1
         with:
-          ruby-version: 3 # reads from a '.ruby-version' or '.tools-version' file if 'ruby-version' is omitted
+          ruby-version: 3.1 # reads from a '.ruby-version' or '.tools-version' file if 'ruby-version' is omitted
           bundler-cache: true
 
       - name: Build site
```

**Comment by hooneychoi** [comment]
> Could you try to limit the Ruby version to 3.1?
> 
> ```diff
> diff --git a/.github/workflows/pages-deploy.yml b/.github/workflows/pages-deploy.yml
> index b2da8d9..00380f6 100644
> --- a/.github/workflows/pages-deploy.yml
> +++ b/.github/workflows/pages-deploy.yml
> @@ -42,7 +42,7 @@ jobs:
>        - name: Setup Ruby
>          uses: ruby/setup-ruby@v1
>          with:
> -          ruby-version: 3 # reads from a '.ruby-version' or '.tools-version' file if 'ruby-version' is omitted
> +          ruby-version: 3.1 # reads from a '.ruby-version' or '.tools-version' file if 'ruby-version' is omitted
>            bundler-cache: true
>  
>        - name: Build site
> ```

It worked! Thank you for your quick response.
I'll close the issue. Thanks agian!
