### ISSUE TITLE
error :  Liquid Exception: undefined method `tainted?' for

### ISSUE THREAD

**Issue by jjuseok** [cotes2020/jekyll-theme-chirpy#816]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description
The following error occurs in the GitHub build:

/home/runner/work/jjuseok.github.io/jjuseok.github.io/vendor/bundle/ruby/3.2.0/gems/liquid-4.0.3/lib/liquid/variable.rb:124:in `taint_check': undefined method `tainted?'(NoMethodError)
return unless obj.tainted?

**Comment by NichtsHsu** [comment]
> There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).

Really?

https://github.com/cotes2020/jekyll-theme-chirpy/issues/811#issuecomment-1364902702
https://github.com/cotes2020/jekyll-theme-chirpy/issues/812#issuecomment-1365208215
