### ISSUE TITLE
Error: The process '/opt/hostedtoolcache/Ruby/3.2.0/x64/bin/bundle' failed with exit code 5 

### ISSUE THREAD

**Issue by myHobbyBest** [cotes2020/jekyll-theme-chirpy#818]
## Checklist

- [x ] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [ x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x ] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x ] My question is based on the latest code of the `master` branch.

## Description

i'm having trouble for uploading my post.md  as follows.
pls  help!!!
![20221227_153332](https://user-images.githubusercontent.com/117243771/209623565-a8ed5ba7-5b73-43af-9add-353256cf2c26.png)

![20221227_153619](https://user-images.githubusercontent.com/117243771/209623585-6e90c256-b1a8-4fb0-9fd4-be5bd48a70c3.png)

**Comment by NameGoesLong** [comment]
It seems like there are some dependency issue that would restrict the application to have ruby version <3.2. The temporary fix would be set the **ruby version** to **3.1** in **pages-deployment.yml**. Check the following issue for more detail: https://github.com/cotes2020/jekyll-theme-chirpy/issues/811#issuecomment-1364902702

For the **maintainer** of the project, the following screen shot should provide more detail about the issue:
<img width="583" alt="Screen Shot 2022-12-26 at 11 43 05 pm" src="https://user-images.githubusercontent.com/39787774/209630455-eadaac13-4828-4726-90a9-3f7348c48567.png">

**Comment by myHobbyBest** [comment]
i'm trying  to limit the Ruby version to 3.1 as follows .
![20221227_172127](https://user-images.githubusercontent.com/117243771/209637114-0c016c00-a66b-4a62-9c72-24ef9a600a89.png)



 It worked , thank you !

**Comment by sunnamed434** [comment]
I'm having the same issue and changing the version to 3.1 doesn't save me, here's my [workflow](https://github.com/sunnamed434/sunnamed434.github.io/actions/runs/3801945887/jobs/6466942555)

#811

**Comment by myHobbyBest** [comment]
If you have CODE 16 error,  
 1.Run bundle lock --add-platform x86_64-linux on your local copy of the repository.
 2.Add the modified gemlock to your repo and commit.
 
 I'd had same trouble but it was solved by that task.
 
pls, read [here](https://github.com/cotes2020/jekyll-theme-chirpy/issues/721)

**Comment by sunnamed434** [comment]
Thanks for the help, I got working it with: `bundle` helped me to solve the issue
