### ISSUE TITLE
how writing a new page ? not post ?

### ISSUE THREAD

**Issue by kerwinxu** [cotes2020/jekyll-theme-chirpy#823]
## Checklist

- [ ] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [ ] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [ ] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [ ] My question is based on the latest code of the `master` branch.

**Comment by MichaelTan9999** [comment]
You may consider adding a markdown file in \tabs to simply have a page.

**Comment by kerwinxu** [comment]
> You may consider adding a markdown file in \tabs to simply have a page.

Thank you for your reply .

3 steps:

1.  adding a markdown file in \tabs to simply have a page.
2. cd _data\locales , and edit some of files .
3. add new line below this 
`# The tabs of sidebar
tabs:
  # format: <filename_without_extension>: <value>`
