### ISSUE TITLE
Modify robots.txt

### ISSUE THREAD

**Issue by eldiep** [cotes2020/jekyll-theme-chirpy#824]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

Hey,

I'm new to jekyll and hope it's really a problem with chirpy and not a jekyll-problem:

I want to disallow some pages of my site in robots.txt. But I don't know where to modify/edit this. When I change it in my _site-folder, it is overwritten with every build. So where can I modify it, so it isn't overwritten with every build?

**Comment by NichtsHsu** [comment]
assets/robots.txt

**Comment by eldiep** [comment]
> assets/robots.txt

That only puts it in my assets-folder. But i need it in my _site-root
