### ISSUE TITLE
Support dark and light mode images

### ISSUE THREAD

**Issue by ruzickap** [cotes2020/jekyll-theme-chirpy#837]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

### To Reproduce

I'm using picture at the top of the post in the markdown file:

```text
---
title: ...
...
image:
  path: https://raw.githubusercontent.com/aws-samples/eks-workshop/65b766c494a5b4f5420b2912d8373c4957163541/static/images/icon-aws-amazon-eks.svg
  width: 200
---

My text...
```

The `5.4.0` version of chirpy brings new feature #481 which is now displaying the svg images differently:

<img width="979" alt="image" src="https://user-images.githubusercontent.com/1434387/210308974-c4678b70-f6ad-4dcb-a595-a8410ab9919b.png">

The "old way" (version `5.3.2` and lower):

<img width="979" alt="image" src="https://user-images.githubusercontent.com/1434387/210308920-57a6930e-4204-4672-933c-87735268598e.png">

Examples (will be removed soon):
- <https://ruzickap.github.io/posts/cheapest-amazon-eks/>
- <https://ruzickap-github-io.pages.dev/posts/cheapest-amazon-eks/>

Is there a chance to configure chirpy to use the old way of displaying the images?

Can I change the way how the "header images" are displayed (https://chirpy.cotes.page/posts/write-a-new-post/#darklight-mode)?

Thank you....

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |         |
| `gem -v`                          |         |
| `bundle -v`                       |         |
| `bundle exec jekyll -v`           |         |
| `bundle info jekyll-theme-chirpy` |         |

**Comment by cotes2020** [comment]
What you describe is about the preview image, not dark/light mode.

For details, see: <https://chirpy.cotes.page/posts/write-a-new-post/#preview-image>

**Comment by ruzickap** [comment]
You are right - the issue is with the [Preview Image](https://chirpy.cotes.page/posts/write-a-new-post/#preview-image).

The way how it was "rendered/displayed" in version `5.3.x` changed in `5.4.0` - as you can see on the screenshots above.

The Preview Image svg image rendering in `5.4.0` is somehow "[broken](https://user-images.githubusercontent.com/1434387/210308974-c4678b70-f6ad-4dcb-a595-a8410ab9919b.png)".

Is there a way how to display Preview Image ([svg](https://raw.githubusercontent.com/aws-samples/eks-workshop/65b766c494a5b4f5420b2912d8373c4957163541/static/images/icon-aws-amazon-eks.svg)) in latest version of theme-chirpy [properly](https://user-images.githubusercontent.com/1434387/210308920-57a6930e-4204-4672-933c-87735268598e.png) (like it was in `5.3.x`)?

Thank you...

**Comment by joshjohanning** [comment]
Did you resolve @ruzickap? I [made a change in my copy](https://github.com/joshjohanning/joshjohanning.github.io/compare/b282712087028da95e292e3159d20cdf63d59feb..73a8a7623f9393cc3d71898ce14c317fbf075564) to strip some of the new preview image functionality in `5.4.0`, unsure or not if helpful for your SVG image issue. 

I came here looking to see if there was a way to do light mode / dark mode preview images 😄

**Comment by ruzickap** [comment]
Thank you Josh. 
I'm going to open issue for the svg images support, because the description above is misleading.
