### ISSUE TITLE
The prompts display incorrectly

### ISSUE THREAD

**Issue by LUKEDUDE97** [cotes2020/jekyll-theme-chirpy#838]
## Checklist

- [X] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [X] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [X] I found the bug on the latest code of the `master` branch.

### To Reproduce

```markdown
> TypeError: `run()` arguement after * must be an iterable, not int
{: .prompt-danger}

> ValueError: not enough values to unpack (expected *, got 1)
{: .prompt-warning}
```

After i updated the jekyll-theme-chirpy to 5.4.0, this happened. Not sure why...

### Screenshots

![image](https://user-images.githubusercontent.com/115708755/210375857-14de723c-70aa-4ff9-947c-067cbfc73f96.png)

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |     3.1.2p20    |
| `gem -v`                          |     3.3.7    |
| `bundle -v`                       |     2.3.24    |
| `bundle exec jekyll -v`           |    4.3.1     |
| `bundle info jekyll-theme-chirpy` |    5.4.0     |

**Comment by NichtsHsu** [comment]
Can you share the link of your web page where you are getting issue?

**Comment by LUKEDUDE97** [comment]
> Can you share the link of your web page where you are getting issue?

https://lukedude97.github.io/posts/plot-digitizer-produce-random-synthetic-images/

**Comment by NichtsHsu** [comment]
I think you may have only updated jekyll-theme-chirpy to 5.4.0 without getting the update for chirpy-starter.

In you web page:
```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.11.2/css/all.min.css">
```

In cotes' live demo:
```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/all.min.css">
```

The new prompt icons must depend on fontawesome 6.x.

The simplest solution is copy the contents of the file [`_data/assets/cross_origin.yml`](https://github.com/cotes2020/chirpy-starter/blob/main/_data/assets/cross_origin.yml) and overwrite your own. But I recommend you sync with the whole chirpy-starter not just this file.

**Comment by LUKEDUDE97** [comment]
It works! Thank you! I forgot to upgrade those files.
