### ISSUE TITLE
Support for a GDPR compliant analytics service solution

### ISSUE THREAD

**Issue by anilbey** [cotes2020/jekyll-theme-chirpy#842]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There is no similar request on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

Hi, I wanted to setup an analytics service. I found this blog post on how to set Google Page View.
https://chirpy.cotes.page/posts/enable-google-pv/

This solution however requires the use of Google Analytics, which comes with the following terms and conditions on privacy.
I don't think jekyll or jekyll-theme-chirpy are complying with this policy by default. There is no cookie consent banner on the template. Nor there is a disclosure on the data collection and processing.

> You must post a Privacy Policy and that Privacy Policy must provide notice of Your use of cookies, identifiers for mobile devices (e.g., Android Advertising Identifier or Advertising Identifier for iOS) or similar technology used to collect data. You must disclose the use of Google Analytics, and how it collects and processes data. This can be done by displaying a prominent link to the site “How Google uses data when you use our partners' sites or apps”, (located at [www.google.com/policies/privacy/partners/](https://www.google.com/policies/privacy/partners/), or any other URL that Google may provide from time to time). You will use commercially reasonable efforts to ensure that a User is provided with clear and comprehensive information about, and consents to, the storing and accessing of cookies or other information on the User’s device where such activity occurs in connection with the Service and where providing such information and obtaining such consent is required by law.
 
More info from [another source](https://www.termsfeed.com/blog/privacy-policy-google-analytics/). 

> Google Analytics stores [cookies](https://www.termsfeed.com/blog/cookies/) on your users' PCs to keep track of usage data. This is enough to evoke the requirement of a Privacy Policy according to the [EU Cookies Directive](https://termsfeed.com/blog/eu-cookies-directive/). The EU's [GDPR](https://termsfeed.com/blog/gdpr/) also requires a Privacy Policy when usage data is collected, such as through cookies.

This is the problem I have. I wish to use an analytics service while remaining compliant to their privacy terms :)

## Describe the solution you'd like

I would really like to be able to use a GDPR compliant analytics service. [This PostHog tool](https://posthog.com/) seems like a good alternative. With that (or with another GPDR compliant tool ([here is a list of 13 tools](https://posthog.com/blog/best-gdpr-compliant-analytics-tools))) there will be no need to integrate a cookie banner.

A blog post on how to configure the jekyll-theme-chirpy with one of these tools would be fantastic :rocket: 

## Describe alternatives you've considered

* If Google Analytics is to be used, then the cookie banner as well as the disclosure need be integrated in the template.
* Very basic but still can display views for each page: https://countapi.xyz/

**Comment by cotes2020** [comment]
Duplicate of #265

**Comment by anilbey** [comment]
Actually there's this quick solution by using `countapi.xyz` @cotes2020 what do you think about it?

Here's how it's implemented in another template
https://github.com/zivhub/monophase/pull/3

**Comment by gonzoknows** [comment]
From looking through alternatives on this list https://alternativeto.net/software/google-analytics/

I've found two https://www.goatcounter.com/ and https://counter.dev/ seem to be free to use for personal sites which would be nice as a google analytics alternative
