### ISSUE TITLE
Markdown post table overflowing

### ISSUE THREAD

**Issue by ArihantB** [cotes2020/jekyll-theme-chirpy#85]
The table in the post content is overflowing and is not limited to the post content width.

![image](https://user-images.githubusercontent.com/16287025/85544096-504f0080-b638-11ea-897f-2fe03b66938c.png)

In the above image, the red line shows the post content width.

I tried testing by adding `overflow: auto;` in each block (wherever found necessary) in main.scss file, but when I checked in the developer options of the browser,  it seems that there is a file called _reboot.scss that overrides the table properties.
When I modified _reboot.scss in browser, it worked, but I was unable to locate the file.

Can you please update this bug?

**Comment by cotes2020** [comment]
It’s fixed, thanks for the report :)

In addition, please do not delete the issue template when you open an issue next time, otherwise your question may be ignored.

**Comment by ArihantB** [comment]
Couple of more things to point out:

1. When using non-squared avatar images, it gets flatten, hence, you can add the following lines to main.css inside `img` tag at line #249:
```
object-fit: cover;
object-position: center;
```
This will fix the image to be perfectly cropped

2. Can you add some space (some margin top and bottom) between the adjacent tables?

![image](https://user-images.githubusercontent.com/16287025/85558824-bf335600-b646-11ea-99df-aab5fa028637.png)

Those red arrows point to congested area.

**Comment by cotes2020** [comment]
> The above solution didn't work for me.

Please post your Markdown table test code to prove it. (The first thing to do when you submit a bug report is to provide test code, right ?)

> Can you add some space (some margin top and bottom) between the adjacent tables

Unless you're creating tables in HTML instead of markdown language,  this is invalid.

**Comment by ArihantB** [comment]
Thanks for comment, it clicked my mind that I hadn't checked my Markdown code... The bug was inside my Markdown code itself and I was able to resolve it. Everything is fixed now.

**Comment by ArihantB** [comment]
One more thing you can add is smooth scrolling when navigating between sections in TOC. Current scrolling behavior is 'auto' and is not so good looking.

You can achieve this by adding `scoll-behavior: smooth;` in main.scss file under the root / html tag.
