### ISSUE TITLE
How to debug GitHub Actions and '--- layout: home # Index page ---' Issues?

### ISSUE THREAD

**Issue by nheidloff** [cotes2020/jekyll-theme-chirpy#853]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

First of all: This is a really great repo! Thanks a lot for sharing this. It comes very close to what I'm looking for to host my own blog.

I've used the theme and the starter and can both deploy successfully via GitHub Actions (I only had to put the lock file in the gitignore and make sure I have only one repo using actions in my account).

Next I added customizations which work great locally. But when I pushed them, the GitHub Actions failed. The logs didn't show anything meaningful. I had to painfully trial and error to find the issues.

Similarly I cannot even push my posts and have no idea what is causing this.

Is there a way to better 'debug' the actions to figure out what is causing the '--- layout: home # Index page ---' issues? Is there a way to run all of this locally, something like GitHub Actions and the GitHub Pages runtime in containers so that I have the exact same env locally and don't have to figure out deltas?

Thanks!
Niklas

**Comment by nheidloff** [comment]
```
bundle exec htmlproofer _site --disable-external --check-html --allow_hash_href
```

**Comment by muhdavi** [comment]
Hi @nheidloff, how to solve this issue? my site muhdavi.github.io is get same error.

**Comment by Printeger** [comment]
> Hi @nheidloff, how to solve this issue? my site muhdavi.github.io is get same error.

hi muhdavi, im having same error now. notice that your blog is working now. could you plz tell me how you solve this error?
thanks a lot

**Comment by muhdavi** [comment]
@Printeger i delete my repository and i fork again. that work for me.

**Comment by Printeger** [comment]
> @Printeger i delete my repository and i fork again. that work for me.

@muhdavi thanks, i will try it : )

**Comment by Printeger** [comment]
> @Printeger i delete my repository and i fork again. that work for me.

@muhdavi it worked. seems use github Action to auto push update to /gh-pages branch could avoid this problem. 

1)modify /.github/workflows/pages-deploy.yml to enable github action
```
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Setup deploy options
      id: setup
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        if [[ ${GITHUB_REF} = refs/pull/*/merge ]]; then # pull request
          echo "SRC_BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT
          echo "NO_PUSH=--no-push" >> $GITHUB_OUTPUT
        elif [[ ${GITHUB_REF} = refs/heads/* ]]; then # branch, e.g. master, source etc
          echo "SRC_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        fi
        echo "DEPLOY_BRANCH=gh-pages" >> $GITHUB_OUTPUT
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
```
2)give read and write permission to action at YourRepository/settings/actions/general/Workflow permissions

3)select branch to none at YourRepository/settings/Page/Build and deployment/Branch

4)change something and push to main branch, let github action auto generate gh-pages branch. then select it at YourRepository/settings/Page/Build and deployment/Branch

**Comment by srcrapi** [comment]
> @Printeger i delete my repository and i fork again. that work for me.

it works thanks a lot

**Comment by waterlovemelon** [comment]
If you create a new branch, maybe you can try to add the branch name to `on/push/branches`  in .github/workflows/pages-deploy.yml, it works for me :(
