### ISSUE TITLE
Add Support to 3.2

### ISSUE THREAD

**Issue by i4pg** [cotes2020/jekyll-theme-chirpy#854]
# Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There is no similar request on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

I am unable to install the Jekyll theme gem because it requires a version of Ruby that is not compatible with my current version (3.2). This error message appears when I run bundle install: "Your Ruby version is 3.2, but your Gemfile specified 2.5.x - 3.1.x"

## Describe the solution you'd like

I would like to request that the Jekyll theme gem be updated to support Ruby version 3.2. This can be done by updating the dependencies and making any necessary changes to the codebase to ensure compatibility with the latest version of Ruby.

## Describe alternatives you've considered

- Installing an older version of Ruby
- Using a different Jekyll theme gem that supports Ruby 3.2

## Additional context

I understand that updating a gem to support a new version of Ruby can be a significant undertaking, but I believe it would be beneficial for the gem and its users to have support for the latest version of the language. If there are any specific concerns or questions, please let me know and I'll be happy to provide more information.

**Comment by cotes2020** [comment]
Hi @i4pg, just look at the commit history to see why `v5.4.0` banned Ruby 3.2. I'm not going to explain the same question twice :)
