### ISSUE TITLE
How to point a tab to a subdomain and in a new tab?

### ISSUE THREAD

**Issue by Aptura** [cotes2020/jekyll-theme-chirpy#855]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

Hello, I've come to bother you again, hoping to have done enough research beforehand.

I have added a page named DRAW under HOME, I would like to make it point to a subdomain and in a new tab but after trying several different things I can't manage to do it.

![image](https://user-images.githubusercontent.com/31808221/212480063-aae508fe-50f7-45e8-a529-d491677a9e3c.png)

I tried different tags in my _tabs/draw.md but nothing worked, I think I'm not looking at the problem from the right angle and I'm missing some information.

**Is it easier to integrate the desired html rather than redirecting to a subdomain?**
**Should I link the DRAW directly with a page in html instead of md?**

Thanks in advance!

**Comment by NichtsHsu** [comment]
Following codes make your tabs point to another page under the same domain.

https://github.com/cotes2020/jekyll-theme-chirpy/blob/41ed33145639415148aec8e85edc7a6fd0de0ca3/_includes/sidebar.html#L41-L50

Here is my suggestion:

```html
  <!-- Add your new tab here without creating a *.md file -->
  <li class="nav-item">
    <a href="/your/subdomain/url" class "nav-link">
      <i class="fa-fw your-icon ml-xl-3 mr-xl-3 unloaded"></i> 
      <span>your_tab_name</span>
    </a>
  </li>

 <!-- Keep original codes -->
 {% for tab in site.tabs %} 
 <li class="nav-item{% if tab.url == page.url %}{{ " active" }}{% endif %}"> 
   <a href="{{ tab.url | relative_url }}" class="nav-link"> 
     <i class="fa-fw {{ tab.icon }} ml-xl-3 mr-xl-3 unloaded"></i> 
     {% capture tab_name %}{{ tab.url | split: '/' }}{% endcapture %} 
  
     <span>{{ site.data.locales[site.lang].tabs.[tab_name] | default: tab.title | upcase }}</span> 
   </a> 
 </li> <!-- .nav-item --> 
 {% endfor %} 
```

Also change `$tab-count` to `{{ site.tabs | size | plus: 2 }}` here.

https://github.com/cotes2020/jekyll-theme-chirpy/blob/41ed33145639415148aec8e85edc7a6fd0de0ca3/assets/css/style.scss#L8

**Comment by Aptura** [comment]
Thanks for your answer @NichtsHsu , I understand the idea, however I use the starter and I don't have a `_includes/sidebar.html` folder.
So should I include the files in the root of my repository?

**Comment by NichtsHsu** [comment]
> So should I include the files in the root of my repository?

Yes, according to the jekyll doc [overriding theme defaults](https://jekyllrb.com/docs/themes/#overriding-theme-defaults), you can cover theme's files by creating your own under the same directory.

**Comment by Aptura** [comment]
It's great, thank you @NichtsHsu ! 
Sorry I'm in the middle of discovering and learning all this!

**Comment by ser-mk** [comment]
I would suggest the easy way with redirect

https://github.com/ser-mk/ser-mk.github.io/commit/a14a03c0aa6582d96ca0bb5df5af84b3a8a36933

just define redirect layout and then set redirect link
