### ISSUE TITLE
Showing sub-headings when hovering over main headings in TOC

### ISSUE THREAD

**Issue by ArihantB** [cotes2020/jekyll-theme-chirpy#86]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There are no similar request on existing issues (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe
It becomes a tedious task when I want to navigate to a sub-heading from my TOC. Firstly, I have to click to the main heading, then I can navigate between its sub-headings and same goes for those sub-headings.

## Describe the solution you'd like
It would be much better if I could see the sub-headings when I hover over the main heading.

**Comment by cotes2020** [comment]
The TOC is generated by [**bootstrap-toc**](https://github.com/afeld/bootstrap-toc) and the existing features have fully met my needs. Maybe you should submit this question to Its author.

See: <https://github.com/afeld/bootstrap-toc/pull/11>
