### ISSUE TITLE
Can't update repos generated with Template from Chirpy Starter 

### ISSUE THREAD

**Issue by gonzoknows** [cotes2020/jekyll-theme-chirpy#871]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

I'm attempting to upgrade my site's repo using the following url
https://github.com/cotes2020/chirpy-starter/compare/%3Colder-version%3E...%3Cnewer-version%3E

Although I'm having issues as my repo https://github.com/gonzoknows/gonzoknows.github.io doesn't pop up upon search nor is it listed as a fork of chripy starter. Do you have any ideas why this is?

I created my site through this link https://github.com/cotes2020/chirpy-starter/generate

**Comment by Cloufish** [comment]
If you used chirpy-starter template then you shouldn't update it by comparing the repositories and making pull requests,
See https://chirpy.cotes.page/posts/getting-started/#upgrading
![image](https://user-images.githubusercontent.com/32965886/218112035-f0b9faaf-807d-4997-8098-95009abdd2aa.png)

**Comment by WellRestedSloth** [comment]
Hi, did you ever figure this one out?

**Comment by gonzoknows** [comment]
> Hi, did you ever figure this one out?

Nope

**Comment by WellRestedSloth** [comment]
Ya I'm in the same boat as you. Trying to upgrade from v5.3.0 to latest v5.5.2.  Upgrading because I am getting Github Actions error (something about nokogiri error):

```
Fetching gem metadata from https://rubygems.org/.........
nokogiri-1.13.8-x86_64-linux requires ruby version < 3.2.dev, >= 2.6, which is
incompatible with the current version, 3.2.1
Error: The process '/opt/hostedtoolcache/Ruby/3.2.1/x64/bin/bundle' failed with exit code 5
```

So I tried to do it github way:

git remote add upstream https://github.com/cotes2020/chirpy-starter.git
git remote -v

git fetch upstream

git rebase upstream/main

And here I get a zillion merge conflicts.  I suppose I can try to resolve them manually, which would take quite a while.  I really don't want to start again.

Anyone else reading this come up with a better solution?

**Comment by WellRestedSloth** [comment]
OK I solved the nokogiri actions deployment error.  I created a new codespace based on my current chirpy (v5.3.0) repository.  That new codespaces comes with ruby 3.1.3, gem 3.3.26, gcc/g++ 9.4.0, make 4.2.1.

Did:
```
echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc
echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
source ~/.bashrc
```

Then:

```
rm Gemfile.lock
gem install jekyll bundler
bundle
```

This fixed the deployment problem.
However, I'm still on v5.3.0.
