### ISSUE TITLE
chirpy-starter repository missing _data folder since v5.5.0

### ISSUE THREAD

**Issue by dvdmtw98** [cotes2020/jekyll-theme-chirpy#873]
## Checklist

- [X] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [X] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [X] I found the bug on the latest code of the `master` branch.

## Describe the bug

The latest version of chirpy-starter repository is missing the _data folder that was present till v5.4.0

### To Reproduce

Compare the code in the commit for tag v5.5.0 with commit for v5.4.0

### Expected behavior

The _data folder should be present so that the share links and sidebar links can be updated. Additionally the folder contains translation files.

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |         |
| `gem -v`                          |         |
| `bundle -v`                       |         |
| `bundle exec jekyll -v`           |         |
| `bundle info jekyll-theme-chirpy` |         |

### Additional context

**Comment by gonzoknows** [comment]
I noticed this too

**Comment by cotes2020** [comment]
Don't worry about the files in `/_data`, Jekyll(>= v4.3.0) can read them from the gem package.

**Comment by gonzoknows** [comment]
> Don't worry about the files in `/_data`, Jekyll(>= v4.3.0) can read them from the gem package.

So where should `contact.yml` be moved to if `/_data` will not be supported anymore?

**Comment by cotes2020** [comment]
@gonzoknows Create `/_data` in your site and then put `contact.yml` into it
