### ISSUE TITLE
Markdown formatting in "spoiler" tag

### ISSUE THREAD

**Issue by mattpopovich** [cotes2020/jekyll-theme-chirpy#880]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There is no similar request on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

Somewhat? Markdown has this "feature" (or maybe it's a hack, unsure if it's officially supported by Markdown or not) that lets you [use a spoiler](https://gist.github.com/jbsulli/03df3cdce94ee97937ebda0ffef28287) to click and show additional information: 

<details>
  <summary>Example spoiler</summary>
  
  With markdown formatting of a link to [Ecosia](https://www.ecosia.org).

  ```python
  # Also supports code blocks and all other Markdown formatting
  x = 5
  ```
  
</details>

## Describe the solution you'd like

Currently, chirpy successfully creates the spoiler, except that any text in the spoiler cannot use Markdown formatting (in my experience). All text in the spoiler can be formatted with HTML, but not Markdown.

## Describe alternatives you've considered

Using HTML in the spoiler... but it's a pain hehe.

## Additional context

Feel free to mark this as "not implementing", but I figured I'd bring it up!

**Comment by NichtsHsu** [comment]
> Currently, chirpy successfully creates the spoiler, except that any text in the spoiler cannot use Markdown formatting (in my experience). All text in the spoiler can be formatted with HTML, but not Markdown.

Note that Chirpy is using [kramdown](https://kramdown.gettalong.org/), you can check its [syntax page](https://kramdown.gettalong.org/syntax.html) to learn how to use Markdown in HTML segments:

> If an HTML tag has an attribute markdown="1", then the default mechanism for parsing syntax in this tag is used.

That means:

```html
<details markdown="1">
<summary>Spoiler</summary>
Some **Markdown** content here.
</details>
```

**Comment by mattpopovich** [comment]
@NichtsHsu Awesome!! Worked like a charm, thank you!
