### ISSUE TITLE
How To Show "uncategorized posts" in categories tab?

### ISSUE THREAD

**Issue by Rootjhon** [cotes2020/jekyll-theme-chirpy#884]
## Checklist

- [x] I have read the [newlest tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There is no similar question on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I have tried to find the answer on [Jekyll Forum](https://talk.jekyllrb.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).
- [x] My question is based on the latest code of the `master` branch.

## Description

when some posts like this

````
title: Customize the Favicon
author: cotes
date: 2019-08-11 00:34:00 +0800
tags: [favicon]
````

without `categories: `

**Comment by NichtsHsu** [comment]
That's weird, why don't `categories: [uncategorized]`?

**Comment by Rootjhon** [comment]
> That's weird, why don't `categories: [uncategorized]`?

okay, It sounds a good proposal.
