### ISSUE TITLE
Do i need to use only lower case for language types of code block?

### ISSUE THREAD

**Issue by baeseongsu** [cotes2020/jekyll-theme-chirpy#89]
As the title says,
and please check the following examples.
1) lower case **```sql**
```sql
select * from table;
```
2) upper case **```SQL**
```SQL
select * from table;
```
3) (Even) we mix upper/lower case  **```sQl**
```sQl
select * from table;
```
There are no difference in markdown even if i use the mixture type. But in the theme, it doesn't work. It only works for lower case. (I just checked it by using `bundle exec jekyll serve`)

If i didn't use your theme correctly, please let me know. I would like to know how to handle this problem. Lastly, thank you so much for letting me use your theme. It's a pretty  charming theme and really has a constructive style.

**Comment by cotes2020** [comment]
Yes, you should use lowercase. Jekyll uses **Kramdown** as a Makrdown renderer, so all non-lowercase languages are invalid in Jekyll themes, not just in this theme.

**Comment by baeseongsu** [comment]
Thanks for comments and also for Nice work 👍
