### ISSUE TITLE
SVG image support

### ISSUE THREAD

**Issue by ruzickap** [cotes2020/jekyll-theme-chirpy#890]
## Describe the bug

I would like to use SVG images in the posts with the [jekyll-theme-chirpy](https://github.com/cotes2020/jekyll-theme-chirpy).

Currently the SVG images are not "sometimes" displayed correctly...

### To Reproduce

Here is the example of the post which contains the SVG images:

```markdown
---
title: SVG test
author: Petr Ruzicka
date: 2023-02-16
description: Test SVG images
image:
#  path: https://raw.githubusercontent.com/aws-samples/eks-workshop/main/static/images/icon-aws-amazon-eks.svg
  path: https://upload.wikimedia.org/wikipedia/commons/5/57/Devicon-ruby-plain-wordmark.svg
  alt: Ruby
---

## SVG Test 1

![SVG test 1](https://raw.githubusercontent.com/aws-samples/eks-workshop/main/static/images/icon-aws-amazon-eks.svg
"SVG test 1")

## SVG Test 2

![SVG test 2](https://upload.wikimedia.org/wikipedia/commons/5/57/Devicon-ruby-plain-wordmark.svg
"SVG test 2")

## SVG Test 3

![SVG test 3](https://raw.githubusercontent.com/jekyll/brand/master/jekyll-logo-black.svg
"SVG test 3")

## SVG Test 4

![SVG test 4](https://raw.githubusercontent.com/aws-samples/eks-workshop/main/static/images/icon-aws-amazon-eks.svg
"SVG test 4")
```

### Expected behavior

The theme should support SVG images.

### Desktop

- OS: macOS 13.2.1 (22D68)
- Browser: Chrome Version 109.0.5414.119 (Official Build) (x86_64)

(this issue is related to https://github.com/cotes2020/jekyll-theme-chirpy/issues/837, where is described similar issue with svg preview image)

**Comment by cotes2020** [comment]
SVG will not be rendered if it has no width:

```md
<!-- set the image width to 128px -->
![SVG test 1](https://url/to/svg){: w="128" }
```

**Comment by ruzickap** [comment]
Does it wok also for the [Preview Image](https://chirpy.cotes.page/posts/write-a-new-post/#preview-image)?

I tried something like:

```
---
...
description: Test SVG images
image:
  path: https://upload.wikimedia.org/wikipedia/commons/5/57/Devicon-ruby-plain-wordmark.svg
  width: 128
  alt: Ruby
---
```

Seem like the svg in not resized:

<img width="870" alt="image" src="https://user-images.githubusercontent.com/1434387/219828693-7c57392e-916e-4808-9695-0a4e4e2b944c.png">


Thank you...

**Comment by cotes2020** [comment]
Don't thank me yet @ruzickap. The preview image is a special role and require an aspect ratio of `1.91 : 1` for social sharing, so since v5.4.0 its size is automatically set to `1200 x 630` and the parameter `width` and `height` have been deprecated.
