### ISSUE TITLE
中文标签和分类乱码

### ISSUE THREAD

**Issue by imcloudfloating** [cotes2020/jekyll-theme-chirpy#9]
build 完成后，中文标签和分类对应的文件夹是乱码的。

**Comment by cotes2020** [comment]
调整好自己本地机器的编码格式就不乱了

**Comment by imcloudfloating** [comment]
终端的编码是 utf-8，jekyll 的编码也是 utf-8。.container 文件夹中的分类和标签是正常的，最后生成 _site 目录时，每个分类和标签对应的中文文件夹都是乱码的。

**Comment by cotes2020** [comment]
我随便看了你仓库的[分类](https://github.com/imcloudfloating/imcloudfloating.github.io/tree/master/categories)文件夹以及[标签](https://github.com/imcloudfloating/imcloudfloating.github.io/tree/master/tags)，不是显示了中文标题吗？我还是相信是你本地编码显示中文的问题。

另外提个建议，提issue的时候，把你使用的操作环境，终端工具，以及异常信息之类的贴出来，不要让我去猜你遇到了什么问题。

**Comment by imcloudfloating** [comment]
仓库的中文标签是手动修改了才提交的。

操作系统： Windows 10
终端：git bash
终端和文件的编码都是 UTF-8

前几个版本就存在分类和标签乱码的问题，我自己也折腾了很久没有搞定。就是最后生成 _site 目录的时候会出现乱码，我看了下项目中的脚本，python 脚本是生成 tags 和 categories 页面的，最后应该是由 Jekyll 生成了 _site 目录，我也试过改 Ruby 中的编码，最后还是没有解决。

build.sh 执行过程中没有提示异常。

**Comment by cotes2020** [comment]
1. 如果你 git bash 用utf-8, 那么请把 Windows10 的 system locale 设置为utf-8.

2. 如果你不习惯Windows系统设置为 utf-8，可以保留默认 locale 的`Chinese(Simplified, China)`，但是你要把 **git bash** 的`locale`设置为`zh_CN`，Charater set 也要使用默认值。

**Comment by imcloudfloating** [comment]
解决了，感谢！

**Comment by cotes2020** [comment]
我还发现一个问题，你使用脚本的方式并不正确，按照你的使用习惯，应该遵循这个[教程](https://chirpy.cotes.info/posts/getting-started/#option-1-built-by-github-pages)来部署，而不是自己手动`build.sh`，把静态文件拷贝过去，太麻烦了，这个不是我写这个脚本的初衷。用`init.sh`就行，省心快捷。

`build.sh`是留给有本地构建需求的用户去使用的。
