### ISSUE TITLE
期望_post下支持子目录，单个_post存放所有md显的有些臃肿，谢谢

### ISSUE THREAD

**Issue by xied5531** [cotes2020/jekyll-theme-chirpy#90]

**Comment by xied5531** [comment]
_post可以放目录，但是直接fork后，tag和category连接不可用，是否需要什么特殊处理？通过tag或category报404

**Comment by xied5531** [comment]
能否通过GitHub的pages自动生成并更新tag和category页面和链接？

**Comment by cotes2020** [comment]
1. 不试试自己建个子目录试试就来发 issue?

2. 链接 404 的连续发炮两三个问题都不愿意花几分钟看看文档吗？
