### ISSUE TITLE
I am not seeing a preview image on socials

### ISSUE THREAD

**Issue by timothystewart6** [cotes2020/jekyll-theme-chirpy#901]
**NOTE:** Before you start, the following should be completed.

- Read [tutorial][tutorial] to understand the usage and the correct effect of functional design.
- Make sure no [similar issue(including closed ones)][issues] exists.
- Try to find the answer on [Jekyll Forum][forum] and [StackOverflow][stack_overflow].

[tutorial]: https://cotes2020.github.io/chirpy-demo/categories/tutorial/
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue
[forum]: https://talk.jekyllrb.com/
[stack_overflow]: https://stackoverflow.com/questions/tagged/jekyll

## Description

Hi.  I cannot see image previews on socials.  I have found a similar issue https://github.com/cotes2020/jekyll-theme-chirpy/issues/797 however that was closed due to their template being wrong.

I feel like mine is right but I could be wrong.

e.g.

post: https://docs.technotim.live/posts/pikvm-at-scale/

I see the `og:image` html

```html
<meta property="og:image" content="https://docs.technotim.live/assets/img/headers/kvm-dark-desktop.jpg">
```

I can access that image anywhere.

However Social Share Preview cannot find it
https://socialsharepreview.com/?url=https://docs.technotim.live/posts/pikvm-at-scale/

and I do not see previews on Twitter https://twitter.com/TechnoTimLive/status/1627410727588794373

My entire site is open source https://github.com/techno-tim/techno-tim.github.io

and here is the post https://github.com/techno-tim/techno-tim.github.io/blob/master/_posts/2023-02-18-pikvm-at-scale.md

I did review all of your examples but didn't see additional metadata that I needed to add to the page, I figured it was just part of the template.

my images are `1200x630`

## Operations you have already tried

see above

Thank you for your help.

**Comment by timothystewart6** [comment]
Also, thank you so much for this template, I made a video about it a while back
https://www.youtube.com/watch?v=F8iOU1ci19Q

**Comment by cotes2020** [comment]
Hi @timothystewart6, I don't see any configuration problems with your source code at the moment.

Looking at the HTML elements, the `<head>` already contains the `og:image` metatag. But the [_socialsharepreview.com_](https://socialsharepreview.com/?url=https://docs.technotim.live/posts/pikvm-at-scale/) scan reports that it is not found. The same issue exists with the `og:description` metatag.

Weird 🤔

**Comment by timothystewart6** [comment]
Thank you. As you can see from my social pest on twitter it is indeed missing otherwise they would have rendered it.

**Comment by timothystewart6** [comment]
@cotes2020  I think i figured out why!  It looks like twitter has their own implementation!
https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started

I will read up and see if I can create a PR

**Comment by timothystewart6** [comment]
I think we might need `<meta name="twitter:card" content="summary"></meta>`

**Comment by timothystewart6** [comment]
Disregard (although it would be nice to have control over specific twitter card configuration in `_config.yaml`)  It turns out it might be my reverse proxy.  I had a minimum of ssl 1.3 and I have a feeling that sites are still using a lower version.  I will report back when I get this working properly.

**Comment by timothystewart6** [comment]
OK, that was it.  It looks like my minim SSL isn't compatible with these sites.  It looks like most of them use 1.2 and I was forcing a minimum of 1.3.  Sorry about the issue!  It still would be cool if we had control over the Twitter card in config https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started

**Comment by cotes2020** [comment]
> ... It still would be cool if we had control over the Twitter card in config https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started

Actually, we don't have to, because _jekyll-seo-tag_ already automatically generates the `twitter:card`.

<img width="711" alt="Screen Shot 2023-02-23 at 18 35 33" src="https://user-images.githubusercontent.com/11371340/220884125-73e107e7-ad52-47b8-977f-59057627c0a0.png">

**Comment by timothystewart6** [comment]
OK, well, I guess there isn't anything to do!  Thank you and sorry for the issue! Again, great template!

**Comment by danielmacuare** [comment]
> Also, thank you so much for this template, I made a video about it a while back
> 
> **Meet Jekyll - The Static Site Generator**
> 
> [![Meet Jekyll - The Static Site Generator](https://camo.githubusercontent.com/440c915fbe0b01d6624ab9c68057b1c1d80039adb51355c2896705510034f698/68747470733a2f2f696d672e796f75747562652e636f6d2f76692f4638694f553163693139512f302e6a7067)](https://www.youtube.com/watch?v=F8iOU1ci19Q)
> 
> https://www.youtube.com/watch?v=F8iOU1ci19Q

Thanks man, I was watching your video, and inspired me to start blogging again using this template. Here is my WIP blog: https://blog.dmac.tech/

Love your channel and thanks again for sharing your videos.

**Comment by timothystewart6** [comment]
> > Also, thank you so much for this template, I made a video about it a while back
> > **Meet Jekyll - The Static Site Generator**
> > [![Meet Jekyll - The Static Site Generator](https://camo.githubusercontent.com/440c915fbe0b01d6624ab9c68057b1c1d80039adb51355c2896705510034f698/68747470733a2f2f696d672e796f75747562652e636f6d2f76692f4638694f553163693139512f302e6a7067)](https://www.youtube.com/watch?v=F8iOU1ci19Q)
> > https://www.youtube.com/watch?v=F8iOU1ci19Q
> 
> Thanks man @timothystewart6 , I was watching your video, and inspired me to start blogging again using this template. Here is my WIP blog: https://blog.dmac.tech/
> 
> Love your channel and thanks again for sharing your videos.

Thank you for the nice comment!  Looks great!  Glad it inspired you to write again!
