### ISSUE TITLE
bogy tag is not closing in production build

### ISSUE THREAD

**Issue by techguy-bhushan** [cotes2020/jekyll-theme-chirpy#902]
## Bug

After generating production build, generated  html pages don't have `</body>` and `</html>` tag
Same thing I observed with https://chirpy.cotes.page/   site there also `</body>` and `</html>` tag missing

## To Reproduce

1. Go to 'https://chirpy.cotes.page/'
2. View Source Code (right click on page, select view source page (in chrome: view-source:https://chirpy.cotes.page/))
3. Search `</body>` tag and `</html>` tag in source code
4. You will not get `</body>` and `</html>` tag 

## Expected behavior

Body tag should be ended with `</body>`
Html tag should be ended with `</html>`

**Comment by cotes2020** [comment]
There is a concept called the omittable endtag
