### ISSUE TITLE
fontawesome does not display properly

### ISSUE THREAD

**Issue by jwcen** [cotes2020/jekyll-theme-chirpy#906]
**NOTE:** Before you start, the following should be completed.

- Read [tutorial][tutorial] to understand the usage and the correct effect of functional design.
- Make sure no [similar issue(including closed ones)][issues] exists.
- Try to find the answer on [Jekyll Forum][forum] and [StackOverflow][stack_overflow].

[tutorial]: https://cotes2020.github.io/chirpy-demo/categories/tutorial/
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue
[forum]: https://talk.jekyllrb.com/
[stack_overflow]: https://stackoverflow.com/questions/tagged/jekyll

**Comment by jwcen** [comment]
![image](https://user-images.githubusercontent.com/45908358/221341297-98b7904d-8d42-4fe5-9d45-c16f5602cb4a.png)

**Comment by MichaelTan9999** [comment]
Hi, jwcen. I checked your blog repo and found it rendered properly. It may be caused by the unstable network in mainland China.
<img width="228" alt="Screenshot 2023-03-27 at 11 20 24" src="https://user-images.githubusercontent.com/20365364/227832835-db9e1809-85c2-4ef1-9d7a-df93958fc96b.png">
