### ISSUE TITLE
post share is sharing local url instead of production url/

### ISSUE THREAD

**Issue by pixelstorm** [cotes2020/jekyll-theme-chirpy#916]
Loving Chirpy. Now, Where can i change the share settings. Currently its set to share a local url instead of the production url. for instance https://dynamitefrog.com/posts/shopify-github-integration/ if you try share this post on twitter you see the share address is localhost:4000 instead of dynamitefrog.com/ 

apologies if these settings are in the documentation https://chirpy.cotes.page/posts/getting-started/. I could not find them.

**Comment by cotes2020** [comment]
Sharing options are set in [`_data/share.yml`](https://github.com/cotes2020/jekyll-theme-chirpy/tree/master/_data/share.yml).

**Comment by pixelstorm** [comment]
Okay Thank you. 
Im aware of this. The problem is 
URL = to localhost:4000/post/title
instead of
URL = https://dynamitefrog.com/post/title 
and there is no where in _data/share.yml to change localhost:4000 to dynamitefrog.com that value.

is there another file i can change the value of URL?

**Comment by pixelstorm** [comment]
i fixed it. i needed to build the site in production mode with 

`JEKYLL_ENV=production` bundle exec jekyll b`
