### ISSUE TITLE
Question set by default dark-light

### ISSUE THREAD

**Issue by uri3l593** [cotes2020/jekyll-theme-chirpy#917]
Hi, how to set dark-light by default instead of light-dark when loading with browser, thanks.

**Comment by MichaelTan9999** [comment]
You may change the theme mode in the _config.yml.
https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/_config.yml#L62-L73

**Comment by uri3l593** [comment]
> You may change the theme mode in the _config.yml.
> 
> https://github.com/cotes2020/jekyll-theme-chirpy/blob/0d9cec6abcb699fc6317dbc97b5ec8b9b5edb698/_config.yml#L62-L73

Thanks a lot for taking your time and answering me, of course setting **theme_mode: dark** is dark and otherwise is light. my question was how to keep the toggle icon and set **dark-light** instead of **light-dark** which is by default on page load.
