### ISSUE TITLE
Compatibility issue on iPhone with Notch: White Bars on the Edges

### ISSUE THREAD

**Issue by wrayx** [cotes2020/jekyll-theme-chirpy#918]
## Describe the bug

There is a white bar at the top of the screen when viewing it from an iPhone (with notch) in Safari dark mode. The light mode works just fine as the background and nav bar's colour are consistent.

## Expected behaviour

In dark mode: a dark background colour on the body that is consistent with the nav bar. 
Or, expand the website to cover the whole area (notch be damned) by adding `viewport-fit=cover` to the meta viewport tag in the default html. 

## Logs/Screenshots

<img src="https://user-images.githubusercontent.com/38561534/222984206-7851cd07-cf8e-4403-9038-a5fd208aeb5c.png" width="400">

### Smartphone

- Device: iPhone 14 Pro Max (but this has been an issue since iPhone X)
- OS: iOS 16.3.1
- Browser: 16.3

## Additional context

Referennce to: [“The Notch” and CSS](https://css-tricks.com/the-notch-and-css/)

**Comment by cotes2020** [comment]
Thank you for reaching out @wrayx, but the referennce ([“The Notch” and CSS](https://css-tricks.com/the-notch-and-css/)) seems to be out of date and does not change the color of the status bar
