### ISSUE TITLE
Hide sidebar

### ISSUE THREAD

**Issue by edward-kings** [cotes2020/jekyll-theme-chirpy#923]
**NOTE:** Before you start, the following should be completed.

- Read [tutorial][tutorial] to understand the usage and the correct effect of functional design.
- Make sure no [similar issue(including closed ones)][issues] exists.
- Make sure the request is based on the latest code in the `master` branch.

[tutorial]: https://cotes2020.github.io/chirpy-demo/categories/tutorial/
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue

## Is your feature request related to a problem? Please describe

Chirpy is a minimal, responsive and feature-rich Jekyll theme for technical writing. Because of this, the reading experience is great and can be improved by hiding the sidebar, this would allow to have a full focus on the reading side.

## Describe the solution you'd like

I would like to achieve hiding the sidebar by the pressing of a button.

## Describe alternatives you've considered

Making a script that removes the sidebar's html code is not enough, alignment errors would happen with the text and the search bar.

## Additional context

This screenshot simplifies pretty much how the reading experience is improved.

![screenshot](https://user-images.githubusercontent.com/101529949/224471375-8c0a1011-28a4-45fb-b1ce-834969f9f963.png)

**Comment by pabloazurduy** [comment]
Hi there! I stumbled upon this issue while trying to figure out how to hide the sidebar on my post layouts in Jekyll. As a newbie to Jekyll 🤚 , I tried several workarounds but none seemed to work elegantly. Eventually, I found a solution that might not be the most efficient, but it did the job. If anyone else is struggling with this issue, this solution might come in handy:

According to the [Jekyll documentation](https://jekyllrb.com/docs/themes/#overriding-theme-defaults), you can customize the HTML template files from the theme by locating them in the gem directory. You can follow those instructions to find your directory, or you can simply copy the default.html file from the repository into `_layouts/default.html`.

Once you have added that file, you can remove the `% include sidebar.html lang=lang %}` line to completely remove the sidebar. Alternatively, if you only want to hide it when reading a post, you can use the following lines (to replace the one removed)

```
    {% unless page.layout == "post" %}
    {% include sidebar.html lang=lang %}
    {% endunless %}
```
Although the solution gets the job done, it's not ideal. I would have preferred to see the hamburger menu collapsed that you get when seen the site on mobile. Hopefully, this helps someone!
