### ISSUE TITLE
请问，我的网站部署上去了，但是分类和标签无法正常访问

### ISSUE THREAD

**Issue by tennsaisama** [cotes2020/jekyll-theme-chirpy#93]
https://tennsaisama.github.io/tabs/tags/

这个地址是可以打开，但是在进一步点里面的标签或分类点击提示没有此页面，不知道这么说是否能够明白。。。

**Comment by tennsaisama** [comment]
是不是需要安装插件呀，不知站长提供travis ci自动部署的方法

**Comment by helloworld28** [comment]
> https://tennsaisama.github.io/tabs/tags/
> 
> 这个地址是可以打开，但是在进一步点里面的标签或分类点击提示没有此页面，不知道这么说是否能够明白。。。

按照作者的教程，是要用到他的脚本进行publish的，那的publish里含有动态创建目录和标签分支目录功能，所以要用作者的脚本来publish才能正常

**Comment by helloworld28** [comment]
关键是作者的脚本是shell脚本，windows不支持，对于windows的用户来说有点难受

**Comment by tennsaisama** [comment]
> > https://tennsaisama.github.io/tabs/tags/
> > 这个地址是可以打开，但是在进一步点里面的标签或分类点击提示没有此页面，不知道这么说是否能够明白。。。
> 
> 按照作者的教程，是要用到他的脚本进行publish的，那的publish里含有动态创建目录和标签分支目录功能，所以要用作者的脚本来publish才能正常

貌似作者的站点是通过travis ci自动部署的，可是我配置了之后跑不起来，不知道为什么

**Comment by tennsaisama** [comment]
`
    git clone https://${GH_PAT}@github.com/${GH_USER}/${BUILDER_REPO}.git
    ${HOME}/${BUILDER_REPO} --depth=1 -q
  - cp -r ${HOME}/${BUILDER_REPO}/framework/* .
  - bash _cibuild.sh
`

作者在某个仓库下有个framework文件夹，然后我想是通过_cibuild.sh这个文件开始自动部署的，不过这些东西貌似作者并没有公开，作为windows使用者自己也写不出来这个脚本。。。看来只能换个主题了

**Comment by cotes2020** [comment]
@tennsaisama 文档写的清清楚楚的事却要发个issue，模板的提示又不看，无语了。。。答案就是如 @helloworld28 所说的一样。

现在你要做的不是去硬磕自己不熟悉的 Travis，而是简简单单用个 WSL 或者 Cygwin 按教程跑 shell，这不是分分钟的事吗？

**Comment by tennsaisama** [comment]
> @tennsaisama 文档写的清清楚楚的事却要发个issue，模板的提示又不看，无语了。。。答案就是如 @helloworld28 所说的一样。
> 
> 现在你要做的不是去硬磕自己不熟悉的 Travis，而是简简单单用个 WSL 或者 Cygwin 按教程跑 shell，这不是分分钟的事吗？

比较喜欢这个主题，才问一下有没有好的解决办法，不用这么抵触吧……而且学东西硬磕不是很正常的事么，travis省去了自己搭建ci的过程，本就是简化了的东西又不是很难，不告诉就自己磕被，何必火药味这么大……初衷就是不想在本地装环境才用ci部署的，并不是用什么系统是否有shell的问题，如果需要装双系统也是分分钟的事，但问题不是这个呀
