### ISSUE TITLE
Form design?

### ISSUE THREAD

**Issue by cfjedimaster** [cotes2020/jekyll-theme-chirpy#932]
## Description

In the various examples of layout, I wasn't able to find one demonstrating a basic form. Is there design for one, and if so, where may I find it?

## Operations you have already tried

Looking through the various posts. :)

**Comment by cotes2020** [comment]
Not sure what form you are talking about, why not write a markdown example?

**Comment by cotes2020** [comment]
Not sure what form you are talking about, why not write a markdown example?

**Comment by cotes2020** [comment]
Consider using the components provided by bootstrap: https://getbootstrap.com/docs/4.6/components/forms/

**Comment by cfjedimaster** [comment]
And I realize now - there's Bootstrap. I can check their docs. :) Sorry!
