### ISSUE TITLE
Getting errors with favicons

### ISSUE THREAD

**Issue by Manicarus** [cotes2020/jekyll-theme-chirpy#937]
**NOTE:** Before you start, the following should be completed.

- Read [tutorial][tutorial] to understand the usage and the correct effect of functional design.
- Make sure no [similar issue(including closed ones)][issues] exists.
- Try to find the answer on [Jekyll Forum][forum] and [StackOverflow][stack_overflow].

[tutorial]: https://cotes2020.github.io/chirpy-demo/categories/tutorial/
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue
[forum]: https://talk.jekyllrb.com/
[stack_overflow]: https://stackoverflow.com/questions/tagged/jekyll

## Description

Hello, I customized favicon following [this tutorial](https://chirpy.cotes.page/posts/customize-the-favicon/). I successfully changed the favicon but the server kept spitting error messages. The error message appears when I try to access my blog with my iPhone 11 Pro with safari browser after tapping [the share button](https://duckduckgo.com/?t=ffab&q=safari+share+button&iax=images&ia=images).

## Operations you have already tried

manually added copies of apple-touch-icon-precomposed.png, apple-touch-icon.png and favicon.ico into the root of the blog. Error messages are gone but it doesn't seem right. I have two copies of favicon.ico (and other files) inside /assets/img/favicons and / (root of the blog).

Just to make sure I am following the tutorial correctly, am I supposed to add generated favicons into /assets/img/favicons or /_site/assets/img/favicons?

Removed custom favicons and checked if the error doesn't appear with the default favicon. Error persists.

EDIT 2: After googling, I found [an article](https://ptc-it.de/add-favicon-to-mm-jekyll-site/) saying that I need to insert the generated code into the `<head>` tag. Since I am using Chirpy Starter, I do not have access to _layout/default.html. I can manually create _layout/default.html but I wish there was a better way.

Following html code is generated by realfavicongenerator.net:
```
<link rel="apple-touch-icon" sizes="180x180" href="/assets/img/favicons/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/assets/img/favicons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/assets/img/favicons/favicon-16x16.png">
<link rel="manifest" href="/assets/img/favicons/site.webmanifest">
<link rel="mask-icon" href="/assets/img/favicons/safari-pinned-tab.svg" color="#5bbad5">
<link rel="shortcut icon" href="/assets/img/favicons/favicon.ico">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#ffffff">
```

## Logs/Screenshots

```
[2023-03-18 12:35:00] ERROR `/apple-touch-icon-precomposed.png' not found.
[2023-03-18 12:35:00] ERROR `/favicon.ico' not found.
[2023-03-18 12:35:00] ERROR `/apple-touch-icon.png' not found.
```

EDIT: trivial typo
EDIT 2:

**Comment by JorgenIvarsson** [comment]
Hi!
You should not user the html code that was generated by realfavicongenerator.net. Only use the images in the zip-file. 
I put the two files favicon.ico and apple-touch-icon.png into the folder favicons (which should be inside the folder img, inside folder assets, in the root directory). After a fresh install I had to create the two folders _img_ and _favicons_. In the _config.yml you can see the default path to the favicons are _/asset/img/favicons/_. No other actions were needed to get the favicons working. Still worked in production after deployment. 
There is a known problem with Safar in iOS when it comes to the favicon and the share button. Here you can read about the problem with the hard cache that is preventing the favicon from updating. Unfortunately there is nothing we can do about it. It's up to Apple to fix [the problem with the long caching of the favicon](https://stackoverflow.com/questions/73462826/iphone-storing-website-favicon-even-though-its-been-updated-and-cache-history-i).

**Comment by Manicarus** [comment]
Thanks for the feedback @JorgenIvarsson!
LIke you said, there's nothing much I can do to get rid of the error messages. I just gave up on it. Thank you for clarifying the location to put favicon.ico. It helped me a lot.
