### ISSUE TITLE
cant see heading on my toc

### ISSUE THREAD

**Issue by AblabiX** [cotes2020/jekyll-theme-chirpy#942]
**NOTE:** Before you start, the following should be completed.

- Read [tutorial][tutorial] to understand the usage and the correct effect of functional design.
- Make sure no [similar issue(including closed ones)][issues] exists.
- Try to find the answer on [Jekyll Forum][forum] and [StackOverflow][stack_overflow].

[tutorial]: https://cotes2020.github.io/chirpy-demo/categories/tutorial/
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue
[forum]: https://talk.jekyllrb.com/
[stack_overflow]: https://stackoverflow.com/questions/tagged/jekyll

## Description
i cant show on my table of contents after the update, i only use for my article heading 2 ## and 3 ###

using mozilla 111.0
Windows 11

## Operations you have already tried

re-update to 5.6.0

## Logs/Screenshots

![](https://i.ibb.co/pJLKhrg/toc.png)

**Comment by gastongc** [comment]
It seems that the `.gitignore` file has the following now:

```
# Misc
assets/js/dist
```

Which is leaving some files behind, if you check the web browser console you can see that is trying to retrieve some files that should be in there but can't find them. I just removed that line from `.gitignore` and added back the files in `assets/js/dist` using the ones from the [Chirpy demo repository](https://github.com/cotes2020/chirpy-demo/tree/main/assets/js/dist). Even in here, I noticed that there is also missing a few JS files: `home.min.js` and `pvreport.min.js`. I retrieved them from a prior release, v5.3.2 to be exact. After that it seems to be working properly on Azure Static Web Apps.

Another problem that seems to be related to this is that on mobile the menu and the search icon doesn't work at all, adding these files back seems to resolve the problem, similar to the TOC not showing anything.

**Comment by AblabiX** [comment]
thank you, for now i will stick with the 5.5.2

i cant update becouse of this https://github.com/cotes2020/jekyll-theme-chirpy/issues/944

**Comment by lyducka** [comment]
> It seems that the `.gitignore` file has the following now:
> 
> ```
> # Misc
> assets/js/dist
> ```
> 
> Which is leaving some files behind, if you check the web browser console you can see that is trying to retrieve some files that should be in there but can't find them. I just removed that line from `.gitignore` and added back the files in `assets/js/dist` using the ones from the [Chirpy demo repository](https://github.com/cotes2020/chirpy-demo/tree/main/assets/js/dist). Even in here, I noticed that there is also missing a few JS files: `home.min.js` and `pvreport.min.js`. I retrieved them from a prior release, v5.3.2 to be exact. After that it seems to be working properly on Azure Static Web Apps.
> 
> Another problem that seems to be related to this is that on mobile the menu and the search icon doesn't work at all, adding these files back seems to resolve the problem, similar to the TOC not showing anything.

Thank you so much! it fixed my problem, very helpful.

**Comment by kinesis19** [comment]
> It seems that the `.gitignore` file has the following now:
> 
> ```
> # Misc
> assets/js/dist
> ```
> 
> Which is leaving some files behind, if you check the web browser console you can see that is trying to retrieve some files that should be in there but can't find them. I just removed that line from `.gitignore` and added back the files in `assets/js/dist` using the ones from the [Chirpy demo repository](https://github.com/cotes2020/chirpy-demo/tree/main/assets/js/dist). Even in here, I noticed that there is also missing a few JS files: `home.min.js` and `pvreport.min.js`. I retrieved them from a prior release, v5.3.2 to be exact. After that it seems to be working properly on Azure Static Web Apps.
> 
> Another problem that seems to be related to this is that on mobile the menu and the search icon doesn't work at all, adding these files back seems to resolve the problem, similar to the TOC not showing anything.

Thanks.
I had a similar problem.
`ERROR `/assets/js/dist/home.min.js' not found.`

When I annotated the contents of assets/js/dist on ReadMe.md , I checked that there was no error.

**Comment by DarylGraves** [comment]
This issue still seems to persist, the .gitignore and most recent release are still missing these JavaScript files.

I'd be happy to submit a pull request to reinclude these files if that helps but it seems this has been closed as not an issue? Have I missed something?

**Comment by kungfux** [comment]
@DarylGraves These files are produced at compile time and so should not be stored in repository. Read more [here](https://github.com/cotes2020/jekyll-theme-chirpy/wiki/Development-&-Test-Environments#compiling-js-files).

**Comment by Kushizu-Kobuchi** [comment]
I'm in the same situation, if these js files are automatically generated, then there is no point in downloading these files, what should I do to solve this problem like you did?

**Comment by Kushizu-Kobuchi** [comment]
I'm in the same situation, if these js files are automatically generated, then there is no point in downloading these files, what should I do to solve this problem like you did?

**Comment by NichtsHsu** [comment]
> I'm in the same situation, if these js files are automatically generated, then there is no point in downloading these files, what should I do to solve this problem like you did?

Ensure `npm` is installed on your system and then execute `bash tools/init.sh`.
