### ISSUE TITLE
Light Mode/Dark Mode buttton is not working after cloning, also search functionality is not working

### ISSUE THREAD

**Issue by nabin-nath** [cotes2020/jekyll-theme-chirpy#948]
**NOTE:** Before you start, the following should be completed.

- Read [tutorial][tutorial] to understand the usage and the correct effect of functional design.
- Make sure no [similar issue(including closed ones)][issues] exists.
- Make sure the bug is found in the latest code of the `master` branch.

[tutorial]: https://cotes2020.github.io/chirpy-demo/categories/tutorial/
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue

## Describe the bug
Light Mode/Dark Mode buttton is not working after cloning, also search functionality is not working, also attaching a video for reference: https://www.loom.com/share/28c6ae992fad414b8a47e45860f98ba1 

## To Reproduce
Clone the repo
```bash
git clone https://github.com/cotes2020/jekyll-theme-chirpy.git
```

Install dependencies
```bash
bundle
```
Start the server
```bash
bundle exec jekyll s
```

## Logs/Screenshots
Video: https://www.loom.com/share/28c6ae992fad414b8a47e45860f98ba1

## Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         | ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]        |
| `gem -v`                          | 3.3.5        |
| `bundle -v`                       |   Bundler version 2.4.6   |
| `bundle exec jekyll -v`           |    jekyll 4.3.2     |
| `bundle info jekyll-theme-chirpy` |       jekyll-theme-chirpy (5.6.0)   |

**Comment by joshjohanning** [comment]
Are you using the forking model? 

See: https://github.com/cotes2020/jekyll-theme-chirpy/wiki/Upgrade-Guide#upgrade-the-fork

You need to run `npm run build` and commit the `assets/js/dist` files starting in 5.6.0.

**Comment by nabin-nath** [comment]
@joshjohanning tried installing the node_modules and then running `npm run build` but this error came
![image](https://user-images.githubusercontent.com/55244069/226821440-ec734e99-0d3d-46a9-b0ee-3677cbaef584.png)

Below is the complete log of the error
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/nabin/.nvm/versions/node/v14.4.0/bin/node',
1 verbose cli   '/home/nabin/.nvm/versions/node/v14.4.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v14.4.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle jekyll-theme-chirpy@5.6.0~prebuild: jekyll-theme-chirpy@5.6.0
6 verbose lifecycle jekyll-theme-chirpy@5.6.0~prebuild: unsafe-perm in lifecycle true
7 verbose lifecycle jekyll-theme-chirpy@5.6.0~prebuild: PATH: /home/nabin/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/nabin/Desktop/blog/nabin-nath.github.io/node_modules/.bin:/home/nabin/gems/bin:/home/nabin/.local/bin:/home/nabin/gems/bin:/home/nabin/miniforge3/bin:/home/nabin/miniforge3/condabin:/home/nabin/.nvm/versions/node/v14.4.0/bin:/home/nabin/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
8 verbose lifecycle jekyll-theme-chirpy@5.6.0~prebuild: CWD: /home/nabin/Desktop/blog/nabin-nath.github.io
9 silly lifecycle jekyll-theme-chirpy@5.6.0~prebuild: Args: [ '-c', 'npx rimraf assets/js/dist' ]
10 silly lifecycle jekyll-theme-chirpy@5.6.0~prebuild: Returned: code: 1  signal: null
11 info lifecycle jekyll-theme-chirpy@5.6.0~prebuild: Failed to exec prebuild script
12 verbose stack Error: jekyll-theme-chirpy@5.6.0 prebuild: `npx rimraf assets/js/dist`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/home/nabin/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
12 verbose stack     at EventEmitter.emit (events.js:315:20)
12 verbose stack     at ChildProcess.<anonymous> (/home/nabin/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
12 verbose stack     at ChildProcess.emit (events.js:315:20)
12 verbose stack     at maybeClose (internal/child_process.js:1051:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
13 verbose pkgid jekyll-theme-chirpy@5.6.0
14 verbose cwd /home/nabin/Desktop/blog/nabin-nath.github.io
15 verbose Linux 5.19.0-35-generic
16 verbose argv "/home/nabin/.nvm/versions/node/v14.4.0/bin/node" "/home/nabin/.nvm/versions/node/v14.4.0/bin/npm" "run" "build"
17 verbose node v14.4.0
18 verbose npm  v6.14.5
19 error code ELIFECYCLE
20 error errno 1
21 error jekyll-theme-chirpy@5.6.0 prebuild: `npx rimraf assets/js/dist`
21 error Exit status 1
22 error Failed at the jekyll-theme-chirpy@5.6.0 prebuild script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]
```

**Comment by nabin-nath** [comment]
@joshjohanning i was using node version `14.4.0`, by chaging the node version to `16.17.0` and deleting node_modules, package-lock.json and installing node_modules again it worked for me
