### ISSUE TITLE
Getting 404-Not Found on "Categories" and "Tags" Page.

### ISSUE THREAD

**Issue by codeh4ck3r** [cotes2020/jekyll-theme-chirpy#95]
I used chirpy theme and added two posts by creating one category as "Write-up" and one subcategory "hackthebox".
I added those two posts under subcategory "hackthebox". 
When I run web server locally on http://127.0.0.1:4000 , the "Category" and "Tags" page shows well and also don't get 404-Not Found but when I upload the same on github pages I get 404-Not Found.

Screenshots attached below for reference.

On local web server (Not getting 404 not found error)

![image](https://user-images.githubusercontent.com/36817997/89107313-c58ace00-d44d-11ea-9b7c-8d8c421ce24d.png)

On website hosted using github pages (Getting 404 not found error)

![image](https://user-images.githubusercontent.com/36817997/89107327-e2270600-d44d-11ea-98f0-1a9d16162150.png)

Any solution on this? 
Thanks in advance.

**Comment by codeh4ck3r** [comment]
Closing the issue.
Sorry, didn't saw old closed issues. Got the answer.

**Comment by hillsonghimire** [comment]
how did you solve this one?

**Comment by codeh4ck3r** [comment]
@hillsonghimire I used tools/publish.sh script to publish my posts and it solved my problem. 
Ps. You need to commit before running that script.

**Comment by hillsonghimire** [comment]
So, should I push after running the script?

**Comment by codeh4ck3r** [comment]
@hillsonghimire No it will push automatically. just do commit and run the script.

**Comment by hillsonghimire** [comment]
@codeh4ck3r  Thanks mate. That helped !!

**Comment by bcaddy** [comment]
I'm also having this issue. I write up a new post, commit, then run `tools/publish.sh` and then the build fails. I'm declaring categories and tags like this in the post if that affects anything

```
categories  : [category1, category two]
tags        : [tag1, Tag2, tag three]

**Comment by cotes2020** [comment]
@bcaddy In your case, there is a lot of white space between your `categories`/`tags` and colon, which prevents the tool script from reading `categories`/`tags` info and thus does not generate the required pages, and it is not surprising that the tests fail. I will enhance the script later to handle extra spaces, now you can simply remove these spaces from the yaml.

More importantly, starting from `v2.5`, no one should use `tools/publish.sh` on github to solve the 404 problems. Please read the latest tutorial and use Github Actions to complete deployment.

**Comment by bcaddy** [comment]
That did it. Thank you!
