### ISSUE TITLE
How to change the word Home in the side bar?

### ISSUE THREAD

**Issue by stormlrd** [cotes2020/jekyll-theme-chirpy#950]
I can't for the life of me find where to do this :\
I'd like to change the word Home to be Designs.
Also is there a way perhaps to actually change the landing page to a static page rather than defaulting to the list of posts?

thanks.

**Comment by stormlrd** [comment]
nevermind I found it :) its in the locals files :)

**Comment by Venompool888** [comment]
> It's ok, I found it :) it's in the local files :)

Can I ask for the path?

**Comment by SawyerHere** [comment]
id like to know too
