### ISSUE TITLE
TocBot Not work with Cloudflare Pages

### ISSUE THREAD

**Issue by Nexus-Gits** [cotes2020/jekyll-theme-chirpy#951]
**NOTE:** Before you start, the following should be completed.

- Read [tutorial][tutorial] to understand the usage and the correct effect of functional design.
- Make sure no [similar issue(including closed ones)][issues] exists.
- Make sure the bug is found in the latest code of the `master` branch.

[tutorial]: https://cotes2020.github.io/chirpy-demo/categories/tutorial/
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue

## Describe the bug
TocBot Not work with Cloudflare Pages & also Netlify Pages. So site does not show the Table of content on the post.

## Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |         |
| `gem -v`                          |         |
| `bundle -v`                       |         |
| `bundle exec jekyll -v`           |         |
| `bundle info jekyll-theme-chirpy` |         |

**Comment by lextm** [comment]
This does not only affect Cloudflare Pages deployment, but I can reproduce the missing TOC contents issue even if running locally.

**Comment by gezhaoyou** [comment]
Ayou blog root dir, run 
`npm install && npm run build`
see [https://github.com/cotes2020/jekyll-theme-chirpy/wiki/Upgrade-Guide#upgrade-the-fork](https://github.com/cotes2020/jekyll-theme-chirpy/wiki/Upgrade-Guide#upgrade-the-fork)

**Comment by gezhaoyou** [comment]
My site now ok. run `npm install && npm run build` at site root dir, then `bundle update`
see https://github.com/cotes2020/jekyll-theme-chirpy/wiki/Upgrade-Guide#upgrade-the-fork

**Comment by lextm** [comment]
That's very helpful a hint. I got mine working now with a custom build script https://github.com/lextm/jekyll-theme-chirpy/blob/master/build.sh

**Comment by creme332** [comment]
I am facing the same issue on a local server.  In my case, only H2 and H3 headings appear in the TOC. H1 tags are ignored.

## Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         | ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux]        |
| `gem -v`                          |   3.2.33      |
| `bundle -v`                       |    Bundler version 2.2.33     |
| `bundle exec jekyll -v`           |      jekyll 4.3.2   |
| `bundle info jekyll-theme-chirpy` |  5.6.1        |


### Desktop

- OS: Windows 10 Pro
- Browser: Chrome 112.0.5615.138 (Official Build) (64-bit)
