### ISSUE TITLE
Can't see Last Posts Info on cloudflare Pages

### ISSUE THREAD

**Issue by Nexus-Gits** [cotes2020/jekyll-theme-chirpy#952]
**NOTE:** Before you start, the following should be completed.

- Read [tutorial][tutorial] to understand the usage and the correct effect of functional design.
- Make sure no [similar issue(including closed ones)][issues] exists.
- Make sure the bug is found in the latest code of the `master` branch.

[tutorial]: https://cotes2020.github.io/chirpy-demo/categories/tutorial/
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue

## Describe the bug
Can't see Last Posts Info on cloudflare Pages.

## Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |         |
| `gem -v`                          |         |
| `bundle -v`                       |         |
| `bundle exec jekyll -v`           |         |
| `bundle info jekyll-theme-chirpy` |         |

**Comment by Mohamed3nan** [comment]
Yes, me too, I'm trying to find the reason
