### ISSUE TITLE
fork下来的/.github/workflows目录下pages-deploy.yml.hook文件

### ISSUE THREAD

**Issue by GiveMeAnApple99** [cotes2020/jekyll-theme-chirpy#955]
**CheckList** 

- Read [tutorial][tutorial] to understand the usage and the correct effect of functional design.
- Make sure no [similar issue(including closed ones)][issues] exists.
- Try to find the answer on [Jekyll Forum][forum] and [StackOverflow][stack_overflow].

[tutorial]: https://cotes2020.github.io/chirpy-demo/categories/tutorial/
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue
[forum]: https://talk.jekyllrb.com/
[stack_overflow]: https://stackoverflow.com/questions/tagged/jekyll

## Description

我对照[Tutorial-Getting Started](https://chirpy.cotes.page/posts/getting-started/)把这个项目fork到我的repo，却发现在/.github/workflows目录下pages-deploy.yml.hook文件，这直接导致2点错误：
Problem 1：执行init文件echo Already initialized，没有继续执行后面的操作
Problem 2：Actions里没有出现Build and Deploy这个Workflow

## Operations I have already tried

我把文件名修改为pages-deploy.yml之后，Problem 2解决了；但是Problem 1还存在

## Logs/Screenshots
![image](https://user-images.githubusercontent.com/55051102/227213553-fd64de31-71ec-435f-bc00-c26a8a242323.png)
pages-deploy.yml.hook文件名出错
![image](https://user-images.githubusercontent.com/55051102/227214968-27c01627-37d2-49de-ba64-ddc801cb323d.png)
init文件执行出错

**Comment by NichtsHsu** [comment]
你需要在项目根路径下执行 `bash tools/init` 而不是 cd 到 tools 目录再执行 `bash init`。

**Comment by GiveMeAnApple99** [comment]
> 你需要在项目根路径下执行 `bash tools/init` 而不是 cd 到 tools 目录再执行 `bash init`。
> 
> https://github.com/cotes2020/jekyll-theme-chirpy/blob/6fec411c18ca5689c467c7b216ddeda02df23623/tools/init#L90-L93
> 
> `pages-depoly.yml.hook` 本来就是要经过 init 处理之后变成 `pages-deploy.yml` 的。

谢谢您的回复。我cd到tools目录执行`bash init`是因为：如果我在项目根路径下执行`bash tools/init`，会出现如下报错
![image](https://user-images.githubusercontent.com/55051102/227451106-4327e028-6fa7-4c9c-ab90-f287c7a235f1.png)

**Comment by NichtsHsu** [comment]
你这个报错应该是这一行报的：

https://github.com/cotes2020/jekyll-theme-chirpy/blob/6fec411c18ca5689c467c7b216ddeda02df23623/tools/init#L81

你想一下是不是 clone 的时候用了 `depth=1` 或者其他什么奇奇怪怪的操作导致的。

**Comment by GiveMeAnApple99** [comment]
> 你这个报错应该是这一行报的：
> 
> https://github.com/cotes2020/jekyll-theme-chirpy/blob/6fec411c18ca5689c467c7b216ddeda02df23623/tools/init#L81
> 
> 仓库里的 tags 全丢失了。你想一下是不是 clone 的时候用了 `depth=1` 或者其他什么奇奇怪怪的操作导致的。

So wierd！我都是照常clone，不知道为啥出错
![image](https://user-images.githubusercontent.com/55051102/227514008-ee640549-ecc7-4825-b5bb-1a3162501d68.png)

**Comment by NichtsHsu** [comment]
尝试手动拉取一下 tags：

```bash
git remote add upstream https://github.com/cotes2020/jekyll-theme-chirpy.git
git fetch --tags upstream
```

**Comment by GiveMeAnApple99** [comment]
> 尝试手动拉取一下 tags：
> 
> ```shell
> git remote add upstream https://github.com/cotes2020/jekyll-theme-chirpy.git
> git fetch --tags upstream
> ```

谢谢！It works！
我刚刚部署上去，可以看到页面了，不过确实像Tutorial里说的：选择fork Chirpy，_Unless you are familiar with Jekyll and are determined to tweak or contribute to this project, this approach is not recommended._
非常感谢您的帮助！
