### ISSUE TITLE
Resizable Preview Image

### ISSUE THREAD

**Issue by ruzickap** [cotes2020/jekyll-theme-chirpy#956]
## Is your feature request related to a problem? Please describe

I would like to use images in [Preview Image](https://chirpy.cotes.page/posts/write-a-new-post/#preview-image) which may have "non-standard" sizes. Images which are not in resolution `1200 x 630` or ratio does not meet `1.91 : 1` are scaled and cropped "automatically" - which doesn't always look good.

Use case: If you are using the external links as images in "[Preview Image](https://chirpy.cotes.page/posts/write-a-new-post/#preview-image)" they are often not in required size and the automated resize/cropping is not always do it the "nice way".

It would be great if there is some way to define the scale / crop factor for the images (or simply define [size](https://chirpy.cotes.page/posts/write-a-new-post/#size)).

## Describe the solution you'd like

Adding a way how to display the image using [size](https://chirpy.cotes.page/posts/write-a-new-post/#size) will help and add the necessary flexibility like it is in case of standard [images](https://chirpy.cotes.page/posts/write-a-new-post/#images):

```yaml
---
image:
  path: /path/to/image
  alt: image alternative text
  width: 700
  height: 400
---
```

## Describe alternatives you've considered

The only way is to download / modify the external image according the described "[rules](https://chirpy.cotes.page/posts/write-a-new-post/#preview-image)".

## Additional context

None...

**Comment by cotes2020** [comment]
It's more like cheating yourself: the custom aspect ratio, while displaying appropriately within your own website, is still a cropped image in social shares.

Why not simply use a plain image, placed directly on top of the body text? If this still doesn't meet your needs, remember that this is an open source project and you can make any personalized modifications to it.

Please don't open another question like this one about the preview image aspect ratio, as I remember I've discussed it with you more than once.
