### ISSUE TITLE
Any way to revert to previous changes/themes??

### ISSUE THREAD

**Issue by jakre1234** [cotes2020/jekyll-theme-chirpy#963]
Hello Team,
Wondering if there's any way we can revert back to last changes/previous version of theme. I see there's some updates and the look and fell of the theme seems to be changed a bit, I don't feel comfortable with this new materilistic kind of cards for posts on homsecreen.
I liked the previous one more and it felt more simple and minimalistic.

Thanks and Regards,

**Comment by lextm** [comment]
> I don't even there is ever a "team" https://github.com/cotes2020/jekyll-theme-chirpy/graphs/contributors

While you might like the old, other users like me prefer the new. So my suggestion is that you create your own fork from the previous release and maintain it as a separate theme.

Of course the owner of this repo is the one to make the final decision.
