### ISSUE TITLE
Can we change font for a paritcular post?

### ISSUE THREAD

**Issue by sukhjinder-kumar** [cotes2020/jekyll-theme-chirpy#971]
## Description

Can we change the fonts of a particular post? We can do it by using HTML tags and writing inline style (font-family), but then we have to use HTML syntax, and can't revert to md syntax (tex syntax with 2 dollars sign doesn't work in HTML for instance) at least till the ending wrapper. What I am really asking is instead of the Loto and Source sans Pro (that is used in this chirpy), can we substitute these (for that particular post) with some other font?

**Comment by NichtsHsu** [comment]
> then we have to use HTML syntax, and can't revert to md syntax (tex syntax with 2 dollars sign doesn't work in HTML for instance) at least till the ending wrapper

Please try `markdown="1"` attribute, e.g.:

```html
<div class="custom" markdown="1">
Use **markdown** syntax here
</div>
```

**Comment by sukhjinder-kumar** [comment]
Thank you for the answer, this is exactly what I was looking for. One more thing I don't know how to accept this has the solution. Should I just close the issue?

**Comment by sukhjinder-kumar** [comment]
I found a working solution, as commented above markdown=1 works. Also one can still use the HTML tags inside for h2, h3, etc. So for headers use an HTML tag.
