### ISSUE TITLE
Can i change my website licence from Creative Commons to MIT license? 

### ISSUE THREAD

**Issue by 0xdroidan** [cotes2020/jekyll-theme-chirpy#972]
**NOTE:** Before you start, the following should be completed.

- Read [Wiki][wiki] to understand the usage and the correct effect of functional design.
- Make sure no [similar issue(including closed ones)][issues] exists.
- Try to find the answer on [Jekyll Forum][forum] and [StackOverflow][stack_overflow].

[wiki]: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue
[forum]: https://talk.jekyllrb.com/
[stack_overflow]: https://stackoverflow.com/questions/tagged/jekyll

## Description
I was wondering if it is possible to change the license of my website from Creative Commons to the MIT license. If this is possible, could you please guide me on how to go about doing it?

Thank you for your time and help!

**Comment by NichtsHsu** [comment]
Of course:

https://github.com/cotes2020/jekyll-theme-chirpy/blob/d97f95fca0bcd450ea50709ffba0217f7e65d339/_data/locales/en.yml#L30-L35

**Comment by jackusay** [comment]
Interesting, it seems we have i18n. But my repo doesn't have this files.
I just fork https://github.com/cotes2020/chirpy-starter
