### ISSUE TITLE
Problems ToC Jekyll-Chirpy

### ISSUE THREAD

**Issue by helhat** [cotes2020/jekyll-theme-chirpy#975]
# Checklist

- I read [jekyll-theme-chirpy/wiki](https://github.com/cotes2020/jekyll-theme-chirpy/wiki).
- I try to find the answer on [Jekyll Forum ](https://talk.jekyllrb.com/)and [StackOverflow](https://stackoverflow.com/questions/tagged/jekyll).

[wiki]: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
[forum]: https://talk.jekyllrb.com/
[stack_overflow]: https://stackoverflow.com/questions/tagged/jekyll

# Description

1.I don't see the table of contents, in the _config.yml toc it is true. 

2.Add in my post:
`---`
`toc: true`
`---`
But I can't see anything in contents

**Comment by gezhaoyou** [comment]
At you blog root dir, run 
`npm install && npm run build`
see [https://github.com/cotes2020/jekyll-theme-chirpy/wiki/Upgrade-Guide#upgrade-the-fork](https://github.com/cotes2020/jekyll-theme-chirpy/wiki/Upgrade-Guide#upgrade-the-fork)

**Comment by gezhaoyou** [comment]
My site now ok. run `npm install && npm run build` at site root dir, then `bundle update`
see https://github.com/cotes2020/jekyll-theme-chirpy/wiki/Upgrade-Guide#upgrade-the-fork

**Comment by lextm** [comment]
Duplicate to #951
