### ISSUE TITLE
Images in Post Listings, Search Results, and Recommended Posts

### ISSUE THREAD

**Issue by timothystewart6** [cotes2020/jekyll-theme-chirpy#976]
**NOTE:** Before you start, the following should be completed.

- Read [Wiki][wiki] to understand the usage and the correct effect of functional design.
- Make sure no [similar issue(including closed ones)][issues] exists.
- Make sure the request is based on the latest code in the `master` branch.

[wiki]: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue

## Describe the solution you'd like

Hi.  I would love to be able to show a preview of the hero image in the post listings.  This would liven up posts and increase click through rate as well as make content more interactive on platform when browsing.

Here is the Material way from Google although I am not so much concerned with the implementation as much as having some option for images in the post listing page, in search, and in the recommended posts.

https://m2.material.io/components/lists#anatomy

e.g. something like this
![image](https://user-images.githubusercontent.com/1322205/230986037-d299383b-f80d-4429-a0fe-ac8ec8853e47.png)

**Comment by cotes2020** [comment]
Please look for similar requests in closed ones, as there have been several for some time now. Although there are plans to display preview image of posts on the homepage in a future version, it's becoming a bit tedious to see these kinds of requests repeatedly without any pull requests being provided.

**Comment by timothystewart6** [comment]
Thanks.  I understand however I manage quite a few open source repos too and I just thought that if an enhancement  was going to be taken into consideration it would still be open, and if not all items closed would have a tag or at least a link to the original request.  I did not see one so I will search once again and try to link back, that way people may understand the reasoning why.

**Comment by timothystewart6** [comment]
- mentioned, no close reason - https://github.com/cotes2020/jekyll-theme-chirpy/issues/769
- closed not following template - https://github.com/cotes2020/jekyll-theme-chirpy/issues/767, https://github.com/cotes2020/jekyll-theme-chirpy/issues/768, https://github.com/cotes2020/jekyll-theme-chirpy/issues/764
- cloud not find anything related in the rest of the issues https://github.com/cotes2020/jekyll-theme-chirpy/issues?page=1&q=is%3Aissue+image+is%3Aclosed

Was this closed because you want a PR?  This was not a request regarding social previews, but image previews on post listing.

**Comment by timothystewart6** [comment]
Believe me, I understand open source, I never said it was a wishing well. Take care.

**Comment by cotes2020** [comment]
> <https://github.com/cotes2020/jekyll-theme-chirpy/issues/976#issuecomment-1504057808> just trying to understand how I can help or **_get help_** ... 

Well, I missed the word "get help" and now I understand what you are complaining about. So reopen this issue and leave it to the community while you wait for other interested volunteers to implement this feature.

BTW, the feature of displaying images on home page posts has been implemented and will be released in the next major version, but you may need to continue to wait for someone to implement the feature of displaying preview images for "related posts" and "search results".
