### ISSUE TITLE
new tab in the style of the home layout

### ISSUE THREAD

**Issue by LeoMaglanoc** [cotes2020/jekyll-theme-chirpy#980]
Hi,

I'm making a personal website with chirpy. It's really great because I don't have any webdev experience but I'm already pretty happy with how it looks like right now! 

I wanted to make my about page as the home page. And then, I wanted to create a separate projects tab for the old home page, where I list all my posts. This is how the new projects page looks like:

![image](https://user-images.githubusercontent.com/30468743/231089742-fd0a4330-ef9a-4640-ba6d-6e603adb5e47.png)
https://leomaglanoc.github.io/projects/

I have another (non-pinned) post which doesn't appear here. I looked at home.html from _layouts. What do I need to change there to fix it such that it looks like the original home page?

Thanks for your help!

**Comment by NichtsHsu** [comment]
Check #711 and get solution.
