### ISSUE TITLE
Why don't use jekyll-feed?

### ISSUE THREAD

**Issue by v4vong** [cotes2020/jekyll-theme-chirpy#982]
## Description

Why don't use [`jekyll-feed`](https://github.com/jekyll/jekyll-feed)? It is a plugin to generate an Atom (RSS-like) feed.

**Comment by cotes2020** [comment]
Thanks for letting me know about this plugin.  I knew about it in the early stages of developing this project. I chose not to use it because I wanted to design a feed with greater flexibility.

**Comment by v4vong** [comment]
OK, thanks for your reply.

**Comment by twhite96** [comment]
Is there some way I could remove your custom version? The feed is not validating per the [W3.org Validator](https://validator.w3.org/feed/check.cgi?url=https://www.tifflabs.org/feed.xml). I've never had a problem with Jekyll-feed

**Comment by kungfux** [comment]
Validator says it is valid for https://chirpy.cotes.page.

I guess, you may try to override it by creating a file `assets/feed.xml` with the content below to get rid of it completely in the output folder.

```xml
---
layout: compress
---
```
