### ISSUE TITLE
Menu bar Icons

### ISSUE THREAD

**Issue by griggril000** [cotes2020/jekyll-theme-chirpy#988]
**NOTE:** Before you start, the following should be completed.

- Read [Wiki][wiki] to understand the usage and the correct effect of functional design.
- Make sure no [similar issue(including closed ones)][issues] exists.
- Try to find the answer on [Jekyll Forum][forum] and [StackOverflow][stack_overflow].

[wiki]: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue
[forum]: https://talk.jekyllrb.com/
[stack_overflow]: https://stackoverflow.com/questions/tagged/jekyll

## Description

I created a new page on my site, but don't know what the frontmatter "icon" is for. I don't see anywhere where they show up.

**Comment by cotes2020** [comment]
Hi there, its value is the class name of FontAwesome icons, and you can choose a **free**  icon from <https://fontawesome.com/search?o=r&m=free>
