### ISSUE TITLE
Update docs about pinned posts

### ISSUE THREAD

**Issue by agarthetiger** [cotes2020/jekyll-theme-chirpy#99]
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There are no similar request on existing issues (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `develop` branch of the latest code.

## Is your feature request related to a problem? Please describe
I followed the guide in the README and was trying to create my own content. I copied the frontmatter from a post from the original _posts folder in your repo. I didn't want to pin a post, so I changed the value to `pin: false` instead of removing this setting. I thought this would be the safer option but doing this causes the post to disappear from the homepage. There are no errors in the terminal running "bash tools/run.sh" but the homepage shows just a clock icon and an Invalid Date message. 
<img width="1679" alt="Screenshot 2020-08-11 at 09 05 15" src="https://user-images.githubusercontent.com/1242023/89873073-ca6c2200-dbb1-11ea-8949-eb735f736e23.png">

This sent me down a rabbithole debugging the date settings etc before I went back to the original repo and copied a post exactly to test (which worked) and then changed one setting at a time. 

## Describe the solution you'd like
Updating the documentation to specifically state indicate that the `pin` setting should be removed if you don't want to pin a page. 

## Describe alternatives you've considered

Setting `pin: false` in the frontmatter works like any other unpinned post, in the same way as omitting the pin setting does.

## Additional context

I really love this theme and am especially impressed and pleased with how good the documentation has been to follow and get started with. I'm starting to open source some of my own projects and I am finding out how much time and effort goes into great documentation. Kudos for your time and effort, I really appreciate it.

**Comment by cotes2020** [comment]
Thank you for your suggestion, this issue is a bug in a sense.  :)
