### ISSUE TITLE
Update mermaid to use mindmap

### ISSUE THREAD

**Issue by bastien-w** [cotes2020/jekyll-theme-chirpy#994]
**NOTE:** Before you start, the following should be completed.

- Read [Wiki][wiki] to understand the usage and the correct effect of functional design.
- Make sure no [similar issue(including closed ones)][issues] exists.
- Try to find the answer on [Jekyll Forum][forum] and [StackOverflow][stack_overflow].

[wiki]: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue
[forum]: https://talk.jekyllrb.com/
[stack_overflow]: https://stackoverflow.com/questions/tagged/jekyll

## Description

Hello, i wanted to use the [mermaid mindmap](https://mermaid.js.org/syntax/mindmap.html) feature so i changed: 

my _data/assets/cross_origin.yml from: 
`
mermaid:
  js: https://cdn.jsdelivr.net/npm/mermaid@9.2.2/dist/mermaid.min.js
`
to this in my local file: 
`mermaid:
  js: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs`

and my _includes/mermaid.html from: 
`<script src="{{ site.data.assets[origin].mermaid.js | relative_url }}"></script>`
to this in my local file: 
```
<script type="module">
    import mermaid from '{{ site.data.assets[origin].mermaid.js | relative_url }}';
</script>
```
Is it the right way to do? Should i expect some bugs or other? 

btw : Awesome template 🥇

**Comment by cotes2020** [comment]
Hi @bastien-w, Starting from version `10.x`, Mermaid no longer supports usage through CJS, which is not very friendly for web page app. Therefore, I only upgraded it to the latest version `9.4` in 25ec7649cd80b788ecfcc51e7c8a4bc9e8150069.

See also: https://github.com/mermaid-js/mermaid/releases/tag/v10.0.0
