### ISSUE TITLE
Latex New Line Command "\\" Do Not Create New Line

### ISSUE THREAD

**Issue by zayn7lie** [cotes2020/jekyll-theme-chirpy#999]
## Describe the bug

When I want to create new line in a latex block, it appears success in vscode preview but I fail to do that in by webpage.

## To Reproduce

1. Create a Latex block in a post:
```latex
$$
Something A \\
Somgthing B
$$
```
2. Compiling to webpage

## Expected behavior

It is expected to appear:
```latex
Something A
Something B
```

but it appears:
```latex
Something ASomething B
```

### Desktop

- OS: windows 11
- Browser: Mozilla/5.0(firefox 112.0.1)

**Comment by NichtsHsu** [comment]
This should be considered a issue with [MathJax](https://github.com/mathjax/MathJax).

However,you can make it work like:
```html
$$
\displaylines{
  Something A \\
  Something B
}
$$
```

**Comment by zayn7lie** [comment]
> 

Thanks, that works. But it will have a wrong display in vscode preview. I will submit this issue to [MathJax](https://github.com/mathjax/MathJax/issues).

**Comment by zayn7lie** [comment]
> This should be considered a issue with [MathJax](https://github.com/mathjax/MathJax).
> 
> However,you can make it work like:
> 
> ```
> $$
> \displaylines{
>   Something A \\
>   Something B
> }
> $$
> ```

Thanks, that works. But it will have a wrong display in vscode preview. I will submit this issue to [MathJax](https://github.com/mathjax/MathJax/issues).

**Comment by zayn7lie** [comment]
Some updates of this issue:
The origin discussion of this issue: https://github.com/mathjax/MathJax/issues/2312
There are several different solutions to solve this issue. 
Now new line function(line break) is also introduced in [MathJax v4.0.0-alpha](https://github.com/mathjax/MathJax-src/releases/tag/4.0.0-alpha.1)
